### ISSUE TITLE
[RFC] codeowner acceptance standards

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1024]
### Summary

We should document our standards of acceptance. What we're looking to see in a contribution. It's currently pretty opaque today as to what we're looking for. As example, our browser support is virtually undocumented as we're currently just using the default browserlist config for autoprefixer. There's a set of must-haves. Is there a set of nice-to-haves that we can defer into separate issues if needed?

Additionally the definition/responsibilities of a codeowner should be codified. Anyone can review a PR, but codeowners are the people relied on to ensure submissions are properly evaluated against the standard of acceptance. 

**Must-have items for all PRs**
- Code
  - Code changes must be properly isolated. Pull requests should be laser focused to one single fix or feature. Without isolated changes we can not reliably cherry pick or back-merge fixes into old versions as hotfixes.
  - For helper functions (not components) intended for internal use only we should attempt to omit it from the final build or make it clear via a prefix with `__internal`. This could include some constants. Experimental _components_ will be flagged via the final decision in #1137 
  - New features should be off by default to preserve the original behavior where possible. Occasionally this principle may be overridden by guidance from the design team, particularly when a change to default behavior increases the usability substantially such as the change in #1063
- Documentation
  - Has the DOM node that an `id` corresponds to changed? This should be visible in the snapshots. If so, provide a migration note that could be included in the release notes.
- Code covered in unit tests
- `data-testid` on outermost container of component
- list of components modified with description of how to utilize
- RTL
- i18n, no hardcoded strings
- ...?

**Deferrable items for PRs**
- a11y?
- ...?

**Codeowner responsibilities**
- Review PRs and sign off on all must-have items
- ...?

**To Do**
- [ ] ~implement [`browserslist-config-carbon`](https://github.com/carbon-design-system/carbon/blob/master/packages/browserslist-config-carbon/index.js#L10) to adhere to the same set of browser support as Carbon.~ new `browserslist` will be implemented in v3 #956 
- [ ] Document contribution guidelines, PR must haves, what an ideal contribution looks like
- [ ] Document codeowner responsibilities, provide PR review template of checklist items
- [ ] Update Pull Request Template to include a link to this documentation
- [ ] Fill in and round out additional related documentation (testing, code documentation, should we provide a code style guide beyond what we get automagically from prettier?)

**Comment by tay1orjones** [comment]
Related reading
- [Carbon style guide](https://github.com/carbon-design-system/carbon/blob/master/docs/style.md)
- [Thoughtbot code review guidelines](https://github.com/thoughtbot/guides/tree/master/code-review)

**Comment by tay1orjones** [comment]
It's becoming somewhat clear that the items in the `code` section are going to more closely resemble a coding style guide, which would be a good first step for this issue.

**Comment by tay1orjones** [comment]
One thing to note - the `__unstable` prefix violates the very common [pascal casing eslint rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-pascal-case.md), so consumers will have to disable that rule anywhere they use the component if they have that rule in their project. 

We have to do it in our tests too 😞  https://github.com/IBM/carbon-addons-iot-react/blob/b3d81b79b4512619cbe1225bbdd847c158c3d7c2/src/components/DateTimePicker/DateTimePicker.test.jsx#L1

I think it's better to just prefix with `Unstable`

`UnstableComponentName`, and in moving to stable it becomes `ComponentName`

**Comment by JordanWSmith15** [comment]
Closed upstream via #2426
