### ISSUE TITLE
[RowActionButtons] row actions column resizing behavior in horizontally scrolling tables

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1043]
### Summary

In https://github.com/IBM/carbon-addons-iot-react/pull/1025#pullrequestreview-381933918 it was identified that row actions may not behave in an ideal fashion when tables horizontally scroll.
<sub>[Internal issue #343](https://github.ibm.com/Watson-IoT/pal-tracking/issues/343)</sub>

**Additional context**
- Should the row actions columns be a "locked" column?
- Additional follow on items:
  - if the first column, or at least the checkboxes (when present) should be frozen too?
  - etc. @lukefirth I suspect you have more thoughts

### Specific timeline issues / requests

I'm unaware of a hard timeline required for this enhancement. Please update if there is.

**Comment by tay1orjones** [comment]
This might be accomplished with or alongside the delivery of #1061

**Comment by kevinsperrine** [comment]
Related: https://github.com/carbon-design-system/carbon-addons-iot-react/issues/127

**Comment by bjornalm** [comment]
This issue is still unclear. It has a status "needs design" and is formulated as a question. The referenced issues give a hint of what might have to be done , but I think we should formally specify what this particular request actually is before we dive in to the estimations.

**Comment by kevinsperrine** [comment]
We actually have designs in the PAL pages. There are currently 3 issues (including this one) open related to this functionality, so we do need to gather them all and make sure everyone is aligned, but I think we have enough to estimate.

https://pages.github.ibm.com/ai-applications/design/components/datatable/rowactions#horizontal-scrolling

https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1061
https://github.com/carbon-design-system/carbon-addons-iot-react/issues/127

**Comment by davidicus** [comment]
comments from duplicate thread:
> I want to hear Cynthia's thoughts here (can we add her to this repo?), but I think @matsgothe's design proposal above makes sense.
> 
> Instead of appending the row actions to the far right side of the table and making the user scroll to see them, the actions would always appear to the right of the visible window, regardless of scrolling. This would probably mean that we need to allocate a certain amount of space to the right side of the viewing window to always be reserved for the row actions.
> 
> Maybe we can consider the row actions as their own column that's always fixed on the right side of the visible screen. The Carbon X kit has actually introduced something similar called an icon column:
> 
> <img alt="Screen Shot 2019-04-09 at 4 54 51 PM" width="1040" src="https://user-images.githubusercontent.com/48336859/55837879-40f19f00-5ae8-11e9-8277-4b133a48cfa9.png">

**Comment by davidicus** [comment]
Related to https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1061. Design will probably come from that issue.

**Comment by davidicus** [comment]
Closing in favor of #1061
