### ISSUE TITLE
[GaugeCard] Needs to support error/nodata state

### ISSUE THREAD

**Issue by stuckless** [carbon-design-system/carbon-addons-iot-react#1058]
The GaugeCard and the ValueCard are pretty much identical in features just the Gauge renders the content in a gauge.

Current the GuageCard supports most of ValueCard, but, does not support the error states, and this needs to be added.

We've worked around this in Graphite (for now), by detecting the error states before rendering the GaugeCard and then showing the ValueCard instead.  (This could be a work around here as well)

The likelihood of a Gauge having no data or error is high.

**Comment by tay1orjones** [comment]
We found this was actually delivered earlier in https://github.com/carbon-design-system/carbon-addons-iot-react/pull/1089

https://carbon-addons-iot-react.com/?path=/story/watson-iot-experimental-gaugecard--with-data-state-no-data
