### ISSUE TITLE
[ProgressIndicator] Change the design of the ProgressStep

### ISSUE THREAD

**Issue by rawa-resul** [carbon-design-system/carbon-addons-iot-react#1074]
### Summary
<sub>[Internal issue #252](https://github.ibm.com/Watson-IoT/pal-tracking/issues/252)</sub>

Change the SVG icons and positioning of the bar and labels such that it adheres to the following illustation:

**Additional context**
From this:
<img width="253" alt="Screenshot 2020-04-08 at 15 56 43" src="https://user-images.githubusercontent.com/61942902/78799105-a4d7cd80-79b1-11ea-9a7a-1765e4e3493c.png">

To this:
<img width="191" alt="Screenshot 2020-04-08 at 15 55 55" src="https://user-images.githubusercontent.com/61942902/78799135-aef9cc00-79b1-11ea-8fde-67c50cf75739.png">

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon Add-ons for Watson IoT is a collaborative system. We encourage teams to build components and submit them for integration._

**Comment by tay1orjones** [comment]
Added a link in the issue body above to the [internal tracking issue](https://github.ibm.com/Watson-IoT/pal-tracking/issues/252).

@lukefirth the designs provided here don't quite match those listed in the internal issue. ([link](https://pages.github.ibm.com/Watson-IoT/IoT-Design-Site/components/progressindicator/overview/)) Could you provide some clarity on what we should for this item?

**Comment by lukefirth** [comment]
Great catch @tay1orjones - it seems the screenshots above came from someone placing it straight from the PAL sketch library (which has a coloring bug at the moment for this component).

@rawa-resul , reminder: please reference the design site as source of truth for components: https://pages.github.ibm.com/Watson-IoT/IoT-Design-Site/components/progressindicator/overview/

**Comment by rawa-resul** [comment]
@lukefirth thanks!
