### ISSUE TITLE
[StatefulTable] cannot select all in StatefulTable if that table is in a modal

### ISSUE THREAD

**Issue by yanzhe2017** [carbon-design-system/carbon-addons-iot-react#1084]
### Describe the bug

I add a StatefulTable in a modal, table data is populated, each line can be selected, but "Select all" checkbox cannot be selected, when click "Select all" checkbox, no change in the table, only the modal "X" close icon is focused.

### To Reproduce

1. Add StatefulTable in a modal, show in page
2. Click on 'select all' checkbox in the modal
3. See error, no line is selected, "X" close icon in the modal is focused

![image](https://user-images.githubusercontent.com/25318085/79113230-041f4e80-7db3-11ea-96c7-33bcd72981c9.png)

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/codesandbox-yxbkg

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. firefox, chrome]
- `carbon-addons-iot-react` version: [e.g. `v2.63.0`]

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by davidicus** [comment]
Hi @yanzhe2017. Thanks for reporting this bug. We will try to address as soon as possible. If you could attach a reduced example that showcases the bug it would help speed up the review.

**Comment by yanzhe2017** [comment]
I found the reason, the issue happen when the page has StatefulTable with select all checkbox already, then in a modal, another StatefulTable with select all checkbox is added again, the two select-all checkbox use same id, so the one in modal does not work. If I change the id from select-all to other value in Chrome inspect, the select all function work in the modal. Please fix this issue, maybe generate unique id for select all checkbox.
