### ISSUE TITLE
[Table] columns rendering incorrectly

### ISSUE THREAD

**Issue by sstone2423** [carbon-design-system/carbon-addons-iot-react#1086]
### Describe the bug

When rendering different tables based on state conditions, incorrect columns from previous renders intermittently in the newly rendered table.

For example, in Monitor we render a different table based on the current data item that is selected. This bug only occurs on a second re-render of the page as the first render does not have previous data to clash with.

![Screen Shot 2020-04-13 at 1 55 14 PM](https://user-images.githubusercontent.com/25177649/79151033-5cdcf000-7d8f-11ea-9048-166c9a6131d7.png)

### To Reproduce

1. Go to a component using Table that renders different data based off conditional state
2. Force a re-render
3. See duplicate key warnings and *possibly* see an extra empty column being rendered from the previous table's state

### Expected behavior

No warnings should appear and the component should only render the current table state's columns, not the previous

### Environment/versions:

- OS: MacOS
- Browser: chrome
- `carbon-addons-iot-react` version: 2.63.0

### Additional context

Internal issue: https://github.ibm.com/wiotp/monitoring-dashboard/issues/934

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

No specific timeline

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by tay1orjones** [comment]
Are you able to work around this by regenerating the key of the table itself when the data changes?

Are you using `Table` or `StatefulTable` - if StatefulTable, this could be a bug in the reducer.

**Comment by sstone2423** [comment]
I'll try that out. Yes this is StatefulTable

**Comment by tay1orjones** [comment]
I think this will be fixed by #1470

**Comment by tay1orjones** [comment]
@sstone2423 this should be fixed in v2.111.4 as we're now using unique id's by default for table components
