### ISSUE TITLE
[ValueCard] refactoring ideas

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#1141]
### Summary

This is a set of refactoring ideas to simplify the code of ValueCard.
We have so many similar props that we're passing through just to decide how to render low-down.  Need to move it up

1. Move off styled-components as the nesting is very confusing

ValueRenderer:
Self-measuring size improvement should allow us to remove unit, size, layout, isSmall, isMini, isVertical, external components are basically having to pass in parameters that calculate the font-size internally, but it's not explicit based on the component input what actual font size gets used

UnitRenderer:
Ideally he wouldn't need to know 'value', 'layout', 'isMini', 'attributeCount'

Attribute:
Why does he need to know the 'attributeCount', 'isMini', 'isSmall', 'size'.  Could attribute simply based on the measured width from SizeMe, dynamically figure out the appropriate font sizes to pass downstream to ValueRenderer and UnitRenderer
Add label to Attribute rendering. Merge AttributeWrapper being a styled-component into Attribute.  Sizing of the fonts is attribute's responsibility, labelSize, unitSize, valueSize up to Attribute to determine and we'll make Value, Unit and Label dumber and just take the sizes
 <AttributeWrapper
                      layout={layout}
                      isVertical={isVertical}
                      isSmall={attribute.secondaryValue !== undefined}
                      isMini={isMini}
                      size={newSize}
                      attributeCount={attributes.length}
                    >

ValueCard:
remove styled components as it's overcomplicating the render to understand them
Rename isVertical to showLabelAboveValue, 
layout determines are the attributes next to each other or above each other, rename attributeLayout
Remove isMini, isSmall determinations from ValueCard

**Additional context**

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon add-ons for Watson IoT is a collaborative system. We encourage teams to build components and submit them for integration._

**Comment by tay1orjones** [comment]
Overlap here with #1276 and #370
