### ISSUE TITLE
[List] Add handleSelect feature to storybook

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#1180]
There should be guidance on how to pass `onSelect` handler to the `ListItem` component.  Our current stories do not make this clear. This should be completed before List is taken out of experimental.

**Comment by kevinsperrine** [comment]
closing as there are now stories showing how handleSelect is passed: https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-list--selectable-items

and documentation in the readmes, too: 
https://next.carbon-addons-iot-react.com/?path=/docs/1-watson-iot-list--basic-single-column#props
https://next.carbon-addons-iot-react.com/?path=/docs/1-watson-iot-simplelist--basic#props
