### ISSUE TITLE
[PieChart] Card shows data using the carbon-charts Pie Chart

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#1181]
### Summary

Create a Dashboard Card type that uses Pie Charts
![image](https://user-images.githubusercontent.com/6663002/81827409-595b9680-94fe-11ea-8d01-b30454ca23e2.png)
https://carbon-design-system.github.io/carbon-charts/?path=/story/pie--pie

It should have the same abilities as every Dashboard Card, to change the Range, etc

**Additional context**
https://github.ibm.com/wiotp/monitoring-dashboard/issues/221

### Specific timeline issues / requests

We're trying to ship this in June in Maximo Asset Monitor

**Comment by bjornalm** [comment]
@scottdickerson Regarding the ability to change the range. Isn't the range in the case of the pie chart just the data (with group and value keys)? The bar chart has a domain range but that is related to the axis.

**Comment by bjornalm** [comment]
Does it makes sense to have a data table for the expanded mode of the PieChartCard? (Like the BarChartCard and TimeSeriesCard have) @dianatran18

**Comment by dianatran18** [comment]
> Does it makes sense to have a data table for the expanded mode of the PieChartCard? (Like the BarChartCard and TimeSeriesCard have) @dianatran18

Mind providing more context or examples of this @bjornalm ?

**Comment by bjornalm** [comment]
> > Does it makes sense to have a data table for the expanded mode of the PieChartCard? (Like the BarChartCard and TimeSeriesCard have) @dianatran18
> 
> Mind providing more context or examples of this @bjornalm ?

The BarChartCards and TimeSeriesCards can be expanded in a non-transactional modal where they below the actual chart also shows the data in a table:

![image](https://user-images.githubusercontent.com/5167091/93817195-df2fe100-fc58-11ea-8ef8-89af2bbb03dd.png)

The PieChartCard table would only be one row and perhaps not add that much value, but it could be nice to be consistent with the other ChartCards and also give the option to download data.

**Comment by lukefirth** [comment]
Chiming in - 

A pie chart is, by definition a moment in time (sure that moment may be pre-aggregated), so @bjornalm is totally right, the table would only show a single timestamped row of data that is feeding it. I think that honestly still makes some sense to show for clarity, consistency and accessibilities sake.

**But** @scottdickerson I'm not sure how you want your request of 

> "It should have the same abilities as every Dashboard Card, to change the Range, etc"

to be fulfilled? Unless:
1. The available range is tied to always be a single data point or,
2. You are proposing that the chart itself does some additional aggregation of data from whatever the selected range is down to a single data point orm
3. A pie chart _per timestamp in the range_ 

Then it's not possible logically for a pie chart to support a range of data as an input.

If you did really have the need to show 'part to whole' like a pie chart, but over a non-single data point time series (ie show a pie chart over time) - then you'd be looking at something like a stacked area graph showing %, eg: https://carbon-design-system.github.io/carbon-charts/?path=/story/area--stacked-area-percentage

**Comment by bjornalm** [comment]
@lukefirth @DianaStanciulescu sounds good. I'm stripping away stuff like pagination, sort, filtering etc:
![image](https://user-images.githubusercontent.com/5167091/93856943-197d9a80-fcba-11ea-8427-6625fb0b8e85.png)
