### ISSUE TITLE
[StatefulTable] Can't set totalItems when late loading

### ISSUE THREAD

**Issue by zhaozhuo813** [carbon-design-system/carbon-addons-iot-react#1191]
### To Reproduce

We are using late loading data in StatefulTable, so at first time, the tabledata sent to StatefulTable is just a part of data, not complete data. 
we want to use totalItems field to specify the real total data count, instead of table data count. However i found totalItems  doesn’t work. 
I found this  https://github.com/IBM/carbon-addons-iot-react/pull/372  seems someone has fixed it but actually still not.
here is my version of carbon-addons-iot-react: 2.62.0

### Expected behavior
When using late loading, we expect to set correct totalItems to do pagination.

### Environment/versions:

- OS: [ MacOS,]
- `carbon-addons-iot-react` version: [ `2.62.0`]

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?
Our product will be released in September, so it will be good if can be fix before that timeline.

**Comment by tay1orjones** [comment]
This might be a small bug in how we set totalItems in the reducer 

https://github.com/IBM/carbon-addons-iot-react/blob/2ff6ad3957c7cda90f9d6396d3ee120b322e16e1/src/components/Table/tableReducer.js#L287

**Comment by tay1orjones** [comment]
One potential workaround is to merge the late data with the existing data and then regenerate the StatefulTable by changing it's `key`
