### ISSUE TITLE
[StatefulTable] When embedded StatefulTable widget in Modal, no response when click rowactions menu

### ISSUE THREAD

**Issue by zhaozhuo813** [carbon-design-system/carbon-addons-iot-react#1193]
### Describe the bug
When embedded StatefulTable widget in Modal, rowactions not work. If select an action in row action menu, no response. No event caught by onApplyRowAction.

![image](https://user-images.githubusercontent.com/65387028/82057159-8625ce80-96f5-11ea-8e49-053761df4bd0.png)

### Expected behavior

When choose action in rowaction menu in table which embedded in Modal,  it can work correctly.

### Environment/versions:

- OS: [MacOS]
- Browser: [all]
- `carbon-addons-iot-react` version: [e.g. `v2.62.0`]

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

Out product will be release at September.

**Comment by tay1orjones** [comment]
I think this is the same root issue as #1084 - the `id` needs to be regenerated/different when two tables are on the same page.

Easiest way to solve this might be by adding the `tableId` as a prefix of the `id` or similar `key`
