### ISSUE TITLE
[Table]  Create & Save views

### ISSUE THREAD

**Issue by bjornalm** [carbon-design-system/carbon-addons-iot-react#1210]
[Internal issue 167](https://github.ibm.com/Watson-IoT/pal-tracking/issues/167)

**Is this an extension to an existing component, pattern, or a brand new asset?**
This is an EDS item.

**What is the rationale for this contribution.**
In certain situations, a user may need to make use of the same resource table for a number of different purposes, which would benefit from different configurations of things like sorting, columns and filters.

This contribution covers the ability to save a particular configuration as a 'view' and later change between saved views.

**Detail the intended behavior**
- The default table gains a dropdown to the left of the toolbar.
- This dropdown is by default 'default view', when a user makes changes to the tables configuration, this changes to 'unsaved view'

- Once a custom view is created through changing table settings. The user can open the settings (disregard incorrect icon usage - should be from settings gear) overflow and choose to 'save view'
Image: 
![image](https://media.github.ibm.com/user/684/files/3dff6480-200e-11ea-894a-59b647fe53b5)

- This will prompt a small dialog to provide a name and description to the custom view and if it should be the view selected by default when the table first loads.
Image: 
![image](https://media.github.ibm.com/user/684/files/46579f80-200e-11ea-9e8c-c528b64e5006)

- Completing this form will save the view as something selectable in the aforementioned dropdown. 
Image: 
![image](https://media.github.ibm.com/user/684/files/4eafda80-200e-11ea-8249-eca38c109700)

- Also in the dropdown of view selection: default view, any saved views and a 'manage views' action.
image:
![image](https://media.github.ibm.com/user/684/files/553e5200-200e-11ea-91fd-4cabeca5dc04)

- The manage views action will pop a modal with a simple table of views that can be edited (name/description/default?) or deleted.
Image: Not provided.

**Comment by lukefirth** [comment]
Adding some clarifications on behavior after discussion with @bjornalm today:

> 1. When should the “Save new view” should be available?

- When a users current configuration of the table is different from the last selection made in the view picker. Eg: making any configuration changes from the 'default' setup of the table in a fresh instance, and after they select 'view X/Y/Z' and then make a change. In other words, the only time it isn't available is when they haven't changed any of the things that form the view (filters, sorts etc) from what we loaded in for them.
- Note: I spotted now looking at the contributed designs that this is missing, but whenever the 'save new view' option is available based on the above, there should also be an action to 'save changes'. Which would update the currently selected view to be whatever the current state of the table is, instead of creating a new one with the current state.

----

> 2. How is the “edit view” stuff expected to work?

In reference to the edit action from the saved views dialog. In this case, it opens the dialog that is triggered when a new view is saved (basically just with its name as an input), so the user can rename the view itself. Editing of the actual content of the view will happen using the note above - select view from dropdown, make changes, click save changes.

**Comment by davidicus** [comment]
Moving to sprint 53 since @bjornalm is out this week.

**Comment by bjornalm** [comment]
Imagine the following scenario: 
A table initially has 10 columns without any width specified but with hasResize active. Upon the initial rendering the 10 columns are rendered by the browser and the width of each column gets measured and each column thereafter gets an internal width property which also is applied using CSS. At this stage, the table "knows" about the width of each visible column and that is needed for the column resize to work. However, the column prop has not changed and still does not specify any widths for the columns.

Now, a new column X is added (appended to the columns prop and ordering prop) and it has a specified width of 500px. The table will try to make room for the new column by shrinking the other columns. The table will not shrink any columns below the specified MIN_WIDTH and if there is not enough horizontal space the table will grow wider to fit the new column. In this case the initial columns are shrunk into MIN_WIDTH but the table still has to grow wider to fit column X. Now, yet a new column Y is added and it also has a specified width of 500px. The initial 10 columns stay at MIN_WIDTH and column X will shrink to MIN_WIDTH to make room for column Y.

At this point there is a potential conflict. The columns prop specifies that the first 10 columns don't have a width and that X and Y both have a width of '500px', but the table has resized the x column to MIN_WIDTH. If the user saves the view, the current columns prop will be used, and when this view is later loaded into a table it will render the first 10 columns (that still don't have a width defined) using MIN_WIDTH and let both X and Y be 500px as specified. Hence, the view that was rendered during save will differ from the loaded one.

Possible remedies:
a) The table will never shrink columns that have a predefined width, only columns with an undefined width, when new ones are added (or toggled for visibility). 
b) The table will never shrink any existing columns when new ones are added (or toggled for visibility) and the table always grows in width.
c) trigger the onColumnResize when the table automatically resizes the table columns as part of the add/remove column operation so that the application will have the latest version of the column widths when a view is saved.
d) We refresh the column props somehow (by force triggering the onColumnResize) before a view save

**Comment by bjornalm** [comment]
@tay1orjones @davidicus Is there a decision on what parts of the view that should/needs to be saved?

Some properties like `view.filters`, `view.table.sort` and `view.table.ordering` seem obvious. The columns prop also needs to be considered since they contain the column widths. But then there are properties like  `view.table.filteredData` that could potentially be the complete dataset...

**Comment by davidicus** [comment]
> Imagine the following scenario:
> A table initially has 10 columns without any width specified but with hasResize active. Upon the initial rendering the 10 columns are rendered by the browser and the width of each column gets measured and each column thereafter gets an internal width property which also is applied using CSS. At this stage, the table "knows" about the width of each visible column and that is needed for the column resize to work. However, the column prop has not changed and still does not specify any widths for the columns.
> 
> Now, a new column X is added (appended to the columns prop and ordering prop) and it has a specified width of 500px. The table will try to make room for the new column by shrinking the other columns. The table will not shrink any columns below the specified MIN_WIDTH and if there is not enough horizontal space the table will grow wider to fit the new column. In this case the initial columns are shrunk into MIN_WIDTH but the table still has to grow wider to fit column X. Now, yet a new column Y is added and it also has a specified width of 500px. The initial 10 columns stay at MIN_WIDTH and column X will shrink to MIN_WIDTH to make room for column Y.
> 
> At this point there is a potential conflict. The columns prop specifies that the first 10 columns don't have a width and that X and Y both have a width of '500px', but the table has resized the x column to MIN_WIDTH. If the user saves the view, the current columns prop will be used, and when this view is later loaded into a table it will render the first 10 columns (that still don't have a width defined) using MIN_WIDTH and let both X and Y be 500px as specified. Hence, the view that was rendered during save will differ from the loaded one.
> 
> Possible remedies:
> a) The table will never shrink columns that have a predefined width, only columns with an undefined width, when new ones are added (or toggled for visibility).
> b) The table will never shrink any existing columns when new ones are added (or toggled for visibility) and the table always grows in width.
> c) trigger the onColumnResize when the table automatically resizes the table columns as part of the add/remove column operation so that the application will have the latest version of the column widths when a view is saved.
> d) We refresh the column props somehow (by force triggering the onColumnResize) before a view save

I would think that `a` is the best option. If a column has a specified width I think we should try to respect that. Any column that does not have a specified width can be shrunk down to the min width but those that are specified will make the table grow to accommodate if there is not enough room.

**Comment by davidicus** [comment]
> @tay1orjones @davidicus Is there a decision on what parts of the view that should/needs to be saved?
> 
> Some properties like `view.filters`, `view.table.sort` and `view.table.ordering` seem obvious. The columns prop also needs to be considered since they contain the column widths. But then there are properties like `view.table.filteredData` that could potentially be the complete dataset...

@lukefirth @dianatran18 is there any guidance on this from the product teams? The easy answer would be to store whatever props need to be saved in order to get the same view loaded that is separate from the data. This would think this excludes the `filteredData` prop since that is a result of the applied filters. Plus that data may have changed since they saved and would like the same "view" to be applied to the updated data set.

**Comment by bjornalm** [comment]
> > @tay1orjones @davidicus Is there a decision on what parts of the view that should/needs to be saved?
> > Some properties like `view.filters`, `view.table.sort` and `view.table.ordering` seem obvious. The columns prop also needs to be considered since they contain the column widths. But then there are properties like `view.table.filteredData` that could potentially be the complete dataset...
> 
> @lukefirth @dianatran18 is there any guidance on this from the product teams? The easy answer would be to store whatever props need to be saved in order to get the same view loaded that is separate from the data. This would excludes the `filteredData` prop since that is a result of the applied filters. Plus that data may have changed since they saved and would like the same "view" to be applied to the updated data set.

Perhaps we can export everything and let the app decide what they want to use. In our Storybook example we can use `filters`, `ordering`, `activeBar` and `search` and ignore the rest.

**Comment by dianatran18** [comment]
> > @tay1orjones @davidicus Is there a decision on what parts of the view that should/needs to be saved?
> > Some properties like `view.filters`, `view.table.sort` and `view.table.ordering` seem obvious. The columns prop also needs to be considered since they contain the column widths. But then there are properties like `view.table.filteredData` that could potentially be the complete dataset...
> 
> @lukefirth @dianatran18 is there any guidance on this from the product teams? The easy answer would be to store whatever props need to be saved in order to get the same view loaded that is separate from the data. This would excludes the `filteredData` prop since that is a result of the applied filters. Plus that data may have changed since they saved and would like the same "view" to be applied to the updated data set.

I'll let @lukefirth answer for the product team requirements, but from my perspective I would agree with you David, and I would save whatever needs to be saved in order to achieve the same view I had just customized.
