### ISSUE TITLE
[DateTime Picker] z-index issue.

### ISSUE THREAD

**Issue by kalyanixraut** [carbon-design-system/carbon-addons-iot-react#1211]
### Describe the bug

DateTime picker selection panel has a high z-index and hence components like Side Nav bar or App switcher are displayed behind it.
Below screen shots are for reference.

<img width="261" alt="image" src="https://user-images.githubusercontent.com/22093326/82546122-463b6d00-9b75-11ea-8293-18e41d39c864.png">
<img width="319" alt="image" src="https://user-images.githubusercontent.com/22093326/82546162-505d6b80-9b75-11ea-9d0a-e8b6a07eb25d.png">

### Specific timeline issues / requests

We are using this component for our upcoming June 2020 release.

**Comment by davidicus** [comment]
After posing the question about z index in the [carbon components slack channel](https://ibm-ai-apps.slack.com/archives/C046Y0YUD/p1593454974052000) this seems to be an issue with Carbon. I have opened up an [issue](https://github.com/carbon-design-system/carbon/issues/6362) to track on the Carbon repo.

**Comment by davidicus** [comment]
Moving out of sprint 51 since the fix needs to be pushed to Carbon repo.

**Comment by kevinsperrine** [comment]
This should have been fixed in https://github.com/carbon-design-system/carbon/issues/6362 and our subsequent upgrades to Carbon.
