### ISSUE TITLE
[OverflowMenu] Story is extremely slow

### ISSUE THREAD

**Issue by bjornalm** [carbon-design-system/carbon-addons-iot-react#1219]
### Describe the bug
The overflowmenu is extremely slow in our story. Keyboard navigation has a delay with 1.2 seconds in Chrome and in Firefox it hardly works at all due to the delay. Firefox creates a warning asking to abort the page due to slow javascript.

This is probably not a problem when using the overflowmenu like normal in a component since if we remove the storybook actions and knobs for this story then the performance is okay.

### To Reproduce
1. Go to https://carbon-addons-iot-react.com/?path=/story/overflowmenu--basic
2. Click the button and use the keyboard to navigate the menu items

### Environment/versions:

- OS: MacOS 10.15.4
- Browser: Chrome (81.0.4044.138), Firefox (76.0.1), Safari (13.1)

**Comment by tay1orjones** [comment]
This might be related to how we import Carbon's stories and re-export them. One way to verify would be to run a profiler on this and look into the flame graph to see what's computationally expensive when the story is interacted with.
