### ISSUE TITLE
[Table]: selection box support indeterminate state based on the selection of their children state

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#124]
Pulled from comments:
> This issue clarifies the general selection state across parent and child row.
> The IoT Table component should follow the core behavior of the Carbon table component, and secondarily any common hierarchical table component row selection industry practices.
> 
> In summary
> 
> * Selection states are none (empty), all (filled), partial (dash). There are selection icons for each.
> * Selecting the parent will select all children
> * Unselecting the parent will unselect all children
> * Changing the selection of a child will change the state of the parent to partial
> * Selecting a partial parent will make the parent and children selected
> 
> Optional
> 
> * A selection state change may be revoked with a ctrl-z

**Comment by matsgothe** [comment]
This issue clarifies the general selection state across parent and child row.
The IoT Table component should follow the core behavior of the Carbon table component, and secondarily any  common hierarchical table component row selection industry practices.

In summary
- Selection states are none (empty), all (filled), partial (dash). There are selection icons for each.
- Selecting the parent will select all children
- Unselecting the parent will unselect all children
- Changing the selection of a child will change the state of the parent to partial
- Selecting a partial parent will make the parent and children selected

Optional
- A selection state change may be revoked with a ctrl-z

**Comment by matsgothe** [comment]
@scottdickerson please review

**Comment by davidicus** [comment]
This issue is stale. Closing. Please re-open if needed.

**Comment by matsgothe** [comment]
This is a base table feature. If we do row selection in a hierarchy we need this parent state visualization. Its the way hierarchies works in any tool. 
@amymillett

**Comment by bjornalm** [comment]
> @bjornalm In #1671 you mention that you would open an issue to track this work. If there is a duplicate issue can we close one of them?

That comment was about deprecating `view.table.isSelectAllSelected` and `view.table.isSelectAllIndeterminate` props and the issue created was this one: https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1673

I think the original PR https://github.com/carbon-design-system/carbon-addons-iot-react/pull/1671 solved the problems described here, but please verify that (or I can take a deeper look if you want).

**Comment by bjornalm** [comment]
Correction #1671 was only concerned with the table header checkbox, not the parent child relationships of each row. This is a new enhancement.
