### ISSUE TITLE
[Component Proposal] Combo Button

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1252]
### Summary

This has been discussed and approved in [Internal Watson-IoT/pal-tracking#291](https://github.ibm.com/Watson-IoT/pal-tracking/issues/291) to follow the Carbon implementation: https://github.com/carbon-design-system/carbon/issues/3371

If an implementation is not yet available in Carbon (as is the case presently), this should be implemented in their repository.

**To close this issue:**
This issue will be resolved when the new component/feature has been accepted and published in Carbon and our package has been updated to consume the new component/feature.

**Comment by lukefirth** [comment]
@davidicus @tay1orjones would it be possible for either of you good folks to do a quick idea of scoping on this item? 

We're seeing a lot of interest externally to IoT, and I know our Sterling siblings are interested / have an older angular implementation. I think it would be valuable to get an idea of 'cost' so someone (possibly a contributing team) could maybe have a conversation around helping out with getting this done it as a community 'good' outside of the normal IoT priority list.

**Comment by davidicus** [comment]
this has been implemented.
