### ISSUE TITLE
[Pagination]: icon size in buttons should be 16 - Bring in from Carbon

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1257]
Will contribute this directly to Carbon: https://github.com/carbon-design-system/carbon/issues/6057

**Comment by tay1orjones** [comment]
This has been merged in https://github.com/carbon-design-system/carbon/pull/6058, we're awaiting it to be published in a new version.

We can close this once we've updated to the Carbon version where this change is available.

**Comment by davidicus** [comment]
Putting off upgrading Carbon until next sprint.

**Comment by tay1orjones** [comment]
This was closed in #1323
