### ISSUE TITLE
[Dropdown | Search | ComboBox] Place custom content inside dropdown/autosuggest box

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1273]
### Summary

Extension to all components that have the 'box' that appears below them when a user interaction (eg: Search, combo-box, dropdown). And allows custom things to be placed inside to enabled a variety of use cases.

**Additional context**
From 
[Internal Watson-IoT/pal-tracking#255](https://github.ibm.com/Watson-IoT/pal-tracking/issues/255)

> Example 1: 
> Used in searching
> ![image](https://media.github.ibm.com/user/684/files/be946000-48ef-11ea-8b4d-c73dc3875f80)
> 
> Example 2: 
> Placing buttons inside a dropdown
> ![image](https://media.github.ibm.com/user/684/files/d9ff6b00-48ef-11ea-8784-f41c17f1c7ae)

**Comment by bjornalm** [comment]
FYI. This is a related discussion from Carbon of allowing custom content as the selected value in the Dropdown component. 
https://github.com/carbon-design-system/carbon/pull/5578

**Comment by tay1orjones** [comment]
Increasing to a val: 2 because a dependent item https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1259 is val: 2.

**Comment by tay1orjones** [comment]
The Dropdown portion of this item will be delivered in #1259 - the Search and Dropdown portions will be delivered separately. So I'm removing the dependency on #1259 and we'll instead treat this as an umbrella issue for the three separate use cases:

1. Dropdown 1 #1259 
1. Search - Issue not yet created
1. ComboBox - Issue not yet created

**Comment by davidicus** [comment]
New guidance available. Closing this issue as out of date
