### ISSUE TITLE
[Component Proposal] HistogramCard

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1274]
### Summary

An extension to dashboard cards to support the histogram charting type.

**Additional context** 
From [Internal Watson-IoT/pal-tracking#275](https://github.ibm.com/Watson-IoT/pal-tracking/issues/275)

> Rationale: Same as the histogram + the fact we deliver charts mostly through dashboards.
> 
> 
> ![image](https://media.github.ibm.com/user/684/files/cc40e100-5304-11ea-811f-4d86e868b4b8)
> 
> Detail design can be provided when issue is in scope.
> 
> 
> **Inspiration from other products**
> https://github.ibm.com/Watson-IoT/pal-tracking/issues/193

**Comment by tay1orjones** [comment]
There's a WIP PR open on carbon charts https://github.com/carbon-design-system/carbon-charts/pull/604

**Comment by davidicus** [comment]
Closing as implementation will come from Carbon charts
