### ISSUE TITLE
[Component Proposal] HeatMapCard

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1285]
### Summary

HeatMap charting type should be available as a card for the dashboard.

**Additional context**
From [Internal Watson-IoT/pal-tracking#192](https://github.ibm.com/Watson-IoT/pal-tracking/issues/192)

Ideally we'll use a HeatMap charting type available in `@carbon/charts`. To my knowledge this is not in progress for them currently, there isn't an issue to track other than https://github.com/carbon-design-system/carbon-charts/issues/359

**If someone on our team intends to implement a HeatMap, it should be contributed to `@carbon/charts` directly** and then the HeatMapCard created in this repository.

There is guidance for HeatMaps on the Carbon Design System website ([link](https://www.carbondesignsystem.com/data-visualization/advanced-charts/#heatmap))

**Comment by davidicus** [comment]
@dianatran18, is there an updated design for this item?

**Comment by dianatran18** [comment]
For any charts on cards in a dashboard, we generally pointed to the Carbon Charts work and provided guidance on the card container itself, and some legend placement. 

That said, we haven't look at heat maps as a charting type on the PAL side yet.

**Comment by davidicus** [comment]
Closing as implementation will come from Carbon charts.
