### ISSUE TITLE
[ComposedModal] it's setting unused classes for error-modal and big-modal

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#1301]
### Describe the bug
See in the source the ComposedModal sets two classnames that it no longer uses.  Plus these aren't prefixed so can collide with other product classes
 className={classNames(className, {
          'error-modal': type === 'warn',
          'big-modal': isLarge,
        })}

**Comment by sstone2423** [comment]
This got fixed at some point
