### ISSUE TITLE
[Card] i18n labels should support nodes or strings

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#1307]
### Describe the enhancement

Depending on your internationalization library, the i18n labels might be returned as a React element rather than a string.  For example <FormattedMessage /> from react-intl.  

this enhancement request is to support PropTypes.node for all the internationalized labels of our elements

**Comment by tay1orjones** [comment]
If possible, could we use `oneOfType` with `Element` instead?
```
PropTypes.oneOfType([
  PropTypes.string,
  PropTypes.element
]),
```

**Comment by JordanWSmith15** [comment]
Closing as stale
