### ISSUE TITLE
[Button] RTL + icons not supported by Carbon

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-addons-iot-react#1317]
In RTL mode, Carbon button does not move the location of the icon to the left.
1. Go to https://carbon-addons-iot-react.com/?path=/story/watson-iot-button--default
2. Select any icon
3. Set to RTL
![image](https://user-images.githubusercontent.com/21066152/84909270-7813f680-b083-11ea-9616-d114e83afe60.png)

**Comment by JordanWSmith15** [comment]
Blocking https://jsw.ibm.com/browse/GRAPHITE-13618

**Comment by tay1orjones** [comment]
Carbon has stated they don't directly provide RTL styling but instead encourage the use of an RTL preprocessing library like RTLCSS to automatically convert directionally-aware properties to an appropriate inverse. For example `margin-left: 1rem;` to `margin-right: 1rem;`

It's possible correct this defect by providing a direct RTL style like:

```css
.#{prefix}--btn:dir(rtl) {
  margin-left: 0:
}
```

or something similar to that, but it may have unintended effects for other consumers that may already be using RTLCSS.

The primary solution for these types of issues right now would be to include RTLCSS as a build step and provide the output when the html direction is RTL.
