### ISSUE TITLE
[Carbon] Update carbon's combobox feature to allow for extension

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#1324]
The changes made in [this]() PR require additional changes to the upstream carbon component. This issue is mean to track that work.

Change required is to the `findHighlightedIndex`, `onHighligtedIndexChange`, and a `handleOnChange` function. Take the changes from our local version and apply to the carbon code base. 

Once this work is complete we will need to consume and refactor our own which will be tracked in #1323

**Comment by JordanWSmith15** [comment]
ComboBox is not a scalable component for MAS data sets. Lowest priority.

**Comment by davidicus** [comment]
closing for now. I think we have consumed necessary changes.
