### ISSUE TITLE
[Component Proposal] BulletGraphCard

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1343]
From 
[Internal Watson-IoT/pal-tracking#271](https://github.ibm.com/Watson-IoT/pal-tracking/issues/271)

> **Is this an extension to an existing component, pattern, or a brand new asset?**
> And extension to the dashboard cards to enabled a bullet graph charting type
> 
> **What is the rationale for this contribution.**
> All the rationale of the bullet graph, plus the fact that most of our charting requirements are needed in dashboards.
> 
> 
> **Detail the intended behavior**
> ![image](https://media.github.ibm.com/user/684/files/30ad7180-5300-11ea-94e1-d1b3b1a8c179)
> 
> 
> Detail design can be provided when in scope.
> 
> 
> 
> **Inspiration from other products**
> Reference original charting issue: https://github.ibm.com/Watson-IoT/pal-tracking/issues/189

**Comment by davidicus** [comment]
closing. Implementation is coming form Carbon charts.
