### ISSUE TITLE
[Component Proposal] SlopeChartCard

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1345]
From [Internal Watson-IoT/pal-tracking#196](https://github.ibm.com/Watson-IoT/pal-tracking/issues/196)

> **Is this an extension to an existing component, pattern, or a brand new asset?**
> This is an EDS item
> 
> **What is the rationale for this contribution.**
> The slope chart is highly effective at providing trend insight at extreme speed in a small space by restricting what a user has to consider to only 2 data points.
> 
> **Detail the intended behavior**
> A two data point line chart, notably missing the lower axis.
> 
> Image:
> ![image](https://media.github.ibm.com/user/684/files/bd3f6900-200b-11ea-8404-c0f643d13206)
> 
> 
> 
> Found at: https://ibm.invisionapp.com/share/U2NYW8D7DFV#/screens/319100274
>

**Comment by davidicus** [comment]
closing. Implementation is coming form Carbon charts.
