### ISSUE TITLE
[Component Proposal] MapComponent exploration

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1347]
### Summary

Component containing mapping capabilities. ~More TBD coming from the dashboarding guild~ 

Outcomes from dashboard guild have been published [here](https://pages.github.ibm.com/ai-applications/design/patterns/maps/overview). For this issue we need to see what pieces are common among map providers like Mapbox, Esri.com, 

Related
[Internal Watson-IoT/pal-tracking#222](https://github.ibm.com/Watson-IoT/pal-tracking/issues/222)
[Internal Watson-IoT/pal-tracking#481](https://github.ibm.com/Watson-IoT/pal-tracking/issues/481)

**Comment by tay1orjones** [comment]
TBD depending on outcomes from the dashboarding guild. 

I'm going to broaden this issue until we hear from the dashboard guild as to two use cases:

1. An interactive map placed in a card to be put on a dashboard
1. An interactive map that is larger, potentially full screen, with many data points/layers/etc.

**Comment by katedraper** [comment]
@davidicus did the dashboard guild ever provide more guidance on the 2 use cases?

**Comment by davidicus** [comment]
The outcomes from the design map exploration have been published on our internal site [here](https://pages.github.ibm.com/ai-applications/design/patterns/maps/overview)

**Comment by katedraper** [comment]
For more background on this item, the MAS team would like to understand what the Health team did for Maps in Graphite for the upcoming MAS v8.4 release to ultimately determine how to leverage the design and component.

**Comment by davidicus** [comment]
May need to look into open layers implementation. Check with Ron Baker for the use cases for this specific technology

**Comment by katedraper** [comment]
Health and Predict designs:
 
Prototype
https://ibm.invisionapp.com/share/APNZ6UW9Z5B#/319820201_APM_Map_-_Map_-_Cluster_Disabled
 
Flow
https://ibm.invisionapp.com/share/APNZ6UW9Z5B#/319900432_Grid_And_Map
 
Environment
http://health-team31.rtp.raleigh.ibm.com:9080/maximo_123/oslc/graphite/relengineer/index.html#/
 
Sketch files
https://ibm.box.com/s/k1uzysok8shrpxypnpe2a91xvkx5byba

These were shared by Steven (stevench@cn.ibm.com).

**Comment by davidicus** [comment]
Exploration is complete for now. Going to track implementation of the component in #2157. The PAL will only be able to provide overlay components that each map provider can wire up to control the map. #2157 will include stories with at least two implementations from MapBox and Openlayers.
