### ISSUE TITLE
[Table/List] Create an error state story to show a best practice error condition

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#1355]
### Describe the bug

To ensure consistency across PAL components, we should add a common UX across our components to indicate Error when loading the data

Currently we are reusing the Empty State prop to display errors, but perhaps we should have a specific 'Error' prop added to each component that renders these errors in a consistent fashion

**Comment by bjornalm** [comment]
If doing that, then we could look at the ValueCard for inspiration since it has implemented a specific error message design.

**Comment by tay1orjones** [comment]
@lukefirth @dianatran18 is there a specific design we should consolidate on here?

**Comment by dianatran18** [comment]
That's a great point. 

Can we gather some existing examples of what some error states look like today in product? Then we can start looking into how to get them consistent.
