### ISSUE TITLE
[CardRenderer] don't force card availableActions 

### ISSUE THREAD

**Issue by alronz** [carbon-design-system/carbon-addons-iot-react#1362]
### Summary

The current behavior in the card render is to [force the card's availableActions (range and expand flags)](https://github.com/IBM/carbon-addons-iot-react/blob/v2.98.0/src/components/Dashboard/CardRenderer.jsx#L112-L120) such that all cards should have a range action and based on the card type, it may or may not be expanded. 

In our use case, we prefer to disable the range action for all the cards, however this is not possible. Therefore, it would be great if you make it possible to override this.

**Comment by tay1orjones** [comment]
The decision was made recently in #1333 to deprecate the `Dashboard` and `CardRenderer` in favor of composing `Card` components directly with `DashboardGrid`.

This is a good example as to why - the `Dashboard` and `CardRenderer` came from a single offering and have a lot of non-configurable preferences baked in that limit its use.

I think this is a reasonable ask and would accept a PR, but know that in the future the intent is that the logic of CardRenderer should be contained at the application level.
