### ISSUE TITLE
[StatefulTable] rowActions on children rows not working 

### ISSUE THREAD

**Issue by alronz** [carbon-design-system/carbon-addons-iot-react#1363]
### Describe the bug

There is a possible bug in [this line ](https://github.com/IBM/carbon-addons-iot-react/blob/v2.98.0/src/components/Table/StatefulTable.jsx#L163) where it doesn't consider the actions of the children rows and I get the following error (it even happens in the storybook demo):

![Annotation 2020-07-06 115120](https://user-images.githubusercontent.com/7453308/86581716-ca5c7f00-bf80-11ea-83cd-fe9489a24b8a.png)

### To Reproduce

1. Go to [this storybook](https://carbon-addons-iot-react.com/?path=/story/watson-iot-table--stateful-example-with-row-nesting-and-fixed-columns) 
2. Click on action of nested row
3. you get the mentioned error

### Expected behavior

Action on nested row should be triggered

### Environment/versions:

- OS: windows
- Browser: chrome
- `carbon-addons-iot-react` version: [e.g. `v2.98.0`]

**Comment by tay1orjones** [comment]
Thanks for opening this @alronz - it does look like something that should be fixed. The current implementation doesn't take into account the nested items. There is no limit to the nesting of rows, so it needs to be modified to recursively search for nested rows.
