### ISSUE TITLE
[Component Proposal] dashboard builder/editor

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1372]
### Summary

<details>
  <summary>Click to expand original spec (that is now outdated) from <a href="https://github.ibm.com/Watson-IoT/pal-tracking/issues/177">Internal Watson-IoT/pal-tracking#177</a></summary>

> **Is this an extension to an existing component, pattern, or a brand new asset?**
> This is an EDS component.
> 
> **What is the rationale for this contribution.**
> This contribution provides a mechanism for users to easily build a dashboard with a floating palette of available options that can be moved around in order to not get in the way, while being searchable for valid items that could be added to the underlying dashboard canvas.
> 
> This is beneficial over typical dialogs in that the user does not need to constantly incur, pick, incur, pick over and over to populate a board.
> 
> Equally, this is beneficial over a side panel or similar that sits on the same plane as the canvas, as this will impact the layout of the dashboard by altering its available width.
> 
> **Detail the intended behavior**
> 
> * The palette will 'float' like a dialog over the top of the typical page content.
> * By default its location will appear in the approximate bottom left of the view port.
> * It will need be either be docked by the implementer, or free to drag by the user.
> * It may begin in an empty search state (small):
>   Image:
>   ![image](https://media.github.ibm.com/user/684/files/4acf8880-200d-11ea-9233-64f2c5819d55)
> * In this case, a search will reveal a list of tiles, possibly grouped into accordions if categorized. Similarly, the palette may load already with a list of tiles populating it without the need to search.
>   Image:
>   ![image](https://media.github.ibm.com/user/684/files/53c05a00-200d-11ea-9412-da7060ccff1d)
>   ![image](https://media.github.ibm.com/user/684/files/5fac1c00-200d-11ea-857d-6e68b53a49e9)
> 
> **Note:** This will need to be an implementation option as the decision to be empty unless search, or populated and search filters/populates with alternatives will depend on what it is being used for.
> 
> * The tiles can be double clicked to add automatically to the next available spot in the dashboard/target area being populated by the palette, or drag and dropped to a specific location on the canvas.
>   Image:
>   ![image](https://media.github.ibm.com/user/684/files/689ced80-200d-11ea-9dcc-40b4ef05320c)
> * When dragged, the tile will change visual look from the small overview version shown in previous screens, to the actual dashboard card/resource being dropped, so users understand the size and look of what they are working with (it would be impractical to keep actual size/look cards in the palette).
>   Image example:
>   ![image](https://media.github.ibm.com/user/684/files/6dfa3800-200d-11ea-85bb-2f6ee2638a6d)
> 
> Found here: https://ibm.invisionapp.com/share/U2NYW8D7DFV#/screens/319194960
> 
> **Note:** The draggable floating dialog element to this is very similar to a form of 'modeless dialog' as expressed in some of the new Carbon dialog pattern work [found here](https://carbon-website-git-fork-aagonzales-dialog-pattern.carbon-design-system.now.sh/patterns/dialog-pattern) We should be sure to leverage this if and where possible in the implementation of this component.
> 
> **Inspiration from other products**
> Used in the EDS dashboard configuration pattern: https://ibm.invisionapp.com/share/U2NYW8D7DFV#/screens/319117751

</details>

Update as of Sept 1 2020:
> New concept design here: https://ibm.invisionapp.com/share/RXO0ECHKZ72#/screens/319676919
> Summary of design: https://ibm.box.com/s/2bspt4yf9mqe5dlv7ugfc8mmqm4kbd6w

**Comment by tay1orjones** [comment]
TBD depending on the outcome of the dashboarding guild.

**Comment by ajnaddell** [comment]
New concept design here: https://ibm.invisionapp.com/share/RXO0ECHKZ72#/screens/319676919

**Comment by tay1orjones** [comment]
Based on the updated spec I have created 4 new issues that encompass the bulk of this functionality:

#1560
#1561 
#1562
#1563

We can consider this an umbrella issue and close it when the above items are complete and we feel that they've been sufficiently documented in the storybook and on the PAL website

**Comment by sstone2423** [comment]
FYI, this issue isn't blocked. @JoelArmendariz and I are actively working on this

**Comment by tay1orjones** [comment]
Thanks for the heads up! It's so easy for labels on umbrella issues to get out of date. 

There are also some new items that will be under this umbrella issue:

#1739 
#1740  
#1741

**Comment by sstone2423** [comment]
This has been completed
