### ISSUE TITLE
[Table] Column overflow menu 

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1375]
### Summary

From [Internal Watson-IoT/pal-tracking#161](https://github.ibm.com/Watson-IoT/pal-tracking/issues/161)

> **Is this an extension to an existing component, pattern, or a brand new asset?**
> This is an EDS item
> 
> **What is the rationale for this contribution.**
> Certain table actions (to come) affect only a specific column of data, this contribution covers a mechanism for how to access/apply these actions using an overflow menu.
> 
> **Detail the intended behavior**
> Include mockups of any fidelity, the more spec the better as this will enable higher quality feedback and evaluation.
> 
> Image:
> ![image](https://media.github.ibm.com/user/684/files/cd0c7c80-200e-11ea-8eee-e6453afa460e)
> 
> **Inspiration from other products**
> (Optional - remove this is you don't have any)

**Comment by tay1orjones** [comment]
This will probably be delivered alongside freeze column or multi-sort as both of those are dependent on this issue.

- `Table` will render the overflow menu if the column has an `options` object. Each item in the object will be placed as an option within the overflow menu. When an item is selected, `Table` will call a callback action with the selected item.
- `StatefulTable` will take advantage of this feature to implement the freezing of columns #1377   and the multi-sort of columns #1376  .

**Comment by tay1orjones** [comment]
Moving this up to a val:2 as it's blocking items that have a val:2

**Comment by lukefirth** [comment]
I'll weigh in some thoughts here. 

Same as what @dianatran18 mentions in the associated slack thread would be my expectation, but I'm very open to technical consideration:
- The 'click the whole column header to sort' is an interaction I'd say is deeply seated in the table, and likely in user expectation. So we don't want to mess with that as much as possible. 
- With this in mind, I wonder if it's a z-index thing -to 'float' the overflow above the existing click target of the column header itself.
- That being said, RE: @dianatran18 's questions around minimum column width, the expectation here would be that the overflow would influence wrapping/truncation in the same way that the icon for sorting does.
