### ISSUE TITLE
[Repo] Remove console noise in our test output

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#1382]
When running test the log can be quite busy. Its hard to read important information in the logs amongst all the noise. 

We should refactor components to get rid of console warnings and deprecation notices.

**Comment by bjornalm** [comment]
Yes great. Perhaps this deserves another issue but there is still a console warning from the `TileGallery` when running the Storybook so it would be nice to get rid of that one as well.

**Comment by davidicus** [comment]
> Yes great. Perhaps this deserves another issue but there is still a console warning from the `TileGallery` when running the Storybook so it would be nice to get rid of that one as well.

Yes. I think this issue should fix that console warning in storybook.

**Comment by davidicus** [comment]
Will complete when we have a lull in priorities.
