### ISSUE TITLE
[Table] Regression: Can no longer change the search via props on table

### ISSUE THREAD

**Issue by stuckless** [carbon-design-system/carbon-addons-iot-react#1386]
### Describe the bug

When a table is created if you later set new props on the table with a search the table ignores it.

### To Reproduce

```
  test('toolbar search should render with default value', () => {
    const wrapper = mount(
      <Table
        columns={tableColumns}
        data={tableData}
        actions={mockActions}
        options={{
          hasSearch: true,
        }}
        view={{
          toolbar: {
            search: {
              defaultValue: '',
            },
          },
        }}
      />
    );

    expect(wrapper.find('.bx--search-input')).toHaveLength(1);
    expect(wrapper.find('.bx--search-input').prop('value')).toEqual('');
    expect(wrapper.find('.bx--search-input').html()).toContain(`aria-hidden="true"`);

    wrapper.setProps({ view: { toolbar: { search: { defaultValue: 'ferrari' } } } });
    wrapper.update();

    expect(wrapper.find('.bx--search-input').prop('value')).toEqual('ferrari');
    expect(wrapper.find('.bx--search-input').html()).toContain(`aria-hidden="false"`);

    wrapper.setProps({ view: { toolbar: { search: { defaultValue: '' } } } });
    wrapper.update();

    expect(wrapper.find('.bx--search-input').prop('value')).toEqual('');
    expect(wrapper.find('.bx--search-input').html()).toContain(`aria-hidden="true"`);
  });
```

### Expected behavior

Updating the props should update the table.

### Additional Notes

The test I pasted in there is the ORIGINAL TEST.  I guess when you upgraded Carbon this test broke, and the fix, apparently was to rewrite the test logic and not test the original behaviour that this test was testing for.  So in essence the fix was to remove the failing test.  If you upgrade carbon and a test requires that you need to refactor the logic of your test, that should send alarm bells that Carbon just broke you... and you are going to break someone else, if you continue.  Rewriting the test logic to test for something completely different, is an effective way to get tests to pass, but it invalidates the purpose to have testing in the first place :(

https://github.com/IBM/carbon-addons-iot-react/commit/5289496c89a49b3d99348fe06d97c9793b02969d#diff-f47894e32d4dbf684d2ac3f89df148c9

**Comment by davidicus** [comment]
Re-opening. The fix for this causes focus to be lost when typing into the search bar.

**Comment by tay1orjones** [comment]
Yeah - I can further clarify when the key should be updated. The `key` should not be updated if the `defaultValue` is being set/updated by the `onChange`/`onApplySearch`. I'll work to push another fix today.
