### ISSUE TITLE
[ImageCard] Zoom buttons go off screen when zoomed in

### ISSUE THREAD

**Issue by JesseSprinkle** [carbon-design-system/carbon-addons-iot-react#1390]
![Screen Shot 2020-07-10 at 1.00.02 PM.png](https://images.zenhubusercontent.com/5ee92b8546aa353f4907eca6/ab3dedf3-6931-4033-955a-0b69c393cec1)

From the html it looks like the zoom buttons positions are dependent on the edge of the image, not the edge of the container, so when you zoom in they go off screen.

**Comment by kevinsperrine** [comment]
This has been fixed. https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-imagecard--basic The zoom buttons are now positioned absolutely relative to the container.
