### ISSUE TITLE
CSS compiled css contains & chars

### ISSUE THREAD

**Issue by stevendwood** [carbon-design-system/carbon-addons-iot-react#1398]
### Summary

Seems like the built CSS in /lib/css contains & chars. postcss with rollup complains about them if you include that file.  It works OK if you just reference .scss - maybe that is the correct usage, but thought I would ask here.

**Comment by tay1orjones** [comment]
Hi @stevendwood 👋  

Sorry for the lack of response here, this issue fell through the cracks unfortunately. Good news though - this was fixed in https://github.com/carbon-design-system/carbon-addons-iot-react/pull/1715 and is available in `v2.140.0-next.4`
