### ISSUE TITLE
[List] propType warning

### ISSUE THREAD

**Issue by sstone2423** [carbon-design-system/carbon-addons-iot-react#1410]
### Describe the bug

The following warning is given when using HierarchyList, but I believe its coming from the underlying ListItem

![Screen Shot 2020-07-17 at 12 11 44 PM](https://user-images.githubusercontent.com/25177649/87813008-b2a9b400-c826-11ea-98e8-1bceaf25627a.png)

### To Reproduce

1. Go to implementation of a List
2. See propType warning
- It is intermittent as I think it requires just the right props to throw the warning for some reason

### Environment/versions:

- OS:  MacOS
- Browser:  chrome
- `carbon-addons-iot-react` version: 2.100.0

### Specific timeline issues / requests

No specific time

**Comment by tay1orjones** [comment]
I'm delivering a fix for this alongside #1664
