### ISSUE TITLE
[SimpleList / ListItem / TileCatalogNew] fix snapshot unique key warnings

### ISSUE THREAD

**Issue by sstone2423** [carbon-design-system/carbon-addons-iot-react#1412]
### Describe the bug

Multiple unique key warnings are being thrown in SimpleList, ListItem, and TileCatalogNew. I've added a snapshot exception  in https://github.com/IBM/carbon-addons-iot-react/pull/1414 for all 3 components as they're causing the snapshots to fail 

### To Reproduce

1. Re-enable the snapshots by removing the regex exception in `StorybookSnapshots.test.js`
2. Run `yarn test:update`
3. See unique key warnings

### Expected behavior

Snapshots should pass with no warnings or errors

### Environment/versions:

- OS: MacOS
- Browser: chrome
- `carbon-addons-iot-react` version: v2.100.2

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

No specific timeline, but non-unique keys can cause unexpected behavior in production

**Comment by sstone2423** [comment]
Looks like I already had an issue open for List as well. Can probably close https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1412 in favor of this one

**Comment by tay1orjones** [comment]
I'm delivering a fix for this alongside https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1664
