### ISSUE TITLE
Experimental components are not using snapshot testing

### ISSUE THREAD

**Issue by sstone2423** [carbon-design-system/carbon-addons-iot-react#1413]
### Describe the bug

Experimental components are not using snapshot testing, meaning there is a loss of actual test coverage when there is indeed stories that could be used for snapshots.

### Expected behavior

All components should have stories and they should all be using snapshot testing

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

Working on myself

**Comment by tay1orjones** [comment]
@sstone2423 what is remaining for this one?

**Comment by sstone2423** [comment]
Meant to tag the other issue before. Here's the remaining components that have not been enabled because of errors: https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1412

**Comment by tay1orjones** [comment]
Going to close this as it's primarily complete - we'll track the re-enabling of the ones with errors in #1412
