### ISSUE TITLE
[sassMsgFormatter] linting violations are printed twice

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1416]
### Describe the bug

Original bug report from @rawa-resul on slack. Sass unit linting errors appear to be printed twice per occurence. 

![Screenshot 2020-07-20 at 17 01 08](https://user-images.githubusercontent.com/3360588/87959697-e5e38180-ca78-11ea-98d6-a0da7ebebc25.png)

Based on the line numbers, I think we just need to check and only print the error/warning once per line instead of once per occurence?

**Comment by soniadeveloper** [comment]
Some notes on the error is that it happens when stylelint is automatically called when committing, but not when manually running yarn lint. I'll be looking into why it happens when committing specifically.
