### ISSUE TITLE
When column is set to always wrap, the "Link" component still does not wrap

### ISSUE THREAD

**Issue by lukefirth** [carbon-design-system/carbon-addons-iot-react#1431]
Migrated from internal issue: https://github.ibm.com/Watson-IoT/pal-tracking/issues/443

Opened on behalf of Yajin Zheng

In table columns, when column resize is active, and columns are set to always wrap, the "Link" component still does not wrap. 
<img width="592" alt="image-2020-05-20-13-04-39-286" src="https://media.github.ibm.com/user/17018/files/2479a880-a4da-11ea-9371-1da0aae90eeb">

Environment:
(see internal issue)

**Comment by bjornalm** [comment]
Probably related to this one https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1262
It might already have been solved.

**Comment by JordanWSmith15** [comment]
Fixed
