### ISSUE TITLE
[Pie & donut charts] Create dashboard ready widgets with these chart types.

### ISSUE THREAD

**Issue by lukefirth** [carbon-design-system/carbon-addons-iot-react#1433]
Migrated from internal issue: https://github.ibm.com/Watson-IoT/pal-tracking/issues/47

I'm sorry this doesn't fit the templates well 😢  but its basically creating a dashboard card, like [these bar chart ones](https://carbon-addons-iot-react.com/?path=/story/watson-iot-barchartcard--simple-bar-horizontal) for two newly available Carbon chart types, the pie and the donut.

**Comment by kevinsperrine** [comment]
The GaugeCard (Donut) and PieChartCard are already implemented and have example stories.
