### ISSUE TITLE
[Component proposal] AreaChartCard

### ISSUE THREAD

**Issue by lukefirth** [carbon-design-system/carbon-addons-iot-react#1434]
Sorry again that this doesn't fit the templates. 😢 

Migrated from internal issue: https://github.ibm.com/Watson-IoT/pal-tracking/issues/49

Basically this is tracking the creation of dashboard cards (just like the [bar chart card)](https://carbon-addons-iot-react.com/?path=/story/watson-iot-barchartcard--grouped-bar-vertical) using the [area chart types](**url**) now available from Carbon charts,

![image](https://user-images.githubusercontent.com/30671949/88412874-d5e0e000-cd9f-11ea-9598-3e6428f91632.png)

**Comment by davidicus** [comment]
closing. Implementation is coming from Carbon charts.
