### ISSUE TITLE
[Component Proposal] Marketplace: Product item in cart - summary

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1442]
### Summary

From @lukefirth via [Internal Watson-IoT/pal-tracking#139](https://github.ibm.com/Watson-IoT/pal-tracking/issues/139)

> **Is this an extension to an existing component, pattern, or a brand new asset?**
> Item from the EDS.
> 
> **What is the rationale for this contribution.**
> ![image](https://media.github.ibm.com/user/684/files/27fb2b00-1b5a-11ea-90c8-0a7a87bbb9a3)
> 
> This component stands to support marketplace type patterns with a 'cart' preview list.
> 
> The concept rationale behind this contribution is to provide a highly lightweight view of the items a user has added to their 'cart' in any marketplace/catalog type pattern where appropriate.
> 
> **Detail the intended behavior**
> This appears in a list format in a flyout when users choose to preview their cart of selected resources, with a simple small thumbnail, title, subtitle, and single action to remove from cart. There is no further interaction.
> 
> **Inspiration from other products**
> 
> * It can be found as an item at this link: https://ibm.invisionapp.com/share/U2NYW8D7DFV#/screens/319196743
> 
> And can be seen in usage in the PAL as shown below:
> ![image](https://media.github.ibm.com/user/684/files/afe13500-1b5a-11ea-8fa8-21deb8228ebc)

**Comment by davidicus** [comment]
no longer valid. closing.
