### ISSUE TITLE
[OverflowMenu] support selectable items

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1444]
### Summary

From @lukefirth via [Internal Watson-IoT/pal-tracking#143](https://github.ibm.com/Watson-IoT/pal-tracking/issues/143)

> **Is this an extension to an existing component, pattern, or a brand new asset?**
> Item from the EDS.
> 
> **What is the rationale for this contribution.**
> ![image](https://media.github.ibm.com/user/684/files/4c1c3380-1b7d-11ea-9990-523e4621ade3)
> This allows users to incur a set of options from a single icon, rather than from the large traditional multi-select input box for use in places where a traditional multi-select will not fit. Equally, the addition of an action allows users to add items to this list via some form of input flow (not shown - will be dependant on the resource being added).
> 
> Found as the second item on this page: https://ibm.invisionapp.com/share/U2NYW8D7DFV#/screens/319196744
> 
> **Note:** The only place at time of writing I have observed this, is in the Guidea proposal for column picking in tables, which IoT has moved away from. For this reason this may be worthy of a low priority ranking.
> 
> **Detail the intended behavior**
> An overflow triggered by interacting with an icon button, displaying a flat list of selectable items. Checking each will make that item appear in whatever this overflow is controlling, and deselecting will reverse this behaviour.
> 
> Secondly, the add button at the top of the list will trigger an add flow for whatever the items being listed are when in use.
> 
> Other overflow behaviors such as dismissal when clicking outside of the menu itself are also expected here.
> 
> **Inspiration from other products**
> In use in the PAL for column picking in tables as shown:
> ![image](https://media.github.ibm.com/user/684/files/686ca000-1b7e-11ea-81a6-b68263e1a863)

**Comment by davidicus** [comment]
Since this is possible to implement using the flyout menu and since Carbon is planning on refactoring their OverflowMenu I am going to pause this issue until the update from Carbon. Feel free to address in our priority calls if need dictates.

**Comment by kevinsperrine** [comment]
Since Carbon v10.36. The new OverflowMenu that uses the new Menu component is available via a v11 feature flag. https://github.com/carbon-design-system/carbon/blob/v10.36.0/packages/react/src/components/OverflowMenu/index.js

**Comment by davidicus** [comment]
Closing as it can be implemented using list and our flyout menu. Can revisit if there is a need for alignment.
