### ISSUE TITLE
[Component Proposal] RuleBuilder

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1445]
The original design has been significantly altered. The new prototype can be found [here](https://ibm.invisionapp.com/share/2YO0PTTRHKU#/319789253_Adv-_Filter-_5-_Add_Rule)

This feature is made up of several components that will have their own issues to track. This issue will be used to track the completion and composition of the various pieces. 

### ~~Summary~~

~~From @lukefirth via [Internal Watson-IoT/pal-tracking#145](https://github.ibm.com/Watson-IoT/pal-tracking/issues/145)~~

> **~~Is this an extension to an existing component, pattern, or a brand new asset?~~**
> ~~This is an EDS item.~~
> 
> **~~What is the rationale for this contribution.~~**
> ~~In many patterns in the EDS, a semi-visual builder is used to form logical expressions (not to be confused with the expression builder...) for use in filters, rule monitors, and more.~~
> 
> ~~This is a mega-component that allows users to type and click in order to formulate a logic tree which will do something when one full route becomes TRUE.~~
> 
> ~~This can be found with its own page here: https://ibm.invisionapp.com/share/U2NYW8D7DFV#/screens/319100296~~
> 
> **~~Detail the intended behavior~~**
> ~~Strap in, this is a long one.~~
> 
> 1. ~~The user is greeted with a text input, and a + / - pair of actions (please ignore incorrect button ordering) and are invited to add a condition (term) to the rule.~~
>    ![image](https://media.github.ibm.com/user/684/files/5987ec80-1b82-11ea-839e-e014a935a0e7)
> 2. ~~When the user interacts with said text input, a number of options will be provided to them to select from, based on the resources (Keys) that the particular type of rule can work with.~~
>    ![image](https://media.github.ibm.com/user/684/files/77ede800-1b82-11ea-9c57-e9911cc99410)
> 3. ~~Selecting a resource (key) will then add it as a 'block' to the input, and immediately create and apply focus to a second area inside the input for supplying the operator. To support in selection, the whole input will suggest valid values for this stage too below.~~
>    ![image](https://media.github.ibm.com/user/684/files/bc798380-1b82-11ea-8021-b043e0a6b63a)
> 4. ~~Once the initial resource (key) has been picked and the operator selected, a third input block will appear in the set, again with focus applied, and the dropdown below will provide selectable options.~~
>    ![image](https://media.github.ibm.com/user/684/files/edf24f00-1b82-11ea-8075-16d1c0928392)
> 5. ~~Now a complete condition on the resource (key term) has been set, focus is applied back to the containing input, and the dropdown will suggest resources (keys) again.~~
>    ![image](https://media.github.ibm.com/user/684/files/3e69ac80-1b83-11ea-96a8-bddec7a01bc0)
> 6. ~~Skipping ahead, multiple of these can be put together to create a more complex term, in this case a second has been added, and demonstrates an error state:~~
>    ![image](https://media.github.ibm.com/user/684/files/60632f00-1b83-11ea-8c05-b4b4280388e6)
> 7. ~~Clicking the [+] in the button pairing at the end will add a new row (default to OR but can be changed to AND, although this blurs when you'd add a new set vs keep adding to one big set...) of terms that can be added, allowing for complex rules to be built.~~
>    ![image](https://media.github.ibm.com/user/684/files/96a0ae80-1b83-11ea-8d65-b0a16aa31878)

### ~~Specific timeline issues / requests~~

~~The internal issue issue has a comment with a potential partial contribution of this item coming from a product team in Q4. We should follow up on this.~~

**Comment by tay1orjones** [comment]
This is much more of an epic item - there's _many_ components within this that need to be built and individually tested to make up this much broader UX pattern/flow. Also major a11y implications throughout the entire flow. 

When this becomes prioritized, we will need to break this apart into smaller deliverable pieces.

**Comment by bjornalm** [comment]
@lukefirth @davidicus I'm not sure if the design and functionality is already set for this feature, but I would love to be a part of this. I have plenty experience of creating visual business rule editors and can hopefully contribute here.

**Comment by ajnaddell** [comment]
Is this only for rules or can this be leveraged for non-rule use cases (filtering, applying functions or scoring mechanisms)?

**Comment by tay1orjones** [comment]
Design is in progress via Steven Chiang, @KarenGski

**Comment by tay1orjones** [comment]
Design is in progress via @stevench, @KarenGski

**Comment by tay1orjones** [comment]
Design is in progress via @stevench-tw, @KarenGski

**Comment by stevench-tw** [comment]
Design requirements of E&U use case
https://ibm.invisionapp.com/share/UCNYY0FB34W#/319379303_Advanced_Filter_Design_Exploration

Initial prototype draft - design in progress
https://ibm.invisionapp.com/share/UCNYY0FB34W#/319623940_Query_Builder_-_Step_1_-_Default

**Comment by tay1orjones** [comment]
@stevench-tw @KarenGski Thanks for posting the in flight design. Is there an ETA for a final design?

**Comment by stevench-tw** [comment]
@tay1orjones 
Sorry for updating this late!
The design has been reviewed with @dianatran18 @KarenGski and few of design leads, currently is under content review with Claudia. The expected final design date would be 10/2, which means after the content review.

**Latest version 3**
https://ibm.invisionapp.com/share/UCNYY0FB34W#/319379303_Advanced_Filter_Design_Exploration

**Comment by stuckless** [comment]
I think this requires a lot much through than the simplified model being presented here.  I would strongly suggest that we look at open source rule engines and get a sense of the scale of what is being asked here.

Some things to consider here, is that there needs to be a well defined AST for what the this rules engine will be building and how it interacts with elements of the AST.  We also have to account for things like data types and the builder's operations (is, is not) needs to be contextual based on the data type.  I'm assume that there will be things like greater than, less and or equal, etc, but these things might not have meaning in the sense of text.  So, the builds needs to be aware of the data types being operated on.

I think we also need to determine how child objects will be supported.  ie, this fine for flat data, but what if I'm building a rule for work orders with an address city equal to London... I need to be able to say, "address.city" as the field and not just a flat structure.

A component like this is every developers fun to build component, but, given the usefulness of it, do we really want to invest 6 months building this, or should we just look for an off the shelf component and then style it, and update our designs to reflect what we found?  This is huge component that is going to tie up developers for quite some time.  By usefulness, I'm not saying it''s not useful, just that when you look at something like a table that is used in every application, this component(s) is a very niche and complex component, that will be used rarely across multiple applications.

**Comment by stevench-tw** [comment]
Hi @stuckless 
Thank you for your comments from technical perspective! Here are my two cents:

I can't comment on the technical directions. However, from design point of view, we cares more about the real use cases, which means that how user will use it, so we started with a real E&U case. 

It is always depend on the balance between two sides of usability and flexibility, the points you raised are very valuable, which is why we leave the flexibility for the advanced value configuration dialogue -- to define the details. We've been revealed this design direction with sponsor user group, they seems like this direction. I recalled that one of the comments received from them is that current advanced query feature in their solutions today is too complicated to use.

**Comment by stuckless** [comment]
Just a couple of other technical things to consider as you go through this exercise.   If you have a Rule Builder then it assumes that there is a Rule Parser (ie, how does one edit and existing rule, or go between the "simple" and "advanced" streams).  This is why having some sort of AST is important here, since, the building/parsing can be pluggable (not part of the component) while the UI can then be used for many types of rule grammars.  I'd also consider adding in drag/reorder, since in many cases, doing that is useful when trying to re-organize expensive OR conditions.

Something to look at.  https://ukrbublik.github.io/react-awesome-query-builder/

**Comment by tay1orjones** [comment]
Here's the most recent invision mockup of an MVP RuleBuilder design from @dianatran18 

https://ibm.invisionapp.com/share/2YO0PTTRHKU#/319789253_Adv-_Filter-_5-_Add_Rule

**Comment by davidicus** [comment]
Closed by the above issues.
