### ISSUE TITLE
[Table] editable with form

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1447]
### Summary

From @lukefirth via [Internal Watson-IoT/pal-tracking#159](https://github.ibm.com/Watson-IoT/pal-tracking/issues/159)

> **Is this an extension to an existing component, pattern, or a brand new asset?**
> This is an EDS item.
> 
> **What is the rationale for this contribution.**
> For the times where you want to edit something not shown in the table, but without going into the resources drill down page. This contribution allows users to edit not only the table row contents that align to cells, but also content present in the expanded row.
> 
> This is an extension to the capability being built in [Internal Watson-IoT/pal-tracking#20](https://github.ibm.com/Watson-IoT/pal-tracking/issues/20)
> 
> **Detail the intended behavior**
> Clicking edit on a row that may expand will trigger the rows expansion and switch of all editable content to an editable state, creating a form from the fields that were previously in the expanded row area:
> 
> ![image](https://media.github.ibm.com/user/684/files/0c138a00-1c2b-11ea-9768-57cace3b8aa2)
> 
> In this case, the save/cancel pairing moves from the right hand side of the row down to the 'footer' of the expanded row area.
> 
> **Inspiration from other products**
> This kind of pattern used to have significant usage in the IoT Platform service UI.
> ![image](https://media.github.ibm.com/user/684/files/5f3a0c80-1c2c-11ea-90d1-288ee0cda6be)

**Comment by davidicus** [comment]
closing. Reopen if you think the use case still exists but this should be currently possible with app logic and render functions provided.
