### ISSUE TITLE
[Dashboard cards] Need "pop out" expand icon in card header

### ISSUE THREAD

**Issue by KarenGski** [carbon-design-system/carbon-addons-iot-react#1461]
### Summary

Need "expand" option in dashboard card header.

![image](https://user-images.githubusercontent.com/51330315/89335161-a6ff1f80-d665-11ea-8b9a-932911685c53.png)

**Additional context**
Health & Predict are following the pattern that Monitor set for expanding cards to show a larger view of the data, but it looks like the expand button isn't available in the IoT cards.  We need to expand a value card first, but also need this option on chart cards.

Click on the expand icon in the upper right to trigger an action.
![image](https://user-images.githubusercontent.com/51330315/89335270-cac26580-d665-11ea-8a5c-81962368a483.png)

_______
FYI: In Health case, this trigger would open a dialog that has additional info, but we do not need that capability built into the trigger.
![image](https://user-images.githubusercontent.com/51330315/89335311-d7df5480-d665-11ea-8a87-aa91a52bbc42.png)

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

Health needs this for our October 2020 release.  
Lack of this button blocks creation of the dialog that is invoked when the user clicks the button.

### Available extra resources

What resources do you have to assist this effort?
The Predict team hard-coded this into their chart cards, copying the Monitor team, and should hopefully be able to contribute it back.

**Comment by JordanWSmith15** [comment]
Would like the button to fire any event, not just a Carbon dialog, since our dialogs in Graphite are different.
