### ISSUE TITLE
[StatefulTable, TableHeader] support nodes as column labels

### ISSUE THREAD

**Issue by kalyanixraut** [carbon-design-system/carbon-addons-iot-react#1465]
### Summary

 StatefulTable to be enhanced to support nodes in addition to strings as column label. In the current component adding icon and customization to specific column header is not supported. For instance:

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/22093326/89496552-30366380-d7d8-11ea-9c55-0be09689f0eb.png">

### Specific timeline issues / requests
We need this for our upcoming release in Sep 2020

**Comment by tay1orjones** [comment]
@dianatran18 @lukefirth is there some design guidance around this? I'd prefer to be prescriptive as to what design configurations we intend to be used (versus, or in addition to) allowing any type of custom column header.

**Comment by kevinsperrine** [comment]
@dianatran18 Is there any guidance on custom column headers like this? I only see tooltip definitions in the AI Apps pages. https://pages.github.ibm.com/ai-applications/design/components/datatable/general#column-header

**Comment by dianatran18** [comment]
We currently don't have any, but there was a previous issue with a similar ask to add icons into the column header which we didn't move forward with. 
(@davidicus I can't remember which one it was but it was from the ELM team I think if you know what I'm referring to.)

The issue with adding decorative icons in the column header is that it can start to compete with other icons in the column headers like sorting and an overflow icon if there are other actions. It starts to overload the column headers in such a small space. Another note on this is that if it's open for teams to drop in any custom icon, then we can run into accessibility concerns with the icons not having a high enough color contrast for the different column header states (if the icon has color in them). 

That's my opinion at least. This looks like a pretty old issue so I'd be curious to hear from the team that needs this to see if they still went in this direction or had an alternative solution. 

Side note: Watson Moments guidance might have a different perspective on how to display moments like this, but I'm not familiar with that set of guidance myself, so this is just my initial thoughts).

**Comment by JordanWSmith15** [comment]
Closing as stale and no longer approved by design.
