### ISSUE TITLE
[Tooltip] Slow timing on tooltip visibility

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#1480]
There is currently no delay from when a tooltip is hovered or focused and when the tooltip appears. Timing function from Carbon is either broken in their implementation or how we have icons implemented. This issue is to get to deduce the cause and provide a fix so that tooltips appear after the appropriate delay.

**Comment by tay1orjones** [comment]
I don't see much of a delay, if any at all, on the Carbon stories

`hasIconOnly` Button hover

> ![hasIcononly-HD](https://user-images.githubusercontent.com/3360588/89823537-3ea5b780-db17-11ea-901d-04712611c507.gif)



Tooltip click interaction

> ![click-tooltip-HD](https://user-images.githubusercontent.com/3360588/89823493-2fbf0500-db17-11ea-9de8-92aebd6bf636.gif)


Tooltip Icon hover

> ![tooltip-icon-hover-HD](https://user-images.githubusercontent.com/3360588/89823447-1ddd6200-db17-11ea-9d65-3370375b171e.gif)

Maybe it was removed?

**Comment by JordanWSmith15** [comment]
Closing. Carbon behaves the same.
