### ISSUE TITLE
[Charting] Combo charts - area and line

### ISSUE THREAD

**Issue by KarenGski** [carbon-design-system/carbon-addons-iot-react#1483]
### Summary

Carbon Charts have been working on the ability to overlay 2 different charts on top of each other, and we want to leverage that capability to show an area chart with one value and show a line chart with other values on top of it.

**Additional context**
Issue in chart repo: https://github.com/carbon-design-system/carbon-charts/issues/527
This issue indicates that it should have been delivered in 2Q2020

Proposed design that needs it
![image.png](https://images.zenhubusercontent.com/5f2aaf1e3c146556652ed02e/5e6c61b1-09ca-4896-840d-22b7c08f8683)

Health score is the area chart and drivers are the line chart another.  They share the same Y axis values.  Additionally, we would like to overlay an event timeline on the same X axis, but I'm not sure if Carbon Charts has that option available yet.

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

This chart is scheduled for Health / MAS October release.

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

Predict team will be working on this chart.  It's possible that @navjeets or others might be able to contribute this to IoT.

_Carbon add-ons for Watson IoT is a collaborative system. We encourage teams to build components and submit them for integration._

**Comment by navjeets** [comment]
Carbon chart issue for area+line combo chart - https://github.com/carbon-design-system/carbon-charts/issues/723

**Comment by tiffany-lai** [comment]
The bounded area chart from Carbon looks similar to these occupancy count graphs from TRIRIGA:
 
![10 30 guests on@2x](https://user-images.githubusercontent.com/34391023/101540315-abf61780-3954-11eb-891f-03fdd0c7e805.png)
![40 20 occupancy single org@2x](https://user-images.githubusercontent.com/34391023/101540320-ad274480-3954-11eb-828b-26e717c89ec9.png)
