### ISSUE TITLE
[Chart] Enable zoom bar

### ISSUE THREAD

**Issue by KarenGski** [carbon-design-system/carbon-addons-iot-react#1484]
### Summary

We want to use the zoom bar that Carbon Charts is building.  We have several charts that originally contained zoom bar designs that we de-scoped because Carbon Charts was working on a zoom bar.  It appears in their storybook now, and we'd like to incorporate it as soon as possible so that we can use it in our Health and Predict charts

Storybook: https://carbon-design-system.github.io/carbon-charts/?path=/story/zoom-bar-alpha--stacked-area-time-series-zoom-bar-enabled

**Additional context**
We've had several user requests for a similar function, and I expect other teams will want to use this as well.

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon add-ons for Watson IoT is a collaborative system. We encourage teams to build components and submit them for integration._

**Comment by tay1orjones** [comment]
The zoombar is already available for TimeSeriesCard and BarChartCard thanks to @sstone2423! 
#1454 #1467 #1474 #1473 

@KarenGski should we scope this issue to other additional chart types, or are we safe to close here?
