### ISSUE TITLE
[Component Proposal] Chips

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#1501]
> **Is this an extension to an existing component, pattern, or a brand new asset?**
> This is an EDS item
> 
> **What is the rationale for this contribution.**
> A simple indicator of initials of users associated with an item in a compact form factor.
> 
> Note: No team has signalled a requirement for this component, and its value is under review.
> 
> **Detail the intended behavior**
> ![image](https://media.github.ibm.com/user/684/files/ac05ef00-1bfc-11ea-9f97-2616c8d5316d)
> 
> It is assumed that a hover state will supply a tooltip (not shown) of the full name or ID that the chip is referencing.

**Comment by JordanWSmith15** [comment]
Closing as this is stale and no longer required by design
