### ISSUE TITLE
[Component Proposal] Link Bar

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#1504]
> **Is this an extension to an existing component, pattern, or a brand new asset?**
> This is an EDS item
> 
> **What is the rationale for this contribution.**
> The link bar offers a text based, lightweight alternative to the [content switcher](https://www.carbondesignsystem.com/components/content-switcher/code) and performs a similar role.
> Note: Its value compared to the content switcher is under review.
> 
> **Detail the intended behavior**
> 
> * The link bar presents itself as a series of text labels, spaced X rem apart from start to finish.
> * There will always be one link that is active, and styled as semibold 14px.
> * The other links will have either the traditional link styling from carbon, or the disabled link styling.
> 
> Found here: https://ibm.invisionapp.com/share/U2NYW8D7DFV#/screens/319257692
> Image:
> ![image](https://media.github.ibm.com/user/684/files/1eb40780-200d-11ea-99a0-afbf7ff4e37a)

**Comment by JordanWSmith15** [comment]
Closing this, as there is no requirement defined by an app team, and this seems redundant with our tabs
