### ISSUE TITLE
[Component Proposal] Marketplace: Numbered Cart Header

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#1505]
> **Is this an extension to an existing component, pattern, or a brand new asset?**
> Item from the EDS.
> 
> **What is the rationale for this contribution.**
> ![image](https://media.github.ibm.com/user/684/files/4dd4ff80-1b5b-11ea-8b8a-eedc7d01880e)
> 
> This contribution covers a special version if the title/header component for use in marketplace type patterns in order to instil a strong ordering of sections on a page through the inclusion of a high contrast numeric step indicator, allowing multiple steps to be shown on a single page clearly.
> 
> **Detail the intended behavior**
> This is used like any other header within section of content in a page. Multiple of them should be deployed at once in any design, with the numeric value of each guiding the user through the order of interaction.
> 
> There may be 'edit' actions associated with each of these, however where edit in other titles allows the user to edit that title, the edit here will link the user into an editable state of that particular step, which may be on another page.
> 
> **Inspiration from other products**
> 
> * Used in the digital twin marketplace/PAL as seen below:
>   ![image](https://media.github.ibm.com/user/684/files/292d5780-1b5c-11ea-8ace-f8ed6360e326)
> * This is a clone of some common mega-online retailors cart flows.

**Comment by JordanWSmith15** [comment]
Closing, as this seems like a very specific requirement that can be done at the app level using iconography
