### ISSUE TITLE
[Component Proposal] Marketplace: Product item in cart - detail

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#1506]
> **Is this an extension to an existing component, pattern, or a brand new asset?**
> Item from the EDS.
> 
> **What is the rationale for this contribution.**
> ![image](https://media.github.ibm.com/user/684/files/6d6b2880-1b59-11ea-8789-fcf67c8258f2)
> 
> This component stands to support marketplace type patterns with a 'cart' step.
> Currently the only identified exmaple of this is the digital twin marketplace, and as such this may receive lower core PAL priority than more general sibling issues.
> 
> The concept rational behind this contribution is to provide a semi-expanded view of a resource that a user is considering purchasing in order to 'review' before checking out.
> 
> **Detail the intended behavior**
> This appears in a list format on certain pages to review selected resources from a marketplace/catalog pattern. It provides key information and 2 primary interactions (a dropdown...) and a remove action styled as a link.
> 
> * This may make sense to be another variant of the other 'resource tile' component styles, such as [Contribution] Marketplace: Featured Product Tile #133
> 
> **Inspiration from other products**
> 
> * It can be found as an item at this link: https://ibm.invisionapp.com/share/U2NYW8D7DFV#/screens/319196743
> 
> And can be seen in usage in the PAL as shown below:
> ![image](https://media.github.ibm.com/user/684/files/88d63380-1b59-11ea-83f6-9f2699b61559)

> **Is this an extension to an existing component, pattern, or a brand new asset?**
> Item from the EDS.
> 
> **What is the rationale for this contribution.**
> ![image](https://media.github.ibm.com/user/684/files/6d6b2880-1b59-11ea-8789-fcf67c8258f2)
> 
> This component stands to support marketplace type patterns with a 'cart' step.
> Currently the only identified exmaple of this is the digital twin marketplace, and as such this may receive lower core PAL priority than more general sibling issues.
> 
> The concept rational behind this contribution is to provide a semi-expanded view of a resource that a user is considering purchasing in order to 'review' before checking out.
> 
> **Detail the intended behavior**
> This appears in a list format on certain pages to review selected resources from a marketplace/catalog pattern. It provides key information and 2 primary interactions (a dropdown...) and a remove action styled as a link.
> 
> * This may make sense to be another variant of the other 'resource tile' component styles, such as [Contribution] Marketplace: Featured Product Tile #133
> 
> **Inspiration from other products**
> 
> * It can be found as an item at this link: https://ibm.invisionapp.com/share/U2NYW8D7DFV#/screens/319196743
> 
> And can be seen in usage in the PAL as shown below:
> ![image](https://media.github.ibm.com/user/684/files/88d63380-1b59-11ea-83f6-9f2699b61559)

**Comment by JordanWSmith15** [comment]
This seems like a layout repeater that is better maintained at the app level rather than PAL
