### ISSUE TITLE
[Component Proposal] Marketplace: Product item with Icon (example: file)

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#1507]
> **Is this an extension to an existing component, pattern, or a brand new asset?**
> Item from the EDS.
> 
> **What is the rationale for this contribution.**
> A compound component for displaying resources inside a tile catalog wrapper to easier, more attractive browsing than tabular forms.
> 
> **Detail the intended behaviour**
> A sister to the 'Product item with Icon' component as well as the 'featured tile' component, this displays a resource on a tile with a 20px icon, title, subtitle and tertiary button.
> 
> Example in the PAL:
> ![image](https://media.github.ibm.com/user/684/files/ed978b00-1b65-11ea-81da-ff72ea7ef46f)
> It can be found as the third component at this link: https://ibm.invisionapp.com/share/U2NYW8D7DFV#/screens/319196743
> 
> **Example from other products**
> None presently, but very likely to be leveraged in the Digital Twin Marketplace, and possibly in the AS function catalog (currently it shows nothing, but an iconography approach would have value).
> 
> **Note: this is a sibling issue to:**
> 
> * [Contribution] Marketplace Featured Tile #133
> * [Contribution] Product item with Thumbnail #135
> * [Tile catalog] Update/deprecate/evolve into wrapper for catalog type patterns. #137

**Comment by JordanWSmith15** [comment]
Seems like a standard layout specific to a single app that would be better maintained at the app level
