### ISSUE TITLE
[Component Proposal] Marketplace: Product item with Thumbnail

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#1508]
> **Is this an extension to an existing component, pattern, or a brand new asset?**
> Item from the EDS.
> 
> **What is the rationale for this contribution.**
> A compound component for displaying resources inside a tile catalog wrapper to easier, more attractive browsing than tabular forms.
> 
> **Detail the intended behaviour**
> A sister to the 'Product item with Icon' component as well as the 'featured tile' component, this displays a resource on a tile with a small thumbnail, title, subtitle and tertiary button, including a hover state when users hover over the thumbnail.
> 
> Example in the PAL:
> ![image](https://media.github.ibm.com/user/684/files/03a44c00-1b64-11ea-9db6-2c74a1e0a6f2)
> It can be found as the second component at this link: https://ibm.invisionapp.com/share/U2NYW8D7DFV#/screens/319196743
> 
> **Example from other products**
> Inside the PAL patterns - for the Digital Twin marketplace:
> ![image](https://media.github.ibm.com/user/684/files/aa88e800-1b64-11ea-8993-8a2875aa05fb)
> 
> And again coupled with the featured tile in the AS function catalog design proposals:
> ![image](https://media.github.ibm.com/user/684/files/487cb280-1b65-11ea-98c4-7bdaa22aed99)
> 
> **Note: this is a sibling issue to:**
> 
> * [Contribution] Marketplace Featured Tile #133
> * [Contribution] Product item with Icon (example: file) #136
> * [Tile catalog] Update/deprecate/evolve into wrapper for catalog type patterns. #137

**Comment by JordanWSmith15** [comment]
Seems like a very specific card type that would be better maintained at the app level
