### ISSUE TITLE
[Icon content switcher] Styling enhancement

### ISSUE THREAD

**Issue by dianatran18** [carbon-design-system/carbon-addons-iot-react#1536]
Looking to update the icon content switcher styling slightly to match what Carbon has for their [content switcher](https://react.carbondesignsystem.com/?path=/story/contentswitcher--content-switcher-playground)

Updates:
- Update color of hover and selected states to match Carbon's content switcher
- remove stroke around default state (although that is in design on the PAL site but I'm not seeing it in code?)
- Round corners on the left and right end buttons
- Build in light variant
- Can we also update the placement of the tooltip that shows up to match what the [icon button](https://react.carbondesignsystem.com/?path=/story/button--playground) does?

Carbon style specs: https://www.carbondesignsystem.com/components/content-switcher/style

Specs:

![Icon content switcher](https://user-images.githubusercontent.com/43549567/94819660-833e2880-03cd-11eb-8061-ba7beb14109c.png)

**Comment by JordanWSmith15** [comment]
This one has been around a while, and the design has changed in the meantime: https://github.com/carbon-design-system/carbon/issues/6745

**Comment by dianatran18** [comment]
Beat me to it! 

We actually have a few issues open this month to update the spec for this in our internal repo:

- Style specs: https://github.ibm.com/ai-applications/pal/issues/707
- Low contrast variation: https://github.ibm.com/ai-applications/pal/issues/702

For the low contrast variation, this was an effort by a designer to contribute it back to the Carbon team. The low contrast version has been approved by Carbon, so we wanted to reflect the additional variation in our PAL too. The end goal is to just contribute this back to Carbon to support an icon version of the content switcher, which has an open ticket from a while ago: https://github.com/carbon-design-system/carbon/issues/6982
