### ISSUE TITLE
[Numeric Input] [Firefox only] Inline error validation does not appear for invalid letter inputs

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-addons-iot-react#1542]
### Describe the bug

On Firefox browser, numeric input does not display inline errors for letters when allowEmpty is set to true

### To Reproduce

1. Using Firefox, go to 'https://carbon-addons-iot-react.com/?path=/story/numberinput--default'
2. Click on 'Knobs'
3. Set "Allow empty value (allowEmpty) to checked
4. Focus on keyboard entry of the component
5. Enter a letter into the input
6. No error is shown. De-focus and error is still not shown

### Expected behavior

The inline error validation should be shown, as it is shown for other browsers

### Specific timeline issues / requests
MAS 8.3

Blocks https://jsw.ibm.com/browse/GRAPHITE-14515

<img width="576" alt="Screen Shot 2020-08-26 at 8 36 47 AM" src="https://user-images.githubusercontent.com/21066152/91305502-21a8ef80-e779-11ea-9876-34a19a11ff83.png">

**Comment by davidicus** [comment]
@JordanWSmith15 I am not seeing any form validation for that in Chrome either. Which browser are you seeing the correct behavior?

**Comment by JordanWSmith15** [comment]
@davidicus  Good point. In Chrome, entering an alphabetic character is not possible. But in Safari, it's the same result as Firefox. I think all browsers should act how Chrome does, or, the validation error should show with the "Allow empty" prop as well across all browsers.

**Comment by davidicus** [comment]
I have opened up a bug with the Carbon team for this. This functionality is behind a feature flag that is set internally. While it is possible to change in your webpack config using the `string-replace-loader` there should probably be a better way. 

```
config.module.rules.push({
      test: /(\/|\\)FeatureFlags\.js$/,
      loader: 'string-replace-loader',
      options: {
        includePaths: [path.resolve(__dirname, '..', 'node_modules')],
        multiple: Object.keys({ useControlledStateWithValue: true }).map(key => ({
          search: `export\\s+var\\s+${key}\\s*=\\s*false`,
          replace: `export const ${key} = true`,
          flags: 'i',
        })),
      },
    });
```

Tracking bug in Carbon here:

https://github.com/carbon-design-system/carbon/issues/7039

**Comment by davidicus** [comment]
After further inspection I see that this is actually a bug in firefox and safari not in Carbon. There seems to be dispute in the application of the spec as far as rendering text in the UI when the value of the input is reported as an empty string. 

I played around a bit and I believe we can add some validation to help catch these values. @JordanWSmith15 your devs can implement as is with the current implementation. 

Basically we just need to pass a validation function to  `onKeyUp` on the `NumberInput`

```
const [isValid, setIsValid] = useState(true);
  const numberRef = useRef();

  const handleKeyPress = (e) => {
    console.log({ value: numberRef.current.value });
    if (
      !/^[1-9]\d*(\.\d+)?$/.test(e.key) &&
      numberRef.current.value.length === 0
    ) {
      setIsValid(false);
    } else {
      setIsValid(true);
    }
  };
  return (
    <NumberInput
      ref={numberRef}
      allowEmpty={true}
      invalid={!isValid}
      onKeyUp={handleKeyPress}
    />
  );
```

See a codesandbox [here](https://codesandbox.io/s/unruffled-framework-6ww00?file=/src/index.js)

**Comment by JordanWSmith15** [comment]
Closing this as stale. Issue was fixed in Graphite (somehow)
