### ISSUE TITLE
[DateTimePicker] lastAppliedValue is never used. 

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#1543]
### Describe the bug

There is a state hook value being used in this component where we are updating the value but the value is never used in the component. This issue is meant to confirm the lack of use and remove from the code base. 

Value is defined on line 265 of DateTimePicker.jsx

**Comment by navjeets** [comment]
lastAppliedValue is being used in onCancelClick() function to revert to the previous applied value.

**Comment by JordanWSmith15** [comment]
Closing as stale
