### ISSUE TITLE
[TimeSeriesCard] slider view zoombar doesn't have correct color background

### ISSUE THREAD

**Issue by sstone2423** [carbon-design-system/carbon-addons-iot-react#1548]
### Describe the bug

The background of the slider of view zoombar should be gray, but it displays as white, meaning we can't see it on our card's white background

### To Reproduce

1. Go to https://carbon-addons-iot-react.com/?path=/story/watson-iot-timeseriescard--with-zoombar
2. Slide the zoombar some
3. See that there is no background

### Expected behavior

Background should be gray

### Environment/versions:

- OS: MacOS
- Browser: chrome
- `carbon-addons-iot-react` version: v2.101.0

### Additional context

Issue opened with carbon charts: https://github.com/carbon-design-system/carbon-charts/issues/750

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

Would be nice to have sooner rather than later

**Comment by JordanWSmith15** [comment]
This appears to have been fixed upstream
<img width="549" alt="Screen Shot 2021-07-23 at 10 29 23 AM" src="https://user-images.githubusercontent.com/21066152/126797068-8f98781c-a5dd-4566-bf40-a4d1410813e4.png">
