### ISSUE TITLE
[CardGalleryList] List variant with large items, pictograms

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1560]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

Create a variation of the List component in support of the dashboard builder/editor #1372

- CardGalleryList component would accept array of list items with card type/title that would map to predefined list. These list items would not support hierarchy (`children`). The `icon` prop could be repurposed to allow pictograms from `@carbon/pictograms-react` 
- It would be nice if we could enforce certain types of cards to have certain pictograms by default. Maybe the predefined list of card types would map item `value` strings to an associated default pictogram from `@carbon/pictograms-react` 
- Additionally a 'custom' list item could be configured and passed in an optional pictogram. If no pictogram is provided, we could choose a default, something generic like `<Analyze />` maybe?
![image](https://user-images.githubusercontent.com/3360588/91896123-f5e8a680-ec5d-11ea-80df-e7778d5dac41.png)
- per the spec below this will need to support:
  - Search 
  - A hover/selected/highlighted state for each item - @CynZhang could you give more specific details on the states of these?
- An 'add' callback via a hasIconOnly button on the right of the item. Text should probably be truncated into a tooltip if it doesn't fit

**Additional context**
![image](https://user-images.githubusercontent.com/3360588/91896731-f170bd80-ec5e-11ea-95d3-90d4016f0527.png)

**Comment by tay1orjones** [comment]
This requests highlights the limitations of a non-composable set of components. The List is not composable. 

If the List _was_ composable, we could simply create a new type of ListItem with the visual/functional updates.

**Comment by davidicus** [comment]
@bryancboyd can you comment on this issue what we discussed about this issue. I believe we are de-prioritizing this right now, correct?

**Comment by sstone2423** [comment]
What still needs to be done:
- [ ] add custom card icon
- [ ] add ability for consumer to add their own card types and icons
