### ISSUE TITLE
[CardGalleryHeader] dashboard builder/editor pane header

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1561]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

In support of the dashboard builder/editor #1372

The Gallery/Editing pane should have a standardized header. From the spec it appears to have two states/configurations
1. Gallery
1. Return to Gallery

This would be a very small component but something that we could publish for ease of design consistency and standardization. Would need to accept props: 
- i18n object prop for the strings
- a `bool` prop `isGallery` which would toggle the two different states. 
- callback for onGalleryClose (the arrow)
- callback for onReturnToGallery (the "open gallery" link and the icon)

**Additional context**

![image](https://user-images.githubusercontent.com/3360588/91897471-f41fe280-ec5f-11ea-81b2-0527c10e47bc.png)
![image](https://user-images.githubusercontent.com/3360588/91897622-2a5d6200-ec60-11ea-8b53-20cf39cb2aeb.png)

**Comment by bryancboyd** [comment]
How about we treat this component as the parent and layout manager of both the CardGalleryList and CardEditForm components (maybe, `<CardEditor>`), and include the header rendering?

Example usage:

```
<CardEditor
  isGallery
  supportedTypes={[CARD_TYPES.LINE, CARD_TYPES.VALUE]}
  i18n={{
    listItemTimeSeries: 'Time series line',
    listItemSimpleBar: 'Simple bar',
    etc...
  }}
  onClose={/* triggered when gallery closes */}
  onAddCard={(cardType) => {}}
  onCardChange={(newCardJSON) => {}}
/>
```

Which would render:

```
<div className="iot--card-editor">
  <div className="iot--card-editor--header">
    { isGallery ? (Gallery -->) : <Button>Open gallery</Button> }
  </div>
  { isGallery ? <CardGalleryList /> : <CardEditForm /> }
</div>
```

**Comment by tay1orjones** [comment]
@bryancboyd what's left for this one since your PR?

**Comment by sstone2423** [comment]
This is managed by CardEditor if the gallery is not showing and CardGalleryList if the gallery is showing. The reasoning is that CardGalleryList can use SimpleList's header

**Comment by davidicus** [comment]
> This is managed by CardEditor if the gallery is not showing and CardGalleryList if the gallery is showing. The reasoning is that CardGalleryList can use SimpleList's header. It would be a good idea to still create a proper CardEditorHeader to keep it consistent though

@sstone2423 is this something you are still working on?
