### ISSUE TITLE
[CardEditForm] configurable form for editing dashboard card parameters

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1562]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

In support of the dashboard builder/editor #1372

Build a component that maps to the JSON configuration schema of a dashboard card, mapping the configrable keys to form inputs.

Most form inputs would be standard - some could be enhanced such as the "Card type" which could potentially use Dropdown with icon selection buttons, #1259 (this could be a stretch goal though - perhaps we use the stock dropdown in the mvp)

This will probably also need to support some sort of 'slot' pattern where components could be passed in and the value map to the json key, such as the 'upload image' section in the spec below. Also will want to keep in mind that the consuming applications will likely be using Formik, so our API design for this should be informed by that.

@bryancboyd I think you have a solid idea in your mind of how this would work beyond these broad strokes I've outlined. it sounds like you'll take this on, so will defer additional implementation details/conversation to your eventual PR 🙂 

**Additional context**
![image](https://user-images.githubusercontent.com/3360588/91898138-e74fbe80-ec60-11ea-9802-f258937aa583.png)

**Comment by davidicus** [comment]
has been de-prioritized for Monitor. Removing from Q3

**Comment by davidicus** [comment]
@sstone2423 Is there anything left for this issue to accomplish or can we close this one out?

**Comment by sstone2423** [comment]
@davidicus the base idea of this implemented, but we are still missing card-specific form items for all card types except TimeSeriesCard.

There is also no way of adding custom card types at the moment beyond the basic 'Custom'. I think this could be a separate issue though.

There is also no way of adding additional custom form items for specific use-cases like the varying ways consumers use `dataSource`

There is also virtually no real validation for cards by default. We simply do a basic valid JSON check so we would need to add in some kind of proper schema for the basic necessities like card size that can cause the editor to blow up (although there is some error boundaries to prevent  a complete crash

I'd say these could all be created into separate issues though if you'd like to close this one out

**Comment by tay1orjones** [comment]
Closing - follow up issues created to continue this work:

- [CardEditor] support editing for TableCard #1739
- [CardEditor] support editing for ValueCard #1740
- [CardEditor] support editing for ImageCard #1741

If there are more we should create, please do so or let me know 👍
