### ISSUE TITLE
[HierarchyList] invalid indentation padding and arrow direction

### ISSUE THREAD

**Issue by JessicaGentry** [carbon-design-system/carbon-addons-iot-react#1568]
Currently Items with no children show up without any indent and are not aligned with items at the same level that do have children, since those are indented for the expand/collapse carat. This implies incorrectly a hierarchical relationship between these items.

Expected behavior is that all items  at the same level will be horizontally aligned. If an item does not have child items it should be indented to match the ones that are indented for carats.

Screenshot shown here:  
(In this situation, Home and My Reports are at the same level as the items below. They should be indented.)

![image (2)](https://user-images.githubusercontent.com/52802834/92147237-72a38e00-ede0-11ea-85b6-104c3589e1b0.png)

**Comment by tay1orjones** [comment]
In addition, children items have the same indent padding as the parent items. This will cause visual confusion between which items are children and which items are root level items with no children.

We'll expand this issue to cover general improvements to the visual treatment of hierarchy list to include:

* Root level items with no children should be indented to align with items (the initial issue reported above)
* Children items should have slightly more indentation than their parent.
* Caret direction needs to be flipped to be consistent with sidenav and accordion. When the section is closed, the arrow should point down.


Screenshot mockup of the intended outcome:

![image](https://user-images.githubusercontent.com/3360588/93786871-66e40400-fbf5-11ea-8297-fcf2edaa79b4.png)
