### ISSUE TITLE
[BarChartCard] interval='year' formats the axes incorrectly for time-based barChart

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#1572]
### What package is this for?

- [x] React

### Describe the bug

Pass 'year' as the interval prop and notice the x-axis doesn't show the year correctly

![image](https://user-images.githubusercontent.com/6663002/92251341-4ea08500-ee92-11ea-9da9-edcd54a8c6e7.png)

**Comment by kevinsperrine** [comment]
@scottdickerson, I'm digging into this one to get it fixed this sprint. Can you help me understand the expected behavior? The interval prop isn't listed in propTypes for the BarChartCard, so, as best I can tell, it's only used in dashboard previews? Is that correct? 

Additionally, I cloned the `Temperature with a very long title that should be truncated and have a tooltip for the full text ` from `Dashboard.story.jsx` and modified it to use year intervals, and it _seems_ to work as expected, but I need your help on that part. 

The code is below and this is the card that gets rendered:
<img width="828" alt="Screen Shot 2021-03-01 at 3 23 29 PM" src="https://user-images.githubusercontent.com/609466/109554361-204add80-7aa2-11eb-9f10-61179dd54048.png">


```
// story modified to use interval='year'
  {
    title: 'Temperature with year',
    id: 'facility-temperature-timeseries-year',
    size: CARD_SIZES.MEDIUM,
    type: CARD_TYPES.BAR,
    content: {
      series: [
        {
          label: 'Temperature',
          dataSourceId: 'temperature',
        },
      ],
      xLabel: 'Time',
      yLabel: 'Temperature (˚F)',
      timeDataSourceId: 'timestamp',
    },
    values: getIntervalChartData('year', 5, { min: 10, max: 100 }, 100),
    interval: 'year',
    timeRange: 'last7Years',
    availableActions: { range: true },
    dataSource: {
      attributes: [
        {
          aggregator: 'last',
          attribute: 'speed',
          id: 'speed_Claudia_Sample_Robot_Type_last',
        },
      ],
      groupBy: ['deviceid'],
      range: {
        count: -7,
        interval: 'year',
      },
      timeGrain: 'year',
    },
  },
```

**Comment by davidicus** [comment]
Seems like this has been resolved. I am closing but if the problem has not be resolved we can re-open.

**Comment by davidicus** [comment]
@scottdickerson Have you worked on this bug yet? Is it resolved?

**Comment by kevinsperrine** [comment]
@scottdickerson I dug into this some more today, and I'd love to fix it, but either 1) it's already resolved, 2) I'm not aware of what the expected results should be, or 3) it's some other combination of props that I'm misinterpreting. A little input would help. Thanks!


When passing year to a BAR card with timeseriesdata:
```
    values: getIntervalChartData('year', 7, { min: 10, max: 100 }, 100),
    interval: 'year',
```
![Screen Shot 2021-07-12 at 5 05 10 PM](https://user-images.githubusercontent.com/609466/125355758-66a72780-e333-11eb-88d8-ba5ed4a3140f.png)

When passing month to a BAR card with timeseriesdata:
```
    values: getIntervalChartData('month', 7, { min: 10, max: 100 }, 100),
    interval: 'month',
```
![Screen Shot 2021-07-12 at 5 04 22 PM](https://user-images.githubusercontent.com/609466/125355759-673fbe00-e333-11eb-87dd-d9d75d195105.png)

When passing week to a BAR card with timeseriesdata:
```
    values: getIntervalChartData('week', 7, { min: 10, max: 100 }, 100),
    interval: 'week',
```
![Screen Shot 2021-07-12 at 5 03 58 PM](https://user-images.githubusercontent.com/609466/125355761-67d85480-e333-11eb-8062-e544c18fb1e8.png)

When passing day to a BAR card with timeseriesdata:
```
    values: getIntervalChartData('day', 7, { min: 10, max: 100 }, 100),
    interval: 'day',
```
![Screen Shot 2021-07-12 at 5 03 42 PM](https://user-images.githubusercontent.com/609466/125355764-67d85480-e333-11eb-9078-1d7566eb3093.png)

When passing hour to a BAR card with timeseriesdata:
```
    values: getIntervalChartData('hour', 7, { min: 10, max: 100 }, 100),
    interval: 'hour',
```
![Screen Shot 2021-07-12 at 5 03 28 PM](https://user-images.githubusercontent.com/609466/125355767-6870eb00-e333-11eb-859a-374d3536137a.png)

// cc @davidicus

**Comment by scottdickerson** [comment]
@kevinsperrine take a look at the month, day, hour formatting of the x-axis in the TimeSeriesCard.  The Bar Chart formats should match it.
