### ISSUE TITLE
[Table] Table header misalignment

### ISSUE THREAD

**Issue by leetosc** [carbon-design-system/carbon-addons-iot-react#1587]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

Table header items are misaligned
![image](https://user-images.githubusercontent.com/13279967/92626751-f7365680-f28f-11ea-8951-7b12e88f0280.png)

### To Reproduce

https://carbon-addons-iot-react.com/?path=/story/watson-iot-table--simple-stateful-example

### Expected behavior

Table header items should be aligned correctly

### Environment/versions:

- OS: MacOS
- Browser: Chrome
- `carbon-addons-iot-react` version: [e.g. `2.114.8`] (latest)

### Additional context

Looks like a recent regression

**Comment by tay1orjones** [comment]
I think this is related to #1597
