### ISSUE TITLE
[TimeSeriesCard] Group is not translated in tooltip

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#1588]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

![image](https://user-images.githubusercontent.com/6663002/92636254-a9741b00-f29c-11ea-86c1-fe1d85b09590.png)

I believe this also happens for certain types of bar charts

**Comment by scottdickerson** [comment]
needs a fix from Carbon-Charts: https://github.com/carbon-design-system/carbon-charts/issues/797

**Comment by sstone2423** [comment]
Fixed
