### ISSUE TITLE
[ProgressIndicator] Click target overlaps the progress indicator bottom

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#1594]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

The click target for the custom progress indicator overlaps the bottom of the indicator, in my case it's obscuring another click target

![image](https://user-images.githubusercontent.com/6663002/92975912-fb5ca280-f44e-11ea-918d-3acb56071996.png)

### To Reproduce

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/IBM/carbon-addons-iot-react/tree/master/examples/codesandbox

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by kevinsperrine** [comment]
This seems to have been fixed, also, but our click area is still slightly larger than the Carbon one. However, we will be moving to Carbon and deprecating the PAL version. https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2605

PAL:
![Screen Shot 2021-07-16 at 9 01 13 AM](https://user-images.githubusercontent.com/609466/125952096-27f3e48f-5695-4a26-97d7-b81b13bb4de4.png)

Carbon:
![Screen Shot 2021-07-16 at 9 02 28 AM](https://user-images.githubusercontent.com/609466/125952092-d556555a-92bd-4654-a57c-1abe072591dc.png)
