### ISSUE TITLE
[Table] Select all checkbox is misaligned

### ISSUE THREAD

**Issue by sstone2423** [carbon-design-system/carbon-addons-iot-react#1597]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

The select all checkbox is not being centered

### To Reproduce

1. Go to https://carbon-addons-iot-react.com/?path=/story/watson-iot-table--simple-stateful-example
2. See misaligned select all checkbox

### Expected behavior

Should be centered

### Environment/versions:

- OS: MacOS
- Browser: chrome
- `carbon-addons-iot-react` version: v2.114.6

### Additional context

![Screen Shot 2020-09-13 at 1 16 03 PM](https://user-images.githubusercontent.com/25177649/93025431-7d6dd800-f5c3-11ea-9558-a0e5429fb142.png)

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

September release

**Comment by marcJV** [comment]
This was fixed in most cases, but is still misaligned in 'Stateful Example with expansion, maxPages, and column resize' and a few others like that story
![image](https://user-images.githubusercontent.com/1293444/93629924-b5ec2800-f9ae-11ea-8f27-22d5bc352120.png)
