### ISSUE TITLE
[ProgressIndicator] current step isn't using the fill: blue

### ISSUE THREAD

**Issue by sstone2423** [carbon-design-system/carbon-addons-iot-react#1599]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

ProgressIndicator's current step svg should be blue, but its showing as black. I think this is a regression from the latest `fill: currentColor` change in the carbon update.

Because of this, we should go through and check all `fill: currentColor` areas to make sure they're working correctly

### To Reproduce

1. Go to https://carbon-addons-iot-react.com/?path=/story/watson-iot-progressindicator--stateful
2. Click on Step 5
3. See black fill

### Expected behavior

Should be blue according to https://react.carbondesignsystem.com/?path=/story/progressindicator--default
### Environment/versions:

- OS: MacOS
- Browser: chrome
- `carbon-addons-iot-react` version: v2.114.0

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

No specific

**Comment by bjornalm** [comment]
@sstone2423 I think this have been fixed. Can you confirm so that we can close?

**Comment by sstone2423** [comment]
Fixed
