### ISSUE TITLE
[Pull Request Template] add a Regression Test field / question

### ISSUE THREAD

**Issue by sstone2423** [carbon-design-system/carbon-addons-iot-react#1610]
### What package is this for?

- [x] React
- [x] Angular

### Summary

The current PR template has an Acceptance Test field/question currently that is helpful to remind the dev to give the reader some idea on how to test the PR. I think it would be beneficial (and I've added it myself before)  to have a similar 'Regression Test' field to remind the user to think about how they could have broken old functionality. An example could be:

**Regression Test (how to make sure this PR doesn't break old functionality)**

It doesn't necessarily have to be specific instructions as it could be fully tested for, but it helps to jog the dev's brain

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

N/A

### Available extra resources

What resources do you have to assist this effort?

Can add myself if others think this would be valuable

**Comment by tay1orjones** [comment]
Great idea - I usually find myself separating my acceptance test section into whats new and what's old that should be double checked. Having it as a separate field could nudge contributors to look more closely at their PR through the lens of possible regressions versus only the additions. 

This also will be good for when regressions _do_ happen as we can go back to see if it was highlighted in the original PR to inform when/how to write unit tests around the regression.
