### ISSUE TITLE
[Header] Header actions buttons with dropdowns styling

### ISSUE THREAD

**Issue by dianatran18** [carbon-design-system/carbon-addons-iot-react#1626]
Moving over internal issue https://github.ibm.com/ai-applications/pal/issues/368

—————

Trying to explore the header action buttons with dropdowns and the styling doesn't match what is shown in the storybook

![Header-action-button-with-drop-downs-style-issue](https://media.github.ibm.com/user/90016/files/5c1d5000-7c0f-11ea-9e7c-f5619dc12068)

![Header-action-button-with-drop-downs-storybook](https://media.github.ibm.com/user/90016/files/50ca2480-7c0f-11ea-8689-33c2ed0c61cb)

**Comment by kevinsperrine** [comment]
@dianatran18 Where did you get the incorrect screenshot from?

**Comment by dianatran18** [comment]
Oh this wasn't created by me — this was created by Josh on this [internal issue](https://github.ibm.com/ai-applications/pal/issues/368https://github.ibm.com/ai-applications/pal/issues/368) and I was just creating an issue here to track it on the dev side back then.

If this is fixed, then we can close both internal/external issues.

**Comment by kevinsperrine** [comment]
I believe this has been fixed, but it's hard to recreate. Feel free to re-open if the problem persists.
