### ISSUE TITLE
[Bug][Data Table] Row action gradient height should be dynamic

### ISSUE THREAD

**Issue by dianatran18** [carbon-design-system/carbon-addons-iot-react#1627]
Moving over internal issue https://github.ibm.com/ai-applications/pal/issues/371

—————

It seems that the gradient fade behind the row-action buttons is a fixed height. In data table rows that are taller, the gradient should grow to match it.
https://pages.github.ibm.com/maximo-app-framework/graphite-testing/pr-GRAPHITE-7359-Llamas-13042020/reference-app/#/tables
![Untitled](https://media.github.ibm.com/user/17018/files/1632ca00-7d7e-11ea-8831-82468b60e31f)

**Comment by bjornalm** [comment]
I think this was already moved and fixed here
https://github.com/carbon-design-system/carbon-addons-iot-react/pull/1297

**Comment by davidicus** [comment]
Closing this as resolved in the pr mentioned above. Feel free to reopen if you see the problem persist.
