### ISSUE TITLE
[Graphite Storybook] - Table - Manage Columns Lookup dialog- Cancel and Close button are saving the selected/unselected items

### ISSUE THREAD

**Issue by dianatran18** [carbon-design-system/carbon-addons-iot-react#1629]
Moving over internal issue https://github.ibm.com/ai-applications/pal/issues/341

—————

Steps to reproduce the problem on Android and iOS
 1) Go to > Table > DataSource table https://pages.github.ibm.com/maximo-app-framework/graphite/react/storybook/?path=/story/components-%E2%98%A2-table--datasource-table

2) For RTL, select *toggle on for* Right-to-left

3) Select "Column Selection" icon

4) Select "Manage Columns" button
 Note that 11 items are marked by default

5) Leave only 1 or 2 items marked. Example: wonum, assetnum

6) Click "OK" Button

Actual: Lookup dialog is closed and Manage Columns button overlaps Column button - See screenshot
 Expected: Lookup dialog is closed and Manage Columns button should not overlap other column buttons.
![ManageColumnOverlaps (1)](https://media.github.ibm.com/user/29043/files/ee8fc680-6e8f-11ea-80e1-b9dc394c48e9)

In Android. on Reference App (No RTL in this case): https://pages.github.ibm.com/maximo-app-framework/graphite/reference-app/#/tables

![Mobile_RefApp_ManageColumns](https://media.github.ibm.com/user/29043/files/42c4b300-7016-11ea-8e83-404941303d07)

**Comment by bjornalm** [comment]
I'm pretty sure that this was solved by https://github.com/carbon-design-system/carbon-addons-iot-react/pull/2489
