### ISSUE TITLE
[Component Proposal] Advanced filter and query editor based on rule builder

### ISSUE THREAD

**Issue by mzuliani-ibm** [carbon-design-system/carbon-addons-iot-react#1634]
### What package is this for?

- [X] React
- [ ] Angular

### Summary

Advanced filtering and search component, based on [Rule management](https://pages.github.ibm.com/ai-applications/design/patterns/rule-management/overview) and an updated design pattern from the **advanced filters query workgroup**.
Required for the IBM Engineering (ELM) suite of products.

### Specific timeline issues / requests

Contact @mzuliani-ibm for details.

### You will consider this component complete when...

- [X] It's available as an export of this library
- [X] Additional criteria you may have [Accessible]

**Comment by davidicus** [comment]
@mzuliani-ibm Do you have any design specs that we can use to start building this component?

**Comment by mzuliani-ibm** [comment]
Design is in-progress: https://ibm.invisionapp.com/d/main?redirHash=#/projects/prototypes/15368301
Contact me or Tim Gaertner to get access.

**Comment by davidicus** [comment]
This was closed by #1445
