### ISSUE TITLE
[PieChartCard] remove workaround for pie label overflow

### ISSUE THREAD

**Issue by bjornalm** [carbon-design-system/carbon-addons-iot-react#1637]
### What package is this for?
- [x] React
- [ ] Angular

### Summary
The carbon react pice chart allows the labels to overflow the container, see issue
https://github.com/carbon-design-system/carbon-charts/issues/822

We added a workaround with additional padding in the PieChartCard, which should be removed when the bug in the carbon-charts is resolved.

**Additional context**
![image](https://user-images.githubusercontent.com/5167091/94447010-a1c3da00-01a9-11eb-8d2f-07ece47e9f0b.png)

**Comment by JordanWSmith15** [comment]
This does not seem to be a problem in the Carbon Charts storybook or code sandbox:
https://carbon-design-system.github.io/carbon-charts/react/?path=/story/simple-charts-pie--pie
https://codesandbox.io/s/vfftw

**Comment by JordanWSmith15** [comment]
Fixed upstream
