### ISSUE TITLE
[IconSwitch] When IconSwitch is used with ContentSwitcher, the hover tooltip is overlapping the selected tooltip

### ISSUE THREAD

**Issue by kennycto** [carbon-design-system/carbon-addons-iot-react#1646]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

Title. When the IconSwitch is selected, the tooltip remains open. If the user hovers over the other IconSwitch, the other tooltip will display, overlapping the tooltip that is selected. This can be replicated in the carbon-addons-iot-react storybook.

### To Reproduce

1. Go to https://carbon-addons-iot-react.com/?path=/story/watson-iot-iconswitch--example-used-in-contentswitcher
2. Click on the 'Graphical View' Icon (left). The tooltip for Graphical View should display.
3. Hover mouse over the 'Source View' icon (right). That tooltip will display as well, overlaying the Graphical view tooltip.

### Expected behavior

Only one tooltip should be showing at at time. When the mouse is hovering over the other tooltip, the selected tooltip should close.

### Environment/versions:

- OS: MacOS
- Browser: Chrome/Firefox/Safari
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`] (not sure about this one, but it's replicated on the version used by the storybook)

### Additional context

<img width="245" alt="image" src="https://user-images.githubusercontent.com/206663/94867040-46862780-03f5-11eb-859b-3b3a214c815e.png">

**Comment by JordanWSmith15** [comment]
Won't fix. Slightly odd, but only occurs on-hover.
