### ISSUE TITLE
[Tab] Scrolling Tab/Tab Overflow Enhancement - React

### ISSUE THREAD

**Issue by ben-bacon** [carbon-design-system/carbon-addons-iot-react#1655]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

This component is an enhancement to the [Carbon tab component](https://www.carbondesignsystem.com/components/tabs/usage). Added enhancements provide a "list all" dropdown for navigating to tabs that exceed the viewport, functionality to add tabs, and functionality to close tabs or perform similar actions through an icon button or overflow menu.

[PAL guidance](https://ibm.box.com/s/l23mzpv98pdq5awa4ar3gjqy4dphzdpu)

### Available extra resources
Related: https://github.ibm.com/ai-applications/pal/issues/469
Angular issue: #1656
 
**Design specs**

-  [Tab actions](https://user-images.githubusercontent.com/52676199/95121443-ab52c200-0714-11eb-8c91-3fad403c6c17.png)
   - Can be a close action, or if the product supports more then it can be an overflow menu
- [Add tabs](https://user-images.githubusercontent.com/52676199/95121450-ac83ef00-0714-11eb-9203-f5d7126a8626.png)
  - Upon adding tab, the new tab gets selected, added to the end of the list, and the tab bar scrolls to display it. Just like [firefox's behavior](https://user-images.githubusercontent.com/52676199/95122075-99bdea00-0715-11eb-8f90-92bd91ac93c8.gif)
- [List all](https://user-images.githubusercontent.com/52676199/95121452-ad1c8580-0714-11eb-873f-288677cbc33e.png)
  - [selected tab](https://user-images.githubusercontent.com/52676199/95122421-1650c880-0716-11eb-9429-2af320765ea5.png) should show up in the middle of the dropdown display area if possible.
- [Keyboard controls](https://user-images.githubusercontent.com/52676199/95121456-adb51c00-0714-11eb-9479-7a754a0578a0.png)

**Comment by JordanWSmith15** [comment]
This enhancement should be prioritized at the Carbon level. Tabs are a very complex control, and I do not want to make any extensions to them in PAL which would be difficult to maintain on Carbon backmerges.

**Comment by ben-bacon** [comment]
Hey @JordanWSmith15 – if I recall correctly, this enhancement is to support [functionality on the AI Apps dashboard pattern](https://pages.github.ibm.com/ai-applications/design/patterns/dashboards-v2/overview#views). Do I have that right? @dianatran18

**Comment by JordanWSmith15** [comment]
Duplicate of https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2149
