### ISSUE TITLE
[PageTitleBar] update styling to match new spec

### ISSUE THREAD

**Issue by sstone2423** [carbon-design-system/carbon-addons-iot-react#1661]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

Internal issue: https://github.ibm.com/wiotp/monitoring-dashboard/issues/1363

With the upcoming and in progress DashboardEditor comes a new spec for PageTitleBar.

See specs below for details:

![image (1)](https://user-images.githubusercontent.com/25177649/95256496-8465c000-07e8-11eb-9a0b-07840603f8ab.png)

![image (3)](https://user-images.githubusercontent.com/25177649/95256763-dad2fe80-07e8-11eb-9c7a-103d97f92a30.png)

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

October release

### Available extra resources

What resources do you have to assist this effort?

 I can add this in

**Comment by stuckless** [comment]
Do these stories include any designs for how this should be rendered when on a tablet/phone... or how the right side collapses into the left side as the screen shrinks?

**Comment by sstone2423** [comment]
@CynZhang Do we have designs for the different viewpoints as @stuckless is asking about?

**Comment by CynZhang** [comment]
@dianatran18 should we discuss this with Mckenzie and update the design specs of the current header component? I don't think we have formalized how the elements respond to adapt to different viewports. But here's my take on the adaptive view of the header. Our dashboard page has the most elements in the header area, it's based on the three breakpoints that we currently have. On small breakpoint, it could utilize the split button to keep all options in one menu.

![image](https://user-images.githubusercontent.com/46002772/95628060-4caa8280-0a4b-11eb-9edb-6bd54283662d.png)

**Comment by dianatran18** [comment]
We're currently working on updating the page header component overall, so we can account for responsive guidelines in there. Anything you can share with us would be great!

I had a question: is the page header pinned when the user scrolls on the dashboard, or does the whole page scroll and the page header scrolls with it?
