### ISSUE TITLE
[HierarchyList] pagination hides list items

### ISSUE THREAD

**Issue by bjornalm** [carbon-design-system/carbon-addons-iot-react#1663]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

When expanding a category in the list the pagination component does not follow the new height of the list, instead it hides part of the list.

### To Reproduce

1. Go to 'story/watson-iot-experimental-hierarchylist--stateful-list-with-nested-searching'
2. Click on category New York Mets
3. Scroll down if needed to see the pagination

### Expected behavior

The pagination component should be at the bottom of the list

### Environment/versions:

- OS: [e.g. MacOS]
- Browser: [chrome]

### Additional context
![image](https://user-images.githubusercontent.com/5167091/95298635-ac066800-087c-11eb-8515-a24b0363457b.png)

**Comment by kevinsperrine** [comment]
This has been fixed. I believe probably by the PR that fixed this issue: https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1479.

https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-hierarchylist--stateful-list-with-nested-searching
