### ISSUE TITLE
[StatefulTable] the column header is truncated with "..." when "width" is set in columns parameter

### ISSUE THREAD

**Issue by ilovepumpkin** [carbon-design-system/carbon-addons-iot-react#1683]
### What package is this for?

- [x ] React
- [ ] Angular

### Describe the bug

Today I updated to the latest Iot carbon version, I found an issue. As you can see below, the first column (should be "Name") and 3rd column (should be "Description") headers are incomplete. There is not such issue in previous versions, so I am sure this is kind of regression issue. I am using StatefulTable component, and in columns array, I set "width:20%" for first column, and "width:30%" for the 3rd one.  I checked the styles of table header and found that a strange style makes the header label occupies 30% of the column header.

![image](https://user-images.githubusercontent.com/11310645/95970913-1736d800-0e43-11eb-86ff-7c422940785c.png)

### Environment/versions:

- `carbon-addons-iot-react` version: v2.133.0

**Comment by bjornalm** [comment]
I can recreate this with a StatefulTable with options `hasResize:false` and columns `isSortable: true` but the issue is then also present in 2.117.0. What table props are used when this is working as expected in 2.117.0?

**Comment by bjornalm** [comment]
What was the behaviour before this bug? Did the columns with a width in percentage actually get the desired widths as well?

**Comment by bjornalm** [comment]
To reproduce (configuration from @ilovepumpkin via slack)

columns:
```
[
      {
        id: 'name',
        name: msg('ui_diagnosisManager_modelTable_header_name'),
        isSortable: true,
        filter: {},
        width: '20%',
        renderDataFunction: ({ value: name, rowId }) => {
          return (
            <Link
              href="#"
              onClick={() =>
                this.onClickUpdateModel(models.find((x) => x.id === rowId))
              }
            >
              {name}
            </Link>
          );
        },
      },
      {
        id: 'version',
        name: msg('ui_diagnosisManager_modelTable_header_apiVersion'),
        isSortable: true,
        filter: {
          placeholderText: msg('ui_diagnosis2_pickUpVersion'),
          options: ['2.0', '1.1', '1.0'].map((value) => ({
            id: value,
            text: value,
          })),
        },
      },
      {
        id: 'description',
        name: msg('ui_diagnosisManager_modelTable_header_description'),
        isSortable: true,
        width: '30%',
        filter: {},
      },
      {
        id: 'created',
        name: msg('ui_diagnosisManager_modelTable_header_created'),
        isSortable: true,
        renderDataFunction: ({ value }) =>
          formatDate(value, { dateOnly: true }),
      },
      {
        id: 'updated',
        name: msg('ui_diagnosisManager_modelTable_header_lastUpdated'),
        isSortable: true,
        renderDataFunction: ({ value }) =>
          formatDate(value, { dateOnly: true }),
      },
      {
        id: 'status',
        name: msg('ui_diagnosisManager_modelTable_header_status'),
        isSortable: true,
        filter: {
          placeholderText: msg('ui_diagnosis2_pickUpStatus'),
          options: ['active', 'inactivated'].map((value) => {
            const status = msg(
              value === 'active'
                ? 'ui_diagnosis_model_active'
                : 'ui_diagnosis_model_inactivated'
            );
            return {
              id: value,
              text: status,
            };
          }),
        },
        renderDataFunction: ({ value: status }) =>
          msg(
            status === 'active'
              ? 'ui_diagnosis_model_active'
              : 'ui_diagnosis_model_inactivated'
          ),
      },
    ]
```

options:
```
{
    hasFilter:true,
    hasPagination: true,
    hasRowActions: true,
    hasSearch:true,
 }
```

**Comment by gillibrand** [comment]
I'm hitting the same problem. Seems like any column width with a percentage value has this problem. Here I set the column to 33% and you can see that the column _label_ is being set to that width too, then clipped.

![image](https://user-images.githubusercontent.com/805573/104527366-69f66c00-55b9-11eb-9cd8-9819f8bbd367.png)

**Comment by ilovepumpkin** [comment]
@gillibrand I found this is related "isSortable" property. If you remove "isSortable" property, percentage width can work. Another workaround is that you use absolute pixel value like "100px" instead of percentage value.

**Comment by JordanWSmith15** [comment]
@bjornalm Let's re-test this with the recent updates you have made, and fix if still present.

**Comment by bjornalm** [comment]
@JordanWSmith15
I been investigating this and  @gillibrand is correct in that is was due to the label itself getting a max-width. That was solved by https://github.com/carbon-design-system/carbon-addons-iot-react/pull/2669 so it is no longer reproducible, but there is some leftover css using variables no longer present and I will clean that up in a PR for this.
