### ISSUE TITLE
[NumberInput] Wrong value showing up when Increasing/decreasing values

### ISSUE THREAD

**Issue by LucasLacer** [carbon-design-system/carbon-addons-iot-react#1693]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

When starting with a decimal value, in some cases after increase/decrease the value a strange value is displayed 
for example:
starting with 0,01, adding up 10 each time, at some point it showed 20,009999999999998.

### To Reproduce

1. Go to https://carbon-addons-iot-react.com/?path=/story/numberinput--default
2. Click on numberInput| Default
3. Change on knobs value(value) to: 0,01
4. Increase the value clicking the up arrow button

### Expected behavior

the value should change only by the step down/up value defined.

### Environment/versions:

- OS: MacOs
- Browser: chrome,safari

### Additional context

![image](https://user-images.githubusercontent.com/37111083/96155947-e60fe380-0ee6-11eb-9ba7-65710f86c5d3.png)

![image](https://user-images.githubusercontent.com/37111083/96156012-f922b380-0ee6-11eb-9cbe-f5fb98e3c8ea.png)

**Comment by tay1orjones** [comment]
Hi - thanks for reporting this. We directly re-export the NumberInput from Carbon with no modifications. This bug is present and reported in theirs as well - https://github.com/carbon-design-system/carbon/issues/5249

Copying relevant info from that issue:
> You hit a famous floating point issue with JavaScript. Will monitor how common the use case is, but meanwhile, you may try listening to onChange() and rectify the number yourself.

>For reference: https://stackoverflow.com/questions/588004/is-floating-point-math-broken
