### ISSUE TITLE
[Empty state] Empty states as an independent component

### ISSUE THREAD

**Issue by dianatran18** [carbon-design-system/carbon-addons-iot-react#1696]
### What package is this for?

- [ ] React
- [x] Angular

Build empty states as it's own component so that it can be used in different contexts vs being created for each use case separately.

This is based on the [Carbon empty state pattern](https://www.carbondesignsystem.com/patterns/empty-states-pattern), but we have created AI Apps specific [empty state guidance](https://pages.github.ibm.com/ai-applications/design/components/empty-states/usage) that includes content suggestions and six illustrations that can universally be used.

**Note:** These empty states work for full pages and larger spaces such as lists and tables. The empty states for smaller spaces such as dashboard cards might be unique (with no image).

![image](https://user-images.githubusercontent.com/43549567/96294454-62bfc200-0fba-11eb-9f1f-33a8530cd803.png)

Illustration SVGs can be downloaded [here](https://ibm.box.com/s/x224l8t2dlqg0p0w3sxsu1piqqalpm5j)

Design specs:
![Empty state specs](https://user-images.githubusercontent.com/43549567/96294578-969ae780-0fba-11eb-9f92-d98d3841d246.png)

**Comment by sstone2423** [comment]
Looks like this one is complete
