### ISSUE TITLE
[AccordionItemDefer] deprecate in favor of Carbon's deferComponentRender

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1703]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

Carbon v10.23.0 should contain https://github.com/carbon-design-system/carbon/pull/7079 which introduces a new HOC, `deferComponentRender`, that will replace the need for our `AccordionItemDefer`. The HOC can be used with any component to defer rendering on initial mount to prevent performance bottlenecks! 🎉 

- [ ] Modify our exports to export `deferComponentRender` from Carbon
- [ ] Ensure we pull through any related documentation on `deferComponentRender`
- [ ] Update our Accordion documentation (if not automatically pulled through via Carbon's storybook documentation)
- [ ] Modify `AccordionItemDefer` to use `deferComponentRender` under the hood
- [ ] Add a deprecation notice to `AccordionItemDefer` directing users to refactor to `deferComponentRender`

### Specific timeline issues / requests

It looks like this will probably ship in 10.23.0 which is slated for end of October/early November 2020.

### Available extra resources

We might roll this into the Carbon upgrade itself https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1702, which a member of the core team will work through.

**Comment by kevinsperrine** [comment]
@tay1orjones Digging into this w/ regard to https://github.com/carbon-design-system/carbon-addons-iot-react/pull/1943; however, it seems https://github.com/carbon-design-system/carbon/pull/7079 was simply closed and never merged.

**Comment by tay1orjones** [comment]
Yeah this can be closed since the HOC didn't pan out.
