### ISSUE TITLE
[repo] umd build is broken, stackblitz fails to load

### ISSUE THREAD

**Issue by jonguenther** [carbon-design-system/carbon-addons-iot-react#1707]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

The codesandbox linked in the issue template cannot load the`carbon-addons-iot-react`. This also affects Stackblitz.

### To Reproduce

1. Open [Codesandbox](https://codesandbox.io/s/github/IBM/carbon-addons-iot-react/tree/master/examples/codesandbox) or [Stackblitz](https://stackblitz.com/github/carbon-design-system/carbon-addons-iot-react/tree/master/examples/codesandbox)
1. Codesandbox won't progress loading while Stackblitz will show show an error after installing the packages.

### Expected behavior

Both editors should be able to load the `carbon-addons-iot-react` package.

### Environment/versions:

- Browser: Chrome & Safari
- `carbon-addons-iot-react` version: `>= 2.115.3`

### Additional context

Stackblitz can actually load `carbon-addons-iot-react` up to version `2.115.2` [(example Stackblitz)](https://stackblitz.com/edit/carbon-dummy?file=package.json) whereas Codesandbox seems to not be able to load any recent versions.

**Comment by tay1orjones** [comment]
Thanks for reporting this! We're aware of the issue with Codesandbox (#1370). Unfortunately it's something they need to fix on their end.

The Stackblitz error is from our `umd` build beginning with v2.115.3 where [in the diff](https://github.com/carbon-design-system/carbon-addons-iot-react/compare/v2.115.2...v2.115.3) you can see the rollup config was altered as part of https://github.com/carbon-design-system/carbon-addons-iot-react/pull/1590. I'm concerned the umd build may be broken in other environments besides Stackblitz, though I haven't confirmed yet. 


@scottdickerson What was the reason for the build change? Looks like this has broken the build before, https://github.com/carbon-design-system/carbon-addons-iot-react/pull/677. `rollup-plugin-node-builtins` has never been used despite it being added as a dependency. The package overall is a bit of a mess - it [isn't maintained](https://github.com/calvinmetcalf/rollup-plugin-node-builtins/issues/56), [has conflicting licenses](https://github.com/calvinmetcalf/rollup-plugin-node-builtins/issues/65) declared in package.json and the readme.md, author is unresponsive to calls for [updates](https://github.com/calvinmetcalf/rollup-plugin-node-builtins/issues/58) or [deprecation](https://github.com/calvinmetcalf/rollup-plugin-node-builtins/issues/65). Unfortunately the rollup team [doesn't really have a good solution](https://github.com/rollup/plugins/pull/51).

**Comment by tay1orjones** [comment]
Woops, reopening. I'm going to mark this as a sev1 until we can confirm the umd build works in a CRA

**Comment by tay1orjones** [comment]
I've confirmed the UMD build is broken when spinning up a `npx create-iot-react-app <app-name>` and modifying the the import to force the umd version in `App.js`

```diff
 import {
   HeaderContainer,
   Header,
   SideNav,
   Button,
   PageTitleBar,
- } from "carbon-addons-iot-react";
+ } from "carbon-addons-iot-react/umd/carbon-addons-iot-react";
```
