### ISSUE TITLE
[TableCard] horizontal scrollbar and focus border offset

### ISSUE THREAD

**Issue by sstone2423** [carbon-design-system/carbon-addons-iot-react#1709]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

TableCards have a horizontal scrollbar and there is some odd spacing issues that are causing focus borders around the card to be offset

  ![Screen Shot 2020-10-19 at 6 03 04 AM](https://user-images.githubusercontent.com/3360588/96446087-895a4480-11d6-11eb-94be-ee95744fe584.png)

![Screen Shot 2020-10-20 at 8 15 40 AM](https://user-images.githubusercontent.com/25177649/96591097-7d40b680-12ac-11eb-826a-ff6377576dd5.png)

### To Reproduce

1. Go to /?path=/story/watson-iot-experimental-dashboardeditor--default once DashboardEditor is merged in
2. Add a TableCard
3. Select the TableCard
The overflow scroll can also be seen in TableCard stories

### Expected behavior

Focus border should be the same size all the way around the card and there should not be a horizontal scrollbar on initial render of a card size

### Environment/versions:

- OS: MacOS
- Browser: chrome
- `carbon-addons-iot-react` version: v2.129.0

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

No specific timeline

**Comment by kevinsperrine** [comment]
I believe this has been fixed. I don't see it in any of the stories involving TableCards or the DashboardEditor.

https://next.carbon-addons-iot-react.com/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-dashboardeditor--with-initial-value

https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-tablecard--with-multiple-actions

Feel free to re-open if it still persists.
