### ISSUE TITLE
[release] October - v2.140.0

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#1724]
End of sprint items:

- [x] merge `next` into `master `to publish the next version of our main channel.
- [x] merge `master` into `next` to properly bump up the version of our next channel
- [x] Create an overview of the features and bugs that were completed during the October sprint of both core and outside contributors.

**Comment by tay1orjones** [comment]
List of pull requests merged during October

https://github.com/carbon-design-system/carbon-addons-iot-react/pulls?page=1&q=is%3Apr+is%3Aclosed+merged%3A2020-10-01..2020-10-30
