### ISSUE TITLE
[HierarchyList] there is obvious delay after adding "rowActions" in data

### ISSUE THREAD

**Issue by ilovepumpkin** [carbon-design-system/carbon-addons-iot-react#1727]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

If the data for "items" contains "rowActions" - either at the level1 or level2 (children), when you moving the items, you will feel obvious delay. 

### To Reproduce

1. Add "rowActions" in "items" data - either at level 1 or level2, "editingStyle" property is set to "single"
2. Move any item the list

(I was trying to create an demo in sandbox, but got errors about installing dependecies)

### Expected behavior

The item should be moved smoothly 

### Environment/versions:

- OS: [Fedora]
- Browser: [chrome]
- `carbon-addons-iot-react` version: [2.133.0]

### Additional context
The moving is smooth if there are no "rowActions".

**Comment by kevinsperrine** [comment]
@ilovepumpkin Can you confirm this is still an issue? I modified a story to recreate it and recorded this gif. Is the issue shown below?

![list-action-reorder](https://user-images.githubusercontent.com/609466/125958108-2a6f96a2-197a-48c5-936d-cc07be5cec08.gif)

**Comment by JordanWSmith15** [comment]
@ilovepumpkin Closing as stale. If this is still an issue, please re-open
