### ISSUE TITLE
[CardEditor] ImageCard editing support

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1741]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

`ImageCard`s should be editable in the `DashboardEditor` via `CardEditor`. Similar in scope to the [TimeSeriesCard](https://next.carbon-addons-iot-react.com/?path=/story/watson-iot-experimental-cardeditor--for-timeseries)

**Additional context** 
- [Internal issue 1152](https://github.ibm.com/wiotp/monitoring-dashboard/issues/1152)
- Related: https://github.com/carbon-design-system/carbon-addons-iot-react/pull/1713

### Specific timeline issues / requests

Marked as a `val:1`, adding to the core team's scope for November.

**Comment by davidicus** [comment]
I am closing this as all parts are complete outside the hotspot editor work that is being tracked [here](https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1753).
