### ISSUE TITLE
[All] add a validation to the generated css file to give an error when it contains & in the output

### ISSUE THREAD

**Issue by stuckless** [carbon-design-system/carbon-addons-iot-react#1745]
### What package is this for?

- [x] React
- [x] Angular

### Summary

There have a couple of issues now where the generated output .min.css file contains an `&` because of sass (likely something not getting processed correctly).  Could we add a simple post-process that checks if the file has `&` and fail the build if it does?

**Comment by JordanWSmith15** [comment]
Stale
