### ISSUE TITLE
[DashboardEditor] id can't be changed through JSON editor

### ISSUE THREAD

**Issue by sstone2423** [carbon-design-system/carbon-addons-iot-react#1762]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

If editing a card in the JSON editor, the id can't be changed because the logic depends upon the id for updates and control

### To Reproduce

1. Go to DashboardEditor story
2. Create any card
3. Select the card
4. Open the JSON editor
5. Change the id
6. Save
7. See that the id did not save

### Expected behavior

The id should be editable OR the id should be disabled for editing

### Environment/versions:

- OS: MacOS
- Browser: chrome
- `carbon-addons-iot-react` version: ^2.141.0-next.3

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

November release

**Comment by scottdickerson** [comment]
honestly we can just hide the ID from the user

**Comment by scottdickerson** [comment]
this is fixed now
