### ISSUE TITLE
[ThresholdsEditor] New component for editing data source configuration and thresholds

### ISSUE THREAD

**Issue by bjornalm** [carbon-design-system/carbon-addons-iot-react#1769]
Part of issue #1753

### What package is this for?

- [x] React
- [ ] Angular

### Summary

We need a new component for editing (hotspot) data source items:
- label
- filter
- unit
- decimal
- thresholds
TODO: This one is not yet 100% completely defined.

**Additional context** 
![image](https://user-images.githubusercontent.com/5167091/103240021-7212a280-494f-11eb-8473-c3b1dcf1e6e4.png)

_Carbon add-ons for Watson IoT is a collaborative system. We encourage teams to
build components and submit them for integration._

**Comment by davidicus** [comment]
@bjornalm putting the needs design label for further definition. If not accurate please remove.

**Comment by bjornalm** [comment]
Based on slack conversation in #iot-mam-dashboard-editor on now 16th I think @JoelArmendariz was gonna pick this one up since he had already started working on a very similar version. Is that correct Joel?

**Comment by sstone2423** [comment]
This is complete
