### ISSUE TITLE
[repo] support React 17

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/carbon-addons-iot-react#1778]
hi, when will the update for? React v17.0.1

### What package is this for?

- [x] React

`npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6" from carbon-addons-iot-react@2.140.0
npm ERR! node_modules/carbon-addons-iot-react
npm ERR!   carbon-addons-iot-react@"*" from the root project`

**Comment by tay1orjones** [comment]
I'm open to modifying the peer dependency range, though we haven't tested any part of the codebase with React 17.

```diff
  "peerDependencies": {
    "d3": ">=5.0.0 <=5.14.2",
-   "react": "^16.8.6",
-   "react-dom": "^16.8.6"
+   "react": "^16.8.6 || ^17.0.1"
+   "react-dom": "^16.8.6 || ^17.0.1"
  },
```

We can have 17 in the peer deps to avoid the warning and keep the dev dependency versions where they are. That said, this work needs to include temporarily modifying the dev dependency range and run storybook, tests, etc. and report any defects. The biggest blocker I think will be our dependencies supporting 17. Enzyme doesn't yet, for instance. 

Would be happy to accept a PR 🙂

**Comment by JordanWSmith15** [comment]
Closing as stale
