### ISSUE TITLE
[PageTitleBar] create Error state for an entire Page

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#1801]
Just the idea is that we could pass an Error to an Page and have it be rendered consistently across the PAL, similar to our other error states.  Perhaps this should have a Refresh link as well.

### What package is this for?

- [x] React
- [ ] Angular

### Summary

Please describe your request in one or two sentences.

**Additional context** Add any other context or screenshots about the feature
request here.

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon add-ons for Watson IoT is a collaborative system. We encourage teams to
build components and submit them for integration._

**Comment by JordanWSmith15** [comment]
We've implemented something similar in Graphite, so would be unlikely to prioritize this
