### ISSUE TITLE
[Hotspots] update hotspot to use carbon colors.

### ISSUE THREAD

**Issue by bjornalm** [carbon-design-system/carbon-addons-iot-react#1806]
### What package is this for?

- [x] React
- [ ] Angular

### Summary
Colors used in the hotspot css do not match carbon colors. We might want to have a designer look at this.

**Comment by tay1orjones** [comment]
https://github.com/carbon-design-system/carbon-addons-iot-react/blob/3133d03b2f446a68a1217264b4168c5d4ed0dda3/src%2Fcomponents%2FImageCard%2F_hotspot.scss#L15-L21

https://github.com/carbon-design-system/carbon-addons-iot-react/blob/3133d03b2f446a68a1217264b4168c5d4ed0dda3/src%2Fcomponents%2FImageCard%2F_hotspot.scss#L41-L51

The box shadows could be standardized to [the helper mixin from carbon](https://github.com/carbon-design-system/carbon/blob/ab61506d52a9e500c4408b83b6b43ce3a87494d6/packages%2Fcomponents%2Fsrc%2Fglobals%2Fscss%2F_helper-mixins.scss#L53-L59)?

The white background ensures that the hotspots aren't transparent.

@dianatran18 These styles are visible on the hotspot present in [the basic imagecard story](https://next.carbon-addons-iot-react.com/?path=/story/watson-iot-imagecard--basic)
