### ISSUE TITLE
[ImageHotspots] clicking on hotspots sometimes fails to open tooltip 

### ISSUE THREAD

**Issue by bjornalm** [carbon-design-system/carbon-addons-iot-react#1808]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug
When clicking on a hotspot the tooltip is shown but sometimes it is immediately closed again. This is extra clear when using icon hotspots.

### To Reproduce

1. Go to https://carbon-addons-iot-react.com/?path=/story/watson-iot-imagehotspots--landscape-image-landscape-container
2. Click on Hotspot2 and then Hotspot1. 
3. Repeat step 2.

### Expected behavior

The tooltip should stay open.

### Environment/versions:

- OS: [MacOS]
- Browser: [chrome]

**Comment by kevinsperrine** [comment]
This has been fixed at some point. The error still happens in the production link above, but I cannot recreate it [on next](https://next.carbon-addons-iot-react.com/?path=/story/watson-iot-imagehotspots--landscape-image-landscape-container). 

//cc @davidicus @bjornalm

**Comment by bjornalm** [comment]
Nice!
