### ISSUE TITLE
[SuiteHeader] add test coverage

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1810]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

`SuiteHeader` and it's subcomponents/hooks `useSuiteHeaderData`, etc are not covered in unit tests but should be to the expected threshold of 80%.

### Environment/versions:

- `carbon-addons-iot-react` version: 2.140.0

### Additional context

There is an [ignore in the jest config](https://github.com/carbon-design-system/carbon-addons-iot-react/pull/1757/files?file-filters%5B%5D=.js#diff-1e058ca1442e46581b13571fb8d261f9e1f5657e26c96634d4c1072f0f0347f1R6) added in #1757 that should be deleted as part of this.

**Comment by tay1orjones** [comment]
This can help inform how we should expect/document hooks to be unit tested #1615

**Comment by bjornalm** [comment]
Closed by https://github.com/carbon-design-system/carbon-addons-iot-react/pull/2693
