### ISSUE TITLE
[Component Proposal] Menu button

### ISSUE THREAD

**Issue by mzuliani-ibm** [carbon-design-system/carbon-addons-iot-react#1821]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

Describe in detail the component you would like developed. Include what
offering/product you plan to utilize this new component in.
- IBM Engineering

**Additional context** 
Menu button, per AI Apps web site:
https://pages.github.ibm.com/ai-applications/design/components/buttons/usage#menu-button

In addition to existing PAL design:
- Read-only headings
- Separator
- Sub-menus

![1 1 Create button variants@2x](https://user-images.githubusercontent.com/11927321/99598725-ff192200-29c7-11eb-9cad-18a7e5310aea.png)

### Specific timeline issues / requests

Do you want this work within a specific time period? ASAP
Is it related to an upcoming release? Yes

### You will consider this component complete when...

- [x] It's available as an export of this library
- [x] Additional criteria you may have [Accessible to WCAG 2.0]

### Available extra resources

What resources do you have to assist this effort?
TBD

**Comment by tay1orjones** [comment]
The entirety of the spec outlined above requires support for nesting of OverflowMenuItems inside the overflow menu.

This issue can/should be contained to the menu button itself, with the additional changes to the overflow menu to be delivered/contained in https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1443

**Comment by davidicus** [comment]
Carbon is set to publish the context menu in v7.31.0 next week.

**Comment by tom-poulin** [comment]
@davidicus @lorelei-ngooi
Per Lorelei's email, ELM has a requirement to show tooltips on menu items, including (specifically) disabled menu items. The use case here is to inform the user why the menu item is disabled so they can correct it.
![image](https://user-images.githubusercontent.com/70283126/112514175-48042d00-8d52-11eb-823f-516baf0abeea.png)

**Comment by davidicus** [comment]
@tom-poulin does the browser tooltip based of title suffice or do we need actual tooltip like we have in the component library?

**Comment by tom-poulin** [comment]
@davidicus I actually prefer the browser tooltip - it's simpler and less obtrusive. @mzuliani-ibm, do you have any objections to this? I wasn't sure if using the browser-based tooltips (title attribute) was out of favor in Carbon.

I believe @lorelei-ngooi had tried to use the browser-based tooltip before but was getting browser warnings because she could attach it to the right element. Lorelei, please chime in you have more to add - I think our conclusion was that the component needed to support passing through the tooltip.
