### ISSUE TITLE
[TimeSeriesCard] data point isFilled is being lost when hovered

### ISSUE THREAD

**Issue by sstone2423** [carbon-design-system/carbon-addons-iot-react#1825]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

See https://github.com/carbon-design-system/carbon-charts/issues/895

### To Reproduce

1. Enable the zoombar on a TimeSeriesCard on the alert range story
2. Hover over any data point
3. See that the fill is lost

https://codesandbox.io/s/nifty-flower-sgir0?file=/src/index.js

### Expected behavior

Should not lose fill

### Environment/versions:

- OS: MacOS
- Browser:chrome
- `carbon-addons-iot-react` version: 2.141.0-next.25

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by scottdickerson** [comment]
this is fixed now
