### ISSUE TITLE
[BarChartCard] resizing card will break the component

### ISSUE THREAD

**Issue by bjornalm** [carbon-design-system/carbon-addons-iot-react#1837]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

Resizing the BarcChartCard  will break the component 

![image](https://user-images.githubusercontent.com/5167091/100632077-af721900-332c-11eb-83ad-1289c1aee78d.png)

This issue was introduced with this change https://github.com/carbon-design-system/carbon-addons-iot-react/pull/1776/files#diff-7694ad9339152b027d404b6561d9948138ff92c11f17b82b157840c1458e3c95R124-R126

**BUT** it also looks like the upgrade of the carbon charts in this PR will solve the problem
https://github.com/carbon-design-system/carbon-addons-iot-react/pull/1835

### To Reproduce

1. Go to https://next.carbon-addons-iot-react.com/?path=/story/watson-iot-barchartcard--simple-bar-vertical
2. Use the knobs to change the size of the card

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/IBM/carbon-addons-iot-react/tree/master/examples/codesandbox

### Expected behavior

Changing size should be working

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by sstone2423** [comment]
Looks like this isn't an issue anymore
