### ISSUE TITLE
[CardEditForm] Open JSON Editor is scrolled off screen

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#1840]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

The Card Edit Form on the Dashboard Editor scrolls off screen to the bottom
![image](https://user-images.githubusercontent.com/6663002/100669457-096de100-3323-11eb-96ca-4d1dfe893efa.png)

### To Reproduce

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/IBM/carbon-addons-iot-react/tree/master/examples/codesandbox

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by JoelArmendariz** [comment]
This was actually an issue in Monitor. Issue here: https://github.ibm.com/wiotp/monitoring-dashboard/issues/1796

**Comment by JoelArmendariz** [comment]
Monitor side PR: https://github.ibm.com/wiotp/maximo-asset-monitor-ui/pull/1581

**Comment by JoelArmendariz** [comment]
Closing in favor of the new issue in Monitor.
