### ISSUE TITLE
[ui-shell] Small breakpoint issues

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-addons-iot-react#1845]
### What package is this for?

- [ ] React

### Describe the bug

• On small screens, text wraps instead of ellipses
• Hamburger and other icons reduce in width
![Screen Shot 2020-12-01 at 3 08 00 PM](https://user-images.githubusercontent.com/21066152/100791470-4bf8f180-33e7-11eb-8ca3-d95bf1e19b07.png)

### To Reproduce

Not reproducable at [IoT storybook](https://carbon-addons-iot-react.com/?path=/story/watson-iot-header--header-subtitle) because there are not enough icons. But, with MAS fully hooked up, the number of icons cause issues. Example can be seen in Graphite which uses the full MAS set of icons
1. Go to 'https://pages.github.ibm.com/maximo-app-framework/graphite/reference-app/#/about'
2. Make screen small or go into responsive mode
3. See error

### Expected behavior

While we don't necessarily support mobile in all apps, it is inevitable that a customer will report this as a bug. Clients and business partners may also choose to create their own simple Graphite/Maximo application for usage on the phone. The masthead should hide some of the less necessary text, or truncate down appropriately with the Carbon smaller breakpoints

### Specific timeline issues / requests
Would be nice to fix this for MAS 8.3

**Comment by tay1orjones** [comment]
@dianatran18 Could we take a look at this from a design perspective and define expectations for how/when/where the header items should collapse at smaller widths? I don't think there's much (any?) guidance for this right now.

**Comment by katedraper** [comment]
@dianatran18 can you please take a look at this item in the March sprint so we can consider it in the next dev sprint?

**Comment by dianatran18** [comment]
MAS has started to look into how to handle responsiveness in the ui shell top nav, so I would follow that:
https://ibm.invisionapp.com/share/6KO0UT1TZUY#/screens/319846452_4-_Responsive_Behaviours

At a small breakpoint, collapse the actions into an overflow menu, and if the App name is long and still can't fit, then use truncation. 

Since this is guidance for Maximo Application Suite, I think all Maximo products should follow for consistency.

**Comment by JordanWSmith15** [comment]
This issue has reared it's head in Maximo Everyplace, after we consumed the MAS Header in Manage. Maximo Everyplace is a very old mobile framework, but still has heavy adoption in the field. This needs to be fixed by 8.5.
