### ISSUE TITLE
[HierarchyList] Add option for complex pagination

### ISSUE THREAD

**Issue by jonguenther** [carbon-design-system/carbon-addons-iot-react#1850]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

Add an option for complex pagination, or let user overwrite pagination for the component.

**Additional context** 

Currently, HierarchyList and SimpleList only use SimplePagination. To provide additional information to the user (max pages, items per page, etc.), the carbon pagination should be an option.

**Comment by tay1orjones** [comment]
Thanks for brining this up @jonguenther! The type of pagination for the List was a design-based decision. 

@dianatran18 could the design team review this? If we can/should provide the option of more robust pagination.

**Comment by JordanWSmith15** [comment]
Closing this issue as stale. Will re-open if and when such a design is required for an upcoming release.
