### ISSUE TITLE
[PageTitleBar] breadcrumb font size should be 12

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#1883]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

The PageTitleBar should follow the spec for what the design team has coined the 'Page Header'. The [AI Applications guidance for this component](https://pages.github.ibm.com/ai-applications/design/components/page-header/usage/) largely defers to the guidance provided by the CD&AI team. @ivanbachev brought up during office hours that the [CD&AI Page Header spec](https://pages.github.ibm.com/cdai-design/pal/components/page-header/style#typography) specifies the breadcrumbs should be 12px, whereas we currently use 14px.

### Expected behavior

The PageTitleBar breadcrumb would have 12px font size.

**Comment by tay1orjones** [comment]
This can be worked around by applying overriding styles to redefine the font-size

**Comment by davidicus** [comment]
This was addressed with the PageTitleBar [audit](https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2143)
