### ISSUE TITLE
[PageWizard] The bullets in left navigator are not displayed well in Safari

### ISSUE THREAD

**Issue by ilovepumpkin** [carbon-design-system/carbon-addons-iot-react#1890]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

The bullets in left navigator are not displayed well in Safari

### To Reproduce

Open https://carbon-addons-iot-react.com/?path=/story/watson-iot-pagewizard--stateful-example in Safari 

Now it is shown like below 
![image](https://user-images.githubusercontent.com/11310645/102952113-57809980-4509-11eb-861b-097e81db6aa8.png)

https://carbon-addons-iot-react.com/?path=/story/watson-iot-pagewizard--with-horizontal-progress-indicator 

![image](https://user-images.githubusercontent.com/11310645/102952672-a0851d80-450a-11eb-86e8-370bf6204f02.png)

### Expected behavior

Same as in Chrome 
![image](https://user-images.githubusercontent.com/11310645/102951943-fb1d7a00-4508-11eb-9aef-ce3aef6d7eee.png)
![image](https://user-images.githubusercontent.com/11310645/102952700-b1359380-450a-11eb-918b-9d859a98586d.png)

### Environment/versions:

- OS: [MacOS]
- Browser: [ safari]
- `carbon-addons-iot-react` version: [2.133.0+]

### Specific timeline issues / requests
Our project is going to be GAed in January. Is it possible to fix this issue ASAP?

**Comment by ilovepumpkin** [comment]
My fix is:

```
.iot--progress-step-button {
      flex-direction: column;
}
```

**Comment by davidicus** [comment]
This should be fixed along with #2129

**Comment by kevinsperrine** [comment]
@ilovepumpkin This seems to be fixed now. Can you confirm, please? 
![Screen Shot 2021-05-07 at 3 08 47 PM](https://user-images.githubusercontent.com/609466/117497229-34013d00-af46-11eb-8ba5-2a7ff30512b4.png)

**Comment by kevinsperrine** [comment]
closing. fixed in both chrome and safari now in both https://carbon-addons-iot-react.com/?path=/story/watson-iot-pagewizard--stateful-example and https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-pagewizard--stateful-example
