### ISSUE TITLE
[Hotspot] keep tooltip open for selected hotspots

### ISSUE THREAD

**Issue by bjornalm** [carbon-design-system/carbon-addons-iot-react#1895]
### What package is this for?

- [x] React
- [ ] Angular

### Summary
As part of #1753 hot spot editor modal we want the hotspot tooltip to stay open while changes are made to the content.
This is currently not possible due to a bug in the version of carbon-components-react  (7.17) we are using.

**Additional context**
The currently used version of the Tooltip component doesn't handle focusTrap={false} which means that the tooltip keeps stealing focus from other input fields. Check out this working example which is using carbon-components-react version 7.25.

https://codesandbox.io/s/tooltip-focustrap-bug-c05l8?file=/index.js

If you change the version of carbon-components-react to 7.17 you will see the error described above.

Once we upgrade to 7.25 we can implement this feature for the Hotspot. It can hopefully be done by adding something like
```
open={isSelected || undefined}
focusTrap={false}
```
to the Tooltip element in the Hotspot.jsx. 

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon add-ons for Watson IoT is a collaborative system. We encourage teams to
build components and submit them for integration._

**Comment by scottdickerson** [comment]
unfortunately it still didn't work all the way, I have opened a bug and PR on Carbon that should fix this:
https://github.com/carbon-design-system/carbon/issues/7598

**Comment by JordanWSmith15** [comment]
@scottdickerson Can this item be closed, since the Carbon item was closed?

**Comment by JordanWSmith15** [comment]
Fixed upstream

**Comment by bjornalm** [comment]
I still think changes to our Hotspot component is needed to make this work even when the Carbon bug is closed.
@JordanWSmith15 Did you get a confirmation by @scottdickerson that the upstream fix would solve this issue?
