### ISSUE TITLE
[HotspotEditorModal] only add the hotspot if the user holds CTRL key before clicking

### ISSUE THREAD

**Issue by bjornalm** [carbon-design-system/carbon-addons-iot-react#1897]
### What package is this for?

- [x] React
- [ ] Angular

### Summary
1. New hotspots should only be added if the user clicks on the image while holding down the ctrl key. Currently any click will add a new hotspot which causes hotspots to be accidentally added.
2. The info text should be updated to reflect this
3. (possibly optional) There has been requests to see the coordinates next to the mouse when hovering the image so that a person defining dynamic hotspots would now what the x/y values should be.

**Additional context** Add any other context or screenshots about the feature

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon add-ons for Watson IoT is a collaborative system. We encourage teams to
build components and submit them for integration._

**Comment by scottdickerson** [comment]
I'm checking with @CynZhang to see
