### ISSUE TITLE
after delete items in the last page of StatefulTable, show empty 

### ISSUE THREAD

**Issue by yanzhe2017** [carbon-design-system/carbon-addons-iot-react#1906]
we are using 
carbon-components@10.17.0 deduped
| +-- carbon-components-react@7.17.0

StatefulTable
There are 2 pages of data, I enter page2, and click all the items on page2 one by one, use toolbar action to delete the selected items, after that, the table show empty, but it is not really, it is just page2 has no data.
The expected behavior is either show previous page, or show current page has no data, and show the pagination.
![image](https://user-images.githubusercontent.com/25318085/103637689-cdafe200-4f86-11eb-812a-f3e13ace8399.png)

**Comment by davidicus** [comment]
Hi @yanzhe2017. From  the issue description is sounds like you are pulling in the carbon packages in addition to the `carbon-addons-iot-react` package. This may have unintended consequences. I would suggest removing those packages from your project.

**Comment by yanzhe2017** [comment]
I have removed carbon-components, only use carbon-addons-iot-react, same behavior, I have 3 pages of data, after I remove the items on the page3, the table show empty message, but it should mean No data in current page, instead of No data for all the table.

**Comment by tay1orjones** [comment]
> The expected behavior is either show previous page

This can be achieved by placing a unique `key` on the Table and changing it when items are deleted. This will regenerate/recreate the component. 

Alternatively you can change the pagination props yourself (to go to the previous page) in the callback that is called when delete is clicked. I believe the callback would be `onApplyBatchAction`.

**Comment by yanzhe2017** [comment]
I revisit this issue, I think this is a defect, in table implementation, if you find data is not empty, but current page is empty, you can just set page number as the first page.
In my application side, it is hard to track the current page number, the total page number, whether this is delete operation/add operation.

**Comment by JordanWSmith15** [comment]
@yanzhe2017 Is this issue still valid? I believe this placeholder state has been updated recently.

**Comment by yanzhe2017** [comment]
I use latest version 2.146.0-next.69 and retry, still get the same error, when remove the last item in page2, there are no pagination bar, cannot change page to page1.
![image](https://user-images.githubusercontent.com/25318085/127443969-e460b21c-029e-4b94-b08a-7c2fc19a8514.png)

**Comment by kevinsperrine** [comment]
@davidicus @dianatran18 What should the expected behavior be here? It's simple to fix it by just keeping the pagination bar visible and staying on the empty page, but then it gets weird because the totals no longer match; however, that could be out of our control if they're passing in props and update pagination props and move back to the previous page may not be clear either...

![delete last page](https://user-images.githubusercontent.com/609466/129246183-8e747814-d9f9-4147-b93e-6016be239b79.gif)

**Comment by dianatran18** [comment]
If I'm on the last page, and delete the last 10 items, then shouldn't it update to the last 10 items available in the data set — which would be 81-90 of 90 items and only 9 pages of data? The pagination bar should update and reflect the total number of rows when things are added or removed.

**Comment by JordanWSmith15** [comment]
> If I'm on the last page, and delete the last 10 items, then shouldn't it update to the last 10 items available in the data set — which would be 81-90 of 90 items and only 9 pages of data? The pagination bar should update and reflect the total number of rows when things are added or removed.

@kevinsperrine Maybe we should just refresh the entire element on delete to get this result.
