### ISSUE TITLE
[SuiteHeader] Side menu is not displayed correctly on RTL mode

### ISSUE THREAD

**Issue by camilasb** [carbon-design-system/carbon-addons-iot-react#1909]
### What package is this for?

- [X ] React
- [ ] Angular

### Describe the bug

Side menu is not displayed correctly on RTL mode

### To Reproduce

1. Open Carbon Storybook
2. Open SuiteHeader component > Header with side nav
3. https://carbon-addons-iot-react.com/?path=/story/watson-iot-suiteheader--header-with-side-nav
4. Click no RTL sub-tab
5. Toggle Right-to-left feature

![image](https://user-images.githubusercontent.com/20360162/103647531-3b81ec80-4f3a-11eb-8de1-ed416f31ad5f.png)
![image](https://user-images.githubusercontent.com/20360162/103647755-8b60b380-4f3a-11eb-9ae5-ba976dc35b80.png)

### Expected behavior

-Side menu should be on the right instead?
-Icons should be better visualized
-When side menu is opened, there should be more spacing in between the icons and the labels

### Specific timeline issues / requests

Impacting Graphite project

**Comment by tay1orjones** [comment]
Thanks for reporting this! One workaround you could use until this is fixed would be to restyle the sidenav rtl in your application.

Lightweight example below, though there's probably more classes you'll want to target:
```scss
[dir='rtl'] {
  .#{$iot-prefix}--side-nav__item {
    // your styles here
  }
}
```

**Comment by camilasb** [comment]
@sls-ca is this something we can do from our side?

**Comment by stuckless** [comment]
It is, but given that this is not blocking us (right now) the best course is to leave this open and have it fixed at the component level.  At some RTL will have to be addressed, and this is the best place to fix it.  We would do the work-around, for sure, if it was preventing us from releasing.

**Comment by camilasb** [comment]
Alright! We'll wait for your next version then @tay1orjones , thanks for the reply! =)
