### ISSUE TITLE
[ValueCardFormSettings]: the precision value should not be global across the value card, but set and managed per attribute

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#1911]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

If you use the DashboardEditor to manage a ValueCard you'll notice that the precision is in the Settings pane and is global to the whole Value Card.  We need this to be specific for each attribute.

It should be listed here in the details pane for a given attribute
![image](https://user-images.githubusercontent.com/6663002/103675733-85b89d00-4f3d-11eb-8cdd-436e9789ec0d.png)

**Comment by JoelArmendariz** [comment]
This will be addressed as part of my work to make the editor aware of data aggregation.
