### ISSUE TITLE
[Table] Row action buttons tooltip shows even when no label is passed to it

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-addons-iot-react#1930]
### What package is this for?

- [ ] React

### Describe the bug
The in-line row actions of the data table display a tooltip when you hover over the icon. However, if a label is not provided, the tooltip still shows, at a greatly reduced height, and emptu

### To Reproduce

Steps outlined in https://jsw.ibm.com/browse/GRAPHITE-27102
 
Reproduce:
http://health1.rtp.raleigh.ibm.com:9080/maximo_123/oslc/graphite/relengineer/index.html#/scoring
 jenn/jenn
When hovering over Row Actions in a Table, there is a horizontal black arrow. There should be a way to disable that arrow.

<img width="285" alt="Screen Shot 2021-01-13 at 9 26 28 AM" src="https://user-images.githubusercontent.com/21066152/104464876-6e069780-5581-11eb-9d29-81ce2c046006.png">
<img width="382" alt="Screen Shot 2021-01-13 at 9 26 20 AM" src="https://user-images.githubusercontent.com/21066152/104464885-7068f180-5581-11eb-81e0-4e2437cdeeb6.png">

### Expected behavior

If a label is not provided, the tooltip should not appear.  (We have added a build warning on the Graphite side if no tooltip is provided, but we cannot make it required)

**Comment by davidicus** [comment]
@JordanWSmith15 Is this not an a11y concern?

**Comment by JordanWSmith15** [comment]
I don't think this is reproducible anymore, and the graphite link was not correct. I am going to close for now.
