### ISSUE TITLE
[Button, Header, SideNav, AddCard, OverflowMenu] Interactions in Firefox slow/not possible

### ISSUE THREAD

**Issue by jkeen** [carbon-design-system/carbon-addons-iot-react#1950]
### What package is this for?

- [ ] React

### Describe the bug

Certain interactions with the following list of components in Firefox will grind things to a halt, eventually popping up the message "A Webpage is slowing down your browser. What would you like to do? [Stop it] [Wait]"

##### Button
1. Go to the [Button story](https://carbon-addons-iot-react.com/?path=/story/watson-iot-button--default)
2. Click on "Button"
3. Wait a few seconds

##### AddCard
1. Go to the [AddCard story](https://carbon-addons-iot-react.com/?path=/story/watson-iot-addcard--handles-click)
2. Click on "Click me"
3. Wait a few seconds

##### SideNav
1. Go to the [SideNav story](https://carbon-addons-iot-react.com/?path=/story/watson-iot-sidenav--side-nav-component)
2. Click on right most header action button
3. Wait a few seconds

##### Header
1. Go to the [Header story](https://carbon-addons-iot-react.com/?path=/story/watson-iot-header--header-action-buttons-with-dropdowns)
2. Click on the alert/bell icon in the header
3. Wait a few seconds

### Expected behavior

Not this

### Environment/versions:

- OS: MacOS, Windows
- Browser: Firefox v84-85
- `carbon-addons-iot-react` version: latest, possibly older judging from previous bug reports

### Additional context

These are all probably related to the same core component, but I'm not sure which is the culprit is at this point. The component might very well be in the base carbon library, but it's affecting everything and preventing other firefox-related bugs from being addressed.

Possibly related issues: #1219, carbon-design-system/carbon#975

**Comment by tay1orjones** [comment]
This might be caused by the storybook environment moreso than the components themselves. 

I'd be curious if turning off knobs and other addons for these stories fixes the issue or not. Also if it improves with updating storybook to v6 in #963

**Comment by jkeen** [comment]
@tay1orjones Good points, I'll look into that

**Comment by jkeen** [comment]
@tay1orjones You're right -- looks like it's`storybook/actions`, and the only suitable fix/workaround I've found so far is to specify the `depth` parameter, e.g. `action('submit', { depth: 3})`
