### ISSUE TITLE
[ComboChart] Cannot import ComboChart in Storyshot Test

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#1976]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

`ComboChartCard`'s import of Carbon's `ComboChart` works in storybook but not in story snapshot test. Snapshot Test have been ignored in order to publish `ComboChartCard` but we need to find the root cause of the error. 

Jest may have a different environment than the storybook but other charts like BarChartCard and TimeSeriesCard both work.

**Comment by jkeen** [comment]
The other charts were being mocked silently and secretly using the root level `__mocks__` folder (a feature I didn't know jest had). Adding the same for combochart fixes the problem.
