### ISSUE TITLE
[StatefulTable] table with sticky header and row expansion with inner table

### ISSUE THREAD

**Issue by lithilKu** [carbon-design-system/carbon-addons-iot-react#2022]
### What package is this for?

- [x ] React
- [ ] Angular

### Describe the bug

When I have a inner table (row expansion) and my outer table (StatefulTable) has sticky header, and the row is expanded, the outer tables rows are not pushed down

### To Reproduce

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/IBM/carbon-addons-iot-react/tree/master/examples/codesandbox

### Expected behavior

Wehn the row is expanded for a StatefulTable with sticky header and an iiner table for the expanded row, the below rows should be pushed down beyond teh inner table height.

### Environment/versions:

- OS:  Windows
- Browser: any or chrome
- `carbon-addons-iot-react` version: 2.141.0

### Additional context

Beforerow expansion:
![image](https://user-images.githubusercontent.com/78891055/107598889-bc838080-6c6a-11eb-8fa8-dc22352b6a9d.png)

After row expansion:
![image](https://user-images.githubusercontent.com/78891055/107598844-a5dd2980-6c6a-11eb-8cfe-8a05ae261583.png)

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by davidicus** [comment]
Sticky header is an experimental feature from Carbon library and as such has not been properly integrated with our other features. If there is a product need to support sticky header we should open up an issue and begin design discussions during our office hours. I would be more than happy to open an issue regarding this. Do you work on a product team that I can add to the issue?
