### ISSUE TITLE
[HotspotContent] passing prop to DOM element

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#2031]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

We are passing a React prop to an element that gets rendered to the DOM. Make sure we remove any props not meant to be rendered.

### To Reproduce

1. Open developer tools
2. Go to http://localhost:3000/?path=/story/watson-iot-hotspotcontent--basic

**Comment by kevinsperrine** [comment]
Fixed by #1382
