### ISSUE TITLE
[ImageHotSpots] Story is throwing error. 

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#2032]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

Story is producing error
![image](https://user-images.githubusercontent.com/1590966/107792852-9c63c800-6d23-11eb-8f87-a0f6fb1ee937.png)

Not sure if it is the story or component. 

### To Reproduce

1. Open dev tools
2. Go to http://localhost:3000/?path=/story/watson-iot-imagehotspots--editable-with-text-hotspot
3. See error

**Comment by kevinsperrine** [comment]
Fixed by #1382
