### ISSUE TITLE
[Table] Stories throwing warning due to deprecated prop type

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#2033]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

Our table stories are using array of nodes and should be passing render function. We should update the stories to remove the noise in our snapshots. 

### To Reproduce

1. Open dev tools
2. Go to http://localhost:3000/?path=/story/watson-iot-table--table-example-with-create-save-views
3. See error

**Comment by kevinsperrine** [comment]
Fixed in #1382
