### ISSUE TITLE
[Table] Clean up table stories

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#2034]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

There are a few console warnings in multiple stories. There are also too many. We need to segment up to have stateful, non-stateful, and more playground type stories so we can consolidate the number we have. We should also look to see how we can rename the stories so they are more digestible. 

Putting a high impact label because I think this will help all devs looking to get information on the data table and how to use it.

**Comment by JordanWSmith15** [comment]
Let's do this for September... it has been an issue for quite some time.

**Comment by JordanWSmith15** [comment]
Table examples to clean up:
Too much content/scrolling
Console errors on some storybooks
Headers with ellipsis/bad examples
