### ISSUE TITLE
[HotspotEditorModal] Warnings and errors in our storybook

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#2035]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

There are multiple warnings and errors that we are seeing in the HotspotEditorModal stories. We need to review and remove the offending code. 

http://localhost:3000/?path=/story/watson-iot-experimental-hotspoteditormodal--empty

**Comment by davidicus** [comment]
related to #1382

**Comment by kevinsperrine** [comment]
Fixed in #1382
