### ISSUE TITLE
[Tooltip] steals focus when shown

### ISSUE THREAD

**Issue by d-akara** [carbon-design-system/carbon-addons-iot-react#2057]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

Tooltip steal focus when shown.

### To Reproduce

1. Create an input field which triggers a Tooltip on typing.
2. Attempt to type in the entry field
3. The tooltip will steal the focus preventing typing in the input field

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/IBM/carbon-addons-iot-react/tree/master/examples/codesandbox
```javascript
import React from 'react';
import {useState} from "react";
import { render } from 'react-dom';
import {Tooltip, Search} from "carbon-components-react";
import 'carbon-addons-iot-react/css/carbon-addons-iot-react.css';

const App = () => {
  const [showTooltip, setShowTooltip] = useState(false)
  return (
    <>
      <Search size={"sm"}
              onChange={()=> setShowTooltip(true)}
              placeHolderText={"type here to lose focus"}
      />
      <Tooltip
          tabIndex={-1}
          showIcon={false}
          open={showTooltip}>
          I'm stealing the focus
      </Tooltip>
    </>
)};

render(<App />, document.getElementById('root'));
export default App;
```

### Expected behavior

Showing the tooltip should not prevent typing into the input field.

### Environment/versions:

- OS: MacOS, Windows
- Browser: firefox, chrome
- `carbon-addons-iot-react` version: [v2.142.0]

### Additional context

This issue seems to be caused by https://github.com/carbon-design-system/carbon/issues/6719
Which appears to be fixed starting with carbon v10.21.0 https://github.com/carbon-design-system/carbon/commit/225f212a8f3e2bd86d4a23f374f205b25bf5b9f0

### Specific timeline issues / requests

This is a Major issue in the ELM people picker.  See - https://jazz.net/jazz/web/projects/Jazz%20Foundation#action=com.ibm.team.workitem.viewWorkItem&id=528119

We need a fix for ELM 7.0.3 by Sprint 6/7 (April/May) time frame.

**Comment by davidicus** [comment]
Hi @d-akara. It looks like this problem has already been resolved in the Carbon library. I have opened an [issue](https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2059) to upgrade our Carbon version in order to pull in these changes. This issue has been added to our March sprint.

**Comment by davidicus** [comment]
This issue should be closed with the above Carbon upgrades. Closing but feel free to re open if issue persist for you.
