### ISSUE TITLE
[ValueCard] Layout for value card has been broken

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#2060]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

ValueCard layout does not match the spec or the old implementation. Redo styles to align with the modern spec

### To Reproduce

1. Go to https://next.carbon-addons-iot-react.com/?path=/story/watson-iot-valuecard--small-thresholds-number-icon
2. See value card icon is not in the proper place

New [dashboard guidance](https://pages.github.ibm.com/ai-applications/design/patterns/dashboards-v2/overview/#value-cards) has the right layout specs

**Comment by JordanWSmith15** [comment]
Current position with no subtitle:
![Screen Shot 2021-02-23 at 10 46 41 AM](https://user-images.githubusercontent.com/21066152/108868795-8deb9b00-75c4-11eb-89f0-bb8c7aedccd1.png)
Desired:
![1](https://user-images.githubusercontent.com/21066152/108869016-cf7c4600-75c4-11eb-9f04-fc60a4b80574.jpg)
