### ISSUE TITLE
[AppShell] Boolean to hide side-nav while still showing the hamburger

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-addons-iot-react#2062]
### What package is this for?

- [X ] React

### Summary

Please describe your request in one or two sentences.
Boolean property on the application shell to hide the side-navigation while still showing the hamburger (three line) icon and passing a state from it

### Specific timeline issues / requests

We are in the process of implementing the MAS header in Manage for 8.4 via an iFrame. However, we are creating our own side-navigation control to match the PAL, and need to render it instead. 

What we need is, a boolean to hide the PAL side-menu, but not the hamburger (three line) icon. When true, the side-nav is not shown, but the hamburger is visible and has it's state exposed so that we can use it. We need notification of that state so that we can when the user toggles the button, we can open and close our own custom menu into a pinned position.  

![Screen Shot 2021-02-24 at 8 33 04 AM](https://user-images.githubusercontent.com/21066152/109008351-3ceaae00-767b-11eb-90f1-1f94c0b14904.png)

**Comment by bryancboyd** [comment]
@blechner I just prototyped this in `2062-hamburger-only`.  Could you take over?
