### ISSUE TITLE
[CodeEditor] Add carbon colors to the theme

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#2063]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

There has been request to provide a IBM colors theme to the code editor. 

```
function App() {
  function handleEditorWillMount(monaco) {
    monaco.editor.defineTheme("my-cool-theme", {
      base: "vs-dark",
      inherit: true,
      rules: [],
      colors: { "editor.background": "#293738" ,  'editorLineNumber.foreground': '#ff0000',}
    });
  }

  return (
    <Editor
      theme="my-cool-theme"
      height="90vh"
      defaultLanguage="javascript"
      defaultValue="// some comment"
      beforeMount={handleEditorWillMount}
    />
  );
}
```

Additional Resources:
- [default themes](https://github.com/Microsoft/vscode/blob/913e891c34f8b4fe2c0767ec9f8bfd3b9dbe30d9/src/vs/editor/standalone/common/themes.ts#L13) for inspiration on token names
- [Codesandbox](https://codesandbox.io/s/monaco-theme-oijvt?file=/src/App.js:72-502) implementing theme
- [Theme sandbox](https://microsoft.github.io/monaco-editor/playground.html#customizing-the-appearence-tokens-and-colors)
- [Color options](https://microsoft.github.io/monaco-editor/playground.html#customizing-the-appearence-exposed-colors)

**Comment by ben-bacon** [comment]
Slack convo: https://ibm-ai-apps.slack.com/archives/C0M053VPT/p1614158951047500

**Comment by JordanWSmith15** [comment]
Stale
