### ISSUE TITLE
[Table - Column sums] No ability to align sums with column

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-addons-iot-react#2067]
### What package is this for?

- [X] React
- [ ] Angular

### Describe the bug

Columns support a right-align feature for the text, which is especially helpful for numeric fields. The new "totals" section (https://next.carbon-addons-iot-react.com/?path=/story/watson-iot-table--simple-stateful-example-with-column-overflow-menu) needs a similar property to align the text with the column. 

### To Reproduce

TBD

![alignment-issue](https://user-images.githubusercontent.com/21066152/109178143-8d830980-7756-11eb-9ffe-4863322cf18a.png)

### Specific timeline issues / requests
MAS 8.4 April

**Comment by JordanWSmith15** [comment]
@kevinsperrine Can we also make an update to match the PAL design for the column alignments? It seems if we don't do this now, we'll have a new defect with sums alignment later anyway.
<img width="486" alt="Screen Shot 2021-02-16 at 4 22 59 PM" src="https://user-images.githubusercontent.com/21066152/109341840-f80c7600-7838-11eb-9850-722cb083a5b1.png">

**Comment by RogerRosado** [comment]
The issue still exist for "end" and "center" alignment  on columns that are sortable. There may be others column headers that me also cause similar issues with alignment:

![image](https://user-images.githubusercontent.com/56408920/112352230-fb144e00-8ca0-11eb-8d8f-317a7bcda351.png)

**Comment by kevinsperrine** [comment]
@RogerRosado You have to pass the alignment to the aggregations prop separately. It isn't read from the columns array, because that prop isn't passed down that far.

```
    view={{
      filters: [],
      aggregations: {
        label: 'Total',
        columns: [
          {
            id: 'number',
            align: 'end',
            isSortable: true,
          },
          {
            id: 'date',
            align: 'center',
            isSortable: true,
            value: '1000',
          },
          {
            id: 'select',
            align: 'start',
            value: '10000',
          },
        ],
      },
```

<img width="1358" alt="Screen Shot 2021-03-24 at 1 11 31 PM" src="https://user-images.githubusercontent.com/609466/112353807-7e826f00-8ca2-11eb-968b-3ba834e982bf.png">

**Comment by RogerRosado** [comment]
Yes .. I did that in the story book: here is some example of that:

with "start" on both column and total:

![image](https://user-images.githubusercontent.com/56408920/112357522-fe5e0880-8ca5-11eb-95dd-c50cd52d41ee.png)

 with "center" on both column and total:
 
![image](https://user-images.githubusercontent.com/56408920/112357689-264d6c00-8ca6-11eb-8ba6-2a5f4d4db74c.png)

and this one with both set to "end":

![image](https://user-images.githubusercontent.com/56408920/112357881-3ebd8680-8ca6-11eb-8599-7ff6fded2008.png)

**Comment by kevinsperrine** [comment]
@RogerRosado Are you also passing `isSortable: true` on columns that are sortable, or is another state on the column that is added the extra padding? That was added in this PR #2106

**Comment by RogerRosado** [comment]
HI @kevinsperrine the Table.jsx has this:
![image](https://user-images.githubusercontent.com/56408920/112360267-7fb69a80-8ca8-11eb-8fe6-c2a7cd0b4322.png)
 it does not have isSortable as part of the aggregations columns propType

**Comment by RogerRosado** [comment]
I added the "isSortable" property and it seems to be working correctly now... are there any other properties missing from the PropType that I should be aware of that is pertinent to column alignment?

**Comment by kevinsperrine** [comment]
Ah, good catch! I'll get that prop added ASAP. Nope, that's the only one.

**Comment by RogerRosado** [comment]
@kevinsperrine ... Thanks Bro...

**Comment by kevinsperrine** [comment]
You're welcome. Sorry for the confusion.
