### ISSUE TITLE
[Table] Support row decorator icons

### ISSUE THREAD

**Issue by gillibrand** [carbon-design-system/carbon-addons-iot-react#2075]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

I need to show decorator icons that pertain to the row, not a specific column. For example, users can lock a row from editing, which in the current implementation is shown as a lock icon in the leading, checkbox column. Another example is a location for a drag/gripper icon when rows can be dragged-n-dropped.

A possible work around is to add these icon to a custom column, but then that column shows in the column picker, takes up additional space, and (I think) requires a column label. Having a special column or just being able to add to the checkbox column is preferred. (My use cases always have a checkbox column, but ideally this support would work with any selection model.)

![image](https://user-images.githubusercontent.com/805573/109541557-caae0b00-7a78-11eb-8465-6a1f742f688d.png)

### Specific timeline issues / requests

ELM 7.0.3. Before June.

**Comment by katedraper** [comment]
@davidicus has indicated this is likely already possible to achieve. If there is a more specific use case, we can discuss further and reopen the issue.

**Comment by gillibrand** [comment]
@davidicus Can you point me to how to do this? Is there a way to add to the checkbox cell? Something else I missed? Thanks.
