### ISSUE TITLE
[Table] Menu for selecting visible columns

### ISSUE THREAD

**Issue by gillibrand** [carbon-design-system/carbon-addons-iot-react#2081]
### What package is this for?

- [X] React
- [ ] Angular

### Summary

The current column picker does not scale well with a large number of attributes. Design has a proposed alternative in the screenshot below. There's also a pic later of the current picker with an absurd number of columns, but even 10 is awkward.

What we' like:

- Column picker is a menu or drop down panel.
- The list of attributes includes all currently visible attributes, plus a specified list of "favorite" or common attributes. The menu should not have to show every available column.
- A search field can search all available column names. That is, the search can match an invisible or non-"favorite" column and show in the results. Once clicked it would be visible, so then in the menu even after the search is cleared.
- The order of the attributes in the menu should be defined by the caller. For large lists they would need to be alphabetical; shorter ones might prefer column order, but that can be left to the caller. 
- There needs to be a "Manage columns" link. This can just be a callback and leave the subsequent dialog to the caller.

Since the Table support adding custom components to the menu bar, it's possible I could implement this myself, but I don't know of a "menu" component I can tap into to drop down from the toolbar. Obviously having it in the Table itself is ideal though.

A ramification of this is that there would be no way to sort columns directly in the table, since the current chooser also handle ordering. The interaction is pretty confusing to though (it's not clear that that those "pills" can be dragged onto each other), and also doesn't scale that well. A better choice would be to just allow reordering the column directly by grabbing them instead of going into this separate mode.

![image](https://user-images.githubusercontent.com/805573/109557768-621d5900-7a8d-11eb-91e9-cf2b0dd52657.png)

![image](https://user-images.githubusercontent.com/805573/109557897-8ed17080-7a8d-11eb-9c4f-bcfe1ca28c5f.png)

### Specific timeline issues / requests

ELM 7.0.3. Around June.

**Comment by kevinsperrine** [comment]
We have this design guidance for column selection. It's a little different than your example, but seems to fit the requirements. Yes? https://pages.github.ibm.com/ai-applications/design/components/datatable/columncustomization#column-selection-and-reordering

**Comment by JordanWSmith15** [comment]
FYI, Graphite has worked around this issue by using the "Manage columns" link 
<img width="1604" alt="Screen Shot 2021-08-25 at 9 48 41 AM" src="https://user-images.githubusercontent.com/21066152/130803411-e12abbc3-cbcd-419a-992d-61c55eb3683b.png">
Example:
https://pages.github.ibm.com/maximo-app-framework/graphite/reference-app/?components%3AselectedTab=0&components%3AselectedSwitch=0&dataFormatting%3AselectedTab=0&tables%3AselectedTab=0#/tables

**Comment by JordanWSmith15** [comment]
This story is invalidated by the completion of the newer design pattern for column management:
https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table-table--with-column-customization-modal
