### ISSUE TITLE
[List builder]

### ISSUE THREAD

**Issue by stulscott** [carbon-design-system/carbon-addons-iot-react#2101]
### What package is this for?

- [X] React
- [ ] Angular

### Summary

IBM Maximo MRO Inventory Optimization will shortly require the List builder component as specified in the design https://pages.github.ibm.com/ai-applications/design/components/listbuilder/overview/

### Specific timeline issues / requests

We would like to be able to start using this component in April.

### You will consider this component complete when...

- [X] It's available as an export of this library
- [ ] Additional criteria you may have [e.g. Fully responsive, Accessible to
      WCAG 2.0, etc.]

### Available extra resources

It's possible that our team can help to implement this component,

# Update: 

Our select users modal seems to fit requirement based on [chat]([url](https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2101#issuecomment-796804927)) below. Updating this issue to export the component for use.

**Comment by katedraper** [comment]
@stulscott - can you please further elaborate the requirements here? 
Would something like the select user modal work: https://next.carbon-addons-iot-react.com/?path=/story/watson-iot-selectusersmodal--default-modal?

**Comment by stulscott** [comment]
Hi @katedraper, yes that looks just like the List builder. I'll check it out. It might be suitable. Thanks!

**Comment by davidicus** [comment]
We will need to export this component. I will convert this issue in order to do so
