### ISSUE TITLE
[FileDrop] Raise test coverage

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#2109]
We must raise the test coverage for this component and remove the exceptions found in [jest.config.js](https://github.com/carbon-design-system/carbon-addons-iot-react/blob/next/packages/react/jest.config.js) file.

- [ ] write test for FileDrop.jsx
- [ ] remove exception from jest.config.js
- [ ] update [epic](https://github.com/carbon-design-system/carbon-addons-iot-react/issues/707) to show this is complete

**Comment by kevinsperrine** [comment]
whoops. Didn't realize you opened an issue for this. Closing in favor of #2135
