### ISSUE TITLE
[PageTitle] Remove from test coverage

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#2111]
Since this component is deprecated we must remove  from test coverage and remove the exceptions found in [jest.config.js](https://github.com/carbon-design-system/carbon-addons-iot-react/blob/next/packages/react/jest.config.js) file.

- [ ] remove coverage for PageTitle.jsx
- [ ] remove exception from jest.config.js
- [ ] update [epic](https://github.com/carbon-design-system/carbon-addons-iot-react/issues/707) to show this is complete

**Comment by kevinsperrine** [comment]
closing favor of #2133
