### ISSUE TITLE
[BarChartCard] Bar Chart Card throws propTypes error in Edit Mode

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#2118]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

When the BarChartCard is in edit mode, it throws an error while it doesn't have a categoryDataSourceId or timeDataSourceId set.

![image](https://user-images.githubusercontent.com/6663002/110975211-aece2300-831c-11eb-8440-66edbfeba9f8.png)

### To Reproduce

Add a bar chart to the dashboardeditor and check the console.log

**Comment by davidicus** [comment]
There is no work around but since dashboard editor is in experimental I have given a SEV 2
