### ISSUE TITLE
[ProgressIndicator] ProgressIndicator presentation vertical has incorrect style in Safari

### ISSUE THREAD

**Issue by zhaozhuo813** [carbon-design-system/carbon-addons-iot-react#2129]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug
This issue only occur in Safari,  ProgressIndicator presentation vertical has incorrect style.

### To Reproduce

1. Go to story book, search `ProgressIndicator`,
2. choose presentation vertical
3.  the incorrect style looks like: 
![image](https://user-images.githubusercontent.com/65387028/111958815-a8178b00-8b28-11eb-9995-dffc17f30cf9.png)

### Expected behavior
The style should be consistent with what shown in other browsers.

### Environment/versions:

- Browser: [safari]
- `carbon-addons-iot-react` version: [e.g. `v2.144.0`]

Impact to product: 
Maximo Assist

**Comment by davidicus** [comment]
This issue is related to #1890

**Comment by kevinsperrine** [comment]
closing. fixed in both https://carbon-addons-iot-react.com/?path=/story/watson-iot-progressindicator--presentation-vertical and https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-progressindicator--presentation-vertical
