### ISSUE TITLE
[FileUploaderDropContainer]  FileUploaderDropContainer can not support drag and drop

### ISSUE THREAD

**Issue by zhaozhuo813** [carbon-design-system/carbon-addons-iot-react#2130]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

FileUploaderDropContainer can not support drag and drop

### Environment/versions:

- `carbon-addons-iot-react` version: [e.g. `v2.144.0`]

**Comment by davidicus** [comment]
Need to investigate why this is not an issue in Carbon storybook. [This](https://next.carbon-addons-iot-react.com/?path=/story/fileuploader--drag-and-drop-upload-container-example-application) story is throwing errors

**Comment by kevinsperrine** [comment]
@davidicus Is this the same issue as the FileUploader story I fixed yesterday in #2233?

**Comment by davidicus** [comment]
I dont think so since this is the one shipped from Carbon

**Comment by davidicus** [comment]
just checked and issue is no longer present. Closing.
