### ISSUE TITLE
[Page header] Design specs

### ISSUE THREAD

**Issue by Najil-K** [carbon-design-system/carbon-addons-iot-react#2143]
### What package is this for?

- [x] React
- [ ] Angular

[Page header - spec sheet.pdf](https://github.com/carbon-design-system/carbon-addons-iot-react/files/6227336/Page.header.-.spec.sheet.pdf)
![Page header](https://user-images.githubusercontent.com/81316430/112952978-b124df80-915a-11eb-8fcf-b9c76021fa18.jpg)

### Available extra resources

Component guidance reference:
https://pages.github.ibm.com/ai-applications/design/components/page-header/usage

**Comment by dianatran18** [comment]
Hey @Najil-K thanks for putting this together. 

Would you be able to do an audit against the existing [page header component](https://next.carbon-addons-iot-react.com/?path=/story/watson-iot-pagetitlebar--base) and see what adjustments need to be made?

Also, can we include the GIF of the collapsing header option. I'd like to include that as part of their sizing to see how much effort it would take to build. 

Thanks!

**Comment by Najil-K** [comment]
**Collapsing page header**

With tabs
![page-header-scrolling-transition-tabs](https://user-images.githubusercontent.com/81316430/112953773-5fc92000-915b-11eb-8f85-a4ba05e169c1.gif)


With buttons
![page-header-scrolling-transition-btns](https://user-images.githubusercontent.com/81316430/112953701-52ac3100-915b-11eb-849f-70867de70a38.gif)

**Comment by Najil-K** [comment]
Page header audit doc
[UI audit - Page header.pdf](https://github.com/carbon-design-system/carbon-addons-iot-react/files/6241276/UI.audit.-.Page.header.pdf)

![UI audit - Page header](https://user-images.githubusercontent.com/81316430/113249173-e4db4300-92db-11eb-9e51-0ff7605252a6.jpg)
