### ISSUE TITLE
[Card] Design specs

### ISSUE THREAD

**Issue by Najil-K** [carbon-design-system/carbon-addons-iot-react#2145]
### What package is this for?

- [x] React
- [ ] Angular

[Cards.pdf](https://github.com/carbon-design-system/carbon-addons-iot-react/files/6399079/Cards.pdf)
![Cards@2x](https://user-images.githubusercontent.com/81316430/116561325-d7879780-a91f-11eb-9c38-0b10228eb73e.jpg)

### Available extra resources

What resources do you have to assist this effort?
Component guidance reference:
https://pages.github.ibm.com/ai-applications/design/components/card/usage

**Comment by JordanWSmith15** [comment]
I assume these updates are targeted to be made against this story:
https://carbon-addons-iot-react.com/?path=/story/watson-iot-card--size-gallery

**Comment by davidicus** [comment]
@Najil-K @dianatran18 Can a card label and subtitle be present at the same time? There are no specs on the treatment of these strings when they are too large for the space. Do we want to provide ellipsis for both label and subtitle? Do we surface the overflown content in a browser tooltip or one of our tool tips like the Title?

**Comment by dianatran18** [comment]
> Can a card label and subtitle be present at the same time? 

No, only one or the other. We currently only have the subtitle in our [card PAL guidance](https://pages.github.ibm.com/ai-applications/design/components/card/usage#anatomy) so we can prioritize that one to prevent confusion. (@Najil-K did the label option come from C&CS?)


> There are no specs on the treatment of these strings when they are too large for the space. Do we want to provide ellipsis for both label and subtitle? Do we surface the overflown content in a browser tooltip or one of our tool tips like the Title?

We're actually working on truncation guidance right now, but it's still a WIP. 

Currently, this is what we have in there:

| UI element  | When to truncate  | When to wrap | How to handle overflow content |
|----------------|------------------------|-------------------|-----------------------------------------|
| Card title | Truncate at the end when the title exceeds one line in the container for only a title, or exceeds two lines in the container for a title and subtitle. | Can be wrapped to no more than two lines. | Display the complete title (and subtitle, if applicable) in a browser tooltip.  |

Do card titles wrap or truncate today @davidicus ?

**Comment by JordanWSmith15** [comment]
Relates to and may fix https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2370

**Comment by davidicus** [comment]
>Do card titles wrap or truncate today @davidicus ?

@dianatran18 we currently have ellipsis for Title when it's too long with a tooltip that has the complete title. Tooltip is only applied when needed.

**Comment by JordanWSmith15** [comment]
@dianatran18 @davidicus Keep in mind there is an item specifically for title = wrap: https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2375

**Comment by dianatran18** [comment]
Seeing all of the requirements... I could see it being that card headers can have _up to_ two lines of text, whether it's just the card title, or a card title + subtitle. 

Variations:
- one line for the card title
- up to two lines for the card title (and then ellipsis)
- one line for the card title (and then ellipsis) + one line for the subtitle (and then ellipsis)

but you can never have two lines of a title _and_ an additional subtitle. 

Is that too complicated?

**Comment by JordanWSmith15** [comment]
> Seeing all of the requirements... I could see it being that card headers can have _up to_ two lines of text, whether it's just the card title, or a card title + subtitle.
> 
> Variations:
> 
> * one line for the card title
> * up to two lines for the card title (and then ellipsis)
> * one line for the card title (and then ellipsis) + one line for the subtitle (and then ellipsis)
> 
> but you can never have two lines of a title _and_ an additional subtitle.
> 
> Is that too complicated?

@dianatran18 It is mildly complicated but I agree with it

**Comment by davidicus** [comment]
In this case do we need a prop? I can simply have title wrap and truncate on two lines unless subtitle is present than both have one line ellipsis. Or do we want the fine grain control to specify wrap or truncate one line?

**Comment by davidicus** [comment]
Other design considerations that we should answer with this spec alignment is cards that currently go to full edge of cards (ie. mapcard, tablecard). Do these now have the padding as the spec is suggesting or do these cases have overrides to make them go full bleed?

![image](https://user-images.githubusercontent.com/1590966/126826053-a99c9b67-946a-407e-9ff8-b8466aa75eea.png)


![image](https://user-images.githubusercontent.com/1590966/126826090-a7e72674-77bd-4ec8-9a83-dc36311f7431.png)

**Comment by dianatran18** [comment]
> In this case do we need a prop? I can simply have title wrap and truncate on two lines unless subtitle is present than both have one line ellipsis. Or do we want the fine grain control to specify wrap or truncate one line?

Was there an ask for the title to truncate at one line before, which is why it's built that way? I would be fine with what you proposed above as long as that's not breaking what people currently have today. For example if there is a small card and the title wrapping pushes content inside the card down (instead of truncating at one line, which is what it does now), I wouldn't want that to mess up team's existing layouts. Card titles shouldn't be that long anyways, but we can't really control that.

**Comment by dianatran18** [comment]
Technically based on the work that Pam did, maps are the one exception of the full bleed with no padding. But the content on top of the map itself (legend container, zoom controls, etc) sit 16px from the edge of the card, which aligns with the padding of a card. The ask for a full-bleed option on the map is because users might want to get as much real estate for the map as possible. 

You can see the exception written on the [dashboard pattern](https://pages.github.ibm.com/ai-applications/design/patterns/dashboards-v2/overview#interactive-maps) when this was worked on last year.

<img width="649" alt="Screen Shot 2021-07-23 at 3 55 42 PM" src="https://user-images.githubusercontent.com/43549567/126834636-ba0bec4d-520e-4479-a12d-5e9501e2e5b2.png">

**Comment by dianatran18** [comment]
Sorry I missed the data table but thanks for reminding me. Based on what Carbon suggests, the table should also be full bleed, but the content inside the table starts at 16px from the sides. So what you have for both maps and data tables for cards is right. 

This is a visual thing, but if you look at the red rule on this example of the dashboard, all of the content visually lines up with each other
<img width="722" alt="Screen Shot 2021-07-23 at 4 01 19 PM" src="https://user-images.githubusercontent.com/43549567/126835235-876413bf-4d5a-4abe-8c16-7d1205805fea.png">

**Comment by JordanWSmith15** [comment]
> In this case do we need a prop? I can simply have title wrap and truncate on two lines unless subtitle is present than both have one line ellipsis. Or do we want the fine grain control to specify wrap or truncate one line?

I think we do need fine-grain control, adding a prop to wrap or not to wrap the title. When there is a subtitle though, it should always wrap... there is no other option.

**Comment by Najil-K** [comment]
> > Can a card label and subtitle be present at the same time?
> 
> No, only one or the other. We currently only have the subtitle in our [card PAL guidance](https://pages.github.ibm.com/ai-applications/design/components/card/usage#anatomy) so we can prioritize that one to prevent confusion. (@Najil-K did the label option come from C&CS?)
> 
> > There are no specs on the treatment of these strings when they are too large for the space. Do we want to provide ellipsis for both label and subtitle? Do we surface the overflown content in a browser tooltip or one of our tool tips like the Title?
> 
> We're actually working on truncation guidance right now, but it's still a WIP.
> 
> Currently, this is what we have in there:
> 
> UI element 	When to truncate 	When to wrap	How to handle overflow content
> Card title	Truncate at the end when the title exceeds one line in the container for only a title, or exceeds two lines in the container for a title and subtitle.	 Can be wrapped to no more than two lines.	Display the complete title (and subtitle, if applicable) in a browser tooltip. 
> Do card titles wrap or truncate today @davidicus ?

@dianatran18 Sorry for the late reply! 
Yes, I took it from the C&CS thinking this could be a useful variation.
