### ISSUE TITLE
[Table] Pagination display incorrect when set number per page is 50 and total count is 201

### ISSUE THREAD

**Issue by zhaozhuo813** [carbon-design-system/carbon-addons-iot-react#2156]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

When using <Table> component,  If set item per page to 50, and if the total count is 201, then the pagination is incorrect.
![image](https://user-images.githubusercontent.com/65387028/112584693-452d3900-8e33-11eb-99a5-34f68a4ac82c.png)

### Environment/versions:
- `carbon-addons-iot-react` version: [e.g. `v2.144.0`]

**Comment by JordanWSmith15** [comment]
Unable to reprosuce

**Comment by zhaozhuo813** [comment]
Hi Jordan, we still have the same problem after upgrade Carbon, now our version is 2.146.0-next.90.

**Comment by JordanWSmith15** [comment]
@zhaozhuo813 Please provide detailed environment information and steps. I cannot reproduce in [IoT storybook](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table-statefultable--stateful-example-with-row-nesting-and-fixed-columns) or [Graphite refapp](https://pages.github.ibm.com/maximo-app-framework/graphite/main/reference-app/?tables%3AselectedTab=0#/tables)

**Comment by JordanWSmith15** [comment]
https://masws.assist.ivt08rel86.ivt.suite.maximo.com
user name / password: assist/Pa66w0rdPa66w0rd
on the home page, you can click manage document choose zztest_wo and click.
It has 201 docs in the list, you set the item per page to 50 and you can reproduce

**Comment by zhaozhuo813** [comment]
Yes, Make sure there are **201** items in the list.
Please don't make any change in the environment, it's our ivt testing environment. Thanks!
