### ISSUE TITLE
[ValueCard] Tooltip placement off

### ISSUE THREAD

**Issue by EdmondCShaffer** [carbon-design-system/carbon-addons-iot-react#2192]
**Describe the bug**
When Value card is on edge of screen and has no value/error user cannot read full error message when you click the indicator. Additionally at smaller sizes the tooltip is off target from trigger. The rendering offscreen seems to happen when card is on the right side of the dashboard and the tooltip renders off to the right. 

![image](https://user-images.githubusercontent.com/1590966/114559163-6f576700-9c39-11eb-85cd-8809a84c134c.png)
 

**To Reproduce**
- Go to dashboard [story](https://next.carbon-addons-iot-react.com/?path=/story/watson-iot-%F0%9F%9A%AB-dashboard--only-value-cards) with value cards
- shorten the window and click on the error icon
- see tooltip off center and offscreen.

**Expected behavior**
User should be able to see full error message.

**Comment by davidicus** [comment]
Also see the tooltip being rendered off target when container is shrunk down.
