### ISSUE TITLE
Labels not appearing on dashboard-value-tile widgets

### ISSUE THREAD

**Issue by EKong-IBM** [carbon-design-system/carbon-addons-iot-react#2200]
### Describe the bug

Labels not appearing on dashboard-value-tile widgets

### To Reproduce

1. Go to Asset AH001
2. See MRR has label in widget
3. See RUL and Next PM do not have labels

<img width="815" alt="Screen Shot 2021-03-31 at 3 33 45 PM" src="https://user-images.githubusercontent.com/82060296/113774467-54df3400-96f5-11eb-8a7b-02be849ed81a.png">

### Expected behavior

All widgets with the label property have labels appearing in the widget.

### System Information

http://health-team11.rtp.raleigh.ibm.com:9080/maximo_123/oslc/graphite/relengineer
Tested in QA Team1 - ORA

### Additional Information

Health Story: https://github.ibm.com/maximo/Asset-Health-Insight/issues/5612
Jira Story: https://jsw.ibm.com/browse/GRAPHITE-33656

**Comment by kevinsperrine** [comment]
@EKong-IBM Can you confirm this is still an issue? I can't connect to the health-team link above.

**Comment by EKong-IBM** [comment]
@kevinsperrine This is no longer an issue.
