### ISSUE TITLE
Date time range selection implementation for Angular

### ISSUE THREAD

**Issue by ninja511** [carbon-design-system/carbon-addons-iot-react#2212]
From #1952

Implementation of the Date time range selection component for Angular

**Comment by Najil-K** [comment]
@cal-smith  Can we start the design review on this component ?

**Comment by cal-smith** [comment]
@Najil-K sure! The one area I know we really diverge is in the absolute picker:

![image](https://user-images.githubusercontent.com/1744185/121547122-d98e4d00-c9d9-11eb-9e0a-8d3fcc17233c.png)

For UX reasons I think we'll end up shipping that kind of interaction.

**Comment by Najil-K** [comment]
@cal-smith Could you drop the latest dev instance link here?

**Comment by cal-smith** [comment]
They're in the comments from the netlify bot in the PR (#2365) 👍 but, this is the angular one for that PR (it'll update when the PR updates): https://deploy-preview-2365--ai-apps-pal-angular.netlify.app
