### ISSUE TITLE
[TableBatchActions] propTypes error for data-testID

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#2244]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

PropType error from Table

    console.error
      Warning: React does not recognize the `data-testID` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `data-testid` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
          in div (created by TableBatchActions)
          in TableBatchActions (created by TableToolbar)
          in section (created by TableToolbar)

### To Reproduce

Use a table with batch actions
> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/IBM/carbon-addons-iot-react/tree/master/examples/codesandbox

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by kevinsperrine** [comment]
This was fixed by https://github.com/carbon-design-system/carbon-addons-iot-react/pull/2288
