### ISSUE TITLE
[SideNav] propTypes error using CarbonSideNav translateById

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#2257]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

The latest carbon-components-react and carbon-components version doesn't like one of the props that we're passing to the CarbonSideNav (it's passing it through to the underlying DOM widget)

![image](https://user-images.githubusercontent.com/6663002/115765587-33708000-a364-11eb-8884-b5723477fe80.png)

**Comment by kevinsperrine** [comment]
This was fixed by https://github.com/carbon-design-system/carbon-addons-iot-react/pull/2354
