### ISSUE TITLE
Improve table column grouping

### ISSUE THREAD

**Issue by zvonimirfras** [carbon-design-system/carbon-addons-iot-react#2258]
https://pages.github.ibm.com/ai-applications/design/components/datatable/groupedcolumns/

We can reuse the code for sterling table and keep the separators between columns, but we need to update the vertical text alignment (should be bottom).

**Comment by katedraper** [comment]
@zvonimirfras - is this an angular request?

**Comment by zvonimirfras** [comment]
@katedraper it is, thanks. Forgot to mark it 🙂
