### ISSUE TITLE
Tree shaking is broken due to wrong "browser" value in package.json 

### ISSUE THREAD

**Issue by ilovepumpkin** [carbon-design-system/carbon-addons-iot-react#2260]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

https://github.com/carbon-design-system/carbon-addons-iot-react/blob/next/packages/react/package.json

Currently the "browser" property is pointing to a CommonJS module folder, which breaks tree shaking in webpack. The correct value should be  "es/src/index.js". 

```
  "browser": "lib/src/index.js",
  "main": "lib/src/index.js",
  "module": "es/src/index.js",
```

### To Reproduce

This is carbon-addons-iot-react size built from graphite, which is 623KB (after gzip) - all the components not being used in my application are bundled in it. 
![image](https://user-images.githubusercontent.com/11310645/115851444-8b3ce300-a459-11eb-83be-eb645411cd02.png)

I manually updated "browser" value to "es/packages/react/src/index.js" in the package.json of carbon-addons-iot-react in my node_modules, then re-run graphite build. Now carbon-addons-iot-react is only 40KB. 
![image](https://user-images.githubusercontent.com/11310645/115850316-54b29880-a458-11eb-8770-10f6576ffb26.png)

Here is the webpack tree shaking documentation https://webpack.js.org/guides/tree-shaking. Refer to the first two bullets. 

![image](https://user-images.githubusercontent.com/11310645/115851853-01414a00-a45a-11eb-89c3-b699015f3c89.png)

### Specific timeline issues / requests

If possible, please fix this ASAP. Since our application is a mobile application, this issue significantly impact the performance.

**Comment by JordanWSmith15** [comment]
Anything that would help performance in Maximo Mobile would be good to look at
