### ISSUE TITLE
[Table] incorrect spacing of table row actions

### ISSUE THREAD

**Issue by bjornalm** [carbon-design-system/carbon-addons-iot-react#2292]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

Padding missing 

### To Reproduce

1. Go to https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table-table--with-row-expansion-and-actions
2. Hover on row 2 and 4
3. See the missing spacing

### Expected behavior

Proper spacing used

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser:  chrome

### Additional context

![image](https://user-images.githubusercontent.com/5167091/117137493-18612f80-adaa-11eb-81f9-869e6fadc862.png)

![image](https://user-images.githubusercontent.com/5167091/117137518-20b96a80-adaa-11eb-94dc-a57c3471c16c.png)

**Comment by JordanWSmith15** [comment]
The issue is still reproducible here
https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table-table--with-row-expansion-and-actions
