### ISSUE TITLE
MAS Header-None of the options are open in help, profile and app switcher using the keyboard

### ISSUE THREAD

**Issue by bakkireddi** [carbon-design-system/carbon-addons-iot-react#2303]
As part of accessibility testing when trying to open the help (system information, what’s new..), profile (Profile option 1, logout) and App Switcher options in Mas Header using the keyboard, none of them are open.
![image](https://user-images.githubusercontent.com/37322952/117448606-92d1b100-af5c-11eb-949e-dfd92345b800.png)

**Comment by JordanWSmith15** [comment]
Upping the severity on this, since it is on every page in MAS
