### ISSUE TITLE
[ComboBox] Negating CSS variables in `calc()` breaks OptimizeCSSAssetsPlugin

### ISSUE THREAD

**Issue by TheSharpieOne** [carbon-design-system/carbon-addons-iot-react#2314]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

negating a `var` within `calc` breaks OptimizeCSSAssetsPlugin (which is used by CRA in production builds) with
```
Failed to compile.

Parse error on line 1: 
-var(--cds-...
-^
Expecting "ADD", "SUB", "LENGTH", "ANGLE", "TIME", "FREQ", "RES", "UNKNOWN_DIMENSION", "EMS", "EXS", "CHS", "REMS", "VHS", "VWS", "VMINS", "VMAXS", "PERCENTAGE", "NUMBER", "dimension", got unexpected "FUNCTION"
CompileError: Begins at CSS selector undefined
```
Tracking down the error (which was not easy) finds the following line:
https://github.com/carbon-design-system/carbon-addons-iot-react/blob/c0328c3869cd9b2ecafbc13b3c04f63114e8a8db/packages/react/src/components/ComboBox/_combo-box.scss#L32
This is just the first of many in this particular file (and probably the entire project).
This particular line end up being interpolated into `bottom: calc(-var(--cds-spacing-08, 2.5rem))` since `$ai-apps-combobox-input-height` is `$spacing-08` and `$spacing-08` is `var(--cds-spacing-08, 2.5rem)`.

The best way to handle negating the value is to multiple by -1: https://github.com/css-modules/postcss-icss-values/issues/64#issuecomment-241285628

### To Reproduce

1. create a new app with CRA
2. add ComboBox styles
3. run the production build

_cannot be recreated using codesandbox since it happens during production build_

### Expected behavior

No error is given and the production build produces the correct code.

### Environment/versions:

- OS: MacOS
- Browser: N/A
- `carbon-addons-iot-react` version: 2.144.0

### Additional context

Current workaround, use CRACO remove / disable OptimizeCSSAssetsPlugin (which is not that great...)

### Specific timeline issues / requests

N/A

**Comment by JordanWSmith15** [comment]
@TheSharpieOne Friendly reminder... can you answer Kevin's question?

**Comment by TheSharpieOne** [comment]
Sorry, I was out for a bit.
It seems that this is triggered by importing `~@console/pal/scss/theme` first. We are using PAL, and the PAL theme seems to set some stuff up that causes this issue. 

I am not sure if we are supposed to be using the PAL theme with this package or not. PAL is setting `$spacing-08` which is being used by this package in the place that is breaking.

importing just `~@console/pal/scss/theme` works fine. importing just `~carbon-addons-iot-react/scss/<stuff>` works fine. Importing both (with pal first since it is setting vars used by `carbon-addons-iot-react/scss`) causes carbon-addons-iot-react/scss to break.

scss:
```scss
@import '~@console/pal/scss/theme';
@import '~carbon-addons-iot-react/scss/globals/vars';
@import "~carbon-addons-iot-react/scss/components/ComboBox/combo-box";
```

**Comment by kevinsperrine** [comment]
@TheSharpieOne Thank you! Where do you get the `@console/pal` package? I'm unfamiliar with it, but I do see references to it in other carbon issues.

**Comment by TheSharpieOne** [comment]
It's available via IBM's artifactory.
More information:
https://github.ibm.com/console-pipeline/docs/tree/master/migrating-to-artifactory#instructions
https://github.ibm.com/ibmcloud/pal#how-to-install-and-use
