### ISSUE TITLE
[SimpleList] Cannot change Icon component without throwing away and regenning the list

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#2316]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

Because the simple list keeps the items property in local state it doesn't update if the items list changes.  Specifically I change the icon based on an interaction with the list, but the list never updates.  I am forced to change the key of the list so React throws it away

### To Reproduce

Pass the simple list a set of items with icons.  Now change the icons based on some interaction with the page (maybe a button at the top).  The icons will never change in the simple list

**Comment by bjornalm** [comment]
@scottdickerson Just to clarify. The desired behaviour is that the list is updated if you modify the items prop? We need to take care that we don't run in to problems with the filter and pagination state.
