### ISSUE TITLE
Changing the default theme?

### ISSUE THREAD

**Issue by chad-ithreat** [carbon-design-system/carbon-addons-iot-react#2318]
### What package is this for?

- [X] React
- [ ] Angular
- [ ] Both

### Summary

Hi all! First, thanks for an awesome set of components. They cover just about everything imaginable and make creating an app so much easier. 

TL;DR: how do we use a theme other than G10? The guides at carbondesignsystem.com do not seem to work and we haven't found a good pointer online for using SCSS. We've tried a bunch of different approaches with no success.

----

I'm trying to switch a project from carbon-components-react to carbon-addons-iot-react and noted that the default theme is G10 inside styles.scss.
```/// Set the theme to Gray 10
@import '~@carbon/themes/scss/themes';
$carbon--theme: $carbon--theme--g10;
// Use the gray 10 theme
@include carbon--theme();
```
Reviewing [https://www.carbondesignsystem.com/guidelines/themes/code](https://www.carbondesignsystem.com/guidelines/themes/code), I haven't been able to figure out a way to override the G10 theme back to white. If I bring in theme above the styles.scss import in our project's index.scss, it gets ignored. If I try to inline it like their examples, it doesn't make a difference. My short term workaround was to copy the contents of styles.scss into my index.scss, but that doesn't work well in the long run. I also rebuilt node-sass at a few points to see if it'd make a difference, but didn't succeed.

Thanks!

**Comment by JordanWSmith15** [comment]
I would ask why you need this... what designer is not using the Grey10 theme in our business unit?

**Comment by JordanWSmith15** [comment]
@chad-ithreat   Can you give me some examples of what design you are attempting to achieve?  If you are just trying to render a "white" style component (perhaps because the background of your page is white, and many Grey10 components lacks contrast with white backgrounds), you can try to use the "light" and "dark" properties, which will change the background contrast colors. However, we do not want to support the darker themes (Grey 100 or Grey 90) in the PAL repo at this time.

**Comment by JordanWSmith15** [comment]
@chad-ithreat Closing this as invalid, for now, as we only support Gray10 theme in this repo (and in the design of our products) in order to maintain visual consistency. If you still require assistance on this, please reach out to me.
