### ISSUE TITLE
[ContextMenu] Export new carbon component

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#2332]
We need to export the new component that we consume from Carbon. We currently use in our MenuButton but the underlining component should be exported as well and added to the storybook.

**Comment by kevinsperrine** [comment]
@davidicus Do we want to go ahead and do this now? Looks like that PR was merged on the carbon side, so we'll be immediately changing it again when we upgrade. https://github.com/carbon-design-system/carbon/pull/8169

**Comment by davidicus** [comment]
@kevinsperrine Let's hold off on exporting this. We should open up a  new issue to consume the latest Carbon package that contains the updated component.

**Comment by davidicus** [comment]
Closing this issue as Carbon has refactored their initial experimental implementation. We will update to the new usage when we next update Carbon.
