### ISSUE TITLE
MasHeader- Help and Profile menu options in mas header are getting cut off in RTL mode

### ISSUE THREAD

**Issue by bakkireddi** [carbon-design-system/carbon-addons-iot-react#2360]
Help and Profile menu options in mas header are getting cut off in RTL mode.
<img width="418" alt="image" src="https://user-images.githubusercontent.com/37322952/119847541-aef7bb00-bf28-11eb-9272-aa023c869ef8.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/37322952/119847641-c6cf3f00-bf28-11eb-933d-bc9f732eb452.png">

**Comment by JordanWSmith15** [comment]
As part of this, we should really check the entire header for BiDi compliance.
