### ISSUE TITLE
[Card] Getting intermittent error when unmounting cards from dashboards

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#2364]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

It's hard to say why this is occurring, but in our logs occasionally while unmounting a dashboard we see this:
![image](https://user-images.githubusercontent.com/6663002/120382837-5f770d80-c2e1-11eb-977b-dcd3e065a118.png)

It seems like something to do with the Size measurement of the card

### To Reproduce

It's pretty hard to reproduce, hopefully this is an error in an underlying library that we could search for.

**Comment by JordanWSmith15** [comment]
@scottdickerson  Have you encountered this again recently? Have any other steps to reproduce?

**Comment by JordanWSmith15** [comment]
@scottdickerson Have you tried this with the latest PAL? David has done some card updates

**Comment by kevinsperrine** [comment]
maybe related: https://githubmemory.com/repo/ctrlplusb/react-sizeme/issues/145
