### ISSUE TITLE
[SuiteHeader] Add tooltips to text with overflow ellipsis

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#2368]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

Add tooltips to text with overflow ellipsis on the suite header. We can either use browser supplied ones from title or incorporate carbon tooltips like we do elsewhere.

**Comment by kevinsperrine** [comment]
@davidicus or @JordanWSmith15 Is the above fix in #2662 sufficient, or do you want me to change it to using an actual tooltip component?

**Comment by JordanWSmith15** [comment]
I think we are good with how it behaves. Closing.
