### ISSUE TITLE
[DashboardEditor] Small Wide is too tall at small layouts

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#2370]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

The small card sizes at various layouts are incorrect

![image](https://user-images.githubusercontent.com/6663002/120535194-ee4a5f80-c39f-11eb-9e09-360ca00dc251.png)

At the medium layout, small wide is the same width as small full, which doesn't seem correct either:
![image](https://user-images.githubusercontent.com/6663002/120535262-028e5c80-c3a0-11eb-8fc2-56d6bda0c593.png)

### To Reproduce

To reproduce, set the Dashboard Editor at the smallest breakpoint.  Now add a card of size Small.  Now change the card to Small Wide, you'lll notice that it gets taller. This shouldn't happen that's what medium card sizes are for.

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/IBM/carbon-addons-iot-react/tree/master/examples/codesandbox

### Expected behavior

Better differentiation between card sizes at these layouts

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Additional context

![image](https://user-images.githubusercontent.com/6663002/120534968-aa575a80-c39f-11eb-80ef-a110a7e21bd1.png)

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by JordanWSmith15** [comment]
May get fixed as part of #2145
