### ISSUE TITLE
[Repo] Pull in Carbon beta release to test for v3

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#2372]
Carbon has released the beta for their next major release. We need to consume and start running provide code mods to test out the ease of use of the migration.  

[Migration guides](https://github.com/carbon-design-system/carbon/tree/main/docs/migration)
[Early Release Program](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/release-partners.md#may-13th-2021)

**Comment by davidicus** [comment]
First attempt to upgrade showed quite a few breaking changes for us without the feature flags. @kevinsperrine can you link to the gist document outlining the issues we encountered when we upgraded Carbon versions here for reference?

**Comment by davidicus** [comment]
Closing this issue as it was simply an exploration. We have other issues open to upgrade Carbon's release candidate.

**Comment by kevinsperrine** [comment]
> First attempt to upgrade showed quite a few breaking changes for us without the feature flags. @kevinsperrine can you link to the gist document outlining the issues we encountered when we upgraded Carbon versions here for reference?

These are the items I had to change in our tests to get them to pass again for each version. All tests related to the ComboBox are still broken because of this issue: https://github.com/carbon-design-system/carbon/issues/8744

https://gist.github.com/kevinsperrine/bfa733699fa723b56eb6173d7c6ac1f2
