### ISSUE TITLE
[repo] Align all uses of testID

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#2374]
The project has variations of whether  components use `testID` or `testId` for prop. We need to align all usages to use the same form. `testId` is the approved prop name moving forward. 

- [ ] all instances of `testID` are swapped to `testId`

**Comment by stuckless** [comment]
How does this relate to data-testid?  I see `data-testid`, `testId`, `testID`, and `test-id`, all being used.

**Comment by bjornalm** [comment]
`data-testid´ is the name of the HTML data attribute that at the end is added to the actual HTML element, whereas `testID` is the name of the react prop used to pass the value down. I did quick search and found one `test-id` in  the `ColorDropDown´ component but that was probably added by mistake and won't work.

**Comment by davidicus** [comment]
Closing in favor of #1001
