### ISSUE TITLE
[ValueCard] Support drill-in text

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-addons-iot-react#2376]
### What package is this for?

- [ ] React

### Summary

1. Support links as values in the card. This indicates to the user that they can "drill in" to each query.
![Screen Shot 2021-06-08 at 12 45 05 PM](https://user-images.githubusercontent.com/21066152/121225706-c8b5ce00-c857-11eb-9e2b-0c75215cb13f.png)

Current storybook:
https://carbon-addons-iot-react.com/?path=/story/watson-iot-valuecard--medium-wide-3
<img width="1117" alt="Screen Shot 2021-06-04 at 12 15 27 PM" src="https://user-images.githubusercontent.com/21066152/120832384-9a21b580-c52e-11eb-980e-b1960cb397f9.png">

**Comment by kevinsperrine** [comment]
@JordanWSmith15 Just to clarify: the links are to allow values on the card to link to another page or anchor within the same page, right? Ie. The card itself isn't changing with this "drill-in". 

Also, for swapping of label position, I'm envisioning a prop that would allow for this:

|Current|Proposed|
|-|-|
|Dollars<br/>89$|Dollars<br/>$89|

**Comment by JordanWSmith15** [comment]
@kevinsperrine  I think we just need the ability to tie a custom event to the value... could be pretty much anything, but most common will be to pop a dialog or link to another page like you said. 

I think you can ignore the swapping of label... it was discussed with design and we decided against it. The example was removed from the issue details... I will now remove it from the title as well.
