### ISSUE TITLE
Data table base API rewrite

### ISSUE THREAD

**Issue by ninja511** [carbon-design-system/carbon-addons-iot-react#2395]

**Comment by sstone2423** [comment]
Love the idea, but hopefully the React side can be involved so that we all stay consistent. I wouldn't recommend this if there are two different ways the table works depending on which framework you're using. The Table is extremely complex so maintaining two of them would be pretty unpleasant

**Comment by stuckless** [comment]
@sstone2423 Don't we already have 2 ways since there are 2 tables... an Angular one and a React one?  I would hope that this means we'd be moving to a common data framework that things like a Table, List, Dropdown, etc can consume vs the model we have today.

**Comment by cal-smith** [comment]
> Love the idea, but hopefully the React side can be involved so that we all stay consistent. I wouldn't recommend this if there are two different ways the table works depending on which framework you're using. The Table is extremely complex so maintaining two of them would be pretty unpleasant

For sure! We'll be sharing all the same underlying styles and structure, so we'll be fully aligned from that perspective. We'll share what we can where it makes sense, but I expect some of the specific interfaces to diverge - Our Angular model will make use of a bunch of Rxjs Observables, but the React model may not be ready to jump into that, for example. I'm sure we'll have some PRs up in a bit, and we can get into some details then.
