### ISSUE TITLE
[Table] Multi-sort feature enhancements 

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#2398]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

These are copied from comment thread from [this PR](https://github.com/carbon-design-system/carbon-addons-iot-react/pull/2336). There are many good suggestions to enhance the usability of this feature. The PAL design team will be taking a look at the existing spec and will take these features into consideration in their finalized spec. 

- [ ]  If existing sorts exist, and I click the triple dot on a column that is not already sorted then it should add a new row and set that selected column in the dropdown.
- [ ] Perhaps if I clicked a table column that is NOT sorted it might remove all other sorts, although I expect that customers would likely expect that action to just add another sorted column automatically.

**Comment by davidicus** [comment]
@dianatran18 FYI. These are some comments regarding enhancements to multi-sort that we should consider when design looks at this pattern.

**Comment by JordanWSmith15** [comment]
Relates to https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2399
