### ISSUE TITLE
[List] Items with 3 dot menu have scrollbars

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#2408]
### What package is this for?

- [X] React
- [ ] Angular

### Describe the bug

Scroll bars are appearing for items that have the 3 dot menu icon. Easier to see if you set your scroll bar to always be visible. 

### To Reproduce

1. Go to https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-list--with-hierarchy
2. Make sure your scroll bars are set to always on. Or just try to scroll inside content area. 

![image](https://user-images.githubusercontent.com/1590966/122061474-8abb2b80-cdbc-11eb-85cf-1efadf1578a6.png)

**Comment by JordanWSmith15** [comment]
Can't reproduce in chrome or firefox. Seems to have been fixed upstream
![Screen Shot 2021-07-28 at 11 52 07 AM](https://user-images.githubusercontent.com/21066152/127355163-2c77ea2a-e73b-4013-8739-a4d2c5e35352.png)
