### ISSUE TITLE
[Repo]: Update README.md files to {Component}.md

### ISSUE THREAD

**Issue by kevinsperrine** [carbon-design-system/carbon-addons-iot-react#2418]
This is to ensure consistency in the documentation going forward.

**Comment by bjornalm** [comment]
I noticed you used extension `mdx` in https://github.com/carbon-design-system/carbon-addons-iot-react/pull/2414/ Should we make that the standard?

**Comment by kevinsperrine** [comment]
> I noticed you used extension `mdx` in #2414 Should we make that the standard?

Yes, but it's only valid after #2414 is merged because `addon-docs` adds the necessary libraries to handle it.
