### ISSUE TITLE
[TableViewDropdown] Object object shows on mouseover

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#2423]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

In the TableViewDropdown component if you mouseOver one of the items, you'll see [Object object]. (Hard to capture in a screenshot as it's a title hover.  I believe this is because we're using itemToString instead of itemToElement here: 

```
   <MyDropDown
              label={i18n.tableViewMenu}
              data-testid={testID}
              selectedItem={mySelectedItem}
              ariaLabel={i18n.ariaLabel}
              disabled={disabled}
              id={`${iotPrefix}--view-dropdown`}
              // We are using itemToString instead of itemToElement since we need the custom
              // rendering to also happen when the item is selected. See closed PR
              // https://github.com/carbon-design-system/carbon/pull/5578
              itemToString={(itemData) => {
                return (
                  <MyTableViewDropDownItem
                    testID={`TableViewDropdownItem-${itemData.id}`}
                    isCompact={measuredSize?.width < 200}
                    item={itemData}
                    isSelected={itemData.id === mySelectedItem.id}
                    activeViewEdited={selectedViewEdited}
                    i18n={i18n}
                    {...overrides?.dropdownItem?.props}
                  />
                );
              }}
```

### To Reproduce

You can see the error here: 
https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table-tableviewdropdown--table-view-dropdown-edited
If you popout the menu and mouse over a bunch of the items.

**Comment by bjornalm** [comment]
You are correct, I think the "object-title" is added by carbon since it expects the output of the itemToString to be a string, but we were forced to render an element to achieve the design as specified. Not sure what the best solution is, carbon probably wont accommodate this design and help us skip the title, and rewriting a complete dropdown would be costly.

We are adding our own title the in the element rendered by the itemToString but there is a gap where the title from carbon is showing. Perhaps there is a way to improve that fix.

**Comment by kevinsperrine** [comment]
We can hack a fix with css by removing the padding/margin from the `bx--list-box__menu-item__option` class in this component, and adding them to the `iot--view-dropdown__item` class instead. This effectively makes the hoverable area containing the `[object Object]` title hidden.

**Comment by JordanWSmith15** [comment]
@scottdickerson I can no longer reproduce. See video:

https://user-images.githubusercontent.com/21066152/130807737-761bb7e6-fe39-4369-a7e9-10b0bc8143a7.mov

**Comment by scottdickerson** [comment]
this seems broken again, take a look at the story and the button is showing title=[Object object] again

**Comment by scottdickerson** [comment]
version 147-64

**Comment by kevinsperrine** [comment]
Yeah, Carbon updated this behavior in 10.43. I've got a PR open to fix this for good and stop overriding itemToString for rendering the selectedItem when a element is needed. https://github.com/carbon-design-system/carbon/pull/10188
