### ISSUE TITLE
[Repo] Upgrade Carbon to fix ref bug in ComboBox

### ISSUE THREAD

**Issue by kevinsperrine** [carbon-design-system/carbon-addons-iot-react#2435]
### What package is this for?

- [X] React
- [ ] Angular

### Describe the bug

Starting in Carbon 10.32/7.32 refs are no longer passed to the ComboBox, so this breaks all custom functionality for tags, etc, in the PAL library. The version needed is unknown, because the issue is still outstanding. 

https://github.com/carbon-design-system/carbon/issues/8744

**Comment by JordanWSmith15** [comment]
@kevinsperrine Is this ready to close? Seems like the proposed carbon upgrade pr has been merged

**Comment by kevinsperrine** [comment]
Yep. This one was fix and merged with the carbon upgrade back before I went on vacation.
