### ISSUE TITLE
[Card][A11Y] Info tooltips remain open when tabbing through

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-addons-iot-react#2437]
### What package is this for?
React

### Describe the bug

When using tab to navigate through cards, the info icon tooltip remains open. 
https://carbon-addons-iot-react.com/?path=/story/watson-iot-card--with-ellipsed-title-tooltip-external-tooltip
Result on a large dashboard can have impact for a11y users:
<img width="1200" alt="Screen Shot 2021-06-29 at 10 31 23 AM" src="https://user-images.githubusercontent.com/21066152/123816423-4d2ec600-d8c5-11eb-969c-82ef563a2b19.png">

Note that this does not happen with the tooltip component itself at https://carbon-addons-iot-react.com/?path=/story/watson-iot-tooltip--default-bottom

Graphite issue:
https://jsw.ibm.com/browse/GRAPHITE-35449
Health issue:
https://github.ibm.com/maximo/Asset-Health-Insight/issues/5787

**Comment by davidicus** [comment]
This is a tooltip bug as it is present in our tooltip stories outside of card

**Comment by kevinsperrine** [comment]
This has been fixed in https://github.com/carbon-design-system/carbon/pull/9545 just a matter of it getting released and us upgrading now.

**Comment by kevinsperrine** [comment]
This was released in https://github.com/carbon-design-system/carbon/releases/tag/v10.43.0. @davidicus or @JordanWSmith15 Do we want to do this upgrade in Sept?
