### ISSUE TITLE
[DateTimePicker] Once I have selected an absolute date it won't change

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#2466]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

 Once I have selected a custom date range, it’s hard to change. I can't figure out how to slide the initial start date and end Date again.

### To Reproduce

Go to this story:
https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-datetime-picker--selected-absolute
Try and change the absolute date to a different one by clicking on the calendar. It won't change until you change the time

Looks like a carbon bug:
https://github.com/carbon-design-system/carbon/issues/8865

**Comment by kevinsperrine** [comment]
closing as duplicate of #2592.
