### ISSUE TITLE
[Repo] Remove stories from coverage report and raise threshold to 90%

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#2469]
In an effort to stabilize our components and make them more resilient to change we are removing the storybook snapshot test from our overall coverage threshold on each file. We will still run snapshots to help highlight where we are changing the output of the component but testing thresholds will now be dependent on unit and browser testing that explicitly test the functionality of each component. 

This issue will be an overarching epic to track the process of doing this per component. 

In order to complete the task for each component they should:
- have the coverage threshold above 90% for all areas (statements, branches, functions, lines) when snapshots are turned off from coverage (found in the `jest.config.js`'s `collectCoverageFrom` prop). 

We may need to turn off coverage as we work each file but not commit that change to the config until all files are above the threshold.

**Comment by bjornalm** [comment]
**Status without snapshot coverage and threshold being 90%**

Indirect tests, i.e. from test files using components where the test target is a child at some level, does touch a lot of code which is good for the coverage, but it is tough to tell if the code they touch is really tested.

> Jest: "global" coverage threshold for statements (90%) not met: 86.83%
> Jest: "global" coverage threshold for branches (90%) not met: 80.56%
> Jest: "global" coverage threshold for lines (90%) not met: 86.97%
> Jest: "global" coverage threshold for functions (90%) not met: 84.93%

Helper and utility js files are note included in the list below:

- Breadcrumb.jsx" coverage threshold for branches (90%) not met: 87.5%
- Breadcrumb.jsx" coverage threshold for lines (90%) not met: 89.66%
- ComposedModal.jsx" coverage threshold for branches (90%) not met: 82.05%
- TableBody/RowActionsCell/RowActionsError.jsx" coverage threshold for branches (90%) not met: 62.5%
- TableBody/RowActionsCell/RowActionsCell.jsx" coverage threshold for branches (90%) not met: 81.82%
- TableBody/TableBodyRow/TableBodyRow.jsx" coverage threshold for statements (90%) not met: 84.06%
- TableBody/TableBodyRow/TableBodyRow.jsx" coverage threshold for branches (90%) not met: 76.86%
- TableBody/TableBodyRow/TableBodyRow.jsx" coverage threshold for lines (90%) not met: 83.33%
- TableSaveViewModal/TableSaveViewForm.jsx" coverage threshold for functions (90%) not met: 83.33%
- ListItem/ListTarget.jsx" coverage threshold for branches (90%) not met: 80%
- ListItem/ListItemWrapper.jsx" coverage threshold for branches (90%) not met: 88.46%
- ListItem/ListItem.jsx" coverage threshold for branches (90%) not met: 89.47%
- ListItem/ListItem.jsx" coverage threshold for functions (90%) not met: 86.67%
- List.jsx" coverage threshold for functions (90%) not met: 86.67%
- TableManageViewsModal/TableManageViewsModal.jsx" coverage threshold for branches (90%) not met: 80%
- TableSkeletonWithHeaders/TableSkeletonWithHeaders.jsx" coverage threshold for branches (90%) not met: 83.33%
- index.jsx" coverage threshold for branches (90%) not met: 87.5%
- FlyoutMenu.jsx" coverage threshold for branches (90%) not met: 83.33%
- TableToolbar/TableToolbarAdvancedFilterFlyout.jsx" coverage threshold for branches (90%) not met: 89.55%
- PageTitleBar.jsx" coverage threshold for statements (90%) not met: 82.22%
- PageTitleBar.jsx" coverage threshold for branches (90%) not met: 83.95%
- PageTitleBar.jsx" coverage threshold for lines (90%) not met: 81.82%
- TileCatalog.jsx" coverage threshold for functions (90%) not met: 66.67%
- StatefulTileCatalog.jsx" coverage threshold for branches (90%) not met: 83.33%
- CatalogContent.jsx" coverage threshold for branches (90%) not met: 50%
- ComposedStructuredList.jsx" coverage threshold for branches (90%) not met: 53.85%
- ResourceList.jsx" coverage threshold for branches (90%) not met: 83.33%
- HierarchyList/HierarchyList.jsx" coverage threshold for branches (90%) not met: 87.84%
- HierarchyList/HierarchyList.jsx" coverage threshold for functions (90%) not met: 82.86%
- CardRangePicker.jsx" coverage threshold for branches (90%) not met: 83.33%
- Card.jsx" coverage threshold for branches (90%) not met: 81.25%
- TimePickerSpinner.jsx" coverage threshold for branches (90%) not met: 80.77%
- DateTimePicker.jsx" coverage threshold for branches (90%) not met: 79.05%
- IconDropdown.jsx" coverage threshold for branches (90%) not met: 84.09%
- IconDropdown.jsx" coverage threshold for functions (90%) not met: 87.5%
- Hero.jsx" coverage threshold for statements (90%) not met: 66.67%
- Hero.jsx" coverage threshold for branches (90%) not met: 0%
- Hero.jsx" coverage threshold for lines (90%) not met: 66.67%
- Hero.jsx" coverage threshold for functions (90%) not met: 0%
- NavigationBar.jsx" coverage threshold for branches (90%) not met: 80%
- NavigationBar.jsx" coverage threshold for functions (90%) not met: 75%
- HeaderAction/HeaderAction.jsx" coverage threshold for branches (90%) not met: 86.67%
- SideNav.jsx" coverage threshold for branches (90%) not met: 87.5%
- SuiteHeaderAppSwitcher/SuiteHeaderAppSwitcher.jsx" coverage threshold for branches (90%) not met: 89.47%
- SuiteHeaderAppSwitcher/SuiteHeaderAppSwitcher.jsx" coverage threshold for functions (90%) not met: 85.71%
- SuiteHeader.jsx" coverage threshold for branches (90%) not met: 78.33%
- SuiteHeader.jsx" coverage threshold for functions (90%) not met: 84%
- DashboardHeader.jsx" coverage threshold for branches (90%) not met: 83.33%
- ValueRenderer.jsx" coverage threshold for statements (90%) not met: 85.71%
- ValueRenderer.jsx" coverage threshold for branches (90%) not met: 70%
- ValueRenderer.jsx" coverage threshold for lines (90%) not met: 85.71%
- Attribute.jsx" coverage threshold for statements (90%) not met: 58.82%
- Attribute.jsx" coverage threshold for branches (90%) not met: 34.38%
- Attribute.jsx" coverage threshold for lines (90%) not met: 58.82%
- Attribute.jsx" coverage threshold for functions (90%) not met: 50%
- ValueCard.jsx" coverage threshold for branches (90%) not met: 78.57%
- editorUtils.jsx" coverage threshold for branches (90%) not met: 84.15%
- HotspotContent.jsx" coverage threshold for functions (90%) not met: 88.89%
- ImageUploader.jsx" coverage threshold for functions (90%) not met: 80%
- tableCardUtils.jsx" coverage threshold for branches (90%) not met: 81.08%
- TableCard.jsx" coverage threshold for branches (90%) not met: 72.66%
- TableCard.jsx" coverage threshold for functions (90%) not met: 79.37%
- ListCard.jsx" coverage threshold for branches (90%) not met: 86.67%
- GaugeCard.jsx" coverage threshold for branches (90%) not met: 80.95%
- DashboardEditorHeader/DashboardEditorHeader.jsx" coverage threshold for branches (90%) not met: 88.89%
- DashboardEditorCardRenderer.jsx" coverage threshold for branches (90%) not met: 83.72%
- DashboardEditorCardRenderer.jsx" coverage threshold for functions (90%) not met: 88.46%
- CardCodeEditor.jsx" coverage threshold for functions (90%) not met: 88.89%
- CardEditForm/CommonCardEditFormFields.jsx" coverage threshold for statements (90%) not met: 86.21%
- CardEditForm/CommonCardEditFormFields.jsx" coverage threshold for lines (90%) not met: 85.71%
- CardEditForm/CardEditFormItems/ThresholdsFormItem.jsx" coverage threshold for branches (90%) not met: 83.33%
- CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx" coverage threshold for statements (90%) not met: 85.71%
- CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx" coverage threshold for branches (90%) not met: 82.65%
- CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx" coverage threshold for lines (90%) not met: 85.71%
- CardEditForm/CardEditFormItems/DataSeriesFormItemModal.jsx" coverage threshold for functions (90%) not met: 88.46%
- CardEditForm/CardEditFormItems/ContentFormItemTitle.jsx" coverage threshold for branches (90%) not met: 83.33%
- Dropdown.jsx" coverage threshold for branches (90%) not met: 87.5%
- HotspotTextStyleTab/HotspotTextStyleTab.jsx" coverage threshold for branches (90%) not met: 83.33%
- HotspotEditorDataSourceTab/HotspotEditorDataSourceTab.jsx" coverage threshold for branches (90%) not met: 87.5%
- HotspotEditorModal.jsx" coverage threshold for branches (90%) not met: 82.98%
- CardEditForm/CardEditFormItems/ImageCardFormItems/ImageCardFormContent.jsx" coverage threshold for branches (90%) not met: 83.33%
- CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormContent.jsx" coverage threshold for branches (90%) not met: 86.67%
- CardEditForm/CardEditFormContent.jsx" coverage threshold for branches (90%) not met: 88.46%
- CardEditForm/CardEditFormContent.jsx" coverage threshold for functions (90%) not met: 80%
- CardEditForm/CardEditFormItems/DataSeriesFormItems/DataSeriesFormSettings.jsx" coverage threshold for functions (90%) not met: 85.71%
- CardEditForm/CardEditFormItems/BarChartCardFormItems/BarChartCardFormSettings.jsx" coverage threshold for functions (90%) not met: 80%
- CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormSettings.jsx" coverage threshold for branches (90%) not met: 81.25%
- CardEditForm/CardEditFormItems/TableCardFormItems/TableCardFormSettings.jsx" coverage threshold for functions (90%) not met: 88.24%
- CardEditor.jsx" coverage threshold for branches (90%) not met: 80%
- PieChartCard.jsx" coverage threshold for functions (90%) not met: 85%
- PageWizardStep/PageWizardStep.jsx" coverage threshold for branches (90%) not met: 87.5%
- StatefulPageWizard.jsx" coverage threshold for branches (90%) not met: 80.95%
- SimpleList/SimpleList.jsx" coverage threshold for branches (90%) not met: 89.19%
- SimpleList/SimpleList.jsx" coverage threshold for functions (90%) not met: 83.33%
- AccordionItemDefer.jsx" coverage threshold for branches (90%) not met: 83.33%
- ScrollingControls.jsx" coverage threshold for branches (90%) not met: 87.5%
- TableHead/FilterHeaderRow/FilterHeaderRow.jsx" coverage threshold for statements (90%) not met: 87.3%
- TableHead/FilterHeaderRow/FilterHeaderRow.jsx" coverage threshold for branches (90%) not met: 81.33%
- TableHead/FilterHeaderRow/FilterHeaderRow.jsx" coverage threshold for lines (90%) not met: 87.1%
- TableHead/FilterHeaderRow/FilterHeaderRow.jsx" coverage threshold for functions (90%) not met: 83.33%
- TableHead/TableHead.jsx" coverage threshold for statements (90%) not met: 89.72%
- TableHead/TableHead.jsx" coverage threshold for branches (90%) not met: 85%
- TableHead/TableHead.jsx" coverage threshold for lines (90%) not met: 89.11%
- TableHead/TableHead.jsx" coverage threshold for functions (90%) not met: 77.14%
- TableMultiSortModal/TableMultiSortModal.jsx" coverage threshold for branches (90%) not met: 85.71%
- ErrorTable/ErrorTable.jsx" coverage threshold for branches (90%) not met: 83.33%
- Table.jsx" coverage threshold for statements (90%) not met: 89.8%
- Table.jsx" coverage threshold for branches (90%) not met: 88.1%
- Table.jsx" coverage threshold for functions (90%) not met: 82.35%
- StatefulTable.jsx" coverage threshold for branches (90%) not met: 86%
- GroupLogic.jsx" coverage threshold for functions (90%) not met: 85.71%
- RuleBuilder.jsx" coverage threshold for branches (90%) not met: 83.78%
- TableDetailWizard/TableDetailWizard.jsx" coverage threshold for branches (90%) not met: 85.71%
- TimeSeriesCard/TimeSeriesCard.jsx" coverage threshold for functions (77%) not met: 71.88%

**Comment by kevinsperrine** [comment]
Closed by #2822
