### ISSUE TITLE
[FullWidthWrapper] full width styles are not applied for non component children

### ISSUE THREAD

**Issue by bjornalm** [carbon-design-system/carbon-addons-iot-react#2470]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

The FullWidthWrapper used to have the styles conditionally applied to avoid setting them for the DeprecationNotice using:
`children.type.name !== 'DeprecationNotice`

This was later changed to avoid console errors when there was no "type" property on the children prop:

`children && children.type && children.type.name !== 'DeprecationNotice'`

However, this actually means that the styles are only applied if the children prop has a type property, which normally only is true when the children is a single react component.

Affects stories for Dashboard, DashboardGrid, PageTitleBar, Table, StatefulTable
 
We should use something like `!(children?.type?.name !== 'DeprecationNotice')` and verify that the stories act as expected.

### Expected behavior

The styles of the FullWidthWrapper should always be applied unless the children is the DeprecationNotice component.

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by JordanWSmith15** [comment]
@bjornalm Is the FullWidthWrapper only used in storybook? So, no app team benefits?
