### ISSUE TITLE
[Table] Manage Column link no longer visible on screen when resolution set to actual size

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-addons-iot-react#2482]
Health: https://github.ibm.com/maximo/Asset-Health-Insight/issues/5994

Describe the bug
Manage Column link blows out of the table and causes horizontal scrolling earlier than it shgould

In our reference app, as early as 1100px, the "Manage columns" button begins to cause a horizontal scroll.

In the IoT storybook, it is less noticeable, but only because there are not as many columns:
https://carbon-addons-iot-react.com/?path=/story/watson-iot-table--with-column-selection

From health:
To Reproduce
Log in to Health application
On Assets grid view click on the Manage Columns icon on the top right of page

ISSUE: The Manage Column blue link is not visible on the page
Workaround: Scroll down to the bottom of the page and see there is now a horizontal scroll bar which you can move all the way to the right and when you scroll back up the link is visible... or change the zoom level from 100% to 90% to see the link.

NOTE : This is new behavior in a recent build as I have not changed anything regarding my browser zoom level. Both the Firefox View-Zoom option is set to Actual Size and hamburger menu set to 100%

Expected behavior
Manage Column link should be visible as in previous builds OR be reactive such that when in this scenario it moves to be next to the Total Cost column button or whatever is the last column in that view.

Screenshots

<img width="1111" alt="Refapp" src="https://user-images.githubusercontent.com/21066152/124757492-a1f0c300-defb-11eb-936d-5a13ca1423cd.png">
<img width="888" alt="iot" src="https://user-images.githubusercontent.com/21066152/124757495-a2895980-defb-11eb-85e6-41aac025b2d9.png">

**Comment by bjornalm** [comment]
I don't think the "Manage columns" button causes the scrolling. I think the width of the columns is causing the table scrollbar to appear.  I notice that you have 2 columns called "description" which might explain why the columns occupy more space than normal.

But the PR is still on the right track to fix the problem by making sure the "Manage columns" button is wrapped to a new line.
