### ISSUE TITLE
[DateTimePicker] Unable to change the selected dates under the absolute option

### ISSUE THREAD

**Issue by navjeets** [carbon-design-system/carbon-addons-iot-react#2592]
Unable to change the selected dates under the absolute option. User is only allowed to click once to make the date selection in calendar view. After that, if the user tries to change the selection by clicking else where on the calendar there is no change in the current selection.

1. Go to https://carbon-addons-iot-react.com/?path=/story/watson-iot-datetime-picker--default
2. Click on calendar icon.
3. Click on 'Custom Range'.
4. Select 'Absolute' radio button.
5. Select start date by clicking on calendar.
6. Select end date by clicking on calendar.
7. Try to change the current selection by clicking on a new date.
8. See that nothing happens and the current selection stays unchanged.

<img width="346" alt="Screen Shot 2021-07-13 at 5 02 47 PM" src="https://user-images.githubusercontent.com/18363183/125524730-00510a8f-621a-444a-807f-183371479a1d.png">

Health defect -> https://github.ibm.com/maximo/Asset-Health-Insight/issues/6896

**Comment by kevinsperrine** [comment]
Might be related to  carbon-design-system/carbon#8865
