### ISSUE TITLE
[Progress Indicator] Upgrade PAL version for feature parity with Carbon

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-addons-iot-react#2605]
### What package is this for?

- [X] React
- [ ] Angular

### Summary

The [progress indicator from PAL](https://carbon-addons-iot-react.com/?path=/story/watson-iot-progressindicator--stateful) was created before the Carbon one. We should implement the Carbon version and deprecate the PAL version, as the Carbon version has "caught up"
[Carbon version](https://react.carbondesignsystem.com/?path=/story/components-progressindicator--default&knob-Collapsed%20icon%20text%20(tileCollapsedIconText)=Expand&knob-Collapsed%20icon%20text%20(tileExpandedIconText)=Collapse&knob-Form%20item%20(name%20in%20%3CTileGroup%3E)=tile-group&knob-Form%20item%20name%20(name%20in%20%3CRadioTile%3E)=tiles&knob-Form%20validation%20UI%20content%20(invalidText%20in%20%3CTimePicker%3E)=A%20valid%20value%20is%20required&knob-Href%20for%20clicable%20UI%20(href)=#&knob-Label%20text%20(labelText%20in%20%3CTimePicker%3E)=Select%20a%20time&knob-Label%20text%20(labelText%20in%20%3CTimePickerSelect%3E)=Please%20select&knob-Label%20text%20(labelText)=Checkbox%20label&knob-Max%20height%20(tileMaxHeight)=0&knob-Maximum%20length%20(maxLength%20in%20%3CTimePicker%3E)=5&knob-No%20label%20(hideLabel%20in%20%3CTimePickerSelect%3E)=true&knob-Plceholder%20text%20(placeholder%20in%20%3CTimePicker%3E)=hh:mm&knob-Regular%20expression%20for%20the%20value%20(pattern%20in%20%3CTimePicker%3E)=(1[012]|[1-9]):[0-5][0-9](\s)?(?i)&knob-Tab%20index%20(tabIndex)=0&knob-The%20title%20(title)=Section%201%20title&knob-Trigger%20icon%20description%20(iconDescription%20in%20%3CTimePickerSelect%3E)=open%20list%20of%20options)
<img width="721" alt="Screen Shot 2021-07-15 at 9 45 23 AM" src="https://user-images.githubusercontent.com/21066152/125798551-673090a8-f6cf-4342-b5e6-1a63c8e099f4.png">

• All props from Carbon are exposed in PAL storybook
• Labels can display ellipsis and tooltip overflow
• Ensure keyboard nav (tab can navigate enter can trigger onChange)
• Migrate into [Wizard component](https://carbon-addons-iot-react.com/?path=/story/watson-iot-pagewizard--stateful-example) and ensure that component functions as it does today
• Create deprecation notice of PAL Progress Indicator (if necessary)

Depended on by https://jsw.ibm.com/browse/GRAPHITE-3838

**Comment by davidicus** [comment]
In order to maintain semantic versioning we should probably deprecate our current progress indicator and also export the Carbon version as `CarbonProgressIndicator`. Then we should open an issue to remove our version and swap out all instances for Carbon's for our v3 major release. Otherwise we are going to have changes in mark up and class names which could break downstream consumers.

**Comment by kalyanixraut** [comment]
Hi @JordanWSmith15 , @davidicus , 

While trying to compare the features of ProgressIndicator between PAL and carbon, I have following observations:
Deprecating the existing component may impact some of the features which applications are already using it. So please suggest.

![image](https://user-images.githubusercontent.com/22093326/126279800-ea057e09-8690-48f4-8cee-cbb2dd47eb3a.png)

**Comment by davidicus** [comment]
@JordanWSmith15 I think the delta between these are enough to not deprecate at this time. If there are features that are missing we should look to extend our component.

**Comment by JordanWSmith15** [comment]
@davidicus Agreed. What is your suggested approach for handling the deltas? Do we add the extensions to the Carbon component in PAL, or do we need to contribute them to Carbon? This component is needed in the next month or so for Graphite.

**Comment by JordanWSmith15** [comment]
After speaking with Kalyani, we are going to update PAL with new props to address #4 and #8, and use the PAL version in Graphite.
