### ISSUE TITLE
[DateTimePicker] 'Relative to' dropdown arrow doesn't work when hasTimeInput is false

### ISSUE THREAD

**Issue by navjeets** [carbon-design-system/carbon-addons-iot-react#2616]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

When the hasTimeInput property is set to false, then the 'Relative to' dropdown arrow doesn't work (under Custom range > Relative).

### To Reproduce

1. Go to 'https://carbon-addons-iot-react.com/?path=/story/watson-iot-datetime-picker--default'.
2. Click on calendar icon.
3. Click on 'Custom Range'
4. Click on the down arrow button next to the 'Relative to' drop down. Nothing happens.
5. Clicking on the drop down box does work.

### Expected behavior

The down arrow should open the 'Relative to' drop down.

### Environment/versions:

- OS: Any
- Browser: Multiple
- `carbon-addons-iot-react` version: latest

### Additional context
<img width="334" alt="Screen Shot 2021-07-22 at 4 31 09 PM" src="https://user-images.githubusercontent.com/18363183/126705777-9147cfc8-985c-4cee-b64e-08abb57b284f.png">

### Specific timeline issues / requests

https://github.ibm.com/maximo/Asset-Health-Insight/issues/6858
Needed for MAS 8.6 / Health & Predict 8.4 (GM - Oct)

**Comment by navjeets** [comment]
@JordanWSmith15 Any idea when this may be addressed?

**Comment by JordanWSmith15** [comment]
@navjeets This is in the September sprint which starts next week. I will speak with @davidicus to see if we can bump it up

**Comment by davidicus** [comment]
closed with https://github.com/carbon-design-system/carbon-addons-iot-react/pull/2778
