### ISSUE TITLE
[datatable--with-overflow-menu] Column width for overflow menu

### ISSUE THREAD

**Issue by mbadman03** [carbon-design-system/carbon-addons-iot-react#2625]
### What package is this for?

- [ ] React

### Summary

The overflow menu takes up so much space on the table and the last column can not be moved into that space.

### Specific timeline issues / requests

We are moving the final parts of our legacy system to our newer product.   Creating the new tables are being implemented now so resolving the issues sooner than later will save us time revisiting where it has been implemented .

![user role table](https://user-images.githubusercontent.com/88175786/127599215-9331e346-9162-4838-92c3-96fe0e932953.jpg)

As can be seen in the image above, the icons, kebabs. etc at the end of a row should have a minimal variable size of the space they need and not share the table width.  The preceding column can not be expanded into the kebab column space.   It should be like the expansion column that is at the start of the row and of minimal width, except obviously as the last column on a table.

Even the documentation suggests it is a narrow column.    https://www.carbondesignsystem.com/components/data-table/usage/ sub topic of inline actions.

Thank you for your consideration.
Regards
Mary Badman

**Comment by JordanWSmith15** [comment]
I have also noticed this issue in Health.

**Comment by bjornalm** [comment]
I think this problem was solved by https://github.com/carbon-design-system/carbon-addons-iot-react/pull/2306
@mbadman03 can you confirm?

**Comment by JordanWSmith15** [comment]
Unable to reproduce in master. Placing this into blocked until confirmed by @mbadman03

**Comment by mbadman03** [comment]
@JordanWSmith15 @bjornalm 
I am having our development team lot at this again.   I will let you know on how we go.

**Comment by mbadman03** [comment]
@JordanWSmith15 @bjornalm 
Working now.  Thanks.
