### ISSUE TITLE
StatefulTable: OverflowMenu should scroll with its container

### ISSUE THREAD

**Issue by ravinain** [carbon-design-system/carbon-addons-iot-react#2629]
RowAction `OverflowMenu` in `StatefulTable` is not scrolling with the container.

This issue is similar to #4755 . However, I'm using `StatefulTable`

When I set the parent `div` position to `relative`, it fixes the scroll issue but introduces another. After scroll, the position of overflow menu is not correct. This is exactly same problem mentioned in the aforementioned ticket.

Dependency: carbon-addons-iot-react: 2.145
Browser: Chrome

Expected Behavior:
`OverflowMenu` should scroll with container. Also, after scroll the overflow menu should display at correct position.

### Steps to reproduce the issue

1. .parent div is scrollable
2. scroll div
3. Now click on overflow rowAction
4. Notice the position of overflow rowAction menu

Example:

```
<div class="parent" data-floating-menu-container="data-floating-menu-container">
        <StatefulTable></StatefulTable>
</div>

.parent {
    position: relative;
}
```

I have created an example here: [Overflow-Menu-Issue](https://codesandbox.io/s/overflow-menu-issue-forked-2kb2d?file=/src/index.js).

Steps to reproduce:

- Click on overflow menu on any record
- Scroll now. (The menu scroll with container, this is expected)
- Click on any other record now. You will notice the menu opened but at incorrect position.

![Overflow-Issue](https://user-images.githubusercontent.com/12138366/127939996-6d5facab-27ea-462d-aa1a-ba4d2a871d02.gif)

**Comment by davidicus** [comment]
It has been quite a while with no response on this issue. I am closing for now but please feel free to re-open if your issue persist.
