### ISSUE TITLE
[DateTimePicker] Cannot change date selections in calendar when placed inside a Graphite page or dashboard

### ISSUE THREAD

**Issue by navjeets** [carbon-design-system/carbon-addons-iot-react#2631]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

In the DateTimePicker's absolute option, one cannot change the date selections in calendar when its is placed inside a Graphite page or dashboard.

### To Reproduce

1. Go to 'http://health-stable-ora.fyre.ibm.com:9080/maximo/oslc/graphite/login/index.html?uri=relengineer#/health'. Slack me for credentials.
2. Click on asset '1001'.
3. Expand the 'Asset timeline' section.
4. Click open the DateTimePicker.
5. Click on 'Custom Range'.
6. Select the 'Absolute' option.
7. Pick a date range.
8. Try changing the end date (it doesn't work).

Note: This works in the 'next' storybook but doesn't inside a Graphite page or dashboard component.

### Expected behavior

DateTimePicker should work as expected inside a Graphite Page/Dashboard/Dialog component.

### Environment/versions:

- OS: Any
- Browser: Any
- `carbon-addons-iot-react` version: `2.146.0-next.67`

### Additional context

Health defect -> https://github.ibm.com/maximo/Asset-Health-Insight/issues/6896

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

Needed for Health & Predict 8.4 (GM 10/26)

**Comment by JordanWSmith15** [comment]
Seems to be an interaction issue with the card, perhaps having to do with z-index?

**Comment by davidicus** [comment]
@navjeets if you pin the version to flatpickr to `4.6.1` using the resolutions field in your package.json this should fix your issue. Kevin goes into detail in [this](https://github.com/carbon-design-system/carbon-addons-iot-react/pull/2594) PR

**Comment by navjeets** [comment]
Thank you @davidicus. The issue does get resolved when I add the following in Health package.json
`"resolutions": {
    "flatpickr": "4.6.1"
  }`

Can this be added in carbon-addons package.json though? There are some complications around adding these resolutions in Health because it won't work in Graphite configuration tool unless they add this resolution as well. Graphite configuration tool does not make use of Health package.json, so such changes are discouraged by @stuckless
