### ISSUE TITLE
[DateTimePicker] If I cross months between start and end date it's a little confusing because it resets the month

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#2635]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

Looks like there is an issue with selecting absolute ranges via the calendar widget.

If you go to a previous month, any time you select a day the calendar jumps back to the current month. This makes it difficult to select a range in a previous month/is confusing. You can still get the range to apply if you navigate back to the previous month to select the second day after being jumped back from the first selection.

I believe this is because we're switching the focus between start and end date on every change in the DateTimePicker code

### To Reproduce

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/IBM/carbon-addons-iot-react/tree/master/examples/codesandbox

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by davidicus** [comment]
@scottdickerson I am not seeing that in our storybook. https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-card--with-date-time-picker-range-selector. 

Can you verify that you still see the behavior in the link above?

**Comment by JordanWSmith15** [comment]
@scottdickerson any update on this?

**Comment by JordanWSmith15** [comment]
Fixed upstream
