### ISSUE TITLE
[Repo] Carbon charts dependency should be pinned to specific version

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#2639]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

All of our Carbon deps should be pinned to prevent unintended changes between versions. We currently have `^0.41.11` which will pull in the latest patch version. We should only have `0.41.100` (latest release) in our package.json
This will require us to upgrade our peer dep for d3 as well and make sure there are no breaking changes. 

### For instance

>![image](https://user-images.githubusercontent.com/1590966/128358762-7abd12d0-1f3b-4515-a174-b1c42ee34a7c.png)

Because of a dep change downstream this patch version broke our consumers.

**Comment by navjeets** [comment]
FYI @JordanWSmith15. We need this in Health & Predict 8.4 (GM 10/26)

**Comment by JordanWSmith15** [comment]
> FYI @JordanWSmith15. We need this in Health & Predict 8.4 (GM 10/26)

Looks like it is in the current sprint
