### ISSUE TITLE
[HierarchyList] error thrown when selecting story knob value

### ISSUE THREAD

**Issue by bjornalm** [carbon-design-system/carbon-addons-iot-react#2733]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug
There is an error saying "Cannot have two HTML5 backends at the same time.". Probably related to the drag and drop.

Use story

### To Reproduce

1. Go to https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-hierarchylist--with-nested-reorder
2. Select 'multiple-nesting' from Editing Style knob

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/IBM/carbon-addons-iot-react/tree/master/examples/codesandbox

### Expected behavior

No error

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Additional context
![image](https://user-images.githubusercontent.com/5167091/130639211-cf32d86b-b5e1-499e-8a1c-0f1b354038c6.png)

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by kevinsperrine** [comment]
closed by 2793.
