### ISSUE TITLE
[build] Build pipeline for PRs should create a production build of an application

### ISSUE THREAD

**Issue by stuckless** [carbon-design-system/carbon-addons-iot-react#2776]
### What package is this for?

- [X ] React
- [ ] Angular

### Summary

As part of the PR build pipeline, there should be a sample app that uses the PAL components.  This app should consume the PAL components as a downstream consumer would do, and create a production build of the application to verify that the entire end to end build pipeline will continue to work with this new build of the components.

**Comment by kevinsperrine** [comment]
duplicate of https://github.com/carbon-design-system/carbon-addons-iot-react/issues/1730.
