### ISSUE TITLE
[Table] Saas compilation error

### ISSUE THREAD

**Issue by vikasjagtap** [carbon-design-system/carbon-addons-iot-react#2792]
### What package is this for?

- [X] React
- [ ] Angular

### Describe the bug
There is a compilation error in down stream build

```
SassError: "calc(48 * var(--is-large-card))" is not a number for `max'
        on line 71 of node_modules/carbon-addons-iot-react/scss/components/Table/_table.scss, in function `max`
        from line 71 of node_modules/carbon-addons-iot-react/scss/components/Table/_table.scss
        from line 233 of node_modules/carbon-addons-iot-react/scss/styles.scss
>>     padding: max(calc(48 * var(--is-large-card)), 0px);
```
The commit that probably caused it
https://github.com/carbon-design-system/carbon-addons-iot-react/commit/c49d72f0d5ff9cf6f00799cfb53a8b5fc725d2cf

**Comment by kevinsperrine** [comment]
@vikasjagtap Are you using node-sass or dart-sass? And what version number?

**Comment by vikasjagtap** [comment]
@kevinsperrine sorry I should have mentioned it, we use node-sass 
`"node-sass": "^4.14.1"`

**Comment by kevinsperrine** [comment]
Thanks, @vikasjagtap. I've created a fix for this, but I would strongly encourage an upgrade to dart-sass as node-sass has been deprecated since Oct. 2020. Additionally, we have a v3.0.0 update coming in the near future that will not be compatible with node-sass.
