### ISSUE TITLE
[table] make preserveColumnWidths default

### ISSUE THREAD

**Issue by bjornalm** [carbon-design-system/carbon-addons-iot-react#2812]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

When `preserveColumnWidths` is true then adjacent column widths are preserved during resize and column toggle/add/remove operations. This behaviour should become default and the prop `preserveColumnWidths`, that when set to be false can be used to switch to the old behaviour, should be deprecated.

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

### Available extra resources

What resources do you have to assist this effort?

_Carbon add-ons for Watson IoT is a collaborative system. We encourage teams to
build components and submit them for integration._

**Comment by kevinsperrine** [comment]
Closed by #3093
