### ISSUE TITLE
[Table] Create coherent table stories

### ISSUE THREAD

**Issue by bjornalm** [carbon-design-system/carbon-addons-iot-react#2820]
### What package is this for?

- [x] React
- [ ] Angular

### Summary
Most of the stories have been built incrementally and combined over time which makes both the individual stories and the "book" itself incoherent. We lack a clear goal and plan for how the stories of this complex component should evolve. There is also no direct link from the story to the parts of the documentation covering the functionality displayed.

**Additional context** 
We should take a hard look at each story and ask if the purpose of the story is clear and if the name matches that purpose.  The two story categories "Table" and "StatefulTable" don't make sense when looking at the stories inside and considering the fact that almost all stories in both categories have a knob to change the table type. 

I think each story, except for the main playground, should tell a coherent story around some settings and data. A combination of settings that was turned into a story in order to fix a bug or prevent regression should be moved to unit/e2e testing instead. The documentation sections could be a good starting point when deciding which stories we should focus on. It would be nice to have some kind of taxonomy to help us in writing and maintaining the stories. Per story type we set some requirements and that could be useful for other components as well. I've thought of the following:

A. MAIN PLAYGROUND
Story is the main playground with as many knobs as possible to cover the largest amount of functionality. The documentation should show the full table documentation.

B. FUNCTIONALITY CONFIGURATION
The most common. Story shows a for the consumer relevant and coherent combination of properties and data. A story could be about showing "how row expansion works" and all the different variants and combinations using knobs, or a story showing "pagination" with all relevant configuration in knobs. We might have to write more than one story to tell the full tale of some complicated functionality but we can group them like carbon does in their table stories. Clicking the docs should open the relevant section.

C. EXTERNAL FUNCTIONALITY COMBINATION
Story code itself has custom code/components showing how to extend the table to get a certain functionality in place, e.g. the "create and save view management" functionality that partly resides outside the table. For these stories we might need custom documentation.

D. FOCUSED PLAYGROUND
Story is a playground to highlight special scenario, limitation or workaround that require interactions outside the table, e.g. 1-watson-iot-table-statefultable--with-pre-filled-search or 1-watson-iot-table-table--with-options-to-explore-column-settings. The scenario must be of interest to the common consumer if we are going to export the story, otherwise we might wanna restrict it to the dev environment.

### Specific timeline issues / requests
The work can be divided into several issues, one per story/story group, and old stories can be removed once they are covered by the new ones. That way this can be turned into an epic instead of a single giant issue.

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon add-ons for Watson IoT is a collaborative system. We encourage teams to
build components and submit them for integration._

**Comment by davidicus** [comment]
This epic has been completed.
