### ISSUE TITLE
[SuiteHeader] Slot for customer-defined content

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-addons-iot-react#2848]
We have many examples of customers making configurations to the global header. The edits are typically minor (a piece of text indicating what version, environment, or type of user). This is a capability they have in Maximo 7.6, and lacking these capabilities is being raised as an impediment for migrating to MAS (8). Some examples I have seen from the field:
 
![Screen Shot 2021-09-15 at 2.01.46 PM.png](https://images.zenhubusercontent.com/5c6ea1fad462891b1fd8e59e/03beb420-2118-4954-898d-bc47fa965a2e)
![Screen Shot 2021-09-15 at 1.08.10 PM.png](https://images.zenhubusercontent.com/5c6ea1fad462891b1fd8e59e/1fff6e83-8691-43df-968d-3d821683d683)
![image_6298.png](https://images.zenhubusercontent.com/5c6ea1fad462891b1fd8e59e/34468b13-e7ed-4de7-a800-80c8dca5a19c)

The suite header allows for a restrictive amount of custom content, but need to validate the extent to which it will support the requirements in the field
https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-suiteheader--header-with-extra-content

**Objective:**
Provide a custom slot, hidden by default, in the central area of the header where custom content can be passed

**Design:**
TBD

**Comment by davidicus** [comment]
There is a prop that can accommodate all of these examples. There may be some extra styling needed on consumers part but the prop allows for any element and the overflow for the header actions checks the size of the extra content when deciding if it should collapse or not.
