### ISSUE TITLE
[StatefulTable] the menu icons stay after clicking a menu item

### ISSUE THREAD

**Issue by ilovepumpkin** [carbon-design-system/carbon-addons-iot-react#2854]
### What package is this for?

- [x ] React
- [ ] Angular

### Describe the bug

After clicking a menu item on  row overlfow menu, the menu area icons stay in the row, never gone. 

It is easy to reproduce in the storybook: 
https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table-statefultable--stateful-example-with-row-nesting-and-fixed-columns

### To Reproduce

Click one menu item in overflow menu on table row, the move your mouse out to somewhere else.

### Expected behavior

The menu item area should disappear once menu item is clicked.

### Environment/versions:

- OS: all
- Browser: all 
- `carbon-addons-iot-react` version: 2.146.0-next.89

### Additional context

![image](https://user-images.githubusercontent.com/11310645/133872368-a77b72cf-5e32-4c93-b70b-c08d65eb39c8.png)

### Specific timeline issues / requests

Please give this issue a high priority because we have a release on Oct. and the code freeze is in Sep.

**Comment by davidicus** [comment]
closed by above PR
