### ISSUE TITLE
[Table] AsyncTable not showing correct total items. Also no filtering possible

### ISSUE THREAD

**Issue by nazarimilad** [carbon-design-system/carbon-addons-iot-react#2855]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

Currently, the table story ["with asynchronous data source"](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table-table--filtered-sorted-paginated-table-with-asynchronous-data-source) renders a table showing a total of 10 items ("1-10 of 10 items"). Which is incorrect, since the correct amount of [total elements is 100](https://github.com/carbon-design-system/carbon-addons-iot-react/blob/88b9127d14ded6756dcc15cfeb47f49625a281b6/packages/react/src/components/Table/Table.story.jsx#L2502) ([mock API](https://github.com/carbon-design-system/carbon-addons-iot-react/blob/fa4c13cc3c7e22d4d3df9b4f8f92494dc211f4d8/packages/react/src/components/Table/AsyncTable/MockApiClient.js#L22)). 

(If you select 20 items per page, it will render a total of 20 items and a total of 30 items for 30 items per page).

Also, it's currently not possible to provide any filtering input for the "first name" column or the "last name" column.

### Expected behavior

I expect the table to show the correct amount of total items: "1-10 of 100 items". I also expect to be able to filter rows based on first name or last name.

### Environment/versions

* OS: all
* Browser: all
* carbon-addons-iot-react version: 2.146.0-next.187

**Comment by objt-mni** [comment]
The `baseTableActions.tableRegister` function is not called correctly [here](https://github.com/carbon-design-system/carbon-addons-iot-react/blob/ddbd45c952a6f36dfa4ccfbf0f54c175db0f43b6/packages/react/src/components/Table/AsyncTable/AsyncTable.jsx#L121). It should be: 

```javascript
baseTableActions.tableRegister(
    { data: [...state.data, ...tableData], totalItems: data.meta.totalRows }
)
``` 

And the reducer is not getting [the totalItems](https://github.com/carbon-design-system/carbon-addons-iot-react/blob/ddbd45c952a6f36dfa4ccfbf0f54c175db0f43b6/packages/react/src/components/Table/AsyncTable/asyncTableReducer.js#L21) correctly. That line of code should be:

`totalItems: { $set: action.payload.totalItems },` 

About the filtering, I'm not sure how to fix that. I'm pretty sure you have to provide a `filter` property to the [column items](https://github.com/carbon-design-system/carbon-addons-iot-react/blob/ddbd45c952a6f36dfa4ccfbf0f54c175db0f43b6/packages/react/src/components/Table/AsyncTable/AsyncTable.jsx#L11). This way an input field will be shown to provide the filter value. 

Unfortuntely I don't know how to make sure the provided filter input can be used to call the mock client api with that filter (just began learning React, coming from Angular).

**Comment by bjornalm** [comment]
> ```js
> totalItems: data.meta.totalRows
> ```

Spot on! I'm creating a PR doing this and a fix for the filters. I also updated the documentation to explain the missing piece needed to get the filters working. Thank you.

**Comment by bjornalm** [comment]
> The `baseTableActions.tableRegister` function is not called correctly [here](https://github.com/carbon-design-system/carbon-addons-iot-react/blob/ddbd45c952a6f36dfa4ccfbf0f54c175db0f43b6/packages/react/src/components/Table/AsyncTable/AsyncTable.jsx#L121). It should be:
> 
> ```js
> baseTableActions.tableRegister(
>     { data: [...state.data, ...tableData], totalItems: data.meta.totalRows }
> )
> ```
> 
> And the reducer is not getting [the totalItems](https://github.com/carbon-design-system/carbon-addons-iot-react/blob/ddbd45c952a6f36dfa4ccfbf0f54c175db0f43b6/packages/react/src/components/Table/AsyncTable/asyncTableReducer.js#L21) correctly. That line of code should be:
> 
> `totalItems: { $set: action.payload.totalItems },`
> 
> About the filtering, I'm not sure how to fix that. I'm pretty sure you have to provide a `filter` property to the [column items](https://github.com/carbon-design-system/carbon-addons-iot-react/blob/ddbd45c952a6f36dfa4ccfbf0f54c175db0f43b6/packages/react/src/components/Table/AsyncTable/AsyncTable.jsx#L11). This way an input field will be shown to provide the filter value.
> 
> Unfortuntely I don't know how to make sure the provided filter input can be used to call the mock client api with that filter (just began learning React, coming from Angular). Otherwise I would've made a pull request with this code changes.

Spot on! I'm creating a PR doing this and a fix for the filters. I also updated the documentation to explain the missing piece needed to get the filters working. Thank you.

**Comment by nazarimilad** [comment]
Glad to be of help!
