### ISSUE TITLE
[DateTimePicker] flatpickr version difference breaking absolute datetime picking

### ISSUE THREAD

**Issue by kevinsperrine** [carbon-design-system/carbon-addons-iot-react#2868]
### What package is this for?

- [X] React
- [ ] Angular

### Describe the bug

After flatpickr version 4.6.1 changing preselected absolute DateTimePicker ranges is not possible.

**Comment by navjeets** [comment]
@kevinsperrine @davidicus I upgraded to Graphite 2.7.201 which has carbon-addons-iot-react version 2.146.0. However, the absolute datetime picker issue still happens. I have to click outside the calendar to be able to select a different date.

**Comment by kevinsperrine** [comment]
@navjeets That fix wasn't in 2.146.0. It was pulled in with `v2.146.1`. Can you give that a try, please?

**Comment by navjeets** [comment]
@JordanWSmith15 the recent carbon-addons upgrade in Graphite didn't pick the build with datetime picker fix. Do we have bandwidth to pick `v2.146.1` for 8.6?

**Comment by JordanWSmith15** [comment]
@kevinsperrine Can we deliver the fix to the 8.6 (2.146.0) branch instead? Bug fixes for 8.6 will need to go into this branch.

**Comment by kevinsperrine** [comment]
Fixed by #2881. @scottdickerson created a new issue for https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2868#issuecomment-954146578 which will be addressed this sprint.
