### ISSUE TITLE
[SideNav] Collapses with subitems still expanded

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-addons-iot-react#2880]
### What package is this for?

- [X] React
- [ ] Angular

### Describe the bug

When user click sub-items in sidenav, and then click anywhere out of the navigator, then the navigator will collapsed but with subitems expanded.

Go to https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-sidenav--side-nav-component
Open a few of the items by clicking
Collapse the menu to closed state
See defect:
<img width="610" alt="Screen Shot 2021-09-23 at 8 58 34 AM" src="https://user-images.githubusercontent.com/21066152/134515858-23bf78c8-10b5-49b9-98e0-d6ecb173aed7.png">

Relates to https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2645

**Comment by kevinsperrine** [comment]
Fixed in carbon. https://github.com/carbon-design-system/carbon/pull/9976 Just waiting for release at the end of this sprint

**Comment by kevinsperrine** [comment]
Closed by #3214
