### ISSUE TITLE
[GRAPHITE]MENUBAR - Menu options are not displaying on changing to RTL Mode

### ISSUE THREAD

**Issue by bakkireddi** [carbon-design-system/carbon-addons-iot-react#2902]
MENUBAR - Menu options in Reference-app are not displaying on changing to RTL Mode and again RTL to Normal Mode.

ScreenShots:
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/37322952/135093977-5a2abc97-0f49-49ef-8eee-c3bed7351dfa.png">
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/37322952/135094160-cb2a3566-468e-4074-a56d-9434b54270ea.png">

On clicking the overflow menu con it's displaying the "X" icon(Overflow close icon).
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/37322952/135094448-14255799-0cb3-4fbf-af7f-6bb7cf73fc5a.png">

In the IoT storybook:
https://carbon-addons-iot-react.com/?path=/story/1-watson-iot-suiteheader--header-with-side-nav

**Comment by JordanWSmith15** [comment]
@bakkireddi I thought we had determined that this was a graphite bug, not a PAL one

**Comment by bakkireddi** [comment]
We are able to reproduce this in PAL and Graphite.
https://carbon-addons-iot-react.com/?path=/story/1-watson-iot-suiteheader--header-with-side-nav
Steps:
1. Go to Suiteheader->Header with side nav
2. Enable RTL mode under RTL tab
3. First time it will show all the icons as below properly.
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/37322952/135989730-60adbc51-8a5d-4a9c-870f-981b85f4abc1.png">
4. Click on any other sub-component (Ex: default/Header with extra content)under Suite header. Now instead of Menu options it is displaying the "overflow menu" icon
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/37322952/135990389-4d8d1fbd-335c-4eba-848c-eaf08dbb7273.png">
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/37322952/135985261-f04ca405-07ca-43e7-bd91-f5316608a4eb.png">
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/37322952/135985298-0913113b-abd7-4411-8626-041e4d0e5cfc.png">
