### ISSUE TITLE
[ValueCard] Unit in value card needs to be positioned correctly.

### ISSUE THREAD

**Issue by kalyanixraut** [carbon-design-system/carbon-addons-iot-react#2903]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

After PAL v2.146.0 pulled into graphite I am seeing unit in value card have moved to right.
![image](https://user-images.githubusercontent.com/22093326/135097969-2d426fe6-a044-413c-b7bc-b4a68a0fa718.png)

### To Reproduce

1. Go to https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-valuecard--large-5
2. Select size as 'SMALL'
3. Change content.attributes knob to have only one field e.g.
`[
  {
    "label": "Comfort Level",
    "dataSourceId": "comfortLevel",
    "unit": "%"
  }
]`
4. See the unit '%' displayed to right with empty space between.

### Expected behavior

![image](https://user-images.githubusercontent.com/22093326/135098679-752b7cc5-0210-400e-b3da-4cba044ced87.png)

### Environment/versions:

- OS: MacOS
- Browser: chrome
- `carbon-addons-iot-react` version: v2.146.0

**Comment by kevinsperrine** [comment]
Fixed by #2904
