### ISSUE TITLE
[ContentSwitcher] Icon-only version displays [object, Object] tooltip

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-addons-iot-react#2905]
Blocks https://jsw.ibm.com/browse/GRAPHITE-40924
On hovering a switcher with icons in Graphite:
https://pages.github.ibm.com/maximo-app-framework/graphite/main/reference-app/?datasources%3AselectedTab=0&containers%3AselectedTabIndex=0&containers%3AselectedSwitch=0#/containers
<img width="165" alt="Screen Shot 2021-09-28 at 2 31 06 PM" src="https://user-images.githubusercontent.com/21066152/135145271-9396f3da-fa30-4ba9-8472-64b7494cd1ac.png">
A change was made to use text as title for tooltips, but when using icons only, this breaks Graphite by displaying [object, Object] as the tooltip. Carbon needs to allow a tooltip to be set which will override the text.
![image (4).png](https://images.zenhubusercontent.com/5c6ea1fad462891b1fd8e59e/f18b7f95-78c6-47df-9524-90361e35c77a)

**Comment by davidicus** [comment]
This issue is unrelated to the PAL library.

**Comment by JordanWSmith15** [comment]
Confirmed with Brian Ragusa that we can close this
