### ISSUE TITLE
[StatefulTable] Color of StatefulTable toolbar button label on Safari browser is dark

### ISSUE THREAD

**Issue by yj-li1** [carbon-design-system/carbon-addons-iot-react#2906]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

Color of StatefulTable toolbar button label on Safari browser is dark, which is confused because it seems disabled

### To Reproduce

It is easy to reproduce in the storybook:
https://carbon-addons-iot-react.com/?path=/story/1-watson-iot-table-statefultable--stateful-example-with-single-nested-hierarchy

On safari browser, click the checkbox of an item and you can see the toolbar with a delete button, and the label of "delete" is dark

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/IBM/carbon-addons-iot-react/tree/master/examples/codesandbox

### Expected behavior

The color of toolbar button label should be the same as other browsers 

### Environment/versions:

- OS: [MacOS]
- Browser: [safari]
- `carbon-addons-iot-react` version: [e.g. `^2.146.0-next.89`]

### Additional context
![image](https://user-images.githubusercontent.com/91594896/135229181-e24e6f51-b530-4b3d-ae8c-a7b7b14e1929.png)

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by bjornalm** [comment]
Thanks for reporting. This is odd, which version of macOS and Safari are you using? I'm trying to reproduce this, using your link, on macOS 11.5.2 and Safari 14.1.2 but it looks normal.

**Comment by yj-li1** [comment]
> Thanks for reporting. This is odd, which version of macOS and Safari are you using? I'm trying to reproduce this, using your link, on macOS 11.5.2 and Safari 14.1.2 but it looks normal.

Hello, and thank you for your reply. I'm using macOS **Big Sur 11.6** and **Safari 14.1.1**. Should I update my safari to verify this issue?

**Comment by bjornalm** [comment]
> > Thanks for reporting. This is odd, which version of macOS and Safari are you using? I'm trying to reproduce this, using your link, on macOS 11.5.2 and Safari 14.1.2 but it looks normal.
> 
> Hello, and thank you for your reply. I'm using macOS **Big Sur 11.4** and **Safari 14.1.1**. Should I update my safari to verify this issue?

Yes, please try that to see if it solves the problem.

**Comment by yj-li1** [comment]
> > > Thanks for reporting. This is odd, which version of macOS and Safari are you using? I'm trying to reproduce this, using your link, on macOS 11.5.2 and Safari 14.1.2 but it looks normal.
> > 
> > 
> > Hello, and thank you for your reply. I'm using macOS **Big Sur 11.4** and **Safari 14.1.1**. Should I update my safari to verify this issue?
> 
> Yes, please try that to see if it solves the problem.

Hi. After upgrading my Safari to 14.1.2, the button is fine now. Turns out it's a issue only on old version Safari. Thank you.
