### ISSUE TITLE
[List] secondary value out of alignment with long primary value

### ISSUE THREAD

**Issue by joannecl** [carbon-design-system/carbon-addons-iot-react#2939]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

When the primary value is too long, the secondary value starts going out of alignment. I have found & reproduced this on HierarchyList but I suspect it's on all the list components.

### To Reproduce

Component to reproduce is below with a screenshot of the outcome attached
```

import React from "react";
import {HierarchyList} from "carbon-addons-iot-react";


export default class ReorderListTest extends React.Component<any, any> {

    handleItemWillMove(): boolean {
        return true;
    }

    render() {

        const items: any = [];
        for (let i = 0; i < 10; i++) {
            items.push({
                id: i + '',
                content: {
                    value: "Item ".repeat(i * 10),
                    secondaryValue: "Jo"
                }
            });
        }

        return (
            <HierarchyList
                title={"Joanne"}
                items={items}
                editingStyle={"single"}
                itemWillMove={this.handleItemWillMove}
            >

            </HierarchyList>

        );

    }
}
```

![misalignment](https://user-images.githubusercontent.com/57422149/136743448-15efe366-de6e-4275-892d-b7cc245cba6c.PNG)

### Expected behavior

The second value should always be aligned

### Environment/versions:

- OS: [Windows]
- Browser: [chrome]
- `carbon-addons-iot-react` version: [v2.147.0-next.14]

**Comment by kevinsperrine** [comment]
Thanks, @joannecl. I've opened a PR for this issue. I also wanted to let you know that we've fixed the code sandbox issues, so you can open reproductions there now (https://codesandbox.io/s/github/carbon-design-system/carbon-addons-iot-react/tree/next/packages/react/examples/codesandbox). Thanks so much for including the code in your issues! It makes it much easier to track down and fix.

**Comment by joannecl** [comment]
Thanks for the fix @kevinsperrine ! Glad to hear the code sandbox is working now, that will make providing the examples much easier. Glad to hear also the code I've been providing has been helpful in finding the bugs!
