### ISSUE TITLE
Sidenav pushes page content instead of overlaying it

### ISSUE THREAD

**Issue by KarenGski** [carbon-design-system/carbon-addons-iot-react#2941]
In MAS 8.3, Health & Predict side nav overlaid content, which is consistent with the Maximo App Suite recommended behavior.  In 8.5 (and possibly 8.4, but I can't verify at the moment), it pushes the page content instead, which is inconsistent with the recommended behavior.  Default behavior of the graphite sidenav should be overlay because that is the recommended pattern.

**Comment by davidicus** [comment]
@JordanWSmith15 Like we discussed in slack this issue needs to be addressed in Graphite
