### ISSUE TITLE
[Table] column tooltips don't truncate

### ISSUE THREAD

**Issue by kevinsperrine** [carbon-design-system/carbon-addons-iot-react#2953]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

![column-tooltips](https://user-images.githubusercontent.com/609466/136964897-9a7b61f2-22ec-47fc-af21-88be571c1b1c.gif)

### To Reproduce

1. go to https://deploy-preview-2945--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-table-statefultable--simple-stateful-example
2. turn on `hasResize`
3. turn on `Demo column tooltips`
4. Resize a column to be very small. Instead of truncating the text it stacks it.

**Comment by andrii-melnychuk-ibm** [comment]
Column resizing doesn't have to be turned on, to see bugs with the tooltip

<img width="326" alt="Screen Shot 2021-11-02 at 12 22 01" src="https://user-images.githubusercontent.com/78968613/139829686-f761d639-a6ad-4c28-b83b-7805469668f0.png">

- tooltip overlaps with row actions menu
- tooltip gets cut when it doesn't fit in the table

**Comment by aovdiien** [comment]
![image1](https://user-images.githubusercontent.com/36842072/139879848-63b10278-09ad-4137-952c-e2e740183e9e.jpeg)
- tooltip gets cut when it doesn't fit in the table (if the table has one or two rows, its height is not enough to fit in the table column tooltip). please fix it.
