### ISSUE TITLE
[nav item] Navigation item support for 4 levels

### ISSUE THREAD

**Issue by tiffany-lai** [carbon-design-system/carbon-addons-iot-react#2959]
### What package is this for?
- [x] React
- [ ] Angular

### Summary

Hi, we would like to get support for side nav menu items that are 4 levels deep, including the enhancement to ctrl-click items. We currently customized the component to support 4 levels in TRIRIGA and had planned to contribute this back to the PAL, but because of our release timelines we weren't able to complete that contribution before we had to ship. We would like to get that 4 levels deep support into the base component as it will make it easier for us to stay current with the PAL if we don't have to re-implement that 4 levels deep when we upgrade.

### Specific timeline issues / requests
This would probably not be our next release, but for the one after (1Q 2022)

Contact Josh Meurer (@josh) for more details if needed

**Comment by kevinsperrine** [comment]
@dianatran18 I have some design questions regarding this pattern. Has anything been created for nesting this deep? Ie. this is what I'm experimenting with:

![Screen Shot 2021-10-19 at 3 48 39 PM](https://user-images.githubusercontent.com/609466/137980458-40f4f629-6851-4507-b965-a6d759d80703.png)
..

**Comment by dianatran18** [comment]
Actually @tiffany-lai can you confirm if it's 4 levels below the main, or including the main?

This is the padding defined for the indentation in the PAL sketch library, but @tiffany-lai @kevinsperrine let me know if that's what you have in your implementations as well

<img width="583" alt="Screen Shot 2021-10-19 at 4 00 03 PM" src="https://user-images.githubusercontent.com/43549567/137981791-c91cba87-576f-48a1-a213-468e424af124.png">
