### ISSUE TITLE
[Card, Modal] Card in expanded mode unable to display custom tooltip/dropdown list due to fixed z-index value.

### ISSUE THREAD

**Issue by kalyanixraut** [carbon-design-system/carbon-addons-iot-react#2963]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

Carbon modal has fixed z-index set to 9000 and as a result some of the components(like dropdowns/tolltips which are Graphite components) are not displayed on top of the card modal when viewed in expanded mode.

![image](https://user-images.githubusercontent.com/22093326/137255552-9d48e1e6-38b0-4041-9c3e-a6624f9ec96b.png)

![image](https://user-images.githubusercontent.com/22093326/137260822-a94ba524-fd6f-4641-8c12-7f40c8332b00.png)

### Expected behavior

Either the z-index be dynamically calculated based on the current/parent z-index or a props to be exposed so that it can be overwritten when needed.

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: 2.146.0

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by kevinsperrine** [comment]
Hi @kalyanixraut, I'm trying to re-create this, but it seems to be working as I would expect using our TableCard as an example. I modified a story locally to include tooltips in the title, columns headers, and as expandedRows in the table. Can you help me recreate the issue you're encountering?

![tooltips-expanded](https://user-images.githubusercontent.com/609466/139873421-5654dadd-e4d5-446d-ab69-2b5544028979.gif)

**Comment by kevinsperrine** [comment]
Friendly reminder, @kalyanixraut. Can you help me by re-creating this in codesandbox?

https://codesandbox.io/s/github/carbon-design-system/carbon-addons-iot-react/tree/next/packages/react/examples/codesandbox

**Comment by davidicus** [comment]
Closing for now. If we feel this is still an issue please feel free to reopen.
