### ISSUE TITLE
[StatefulTable] current page doesn't reset to initial value when new data is passed to the table

### ISSUE THREAD

**Issue by andrii-melnychuk-ibm** [carbon-design-system/carbon-addons-iot-react#2971]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug
If the user is on the page higher that 1 when data changes and there is not enough data entries to fill all pages before the current one and be displayed on the current page - the empty state is shown;

### To Reproduce

1. Go to 'https://stackblitz.com/edit/carbon-table-example-3zk62j?file=components%2FStatefulTable.jsx'
2. Choose `Table`
2. Go to page 2 of the table
3. Click the `short` button above the table (it will change table data)
4. Empty state is shown because there is not enough data to fill the first page and be shown on the second page

test case:
https://stackblitz.com/edit/carbon-table-example-3zk62j?file=components%2FStatefulTable.jsx
please note that in the test case the version is v2.141.0-next.36 just because it crashes every time you try to use a newer version, but the bug is reproducible with newer versions.

### Expected behavior

Current page number should be reset to the initial value

### Specific timeline issues / requests

Related to release at the end of this month

**Comment by kevinsperrine** [comment]
@andrii-melnychuk-ibm Thanks. I've opened a PR to fix this issue. I also wanted to let you know that we've fixed the bug with Stackblitz, so you can also use newest versions of the library (v2.147.0-next.37) and higher

**Comment by andrii-melnychuk-ibm** [comment]
@kevinsperrine that's great news, thank you!
