### ISSUE TITLE
[PageTitleBar] .page-title-bar-header should have padding-top of 32px

### ISSUE THREAD

**Issue by eosineye1** [carbon-design-system/carbon-addons-iot-react#3012]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

Per IBM carbon header style, the `PageTitleBar` should have a padding-top of 32px. The current implementation of the component does not follow this practice. Please refer to the link below. This should only affect the title and not the breadcrumb.
https://pages.github.ibm.com/ai-applications/design/components/page-header/style/
![image](https://user-images.githubusercontent.com/49462241/139459166-dee1fb92-1562-4c12-b18c-45147937348e.png)

### To Reproduce

1. Go to https://carbon-addons-iot-react.com/?path=/story/1-watson-iot-pagetitlebar--base
2. Inspect component
3.  Search for XPath: `/html//div[@id='root']/div[@class='storybook-container']//div[@class='page-title-bar-header']`
4. The `page-title-bar-header does not have padding-top: 32px

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/carbon-design-system/carbon-addons-iot-react/tree/next/packages/react/examples/codesandbox

### Expected behavior

The `PageTitleBar` should have a padding-top styling of 32px

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by eosineye1** [comment]
@kevinsperrine Could the margin-top be changed to padding-top to accommodate for PageTitleBar's with a different color background compared to the widget
![image](https://user-images.githubusercontent.com/49462241/140400741-219a94fd-8bf7-42b3-849c-e4d4292146a8.png)

**Comment by CynZhang** [comment]
the 32px margin should only be applied to the page title. When there's a breadcrumb above it, it should not affect the position of the page title. The spacing between the breadcrumb and the top banner is always 12px.
