### ISSUE TITLE
[Repo] Unify Layout, Spacing, and Color to Carbon Tokens

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-addons-iot-react#303]
It's been surfaced that there are consistency gaps in these components in regards to layout and spacing.

We should rectify this by 
- [x] Remove hardcoded `margin`, `padding`, etc where possible and use scss/js variables available in `@carbon/layout`
- [x] Remove hardcoded color hex and rgb(a) values, replace with scss/js variables available in `@carbon/colors`
- [x] Add the Carbon Gray 10 theme to our storybook to ensure components adhere to the theme appropriately. We may need to modify some variable names to get the color usage right.

**Comment by tay1orjones** [comment]
@stuckless could you provide a couple component examples where you found this to be present?

**Comment by tay1orjones** [comment]
@davidicus this would be a good item to include in the v2 release alongside the update to Carbon v10

**Comment by tay1orjones** [comment]
I'm going to add here that we should include colors in this work, remove hardcoded hex values and replace current variables with ones directly from the `@carbon/colors` package.

Additionally, we can at that point import the Carbon Gray 10 theme to ensure all our components follow the theme appropriately as we recommend/require consuming product teams to use the Gray 10 theme based on guidance in the design system site.

**Comment by sstone2423** [comment]
Is there a list of components that this applies to? Or is it best to just go through each component and look for these hard-coded values?

**Comment by davidicus** [comment]
This is still valid request. We need to audit all styles and remove hard coded values mentioned above

**Comment by tay1orjones** [comment]
@sstone2423 Yeah, unfortunately it's just a manual process that we need to do for each component

**Comment by tay1orjones** [comment]
color tokens https://www.carbondesignsystem.com/guidelines/color/usage
spacing tokens https://www.carbondesignsystem.com/guidelines/spacing/overview#spacing-scale
type tokens https://www.carbondesignsystem.com/guidelines/typography/productive
