### ISSUE TITLE
[HierarchyList] Expand/Collapse all or some rows

### ISSUE THREAD

**Issue by schadha** [carbon-design-system/carbon-addons-iot-react#3037]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

I want to be able to expand/collapse all levels of a HierarchyList (basically pass an array of row Ids as a prop to allow expanding or collapsing of rows).
Using `defaultExpandedIds` only expands specified rows on the first render. I can change the value of that prop by changing a state, but it doesn’t trigger a change in the collapse/expanded state of the rows.

When clicking the Open All button
<img width="1586" alt="Screen Shot 2021-11-04 at 9 17 13 AM" src="https://user-images.githubusercontent.com/2460655/140320100-fcd6ef88-bfa7-44c3-8fab-d21d0ebf0d34.png">

All rows specified in the prop are expanded
<img width="1563" alt="Screen Shot 2021-11-04 at 9 17 43 AM" src="https://user-images.githubusercontent.com/2460655/140320097-6a38a2d4-0312-4e52-94da-cc9adf52d125.png">

### Specific timeline issues / requests

The sooner the better. We have a product release coming up in January, so would be great to have the feature in before then.

### Available extra resources

I am available to test the feature

**Comment by JordanWSmith15** [comment]
I have seen this requirement in other Maximo products

**Comment by JoshPF** [comment]
I am currently having a slight issue with this at the moment, as the `onExpandedChange` seems to be called as soon as the array of ids to open are passed in, and not when the actual rows themselves are opened.

This is an issue for us as we have a table with a couple thousand entries, and there is a good second or two delay between hitting our "Open All" button, and actually having all of the rows opened. 

We'd like for the `onExpandedChange` function to be called once all of the rows are opened (and not immediately after getting the array of row ids passed in), as we need to display a loading spinner while this delay occurs.

**Comment by bjornalm** [comment]
@JoshPF You are mentioning the table above (and we have a table component), but do you mean the HierarchyList component?

**Comment by JoshPF** [comment]
> @JoshPF You are mentioning the table above (and we have a table component), but do you mean the HierarchyList component?

I am referring to the HierarchyList component. I'd like the `onExpandedChange` prop function to be run once the rows are actually expanded

**Comment by bjornalm** [comment]
> > @JoshPF You are mentioning the table above (and we have a table component), but do you mean the HierarchyList component?
> 
> I am referring to the HierarchyList component. I'd like the `onExpandedChange` prop function to be run once the rows are actually expanded, and not just once the row ids are passed in

Alright, I'll open up a new issue for that
