### ISSUE TITLE
[Card] Style audit

### ISSUE THREAD

**Issue by dianatran18** [carbon-design-system/carbon-addons-iot-react#3043]
### What package is this for?

- [x] React
- [ ] Angular

## 1. Card (basic)

The title on the card sits a little high compared to the design. The header `productive-heading-02` should be vertically centered to the 48px height space with no subtitle (update top-margin from 8 to 13)

Design spec: https://pages.github.ibm.com/ai-applications/design/components/card/style
Storybook: https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-card--basic

<img width="962" alt="Screen Shot 2021-11-08 at 3 00 27 PM" src="https://user-images.githubusercontent.com/43549567/140809609-72bbb54b-2aec-4df7-9b6f-328e6bd623a1.png">

### Current

<img width="534" alt="Screen Shot 2021-11-08 at 3 11 56 PM" src="https://user-images.githubusercontent.com/43549567/140811146-4d7bc8e1-4750-4cc5-b744-455f77f6c877.png">

### Proposed

<img width="532" alt="Screen Shot 2021-11-08 at 3 11 16 PM" src="https://user-images.githubusercontent.com/43549567/140811035-55b6bf49-3d9b-415f-9c30-f66c1119b38f.png">

———

## 2. Card with subtitle
For the card with a subtitle, the card header space is actually 64px. The top margin for the header is the same as the card with no subtitle.

Design spec: https://pages.github.ibm.com/ai-applications/design/components/card/style#title-and-subtitle

### Current
Storybook: https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-card--with-date-time-picker-range-selector-existing-value

<img width="442" alt="Screen Shot 2021-11-08 at 3 39 43 PM" src="https://user-images.githubusercontent.com/43549567/140814806-8f10d3ce-b6bd-4a0c-a541-3734c1109cdc.png">

### Proposed
<img width="546" alt="Screen Shot 2021-11-08 at 3 14 34 PM" src="https://user-images.githubusercontent.com/43549567/140811461-95a04c58-296f-4eee-9644-43e4191ee486.png">

———

## 3. Card with footer

Adjust ghost button placement and size of footer. 

### Current
Storybook: https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-card--with-ellipsed-title-tooltip-external-tooltip
<img width="570" alt="Screen Shot 2021-11-08 at 3 31 11 PM" src="https://user-images.githubusercontent.com/43549567/140814651-847768c9-a2f6-4f26-a491-b60a1d6a47a9.png">

### Proposed

(spec from #2145)
<img width="1271" alt="Screen Shot 2021-11-08 at 3 32 23 PM" src="https://user-images.githubusercontent.com/43549567/140813822-ba03bb4a-2440-4f52-b960-305ef91e6312.png">

(The spec isn't on the design site right now but we are also updating the site to include the footer option)
<img width="805" alt="Screen Shot 2021-11-08 at 3 36 06 PM" src="https://user-images.githubusercontent.com/43549567/140814340-13154385-93a9-4d17-92ec-62183ecb2208.png">

## 4. Card with empty/error state

We should be consistent on the empty states and have the empty state content be left aligned (not centered).
Already available in [code](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-emptystate--error).
For small cards, we can use the option [without the icon](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-emptystate--without-icon)

### Current
Storybook: https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-card--error
<img width="602" alt="Screen Shot 2021-11-08 at 3 40 09 PM" src="https://user-images.githubusercontent.com/43549567/140814853-491d3c78-62f4-4df5-bedd-2fb274f51025.png">

**Comment by JordanWSmith15** [comment]
#3 may be difficult to achieve, as the card margin would need to be removed for the footer section only

**Comment by dianatran18** [comment]
Not sure if this helps, but here's the C&CS storybook example of the same: https://ibm-cloud-cognitive.netlify.app/?path=/story/cloud-cognitive-components-cards-productivecard--supplemental-bottom-bar
