### ISSUE TITLE
[MenuButton] Style audit + button variations

### ISSUE THREAD

**Issue by dianatran18** [carbon-design-system/carbon-addons-iot-react#3044]
### What package is this for?

- [x] React
- [ ] Angular

## 1. Menu heights

Similar to other components like [dropdowns](https://react.carbondesignsystem.com/?path=/story/components-dropdown--playground) and [overflow menu](https://react.carbondesignsystem.com/?path=/story/components-overflowmenu--playground), there are multiple size variations for the component, and the menu items should match the height of the component. 

### Current

Storybook: https://next.carbon-addons-iot-react.com/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-menubutton--single-menu-button
<img width="563" alt="Screen Shot 2021-11-08 at 3 58 34 PM" src="https://user-images.githubusercontent.com/43549567/140817123-e3ffbd37-7879-49ca-9807-e92bdf18beaf.png">

### Proposed
Design spec: https://pages.github.ibm.com/ai-applications/design/components/buttons/style

<img width="930" alt="Screen Shot 2021-11-08 at 3 53 08 PM" src="https://user-images.githubusercontent.com/43549567/140816409-8f146fc5-d69b-4cab-b121-05331a04d582.png">

## 2. Button variations

The menu button in the design can be used with the primary, secondary, tertiary, and ghost.
The split (combo) button in the design can be used with the primary, secondary, and tertiary.

Note: the secondary button is up for discussion to see if we need to support that, since secondary buttons are generally used in conjunction with primary buttons and acts as the negative action of the set, but it would be good to support the tertiary and ghost (for menu only) as well.

Design spec: https://pages.github.ibm.com/ai-applications/design/components/buttons/style

## 3. Fix z-index on shadow for icon only button

The shadow from the popover shows above the icon button. Also, same note on the button size vs the menu items being the same size.

### Current

Storybook: https://next.carbon-addons-iot-react.com/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-menubutton--icon-only-menu-button

<img width="533" alt="Screen Shot 2021-11-08 at 4 05 43 PM" src="https://user-images.githubusercontent.com/43549567/140817972-f8d0074e-4b5d-450b-b786-09c768639edf.png">

### Proposed

<img width="551" alt="Screen Shot 2021-11-08 at 4 05 57 PM" src="https://user-images.githubusercontent.com/43549567/140818013-ed9ebb3d-e5d0-4664-95d5-2a61cf5bbfc4.png">

**Comment by JordanWSmith15** [comment]
@dianatran18  Can we get a design spec for 1 that includes icons? If the design spec had icons, I don't think we'd see much of a difference. Literally a couple pixels at most.

**Comment by dianatran18** [comment]
> @dianatran18 Can we get a design spec for 1 that includes icons? If the design spec had icons, I don't think we'd see much of a difference. Literally a couple pixels at most.

I personally haven't seen any use cases with icons — the icons In the storybook came for free from the Carbon context menu component, but that is a different use case from the action buttons teams have been using. If you look at some of the examples below, those actions don't have a natural icon that can be associated with it. 

![image (1)](https://user-images.githubusercontent.com/43549567/141346549-9397d359-002c-429d-97c2-e5e015d026cb.png)

![image (2)](https://user-images.githubusercontent.com/43549567/141346665-4550d978-2451-4c81-9c4a-caeae5b97759.png)


The request for 1 is to have matching button sizes to each menu item. I realized the screenshot I have in the issue is actually wrong — the menu items are 32px in size, while the button is 48px. If the menu items are 32px, then that should go with the 32px (small) button. If the menu heights are 48px, that should go with the 48px (large) button, etc. 

<img width="798" alt="Screen Shot 2021-11-11 at 12 58 34 PM" src="https://user-images.githubusercontent.com/43549567/141346432-c470ea18-0cc4-4799-8e99-66d5e6a95cea.png">

**Comment by dianatran18** [comment]
The best example to show this is Carbon's overflow menu if you change the sizes in the knobs (although it looks a little broken on the small).

https://react.carbondesignsystem.com/?path=/story/components-overflowmenu--playground

**Comment by JordanWSmith15** [comment]
@dianatran18 Seems your recommendation is to deprecate support for menu item icons then. @davidicus will need to weigh in on risk. Maybe we can detect if anyone is using the feature somewhere.

**Comment by dianatran18** [comment]
I don't think we necessarily need to deprecate it, but it's optional for teams to use or not. Is that just a prop that can be turned on/off? I assume the icons we just got for free from what Carbon has.

**Comment by bjornalm** [comment]
@dianatran18 Besides the fact that one is containing icons, what is the difference between 
https://next.carbon-addons-iot-react.com/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-menubutton--icon-only-menu-button 
and https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-overflowmenu--basic

**Comment by dianatran18** [comment]
The main difference between the two is that the first one has a submenu for Share with and Export, whereas the second one doesn't and is just a simple list of actions. I agree that these are both just overflow menus though, but I think the way the menu part itself is built in Carbon are different since the menu button popover part was a more recent add to Carbon. @davidicus you might have more insight on how it's coded.

**Comment by bjornalm** [comment]
Should we align the sizes with the sizes of the underlying Carbon button?  If you look [here](https://react.carbondesignsystem.com/?path=/story/components-button--playground) the `large` is 64px. Your proposed `large` corresponds to the carbon `default` of 48px so perhaps we can just call our large default instead?

**Comment by dianatran18** [comment]
For Carbon v11, they will be changing their sizing naming convention to `large (48px)` `medium (40px)` and `small (32px)`. They've already started to do this for some newer components they've updated, but buttons has not made the full switch yet.

From one of the Carbon designers: 

> It is changing ! It will be the new large (48px), medium (40 px), and small (32px) for v11

**Comment by elenachernih** [comment]
Hello guys,

Do you know maybe when the Menu Button component will be available to use in production level for React apps? 

Thanks,
Elena

**Comment by JordanWSmith15** [comment]
@elenachernih It is available in our storybook today. Look here:
https://next.carbon-addons-iot-react.com/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-menubutton--single-menu-button

**Comment by elenachernih** [comment]
@JordanWSmith15 Thank you for your comment,
but you can see there that it is considered experimental and not recommended for production level: 
![image](https://user-images.githubusercontent.com/106759570/201676788-6c7a78d0-e23a-4658-81d2-845e879650af.png)
We need this component for production

**Comment by JordanWSmith15** [comment]
@davidicus FYI. I think we should just remove this notice, as the component has been around for almost two years. There are no known gaps or issues with the control.

**Comment by elenachernih** [comment]
@JordanWSmith15 Thank you! 
@davidicus is it official to use it?
