### ISSUE TITLE
[PageTitleBar] Style audit

### ISSUE THREAD

**Issue by dianatran18** [carbon-design-system/carbon-addons-iot-react#3045]
### What package is this for?

- [x] React
- [ ] Angular

## 1. Padding adjustment

On the dynamic page header, there is an extra 2px in the collapsed header state, making it 42px high and not 40px.

### Current

Storybook: https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-pagetitlebar--with-dynamic-scrolling

<img width="535" alt="Screen Shot 2021-11-08 at 4 10 47 PM" src="https://user-images.githubusercontent.com/43549567/140818822-38e90aaa-203b-4c24-91e2-ce3018521236.png">

### Proposed
<img width="778" alt="Screen Shot 2021-11-08 at 5 52 36 PM" src="https://user-images.githubusercontent.com/43549567/140830946-c35eb0a6-59c0-4c0d-93df-bb26a541151f.png">

## 2. Dividing line between buttons for accessibility

Similar to how a dividing line was adding between button groups in places like [modals](https://next.carbon-addons-iot-react.com/?path=/story/3-carbon-modal--default), we need a dividing line between any secondary/primary button pairings for accessibility

### Current

Storybook: https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-pagetitlebar--with-dynamic-scrolling

<img width="440" alt="Screen Shot 2021-11-08 at 4 32 14 PM" src="https://user-images.githubusercontent.com/43549567/140821478-571ddfd6-742a-4926-a9dc-cc065b62c3b1.png">

Storybook: https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-pagetitlebar--with-condensed-header

### Proposed
<img width="778" alt="Screen Shot 2021-11-08 at 5 52 36 PM" src="https://user-images.githubusercontent.com/43549567/140830946-c35eb0a6-59c0-4c0d-93df-bb26a541151f.png">

## 3. Line below tabs in collapsed state

Similar to the dynamic header with no tabs, there should be a dividing line to create separation from the tabs and content on scroll.

### Current

Storybook: https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-pagetitlebar--with-dynamic-scrolling-and-tabs

<img width="1564" alt="Screen Shot 2021-11-08 at 4 34 19 PM" src="https://user-images.githubusercontent.com/43549567/140821898-bac5288e-e637-4fa5-8003-c209d2d26a85.png">

### Proposed

<img width="1070" alt="Screen Shot 2021-11-08 at 5 57 02 PM" src="https://user-images.githubusercontent.com/43549567/140831405-001cf275-a922-42bc-9be9-3e8090c8f324.png">

## 4. Dynamic header with tabs enhancement

Can we add a variation/prop to have both the collapsed header and tabs both sticky? This is an enhancement we're making on the design side as well based on feedback so you don't lose your page-level actions and breadcrumb/page title. 

### Proposed

<img width="1627" alt="Screen Shot 2021-11-08 at 5 57 43 PM" src="https://user-images.githubusercontent.com/43549567/140831477-ccc7da92-6493-43df-affe-a1230dddba1c.png">

**Comment by kevinsperrine** [comment]
Hi @dianatran18, regarding #4, Can you give me a little more details? 

Should it happen with both headerMode=condensed and headerMode=dynamic?
Would a prop name like `stackHeaderAndTabs` work to turn this on, or should this be default behavior in one of those two modes?

**Comment by dianatran18** [comment]
> Hi @dianatran18, regarding point 4, Can you give me a little more details?
> 
> Should it happen with both headerMode=condensed and headerMode=dynamic? Would a prop name like `stackHeaderAndTabs` work to turn this on, or should this be default behavior in one of those two modes?

Yeah it should work with both dynamic and condensed. The primary use case should be dynamic, but if teams are using the condensed header only then it makes sense to have them be aligned.

And I would probably say it makes sense to make that the default behavior if teams have both a page header and tabs, and then the current collapsing version is on a prop. 


This is the updated guidance from [Cloud & Cognitive](https://pages.github.ibm.com/cdai-design/pal/components/page-header/usage#scrolling) and they say 

> #### With tabs
> There are two available behaviors for scrolling with tabs.
> 
> 1. The primary scrolling behavior is to position the tabs directly underneath the breadcrumb toolbar upon collapse. This keeps the breadcrumbs and page title always visible for wayfinding and to navigate elsewhere on the product.
> 
> 2. The second option pushes the breadcrumb out of view, replacing it with tabs on scroll. This should be only be used for stage space saving needs. The intial page title transition remains the same. After this initial transition, the tabs push the breadcrumbs out of view as the page is scrolled further. As soon as the page is scrolled towards the top, the breadcrumb row reveals again stacked above the tabs.
