### ISSUE TITLE
Title of x-axis bleeds below chart in certain circumstances

### ISSUE THREAD

**Issue by tedlyons** [carbon-design-system/carbon-addons-iot-react#3049]
### What package is this for?

- [x ] React
- [ ] Angular

### Describe the bug

Some (all?) charts when they have legends positioned top and orientation vertical will push the chart down so that the x-axis title goes beyond the lower bondary.

### To Reproduce

To recreate this behavior in the carbon charts storybook (although its not obvious there because the background is black for the entire page).  Use the Line (discrete) story.  Add the following option:  "legend":{"position":"top","orientation":"vertical"}.  This will cause the x-axis title "2019 Annual Sales Figures" to bleed below the element.  You can inspect the elements with dev tools to see this.

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/carbon-design-system/carbon-addons-iot-react/tree/next/packages/react/examples/codesandbox
You can recreate this in the story: https://charts.carbondesignsystem.com/?path=/story/simple-charts-line--line-discrete
by using this for the options knob: 
{
  "title": "Line (discrete)",
  "axes": {
    "bottom": {
      "title": "2019 Annual Sales Figures",
      "mapsTo": "key",
      "scaleType": "labels"
    },
    "left": {
      "mapsTo": "value",
      "title": "Conversion rate",
      "scaleType": "linear"
    }
  },
  "height": "400px",
  "legend":{"position":"top","orientation":"vertical"}
}

### Expected behavior

The entire chart should remain contained in the element.

### Environment/versions:

- OS: [Windows]
- Browser: [chrome, ff]
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Additional context

![image](https://user-images.githubusercontent.com/11442935/141008519-da888b33-f5d7-4b5c-a075-d3b0e26f5224.png)

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by davidicus** [comment]
Hi @tedlyons. Do we see this bug in an actual application? I ask only because the storybook has a lot of wrapping divs that are being dynamically sized. A height of 400px is being directly applied to a wrapping div that is not part of the component. If you could open a codesandbox that contains the bug it would be a lot easier to debug and figure out a resolution.

**Comment by JordanWSmith15** [comment]
We worked around this issue in Graphite.
