### ISSUE TITLE
Use of a vulnerable version of polished npm package

### ISSUE THREAD

**Issue by piotr-kotara-ibm** [carbon-design-system/carbon-addons-iot-react#3050]
The package `polished@^2.3.3` is used as the dependency. This version is vulnerable to the ReDoS described here: https://security.snyk.io/vuln/SNYK-JS-POLISHED-1298071

Vulnerability is fixed in versions 3.7.2, 4.1.3 or higher.

**Comment by JordanWSmith15** [comment]
@piotr-kotara-ibm How critical is this item? Would there be an issue for you if this was fixed in January, rather than immediately?

**Comment by piotr-kotara-ibm** [comment]
@JordanWSmith15 The severity of this vulnerability is low, there is no need to deliver immediate fix. Fix in January wouldn't be a problem
