### ISSUE TITLE
[List] Style audit

### ISSUE THREAD

**Issue by dianatran18** [carbon-design-system/carbon-addons-iot-react#3062]
### What package is this for?

- [x] React
- [ ] Angular

## 1. Header

The padding to the left and the right of the header should be 16px — it is currently at 12px

### Current

Storybook: https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-list--basic-single-column

<img width="490" alt="Screen Shot 2021-11-15 at 2 14 52 PM" src="https://user-images.githubusercontent.com/43549567/141840531-a5e253cf-0bfc-4c76-b1d8-e877b053a57b.png">

<img width="229" alt="Screen Shot 2021-11-15 at 4 20 16 PM" src="https://user-images.githubusercontent.com/43549567/141855390-ed0c7538-bf02-4fb8-8669-1767aadefc1d.png">

## 2. Search

Update search space to be a search container that fills the full row. The row height should be the same as the row items (40px)

### Current

Storybook: https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-list--basic-single-column-with-search

<img width="440" alt="Screen Shot 2021-11-15 at 2 25 33 PM" src="https://user-images.githubusercontent.com/43549567/141841779-875f49de-3157-4ae0-ade3-825384da0b54.png">

<img width="461" alt="Screen Shot 2021-11-15 at 2 28 55 PM" src="https://user-images.githubusercontent.com/43549567/141842252-4a8b8843-b111-4c91-b774-9aec364b4c7d.png">

### Proposed

<img width="698" alt="Screen Shot 2021-11-15 at 2 45 43 PM" src="https://user-images.githubusercontent.com/43549567/141844269-fbec0028-e32f-4e45-8551-52218103428a.png">

<img width="973" alt="Screen Shot 2021-11-15 at 2 45 11 PM" src="https://user-images.githubusercontent.com/43549567/141844210-ab313b84-3a5d-4901-b884-8e0cd8805931.png">

## 3. Overflow icon 

Fix overflow icon button size to match single icon size and placement

### Current
Storybook: https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-list--with-row-actions-multiple

<img width="460" alt="Screen Shot 2021-11-15 at 2 50 35 PM" src="https://user-images.githubusercontent.com/43549567/141844893-e7eb8f71-ec7d-40e4-bbc9-4f59d1fd3bc5.png">

Placement of the overflow menu looks detached as well

<img width="246" alt="Screen Shot 2021-11-15 at 2 50 46 PM" src="https://user-images.githubusercontent.com/43549567/141844917-3b6035f0-5453-4782-9b62-ceea52bc3dc9.png">

### Proposed

Match icon button placement and size to this storybook item: https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-list--with-row-actions-single
<img width="473" alt="Screen Shot 2021-11-15 at 2 51 21 PM" src="https://user-images.githubusercontent.com/43549567/141844994-68c142c6-6298-4216-b1c5-5bc819b34cfc.png">
<img width="1473" alt="Screen Shot 2021-11-15 at 2 54 29 PM" src="https://user-images.githubusercontent.com/43549567/141845327-7fb5d4ae-5428-489d-a0a0-ce085c724f87.png">

## 4. Empty state

Update the empty state to use the newer empty state pattern (left aligned)

### Current

Storybook: https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-list--with-empty-state

<img width="461" alt="Screen Shot 2021-11-15 at 2 56 38 PM" src="https://user-images.githubusercontent.com/43549567/141845572-cfe547c7-87d8-478e-881e-47386249643d.png">

### Proposed

Empty state storybook existing component: https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-emptystate--first-time-use

<img width="1291" alt="Screen Shot 2021-11-15 at 3 16 12 PM" src="https://user-images.githubusercontent.com/43549567/141847881-b6901fca-15e1-4322-8065-d9648eece768.png">

## 5. Pagination footer

The text in the footer should be 16px from the left to line up with the content. There also shouldn't be a border around the full component, as it creates a double border at the top and unnecessary border around the sides and bottom. 

### Current

Storybook: https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-list--with-pagination

<img width="480" alt="Screen Shot 2021-11-15 at 3 19 18 PM" src="https://user-images.githubusercontent.com/43549567/141848218-59815546-b29c-486b-80ad-74a631b699bd.png">

### Proposed

PAL guidance: https://pages.github.ibm.com/ai-applications/design/components/pagination/overview#list-pagination 
(this came from the former IoT PAL but is still correct for the list component footer)

<img width="881" alt="Screen Shot 2021-11-15 at 3 24 48 PM" src="https://user-images.githubusercontent.com/43549567/141848878-e2eebcad-b662-4de3-8b9e-13074a3ccb0c.png">

## 6. Load more

This seems like it was a request that came from a team but wasn't approved by PAL. 
Generally, any loading state should use the skeleton state (which is already available in the knobs as isLoading).

A better experience would be a lazy load where the rows loading automatically happened when reaching the end of the current populated list, but I'm not sure if that's available/a team technical limitation.If there needs to be a manual load trigger, the text shouldn't be center aligned, but left aligned to line up with the row text. In this case, if there is a hierarchy, then it should line up with the level it is associated with. 

### Current

Storybook: 

Placement
<img width="469" alt="Screen Shot 2021-11-15 at 3 26 32 PM" src="https://user-images.githubusercontent.com/43549567/141849074-f5d6d6d8-dd41-461f-b0e3-330d45f218be.png">

Loading state
<img width="642" alt="Screen Shot 2021-11-15 at 3 27 36 PM" src="https://user-images.githubusercontent.com/43549567/141849210-7b9d799d-5df8-4f5a-8189-2ddfb58d8bfb.png">

### Proposed

Placement - can we also update the text to say "View more" instead of "Load more..."

<img width="983" alt="Screen Shot 2021-11-15 at 4 04 10 PM" src="https://user-images.githubusercontent.com/43549567/141853574-bc2f7307-8a6f-4c38-a189-94741c1a87ec.png">

Loading state (skeleton state)
<img width="960" alt="Screen Shot 2021-11-15 at 3 40 21 PM" src="https://user-images.githubusercontent.com/43549567/141850771-33ec515f-9869-4025-8df3-5eb373874b29.png">

## 7. Mixed hierarchies

In the mixed hierarchy (which is actually called hierarchy), the parent levels and nested levels that expand should not be semi-bold in text. All levels should be using `body-short-01` and `text-02` color. Only in the regular hierarchy list (actually called categories) should the parent levels be semi-bold/productive-heading-01.

### Current
Storybook: https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-hierarchylist--with-mixed-hierarchies

<img width="496" alt="Screen Shot 2021-11-15 at 4 08 47 PM" src="https://user-images.githubusercontent.com/43549567/141854090-f9170ed7-ff5a-4f5d-aa43-b81301c53d4a.png">

### Proposed

<img width="695" alt="Screen Shot 2021-11-15 at 4 11 27 PM" src="https://user-images.githubusercontent.com/43549567/141854393-7f8ad3ee-7ce5-49d2-bc0e-2047ed3db415.png">

## 8. Tall row

Adjust the height and text alignment in the large row

### Current

Storybook: https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-list--with-is-large-row-and-icon

<img width="479" alt="Screen Shot 2021-11-15 at 4 13 26 PM" src="https://user-images.githubusercontent.com/43549567/141854603-bac953e8-0cdf-4b99-8ab1-7960038d3619.png">

<img width="544" alt="Screen Shot 2021-11-15 at 4 19 37 PM" src="https://user-images.githubusercontent.com/43549567/141855294-ba3885be-e65e-4f79-a218-e9f05b9434eb.png">

### Proposed
<img width="1217" alt="Screen Shot 2021-11-15 at 4 19 10 PM" src="https://user-images.githubusercontent.com/43549567/141855244-0190fce2-3d5f-4218-befa-a5b4a6d34e5a.png">

**Comment by JordanWSmith15** [comment]
This story is lower priority, as Graphite does not consume this control

**Comment by bjornalm** [comment]
@dianatran18 If we have tall rows with checkboxes, how are the checkboxes aligned? vertically with the primary value?

**Comment by dianatran18** [comment]
> @dianatran18 If we have tall rows with checkboxes, how are the checkboxes aligned? vertically with the primary value?

Yep!

**Comment by bjornalm** [comment]
This one is needed for #2603

**Comment by bjornalm** [comment]
@dianatran18 Just to be clear. The height of the search row should be 40px? I ask because in the [list design spec](https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2601) it states that it should be 48px.

![image](https://user-images.githubusercontent.com/5167091/144869159-4b0f9aab-2b0c-455b-a2bc-a929510d1d7d.png)

And another related question. What should the focus state look like? I've made it fill the entire row while also removing the bottom gray line like this:
![image](https://user-images.githubusercontent.com/5167091/144869819-031d1d55-f77d-4dd0-b0b9-56b67fedc79d.png)

Is that correct?

**Comment by bjornalm** [comment]
@dianatran18 The pagination top border is a bit complicated since there are more scenarios than shown in this style audit. We also have cases where we do need a border:
![image](https://user-images.githubusercontent.com/5167091/145093093-ee0ddfff-7479-481b-b334-2069deae6b79.png)
And in this scenario I think it will add plenty of additional complexity to figure out when to show/hide the border for the pagination:
![image](https://user-images.githubusercontent.com/5167091/145093136-c4dfe1f7-7128-47b4-9b00-4621c1396557.png) 
I suggest we keep it visible for now.

**Comment by dianatran18** [comment]
> @dianatran18 Just to be clear. The height of the search row should be 40px? I ask because in the [list design spec](https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2601) it states that it should be 48px.
> 
> ![image](https://user-images.githubusercontent.com/5167091/144869159-4b0f9aab-2b0c-455b-a2bc-a929510d1d7d.png)
> 
> And another related question. What should the focus state look like? I've made it fill the entire row while also removing the bottom gray line like this: ![image](https://user-images.githubusercontent.com/5167091/144869819-031d1d55-f77d-4dd0-b0b9-56b67fedc79d.png)
> 
> Is that correct?

Ah yes sorry. Technically on the [style page](https://pages.github.ibm.com/ai-applications/design/components/list/style#row-size-variations) there are different row height variations. I believe in code today it's just 40px and tall? So what you have is right, the search height should match the other row heights. And yes the focus state is correct!

**Comment by dianatran18** [comment]
> @dianatran18 The pagination top border is a bit complicated since there are more scenarios than shown in this style audit. We also have cases where we do need a border: ![image](https://user-images.githubusercontent.com/5167091/145093093-ee0ddfff-7479-481b-b334-2069deae6b79.png) And in this scenario I think it will add plenty of additional complexity to figure out when to show/hide the border for the pagination: ![image](https://user-images.githubusercontent.com/5167091/145093136-c4dfe1f7-7128-47b4-9b00-4621c1396557.png) I suggest we keep it visible for now.

The top border on the pagination footer is fine, I was calling out the _extra_ border around the pagination container, shown here:
<img width="445" alt="Screen Shot 2021-12-08 at 9 55 54 AM" src="https://user-images.githubusercontent.com/43549567/145230095-85c1d354-234d-4fe0-93b3-d1532f17c057.png">

It looks like that was removed in your screenshots though?

**Comment by bjornalm** [comment]
> The top border on the pagination footer is fine, I was calling out the _extra_ border around the pagination container, shown here: <img alt="Screen Shot 2021-12-08 at 9 55 54 AM" width="445" src="https://user-images.githubusercontent.com/43549567/145230095-85c1d354-234d-4fe0-93b3-d1532f17c057.png">
> 
> It looks like that was removed in your screenshots though?

Yes, the extra borders are gone. Only the top border of the pagination container is kept, which could lead to this in some scenarios:
![image](https://user-images.githubusercontent.com/5167091/145233439-490d5301-d784-4af4-826b-cc217411b029.png)

**Comment by bjornalm** [comment]
In this scenario with tall rows and secondary values, how do we align the tags and overflow menus? 
![image](https://user-images.githubusercontent.com/5167091/145648010-a6293047-d4a2-4ac7-81a1-32fbd4cef541.png)

Do we align them in the middle of the row like in the screenshot, or do we align them with the top text (like the checkbox)?
