### ISSUE TITLE
[List] support async search

### ISSUE THREAD

**Issue by bjornalm** [carbon-design-system/carbon-addons-iot-react#3078]
### What package is this for?

- [ x] React
- [ ] Angular

### Summary

Since the list now as (rudimentary) functionality to load more items in an async matter we should also support async search. This is to some extent already supported but we probably need some UX improvements like triggering search on enter instead of key press. We also need a search loading indicator, not sure if the general list loading is sufficient or not.

**Additional context** Add any other context or screenshots about the feature
request here.

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon add-ons for Watson IoT is a collaborative system. We encourage teams to
build components and submit them for integration._

**Comment by JordanWSmith15** [comment]
@bjornalm  The general list loading is sufficient.
