### ISSUE TITLE
[ValueCard] Default FontSize changed from 42 to 18 to prevent truncation of text

### ISSUE THREAD

**Issue by eosineye1** [carbon-design-system/carbon-addons-iot-react#3090]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

ValueCard's default size is currently 42 which is quite large and leads to truncation of text. Customers can change the size of the font in the advance settings, but some have hundreds of cards on a dashboard. This would be an annoyance to the customer to have to change the font size of hundreds of cards just to be able to see the text in the value card.

### To Reproduce

1. Go to https://carbon-addons-iot-react.com/?path=/story/1-watson-iot-valuecard--small-long-no-units
2. ValueCard text is truncated after 10 letters for a size small card

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/carbon-design-system/carbon-addons-iot-react/tree/next/packages/react/examples/codesandbox

### Expected behavior

Default font size of Value Card should be 18.

### Environment/versions:

- OS: MacOS
- Browser:chrome
- `carbon-addons-iot-react` version: `v2.147.0-next.43`

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by JordanWSmith15** [comment]
@dianatran18 I believe this is working as designed? My assumption is that small value cards do not have smaller type, and should not be used with large strings.

**Comment by dianatran18** [comment]
Yes, you're correct @JordanWSmith15. Value cards are generally used display KPIs or metrics as a summary, and not large strings of text. The reason why we have one set size for the value is to not have varying sizes of text all over the page, especially if the value cards are adjacent to each other. 

For numeric values, we have guidance on how to abbreviate large numbers is space is limited, with the full value displaying in a tooltip: 
https://pages.github.ibm.com/ai-applications/design/content-guide/abbreviations-symbols/overview#abbreviating-words-related-to-numbers

**Comment by JordanWSmith15** [comment]
@eosineye1 I am going to invalidate this work item, as working-as-designed. However, keep in mind that there is an override property that allows you to change the type size to 18
<img width="751" alt="Screen Shot 2021-12-02 at 10 24 01 AM" src="https://user-images.githubusercontent.com/21066152/144451248-b2e645ca-74e5-484c-aea8-fbd7db450880.png">
.
