### ISSUE TITLE
[TableCard] Cannot filter on timestamp strings

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#3094]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

In the tableCard the TIMESTAMP type column filters do not work.

### To Reproduce

1. Go to TableCard story
2. Click on the column filter for a timestamp column
3. Type a partial string and notice that no records match this filter

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/carbon-design-system/carbon-addons-iot-react/tree/next/packages/react/examples/codesandbox

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by kevinsperrine** [comment]
@scottdickerson Was #3058 supposed to close this issue, or is this separate?

**Comment by kevinsperrine** [comment]
@EdmondCShaffer This was supposed to be closed by your other, PR #3058, right?

**Comment by kevinsperrine** [comment]
Closing as I believe #3058 fixed this. Please re-open if not.
