### ISSUE TITLE
Cannot see Id in JSON editor 

### ISSUE THREAD

**Issue by EdmondCShaffer** [carbon-design-system/carbon-addons-iot-react#3098]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug
User cannot see ID in JSON editor 

### To Reproduce

1. edit any dashboard
2. edit any card
3. Click JSON Editor
4. The json will not have the id field.

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/carbon-design-system/carbon-addons-iot-react/tree/next/packages/react/examples/codesandbox

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by JordanWSmith15** [comment]
@EdmondCShaffer Why is this needed? What is the impact to the user/application?

**Comment by JordanWSmith15** [comment]
This is already a customer facing issue for monitor team. 
Scenario: I am editing the dashboard in my editor of choice. I want to add a card or edit a card.
I use the gui to add a card or edit a card. I open the JSON editor to get the JSON for the new or altered card, so I can paste it into the full dashboard in my editor or choice.
If the id field is missing, I can't replace a card cleanly, or add the card without additional editing, which will be error prone.

**Comment by kevinsperrine** [comment]
Fixed by #3097
