### ISSUE TITLE
[Tooltip] Remains open when we have links/buttons in tooltip content

### ISSUE THREAD

**Issue by meshack-chintagunta** [carbon-design-system/carbon-addons-iot-react#3101]
### What package is this for?

Carbon Components React v7.48.1

### Describe the bug

We are able to access the content in tooltip using tab but when we try to come out of using tab is not coming out from tooltip message as it keep on rotating between link and button in tooltip, even esc key is also not working in that case. Tooktip remains open.

### To Reproduce

https://react.carbondesignsystem.com/?path=/story/components-tooltip--render-custom-icon
Assess the above link:
Click on tooltip try using tab to access content, we can observe that focus is keep on shifting between button and link in the tooltip never comes out. Even though when we use esc key.

### Expected behavior

Focus should come of tooltip and is should be closed.

### Environment/versions:

- OS: MacOS, 
- Browser: chrome Version 96.0.4664.55
- `carbon-addons-iot-react` v7.48.1

### Additional context

<img width="845" alt="image" src="https://user-images.githubusercontent.com/83823919/144444163-27ec27bd-15de-4751-8fb5-df910fc9dc6d.png">

**Comment by JordanWSmith15** [comment]
Blocks https://jsw.ibm.com/browse/GRAPHITE-43050

**Comment by kevinsperrine** [comment]
An issue is opened on the carbon side already. https://github.com/carbon-design-system/carbon/issues/10204
