### ISSUE TITLE
[List] Drag preview not covering full width for large rows

### ISSUE THREAD

**Issue by bjornalm** [carbon-design-system/carbon-addons-iot-react#3147]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug
The drag preview is not covering full width for large rows. This is true for all components using the List.

### To Reproduce

1. Go to https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-hierarchylist--with-nested-reorder
2. Enable knob isLargeRow
3. Drag an item 
4. Notice how the Drag preview (the blue line) and Drop target indications (blue border around other items that accepts drop) are not full width

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/carbon-design-system/carbon-addons-iot-react/tree/next/packages/react/examples/codesandbox

### Expected behavior

Blue line is full width

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Additional context

Screenshot from TableColumnCustomizationModal showing the same problem:
![image](https://user-images.githubusercontent.com/5167091/146200737-f29e11f8-43b0-4581-b2eb-9c995190c398.png)

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by bjornalm** [comment]
@dianatran18 Just verifying with you that this is a bug right?

**Comment by dianatran18** [comment]
Yes that looks like a bug. It should span the full width like the other single row examples.
