### ISSUE TITLE
[carbon-charts] upgrade to version 0.53.5 or later

### ISSUE THREAD

**Issue by navjeets** [carbon-design-system/carbon-addons-iot-react#3169]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

Upgrade carbon-charts to version 0.53.5 or later.

**Additional context** 

Needed for Health story -> https://github.ibm.com/maximo/Asset-Health-Insight/issues/8035

### Specific timeline issues / requests

Needed for Health 8.5 release (Feb).

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon add-ons for Watson IoT is a collaborative system. We encourage teams to
build components and submit them for integration._

**Comment by davidicus** [comment]
@JordanWSmith15 FYI
