### ISSUE TITLE
[Repo] Align story titles to the design site. 

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#3175]
Our component names do not always match the names used in the design site spec. While we can not easily change component names we can change the titles of the stories to match. 
`Table -> DataTable`
This issue should update those title names to match and add documentation to the readme explaining how to import the actual name.

**Comment by Ritu-Thakur** [comment]
Compared components on PAL storybook:
https://next.carbon-addons-iot-react.com/?path=/story/0-overview-getting-started--about-storybook
with carbon design spec:
https://react.carbondesignsystem.com/?path=/story/getting-started--using-the-storybook


Looks like there are 4 components which need title change:

@davidicus can you please confirm if my understanding is correct?

&nbsp;| PAL   components | Corresponding Carbon components | Different title?
-- | -- | -- | --
1 | AccordionItemDefer |   |  
2 | AddCard |   |  
3 | BarChartCard |   |  
4 | BreadCrumb | BreadCrumb |  
5 | Button | Button |  
6 | Card |   |  
7 | CardCodeEditor |   |  
8 | ComboBox | ComboBox |  
9 | ComposedModal | ComposedModal |  
10 | ComposedStructuredList |   |  
11 | Dashboard |   |  
12 | Dashboard Grid |   |  
13 | Dashboard Header |   |  
14 | DateTime Picker | DatePicker | Y
15 | Dropdown | Dropdown |  
16 | EditPage |   |  
17 | EmptyState |   |  
18 | FileDrop | FileUploader | Y
19 | FilterTags |   |  
20 | FlyoutMenu |   |  
21 | GaugeCard |   |  
22 | Header |   |  
23 | Hero |   |  
24 | HierarachyList |   |  
25 | HotspotContent |   |  
26 | IconSwitch |   |  
27 | ImageCard |   |  
28 | ImageGalleryModal |   |  
29 | ImageHotspots |   |  
30 | List |   |  
31 | ListCard |   |  
32 | ListItem |   |  
33 | NavigationBar |   |  
34 | OverflowMenu | OverflowMenu |  
35 | PageHero |   |  
36 | PageTitleBar |   |  
37 | PageWizard | PaginationNav | ?
38 | PieChartCard |   |  
39 | ProgressBar |   |  
40 | ProgressIndicator | ProgressIndicator |  
41 | ResourceList |   |  
42 | SelectUsersModal | Select | ?
43 | SideNav |   |  
44 | SimpleList |   |  
45 | SimplePagination |   |  
46 | SuiteHeader |   |  
47 | Table | DataTable | Y
48 | TableCard |   |  
49 | TableDetailWizard |   |  
50 | TearSheet |   |  
51 | TileCatalog |   |  
52 | TileCatalogNew |   |  
53 | TileGallery |   |  
54 | TimePickerSpinner | TimePicker | Y
55 | TimeSeriesCard |   |  
56 | Tooltip | Tooltip |  
57 | ValueCard |   |  
58 | WizardInline |   |  
59 | WizardModal |   |

**Comment by Ritu-Thakur** [comment]
Above comparison is wrong, we have to compare components on PAL storybook:
https://next.carbon-addons-iot-react.com/?path=/story/0-overview-getting-started--about-storybook
with the Component section under :
https://pages.github.ibm.com/ai-applications/design/


I have setup meeting with Diana to discuss more about this issue.

**Comment by Ritu-Thakur** [comment]
&nbsp;| PAL Stories | Design   Guidelines | Different Title/Folder? | Comments
-- | -- | -- | -- | --
1 | AccordionItemDefer |   |   |  
2 | AddCard | Card | Y | SubItem   of Card
3 | BarChartCard | Card | Y | SubItem of Card
4 | BreadCrumb |   |   |  
5 | Button | Buttons | Y | SubItem of Buttons
6 | Card | Card | N |  
7 | CardCodeEditor |   |   | SubItem of Card?
8 | ComboBox | DropDown | Y | SubItem   of dropdown
9 | ComposedModal |   |   |  
10 | ComposedStructuredList |   |   |  
11 | Dashboard |   |   |  
12 | Dashboard Grid |   |   |  
13 | Dashboard   Header |   |   |  
14 | DateTime   Picker | Date   time range selector | Y |  
15 | Dropdown | Dropdown | N |  
16 | EditPage |   |   |  
17 | EmptyState | Empty states | Y |  
18 | FileDrop |   |   |  
19 | FilterTags |   |   |  
20 | FlyoutMenu | Menus | Y | SubItem   of Menus
21 | GaugeCard | Card | Y | SubItem of Card
22 | Header | UI   Shell | Y | SubItem   of UI shell
23 | Hero |   |   |  
24 | HierarachyList | List | Y | Subitem   of List
25 | HotspotContent |   |   |  
26 | IconSwitch | Icon   Content switcher | Y |  
27 | ImageCard | Card | Y | SubItem of Card
28 | ImageGalleryModal |   |   |  
29 | ImageHotspots | Schematic diagram | Y |  
30 | List | List | N |  
31 | ListCard | Card | Y | SubItem of Card
32 | ListItem | List | Y | SubItem   of List
33 | NavigationBar | Tabs? | ? | Is it part of Tabs?
34 | OverflowMenu | Menus | Y | SubItem   of Menus
35 | PageHero |   |   |  
36 | PageTitleBar | Page   header | Y |  
37 | PageWizard | ProgressIndicator | Y |  
38 | PieChartCard | Card | Y | SubItem   of card
39 | ProgressBar |   |   |  
40 | ProgressIndicator | Progress   Indicator | Y |  
41 | ResourceList | List |   | SubItem of List
42 | SelectUsersModal |   |   |  
43 | SideNav | UI Shell | Y | Subitem of UI shell
44 | SimpleList | List | Y | Subitem   of List
45 | SimplePagination | Pagination | Y | SubItem of Pagination
46 | SuiteHeader | UI   Shell | Y | SubItem   of UI Shell
47 | Table | Data Table | Y |  
48 | TableCard | Card | Y | SubItem   of Card
49 | TableDetailWizard |   |   |  
50 | TearSheet | TearSheet | N |  
51 | TileCatalog |   |   |  
52 | TileCatalogNew |   |   |  
53 | TileGallery |   |   |  
54 | TimePickerSpinner | Date   time range selector? | Y | Subitem   of Date timeRangeselector?
55 | TimeSeriesCard | Card | Y | SubItem of Card
56 | Tooltip |   |   |  
57 | ValueCard | Card | Y | SubItem of Card
58 | WizardInline |   |   |  
59 | WizardModal |   |   |

**Comment by dianatran18** [comment]
@Ritu-Thakur I filled this out as much as I could, and included the Experimental items. @davidicus I grouped any deprecated ones under a `Deprecated` folder but let me know if you want to handle those differently. 

&nbsp;| PAL Stories | Design   Guidelines | Different Title/Folder? | Comments
-- | -- | -- | -- | --
1 | AccordionItemDefer | Accordion | Y  | _Not in the PAL but can have a folder_
2 | AddCard | Card | Y | SubItem of Card
3 | BarChartCard | Card | Y | SubItem of Card
4 | BreadCrumb |  Breadcrumb | Y  |  _Not in the PAL but can have a folder. No capital C in name._
5 | Button | Buttons | Y | SubItem of Buttons
6 | Card | Card | N |  
7 | CardCodeEditor |   |  Y | SubItem of Card
8 | ComboBox | DropDown | Y | SubItem   of dropdown
9 | ComposedModal |  Modal | Y  |  _Not in the PAL but can have a folder_
10 | 🚫 ComposedStructuredList |  Deprecated? | Y  |  Subitem of Deprecated
11 | 🚫 Dashboard | Deprecated?  | Y  |  Subitem of Deprecated
12 | Dashboard Grid | Dashboard  | Y  |  
13 | 🚫 Dashboard   Header | Deprecated?  | Y  |  Subitem of Deprecated
14 | DateTime   Picker | Date   time range selector | Y |  
15 | Dropdown | Dropdown | N |  
16 | 🚫 EditPage |  Deprecated? | Y  | Subitem of Deprecated  
17 | EmptyState | Empty states | Y |  
18 | FileDrop |  File uploader | Y  |  _Not in the PAL but can have a folder_
19 | FilterTags |  Tags |  Y |  
20 | FlyoutMenu | Menus | Y | SubItem   of Menus
21 | GaugeCard | Card | Y | SubItem of Card
22 | Header | UI   Shell | Y | SubItem   of UI shell
23 | 🚫 Hero | Deprecated?  | Y  | Subitem of Deprecated  
24 | HierarachyList | List | Y | Subitem   of List
25 | HotspotContent | Schematic diagram?  | Y  |  Need to follow up on this one
26 | IconSwitch | Icon  content switcher | Y |  
27 | ImageCard | Card | Y | SubItem of Card
28 | ImageGalleryModal | Modal  | Y  |  Subitem of modal
29 | ImageHotspots | Schematic diagram? | Y |  Need to follow up on this one
30 | List | List | N |  
31 | ListCard | Card | Y | SubItem of Card
32 | ListItem | List | Y | SubItem   of List
33 | NavigationBar | Page header | ? | Not sure if teams are using this, but we'll move it part of Page header for now.
34 | OverflowMenu | Menus | Y | SubItem   of Menus
35 | 🚫 PageHero |  Deprecated? | Y  |   Subitem of Deprecated  
36 | PageTitleBar | Page   header | Y |  
37 | PageWizard | ProgressIndicator | Y |  
38 | PieChartCard | Card | Y | SubItem   of card
39 | ProgressBar | Progress bar  |   |  The design site will eventually have a Progress bar component to match 
40 | ProgressIndicator | Progress   Indicator | Y |  
41 | ResourceList | List |   | SubItem of List
42 | SelectUsersModal | Modal  | Y  |  
43 | SideNav | UI Shell | Y | Subitem of UI shell
44 | SimpleList | List | Y | Subitem   of List
45 | SimplePagination | Pagination | Y | SubItem of Pagination
46 | SuiteHeader | UI   Shell | Y | SubItem   of UI Shell
47 | Table | Data Table | Y |  
48 | TableCard | Card | Y | SubItem   of Card
49 | TableDetailWizard |   |   |  Maybe this can go under Progress indicator?
50 | TearSheet | TearSheet | N |  
51 | TileCatalog | Catalog/Marketplace  | Y  |  This is something we removed from the design site right now, but we can still create a folder for it here 
52 | TileCatalogNew | Catalog/Marketplace  | Y  |  
53 | TileGallery | Catalog/Marketplace  | Y  |  
54 | TimePickerSpinner | Date   time range selector | Y | Subitem   of Date timeRangeselector
55 | TimeSeriesCard | Card | Y | SubItem of Card
56 | Tooltip | Tooltip  | N  |  
57 | ValueCard | Card | Y | SubItem of Card
58 | 🚫 WizardInline | Deprecated?  | Y  | Subitem of Deprecated  
59 | WizardModal | Progress indicator  | Y  | Subitem of Progress indicator  
60 | ☢️ Card editor | Dashboard | Y | Subitem of Dashboard
61 | ☢️ ColorDropdown | Dropdown | Y | Subitem of Dropdown
62 | ☢️ ComboChartCard | Card | Y | Subitem of Card
63 | ☢️ DashboardEditor | Dashboard | Y | Subitem of Dashboard 
64 | ☢️ DateTimePickerV2 | Date time range selector | Y | Subitem of Date time range selector
65 | ☢️ HotSpotEditorModal | Schematic diagram? | Y | Need to follow up on this one
66 | ☢️ IconDropdown | Dropdown | Y | Subitem of Dropdown
67 | ☢️  ListBuilder | List builder | N | 
68 | ☢️ MapCard | Card | Y | Subitem of Card
69 | ☢️ MenuButton | Buttons | Y | Subitem of Buttons
70 | ☢️ RuleBuilder | Rule builder | N |
71 | ☢️ SimpleIconDropdown | Dropdown | Y | Subitem of Dropdown

**Comment by davidicus** [comment]
@Ritu-Thakur, FYI, We can skip the Table stories as these are being worked in another issue

**Comment by Ritu-Thakur** [comment]
@dianatran18 
Are the experimental storybooks going under "1 - Watson IoT" ?

**Comment by dianatran18** [comment]
> Are the experimental storybooks going under "1 - Watson IoT" ?

@davidicus did we say we wanted to move all of the experimental items up, or just the ones that are stable that don't need to be in the experimental section anymore?

> Are we going to have a folder structure of Catalog/Marketplace for these:
> TileCatalog
> TileCatalogNew
> TileGallery

Yes

**Comment by dianatran18** [comment]
<img width="185" alt="Screen Shot 2022-02-16 at 1 07 04 PM" src="https://user-images.githubusercontent.com/43549567/154328124-a446e9b3-a758-4cce-ba7c-ea069ab68945.png">

@davidicus would it also be a breaking change to update these titles in the storybook?
We're not Watson IoT anymore, but I guess that's something we'd have to change across the board, like in the About section too.

<img width="741" alt="Screen Shot 2022-02-16 at 1 07 49 PM" src="https://user-images.githubusercontent.com/43549567/154328271-2f49dceb-4c63-4781-8209-9935b81313ea.png">

**Comment by davidicus** [comment]
@dianatran18 yes. we should open an issue to correct the verbiage mentioning Watson. Let's leave the experimental components now and tackle those in a separate issue. For those I want to look at the last changes to those components, test levels, etc to be sure they are ready to be removed from experimental.

**Comment by Ritu-Thakur** [comment]
@dianatran18 I have fixed all titles but experimental and PR is ready to review . Can you please verify if they look ok - https://deploy-preview-3291--carbon-addons-iot-react.netlify.app/?path=/story/0-overview-getting-started--about-storybook ?
