### ISSUE TITLE
[Table] Filter tag using wrong color on hover

### ISSUE THREAD

**Issue by ben-bacon** [carbon-design-system/carbon-addons-iot-react#3189]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table-statefultable--stateful-table-with-advanced-filters

The tags used for table filters are using the wrong color token on hover, instead of [Carbon's default styling](https://react.carbondesignsystem.com/?path=/story/components-tag--filter) (select blue tag in knob section).

Proposed styling:
<img width="263" alt="Screen Shot 2022-01-13 at 3 02 56 PM" src="https://user-images.githubusercontent.com/52676199/149408710-d47ab9f2-6a9c-4cbd-afc2-f3b718ae8035.png">

**Comment by Ritu-Thakur** [comment]
@ben-bacon 
Hi Ben,
The hover text which says "Clear Filter" has black background in the above summary screenshot. But the Carbon default styling has grey background:
<img width="758" alt="image" src="https://user-images.githubusercontent.com/30444945/151066827-b3b6f758-8f8d-4aca-a100-032dcf475611.png">

Which background should I use for "Clear Filter" ?

**Comment by ben-bacon** [comment]
@Ritu-Thakur Sorry, my issue was not clear. The issue is the hover state over the close icon is incorrect in the iot-addons library. see below,

**iot-addons (incorrect hover state styling over close icon):**
<img width="284" alt="Screen Shot 2022-01-26 at 9 56 06 AM" src="https://user-images.githubusercontent.com/52676199/151198897-d4520c71-7b51-4f5e-9266-77e32f20b64c.png">

**Carbon (the proposed styling for hover state over close icon):**
<img width="157" alt="Screen Shot 2022-01-26 at 9 56 23 AM" src="https://user-images.githubusercontent.com/52676199/151199018-0039b707-4e94-4cc3-8560-8b4b974dabd0.png">

The hover state for the close icon in the iot-addons library is #c6c6c6, but it should be blue30 (#a6c8ff)

Now that I look at it more closely, the color of the text is incorrect in the iot-addons library as well. The text and icon, including in the hover state, should be blue80 (#002d9c).

**Comment by Ritu-Thakur** [comment]
@ben-bacon Thanks for explaining it more. Yes I noticed the close button's background on hover yesterday and tried to fix it.
I'll fix text/icon too.
