### ISSUE TITLE
[Table] Toolbar action's overflow menu shows items wrapped.

### ISSUE THREAD

**Issue by kalyanixraut** [carbon-design-system/carbon-addons-iot-react#3198]
### What package is this for?

- [ x] React
- [ ] Angular

### Describe the bug

1. The toolbar action’s overflow menu items wrap by default making the text to overflow. 
2. Also, icon size changes automatically with longer texts.
3. If all items in overflow menu are hidden (not disabled but hidden), then the overflow icon(3 dots) should also be hidden. Currently there's no way to hide the overflow menu.

### To Reproduce

![image](https://user-images.githubusercontent.com/22093326/149952884-e2603edb-0250-44e3-b881-ee8b3579e697.png)

https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table-table--with-filters

### Expected behavior

1. Longer menu item texts should not wrap by default, instead should be displayed with ellipsis and show a tooltip on-hover.
2. icon size should remain unchanged.
3. Hide overflow icon(3 dots) if all items in overflow menu are hidden

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.147.0`]

**Comment by JordanWSmith15** [comment]
@davidicus  Need this fix in the 8.7 branch of PAL

**Comment by kevinsperrine** [comment]
Closed by #3203
