### ISSUE TITLE
Modal missing data text an bee alignment issue 

### ISSUE THREAD

**Issue by EdmondCShaffer** [carbon-design-system/carbon-addons-iot-react#3199]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

Bee and Text misaligned when no data is present 

### To Reproduce

1. Go to 'Monitor tab'
2. Click on 'Alerts'
3. Click on 'View all'
4. Click on 'Manage Views'
5. Uncheck 'Display public view'

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/carbon-design-system/carbon-addons-iot-react/tree/next/packages/react/examples/codesandbox

### Expected behavior
Bee should have space between the line And text should be centered under the bee.

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Additional context
![image](https://user-images.githubusercontent.com/38738726/149957563-386aaec1-da31-42fd-b876-96d2ff65ac83.png)

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by JordanWSmith15** [comment]
@EdmondCShaffer Is this needed for 8.7?

**Comment by kevinsperrine** [comment]
I'm having trouble re-creating this one. I don't know what system these reproduction instructions were written for, but this looks like the manage views modal for save table views. However, in next, we show the "empty state" in this situation not the bee.

1. go to [this story](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table-table--table-example-with-create-save-views)
2. Click the "eye" icon for the view management dropdown
3. Click "Manage views"
4. Uncheck "Display public views"
5. Delete the single private view
6. see "Empty state"

![Screen Shot 2022-01-24 at 10 19 19 AM](https://user-images.githubusercontent.com/609466/150810964-247f6917-a463-47f5-b114-1ea3e6eda4ae.png)

**Comment by davidicus** [comment]
@EdmondCShaffer Bump for a response to @kevinsperrine question? Will move over to next sprint.

**Comment by EdmondCShaffer** [comment]
I have fixed this issue in Monitor no longer an issue closing
