### ISSUE TITLE
[Table]  Hidden property is not available for rowActions.

### ISSUE THREAD

**Issue by kalyanixraut** [carbon-design-system/carbon-addons-iot-react#3208]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

rowAction(list of actions visible on row hover) currently has only disabled prop, but no hidden prop is exposed

### To Reproduce

Following are the rowAction props. Since 'hidden' prop is missing in the list, a row-action cannot be hidden.

![image](https://user-images.githubusercontent.com/22093326/150305222-6110591e-2d61-4aac-b437-ff7bf4da8c51.png)

### Expected behavior

Expecting 'hidden' prop be made available so that buttons/overflowMenu items defined in rowAction can be hidden when needed.

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.147.0`]

**Comment by davidicus** [comment]
@bjornalm is this issue now closed by #3238

**Comment by bjornalm** [comment]
> @bjornalm is this issue now closed by #3238

Yes, sorry for late reply.
