### ISSUE TITLE
[Progress Bar] New component

### ISSUE THREAD

**Issue by dianatran18** [carbon-design-system/carbon-addons-iot-react#3215]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

This is a component that is needed for Maximo Scheduler, and can be reused for other use cases (I will add in other variations at a later time)

Carbon has one in [experimental](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-progressbar--progress-bar) currently, and Carbon Charts has something similar called [meter](https://charts.carbondesignsystem.com/?path=/story/simple-charts-meter--meter-chart-with-statuses). This component is similar, but the positioning of text is a little different. If we can use one of the existing ones as a base that would be great!

#### Specs

![progress-bar-spec](https://user-images.githubusercontent.com/43549567/150436890-ffdc25ff-2bd0-4ab2-8680-299ec84e4ae2.png)

#### Colors

Background color of the progress bar (when it is not filled): $ui-02

General/default color: Blue 60

Colors needed for Maximo Scheduler:
- Under 80%: Yellow 30 fill / Yellow 50 stroke (see extended yellow palette [here](https://www.carbondesignsystem.com/patterns/status-indicator-pattern/#status-palette))
- 80–90%: Green 20 fill / Green 50 stroke
- 90–95%: Green 30 fill / Green 50 stroke
- 95–100%: Green 40 fill / Green 50 stroke
- Over 100%: Red 60 fill / no stroke
_(Note: the strokes are included for color fills that are below 50 in order to pass accessibility)_

### Specific timeline issues / requests

I believe this is for Maximo 8.8

**Comment by JordanWSmith15** [comment]
Colors should be fully customizable by consumers. I have use cases for other colors appearing already.

**Comment by JordanWSmith15** [comment]
This should likely borrow from the `[value card's model for thresholds](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-valuecard--small-wide-thresholds-string)`, rather than creating a new approach of something very similar.

**Comment by dianatran18** [comment]
> This should likely borrow from the [value card's model for thresholds](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-valuecard--small-wide-thresholds-string), rather than creating a new approach of something very similar.

@JordanWSmith15 What part are you specifically referencing in the value cards, the status icon?

**Comment by JordanWSmith15** [comment]
@dianatran18 I am referring to the architecture/logic of the thresholds. The thresholds behave very similarly, and any developer who uses thresholds in the Value Card would easily understand this component.
I see four possible routes:
1. Build it custom
2. Pull in and extend [Graphite's current progress bar](https://pages.github.ibm.com/maximo-app-framework/graphite/main/react/storybook/?path=/story/components-%F0%9F%96%A5-%F0%9F%91%86-progress-bar--progress-bar-predefined-download-label).
3. Pull in and extend [Carbon's progress bar ](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-progressbar--progress-bar&knob-Collapsed%20icon%20text%20(tileCollapsedIconText)=Expand&knob-Collapsed%20icon%20text%20(tileExpandedIconText)=Collapse&knob-Form%20item%20(name%20in%20%3CTileGroup%3E)=tile-group&knob-Form%20item%20name%20(name%20in%20%3CRadioTile%3E)=tiles&knob-Form%20validation%20UI%20content%20(invalidText%20in%20%3CTimePicker%3E)=A%20valid%20value%20is%20required&knob-Href%20for%20clicable%20UI%20(href)=#&knob-Label%20text%20(labelText%20in%20%3CTimePicker%3E)=Select%20a%20time&knob-Label%20text%20(labelText%20in%20%3CTimePickerSelect%3E)=Please%20select&knob-Label%20text%20(labelText)=Checkbox%20label&knob-Max%20height%20(tileMaxHeight)=0&knob-Maximum%20length%20(maxLength%20in%20%3CTimePicker%3E)=5&knob-No%20label%20(hideLabel%20in%20%3CTimePickerSelect%3E)=true&knob-Plceholder%20text%20(placeholder%20in%20%3CTimePicker%3E)=hh:mm&knob-Regular%20expression%20for%20the%20value%20(pattern%20in%20%3CTimePicker%3E)=(1[012]|[1-9]):[0-5][0-9](\s)?(?i)&knob-Tab%20index%20(tabIndex)=0&knob-The%20title%20(title)=Section%201%20title&knob-Trigger%20icon%20description%20(iconDescription%20in%20%3CTimePickerSelect%3E)=open%20list%20of%20options)
4. Pull in and extend [Carbon Chart's meter chart](https://charts.carbondesignsystem.com/react/?path=/story/simple-charts-meter--meter-chart-with-statuses)

**Comment by JordanWSmith15** [comment]
Initial implementation in Maximo (Graphite) Scheduler:
https://ibm.invisionapp.com/share/ADO1LJGMU6Q#/320158817_Resource_Leveling_
<img width="1287" alt="Resource-Leveling" src="https://user-images.githubusercontent.com/21066152/151169275-f87c12f8-f290-4f93-8fb3-89c48dca877e.png">
