### ISSUE TITLE
[SuiteHeader] Application Side panel items are tab-able when panel is closed

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#3217]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

When application panel is open on the right, menu items are still tab-able, causing user to lose focus.

### To Reproduce

1. Go to [SuiteHeader story](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-suiteheader--header-with-extra-content)
2. Open dev panel and change styles so panel is visible
3. start tabbing
4. Notice that focus goes into side panel even when "closed"

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/carbon-design-system/carbon-addons-iot-react/tree/next/packages/react/examples/codesandbox

### Expected behavior

Items in closed menu should not be reachable when closed

**Comment by kevinsperrine** [comment]
Closed by #3219
