### ISSUE TITLE
[Table] Filterable column header padding adjustment

### ISSUE THREAD

**Issue by ben-bacon** [carbon-design-system/carbon-addons-iot-react#3231]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

The padding around the filterable column headers has been adjusted to try and give the most space possible to the text field, while at the same time remaining visually separated from column-to-column. This has also been adjusted with better consideration to filterable right-aligned columns and selectable + filterable columns.

#### Proposed styling
<img width="1189" alt="Screen Shot 2022-01-26 at 10 44 41 AM" src="https://user-images.githubusercontent.com/52676199/151207528-d2e84e9e-e640-40d7-b06c-5c7f1cdb61b0.png">

#### Red lines & interaction states
![image](https://user-images.githubusercontent.com/52676199/151207382-85fdb229-07c3-42dd-b579-5e4762685646.png)

![image](https://user-images.githubusercontent.com/52676199/151207398-3ed60f97-ba3b-4df9-b89a-559190f67264.png)

**Comment by JordanWSmith15** [comment]
This is a good one to do. It is used almost everywhere and has always looked a bit sloppy.

**Comment by bjornalm** [comment]
The design shows `short` and `default` column heights but the PAL Table component currently has the sizes `xs`, `sm`, `md`, `lg` and `xl`. Do we need a design for all the sizes?

Example xs:
![image](https://user-images.githubusercontent.com/5167091/152963902-5770f782-98d6-4db9-ab60-3513a51fd5f2.png)
 
Example  xl:
![image](https://user-images.githubusercontent.com/5167091/152963985-b8280afb-a98e-4037-bb1a-e40e253812b8.png)

The design shows left and right alignment but the Table also support text alignment `center`. Do we need to include that in the design?

![image](https://user-images.githubusercontent.com/5167091/152970241-427f94fc-6838-44de-ad6c-e43878c6af29.png)


If multisort is active here will be an overflow button in the column header. I guess we should take that into consideration as well, what padding, what alignment etc? There is also the resize handle to consider:

![image](https://user-images.githubusercontent.com/5167091/152960542-75c2e7cc-98b3-492f-b449-a90fdf695f4b.png)

And there is yet another variable here which is the column grouping with white separators between the columns, how should that look?

![image](https://user-images.githubusercontent.com/5167091/152970667-0c143cdc-1f1b-4970-a48f-69c4db950171.png)


All in all the column headers can get very crowded and complex and the developer implementing this issue needs to be aware of the all the different scenarios, including when the columns are all dynamically resized.

**Comment by JordanWSmith15** [comment]
@ben-bacon Please see above

**Comment by ben-bacon** [comment]
@bjornalm Thanks for linking some more instances! Here are my thoughts:

> Do we need a design for all the sizes?

No, I think we should just support the sizes listed in the original post for now, those map to Carbon sizes. That would be `lg` and `sm` variants in the Watson IoT nomenclature. 

> the Table also supports text alignment center. Do we need to include that in the design?

No, center-aligned columns should follow the [guidance](https://pages.github.ibm.com/ai-applications/design/components/datatable/columnalignment#icon-only-columns) reserving them for icon-only rows.

> If multisort is active there will be an overflow button in the column header. I guess we should take that into consideration as well, what padding, what alignment etc?

The column header text should follow [truncation guidance](https://pages.github.ibm.com/ai-applications/design/components/datatable/general#truncating-and-wrapping-column-headers) for column headers with icon buttons. The "text box" should be the element that gets smaller, while retaining it's original element boundaries, when more icon buttons are present. 

> How should the different filters react when the column is resized

Interesting issue here, if we're constrained to the inherited max width then that is fine. It looks a little odd, but it is usable. I think preferably the dropdown/input width is tied to the width of the column, but that is just for visual fit and finish's sake, and does not add a considerable amount of usability.

> And there is yet another variable here which is the column grouping with white separators between the columns, how should that look?

With the added 4px padding outside of the column filter, the column grouping separator should fit between the adjoining filter inputs.

<img width="1088" alt="Screen Shot 2022-02-14 at 11 41 27 AM" src="https://user-images.githubusercontent.com/52676199/153917394-41b1271a-a543-415d-8fd6-ce1391ca19c0.png">


If nothing is being broken but the column filter as it is now, I don't _think_ this update will exacerbate any issues as it decreases the width of the filter input and only adds vertical padding below the input. But let me know if that line of thinking is wrong and we can iron out any budding issues.

**Comment by bjornalm** [comment]
@ben-bacon Thanks for clarifying. 

- About the sizes, should we not open an issue to have the table row sizes aligned with carbon? I think the difference will be a reoccurring source of confusion.

-About resizing, how about a min size? Should we allow this, e.g. only the chevron is visible due to the limited space:
![image](https://user-images.githubusercontent.com/5167091/154254096-08248421-53bf-427d-b937-291ba1094b64.png)

**Comment by ben-bacon** [comment]
@bjornalm I agree about the confusion part but I think that depends on how many teams we have using the bespoke sizes. Do we have any insight on that? Carbon is also moving to a new [nomenclature and property sizing in v11](https://v11.carbondesignsystem.com/migrating/guide/develop#component-api) - I'm unsure if the data table will have every size or just the ones they have now. They have already updated the names od the sizes they have now [here](https://react.carbondesignsystem.com/?path=/story/components-datatable-basic--default-lg). But when v11 happens we should align IoT's row sizes with their naming and sizing. 

On resizing, no, we should always try to show some of the column's content. Is there a minimum size inherited from the carbon component?

**Comment by bjornalm** [comment]
> @bjornalm I agree about the confusion part but I think that depends on how many teams we have using the bespoke sizes. Do we have any insight on that? Carbon is also moving to a new [nomenclature and property sizing in v11](https://v11.carbondesignsystem.com/migrating/guide/develop#component-api) - I'm unsure if the data table will have every size or just the ones they have now. They have already updated the names od the sizes they have now [here](https://react.carbondesignsystem.com/?path=/story/components-datatable-basic--default-lg). But when v11 happens we should align IoT's row sizes with their naming and sizing.
> 
@davidicus do you know?

> On resizing, no, we should always try to show some of the column's content. Is there a minimum size inherited from the carbon component?

No I don't think so, but we have a min-width for the columns in PAL. Perhaps we should increase the min column width if the table is filterable, so that something from the filter value is always visible?

**Comment by davidicus** [comment]
@bjornalm I unfortunately do not have any data of prop usage.

**Comment by bjornalm** [comment]
@davidicus FYI, created a new feature request to increase the min width when filtering as suggested above
https://github.com/carbon-design-system/carbon-addons-iot-react/issues/3387
