### ISSUE TITLE
[Table] Adjust padding on empty state placement

### ISSUE THREAD

**Issue by ben-bacon** [carbon-design-system/carbon-addons-iot-react#3236]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

In the [current implementation](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table-table--with-table-states) of an empty state of a table, adjust the left padding of the components to align with the [table empty state guidance ](https://pages.github.ibm.com/ai-applications/design/components/datatable/emptystates/#empty-state-placement).

#### Current alignment:
<img width="1775" alt="Screen Shot 2022-01-26 at 3 02 34 PM" src="https://user-images.githubusercontent.com/52676199/151246656-c87265c3-2008-4c2b-9e1e-d9be5ac89c9c.png">

#### Proposed alignment:
<img width="1775" alt="Screen Shot 2022-01-26 at 2 17 45 PM" src="https://user-images.githubusercontent.com/52676199/151245448-da977244-bddc-4335-b510-cbfe45fac2ff.png">

**Comment by ben-bacon** [comment]
large default breakpoint - with grid overlay<img width="1100" alt="Screen Shot 2022-02-03 at 2 47 04 PM" src="https://user-images.githubusercontent.com/52676199/152426308-5895af0c-3b02-4573-b090-4f223296b529.png">
Large default breakpoint - without grid overlay<img width="1102" alt="Screen Shot 2022-02-03 at 2 47 23 PM" src="https://user-images.githubusercontent.com/52676199/152426323-47ef0a78-0dcf-4663-85e4-3988b12c17b6.png">

Looks alright here, I could not get it to respond to my browser size in the storybook to test the smallest "large" breakpoint (673px) so I mocked it up for a test. 

---
Smallest lg breakpoint - with grid overlay
<img width="630" alt="Screen Shot 2022-02-03 at 3 06 35 PM" src="https://user-images.githubusercontent.com/52676199/152428735-1db69675-533c-41c8-9118-156ea0472e49.png">


Smallest lg breakpoint - without grid overlay 
![image](https://user-images.githubusercontent.com/52676199/152428463-21a5a505-8956-4750-9cee-c2e6b3c43fbc.png)

**Comment by davidicus** [comment]
@dianatran18 Didn't Carbon state that the grid was not intended for a components internal layout, only for its placement on a page?
