### ISSUE TITLE
[ComponentName] bug_title

### ISSUE THREAD

**Issue by msperli** [carbon-design-system/carbon-addons-iot-react#3243]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

If you manage views and in the modal uncheck “display public views”, close the modal, then open up manage views again, it stays unchecked but public views are show.

https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table-statefultable--stateful-example-with-create-save-views

### To Reproduce

1. Go to Manage views
2. uncheck "display public view"
3. close modal
4. open mange views again

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/carbon-design-system/carbon-addons-iot-react/tree/next/packages/react/examples/codesandbox

### Expected behavior

The list would follow whatever the checkmark says

### Environment/versions:

- OS: Mac
- Browser: Firefox
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Additional context

![image](https://user-images.githubusercontent.com/71150828/151854666-02f83e0e-cf15-432e-9497-9eeb106ab703.png)

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by bjornalm** [comment]
Will be solved by https://github.com/carbon-design-system/carbon-addons-iot-react/issues/3234

**Comment by msperli** [comment]
> Will be solved by #3234 This is a bug in the Storybook story and not the actual component.

Ok thanks. 
@dianatran18 Asked me to log this one
