### ISSUE TITLE
[Card] Charts(Donut/Pie) are not rendered complete when viewed on small devices.

### ISSUE THREAD

**Issue by kalyanixraut** [carbon-design-system/carbon-addons-iot-react#3272]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

Using Card and rendering charts(`@carbon/charts-react`) inside it, I find that the  charts are not resizing to fit in small device resolutions. 

### To Reproduce

Below is the screen shot of the card with pie chart when `isExpanded` is set to `true` for card.

![image](https://user-images.githubusercontent.com/22093326/152931459-fd14cdd4-3e88-4900-8262-687803332b4d.png)

Sample data used:

`[{"group":"2007","value":2176.33},{"group":"2007","value":2643.25},{"group":"2008","value":4392.2},{"group":"2008","value":2491.94},{"group":"2009","value":1302.18},{"group":"2009","value":2936.33},{"group":"2010","value":2426.33},{"group":"2010","value":3821.25},{"group":"2011","value":-1203.56},{"group":"2011","value":4094.25}]`

When I checked in carbon/chart_react codesandbox, on mobile resolution it shows the similar behaviour:

https://codesandbox.io/s/carbon-chart-react-hq513?resolutionWidth=320&resolutionHeight=675

### Expected behavior

Charts(Pie,Donut) `@carbon/charts-react` should resize to fit in small device resolution.

### Environment/versions:

- OS: MacOS
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: 2.147.3

**Comment by davidicus** [comment]
One of the issues may be the toolbar you have exposed here. Although it's removal will make the chart bigger, we will want to remove that secondary toolbar that is coming from the chart in order to not affect our style code that you will apply for this. You may want to checkout our PieChartCard files to see how we achieved this. 

I would not say its a bug since we have the same chart in a card in our [storybook](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-piechartcard--with-card-variables)

**Comment by kalyanixraut** [comment]
Hi @davidicus,

I checked the PieChartCard storybook with the sample dataset that I had provided above and this is how it is displayed

![image](https://user-images.githubusercontent.com/22093326/153381601-93a43b41-ef56-430a-8345-8688266c5262.png)

Though the label is fitting in the screen but looks very close to the edge. 

Also, in our case by removing the chart toolbar(as you have suggested) it looks similar to this screen shot.

**Comment by davidicus** [comment]
Hi, @kalyanixraut `.bx--chart-holder` will allow you to select this chart container. Then you can bump the width down. If this was done in PAL would you still need to create your own?

**Comment by kalyanixraut** [comment]
Hi @davidicus, Donut and Pie charts are the ones which are showing this behaviour. SVGs of Line/bar charts seems to fit-in well on small devices.
Currently as a workaround I have made use of the `.bx--chart-holder ` in graphite and tried to make donut and pie charts to fit in the screen. So we can close this bug.
