### ISSUE TITLE
[ai-flyout-menu] track open/close state of the filter-flyout menu

### ISSUE THREAD

**Issue by indieNik** [carbon-design-system/carbon-addons-iot-react#3334]
### What package is this for?

- [ ] React
- [x] Angular

### Summary

In the `ai-flyout-menu`, currently there's no way to react to the flyout's open/close state. Provide an @Output event to know the same?

**Additional context** Need this to close the pane when we use a custom header instead of the in-built header.

### Specific timeline issues / requests

I'm working on utilising this in `orderlines-table` component for the CC team.

**Comment by kevinsperrine** [comment]
@JordanWSmith15 This one is for Angular. The react FlyoutMenu already provides an `onChange` prop to achieve this. I'm going to remove this from the March release.

**Comment by indieNik** [comment]
Hi @kevinsperrine,
Do we have a way to know the filters state (`isActive / isOpen`) or something similar in Angular for now?

**Comment by kevinsperrine** [comment]
> Hi @kevinsperrine, Do we have a way to know the filters state (`isActive / isOpen`) or something similar in Angular for now?

Sorry, @indieNik, I know very little about Angular, but I don't _think_ there is. @zvonimirfras, @Donisius, or @sophiiae  Can you answer this?

**Comment by indieNik** [comment]
@zvonimirfras, is there a timeline that is being followed for the releases? I can see that it has been moved to `Angular Q1 - 2022`. Does that mean this change will only be available at the end of Q1? One of my tasks has a dependency on this issue, hence the ask.
