### ISSUE TITLE
[Card] Enable definition tooltips as the title text (in place of info icon)

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-addons-iot-react#3383]
• Info icon prop still exists. This story does not replace that feature. This is an additional, mutually-exclusive property
• Ensure that the tooltip opens in an appropriate direction (not off the page to the left, when the card is on the left edge of the screen)
• Ensure that the tooltip opens at the proper z-index, and does not get covered up by other cards, card content, etc
• Allow a custom render inside of the tooltip (buttons, links, etc. Not just a label)
• Title text truncates into an ellipsis if it does not fit. There is no option for wrapping.
![Screen Shot 2022-03-18 at 8.37.35 AM.png](https://images.zenhubusercontent.com/5c6ea1fad462891b1fd8e59e/5d8d5d83-abdc-4447-8be9-71eae0a7ae04)

**Comment by davidicus** [comment]
@JordanWSmith15 How does this feature operate with the overflow tooltip that is standard on the cards?

**Comment by JordanWSmith15** [comment]
@davidicus Do you mean the info icon? My preference was to completely replace it, but @dianatran18 wants to continue to support them. First line in the description above:

> • Info icon prop still exists. This story does not replace that feature. This is an additional, mutually-exclusive property

**Comment by davidicus** [comment]
@JordanWSmith15 No if the card title is too long it gets ellipsis and a tooltip that shows the whole text. 
<img width="626" alt="image" src="https://user-images.githubusercontent.com/1590966/159943281-a568a37f-3691-4e71-ad04-33bbfa692f9b.png">

**Comment by JordanWSmith15** [comment]
@davidicus Got it. So in that case I guess we would want to pass that text into the tooltip, as the first paragraph of text.  Then, the help information would appear after, as a second paragraph. @dianatran18 can confirm. 
<img width="483" alt="Screen Shot 2022-03-24 at 10 59 04 AM" src="https://user-images.githubusercontent.com/21066152/159945454-098fbfe1-ec24-40f2-875c-847b9d3003b0.png">

**Comment by davidicus** [comment]
OK. Any reason not to just use the info icon that is for that purpose? Just wondering why we are endorsing multiple ways to do things.

**Comment by JordanWSmith15** [comment]
@davidicus I agree, but I think the definition tooltip is actually a much cleaner/condensed approach. The info icon takes up space and consumes space needed by the other icons that can appear on the right.  I will be setting it as the ONLY option in Graphite, and deprecating the info icon there. I am open to doing that in PAL as well, if you can convince @dianatran18 :)

**Comment by davidicus** [comment]
This also conflicts with the multiline prop we have for title to be on multi-line. @bjornalm we will have to warn with both are added together.

**Comment by dianatran18** [comment]
Note: especially if there are actions in the tooltips like in the two cards in the example, the tooltip needs to be triggered on click for accessibility reasons.

**Comment by JordanWSmith15** [comment]
Agree about click vs hover. I also prefer click due to touch screens/mobile.

**Comment by bjornalm** [comment]
> But for the truncated text, do we generally style our own tooltip like that, or use the browser tooltip to show the full name? I don't know how it works in other components.

@dianatran18 We do both. I think the browser tooltip (I assume you are referring to the title attribute) is more commonly used for smaller elements like List and Dropdown items

**Comment by JordanWSmith15** [comment]
> If we keep the browser tooltip on hover for truncated text we can perhaps let the TooltipDefinition open on click and only show custom content there like Jordans initial suggestion?
I don't typically like to rely on hover effects, because I anticipate touch screens/mobile scenarios to come into play in the future for all of these applications.

**Comment by bjornalm** [comment]
@JordanWSmith15 Turns out I can't use the TooltipDefinition component for this since it doesn't support interactive content. Trying to click a button in the TooltipDefinition will close the tooltip and the click event from the button is never triggered.

So I will use the normal "Tooltip" function and make it look like the TooltipDefinition. The normal "Tooltip" also has the advantage that it can be triggered by click.
