### ISSUE TITLE
[TableCardFormContent] Thresholds not being updated when data item is removed

### ISSUE THREAD

**Issue by eosineye1** [carbon-design-system/carbon-addons-iot-react#3389]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

When a data item for DataTable is added with thresholds. When the dataItem is removed, the JSON editor does not reflect the change for the threshold.

### To Reproduce

1. Go to  https://next.carbon-addons-iot-react.com/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-dashboardeditor--with-initial-value
2. Click on already created DataTabe
3. Add a threshold to a data item. Open JSON editor to see threshold has been added
4. Remove that same data item and open JSON editor. The threshold has not been removed from JSON

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/carbon-design-system/carbon-addons-iot-react/tree/next/packages/react/examples/codesandbox

### Expected behavior

Thresholds associated with dataItem should be removed when dataItem is removed for DataTable.

**Comment by JordanWSmith15** [comment]
@eosineye1 I see you have a draft PR. Do you need any guidance with this?

**Comment by jessieyan** [comment]
Related to #3566
