### ISSUE TITLE
[Component Proposal] Radio buttons on data table

### ISSUE THREAD

**Issue by jennyyao98** [carbon-design-system/carbon-addons-iot-react#3394]
### What package is this for?

- [x] React
- [ ] Angular

### Summary
Radio button to enable single selection on data tables as currently there only exist multi selection capability with checkboxes. 
• Add radio button styling prop, mutually exclusive with the blue line styling that appears on the start of the row
• Consider allowing the radio button for data table is to allow a null state. So, on-load, the table has nothing selected, and I can click the currently selected radio to go back to null
Implementing this pattern in the design for Maximo Manager Role-Based Application - Maintenance manager for Release 1

**Additional context** 
This pattern currently exists in Carbon ([usage guidance ](https://www.carbondesignsystem.com/components/data-table/usage/#radio-selection)and [storybook example](https://react.carbondesignsystem.com/?path=/story/components-datatable-selection--with-radio-selection))

Invision design prototype for Maintenance manager utilizing this radio selection pattern: https://ibm.invisionapp.com/d/main#/console/15384087/320231588/preview

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release? Maximo Manager Role-Based Application - Maintenance manager for Release 1

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### You will consider this component complete when...

- [ ] It's available as an export of this library
- [ ] Additional criteria you may have [e.g. Fully responsive, Accessible to
      WCAG 2.0, etc.]

### Available extra resources

What resources do you have to assist this effort?

_Carbon add-ons for Watson IoT is a collaborative system. We encourage teams to
build components and submit them for integration._

**Comment by JordanWSmith15** [comment]
This is another on where we need to consider globally replacing the current treatment for a blue line (which is not very accessible)
![Screen Shot 2022-03-24 at 11.15.43 AM.png](https://images.zenhubusercontent.com/5c6ea1fad462891b1fd8e59e/2503bb2d-d7c6-4996-9bca-7f638876a30f)

**Comment by jessieyan** [comment]
> This is another scenario where we need to consider globally replacing the current treatment. Currently, we use a blue line (which is not very accessible) ![Screen Shot 2022-03-24 at 11.15.43 AM.png](https://camo.githubusercontent.com/14cb87ff5211977ef594176ffccdbc44d40b30c732d38cb7d8f462b19dbf3aeb/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563366561316661643436323839316231666438653539652f32353033626232642d643763362d343939362d396263612d376636333838373661333066)

Hello Jordan  @JordanWSmith15 

Just want to be clear on the proposal here. Do you mean we should remove the blue highlight and use radio button here for single selection when there is row hierarchy?  Do we have a design for radio button in hierarchy scenario?
