### ISSUE TITLE
[carbon-addons-iot-react] wait for new version dom-to-image to fix jquery 2.1.4 vulnerability

### ISSUE THREAD

**Issue by YolandaZhang369369** [carbon-design-system/carbon-addons-iot-react#3416]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

Our product directly use "carbon-addons-iot-react": "^2.147.0-next", the dependency chain is as follow: 
> dom-to-image@2.6.0
> <- @carbon/charts@0.54.14
> <- @carbon/charts-react@0.54.2
> <- carbon-addons-iot-react@2.148.0

Our vulnerability scanning tool notify us to upgrade to jquery 3.0.0, we find **dom-to-image** packaged **jquery 2.1.4** internally (/dom-to-image/bower_components/jquery 2.1.4), so that we could not upgrade its version directly, so we are waiting for new version dom-to-image to fix this vulnerability of jquery.

### Expected behavior

New version dom-to-image to fix this vulnerability of jquery, upgrade to jquery 3.0.0.

**Comment by JordanWSmith15** [comment]
@YolandaZhang369369  Depends on https://github.com/carbon-design-system/carbon-charts/issues/1224
Have you contacted the charting team for prioritization?

**Comment by YolandaZhang369369** [comment]
@JordanWSmith15 , what do you mean when saying "charting team"? We are one of the development team in IBM Maximo Application Suite. Now we need to resolved this issue as soon to fullfill company IT security requirement for High severity issues.

**Comment by JordanWSmith15** [comment]
FYI @davidicus .  What I mean by charting team is the Carbon charts team, which is where this vulnerability lies. I would open an issue in https://github.com/carbon-design-system/carbon-charts, or ask the Carbon Charts slack channel https://ibm-watson-iot.slack.com/archives/CCA7L4MS9

**Comment by davidicus** [comment]
[Inquiring](https://github.com/carbon-design-system/carbon-charts/pull/1403#issuecomment-1245873243) about the possibility of back porting the solution to `v0.55.1`

**Comment by davidicus** [comment]
Carbon chart's team [investigation](https://github.com/carbon-design-system/carbon-charts/issues/1206#issuecomment-1112490866) found this to be a dev dependency for the `dom-to-image` package and is not used in the charts codebase.
