### ISSUE TITLE
DateTime: Z-index solution for Graphite

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-addons-iot-react#3420]
For the date/time component, ensure that it will function properly with the z-index manager of Graphite, most likely by using a portal for the menu section
https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-date-time-range-selector-datetime-picker--selected-absolute

**Comment by jessieyan** [comment]
@JordanWSmith15 
Hello Jordan, the  `z-index` was hardcoded on the menu, we can use css attribute to make it respect zindex set by the graphite ZIndexManager. Does it sound a good solution for you or do you still prefer using react portal?

**Comment by JordanWSmith15** [comment]
Yes, I believe that would work fine, but please confirm with @davidicus and Brian
