### ISSUE TITLE
[Table] Unable to select the checkboxes using keyboard(Enter key)

### ISSUE THREAD

**Issue by bakkireddi** [carbon-design-system/carbon-addons-iot-react#3425]
Unable to select the checkboxes using the keyboard(Enter key) in the below components:
Table -With selection and batch actions
Table Save View Model 
 User view management

**Steps:**
1. Go to the "Table - with the selection and batch actions" component in the storybook  
PAL URL: https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table--with-selection-and-batch-actions
2. Select the checkboxes using the keyboard.
 Current Behavior: Unable to select the checkboxes using keyboard (Enter key)
Actual Behavior: should be able to select the checkboxes using keyboard.

**PAL URLS:
Table -With selection and batch actions**
https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table--with-selection-and-batch-actions
**Table Save View Modal** 
https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table-user-view-management-tablesaveviewmodal--playground
**Table Manage Views Modal**
https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table-user-view-management-tablemanageviewsmodal--with-callbacks-implemented
**User view management**
https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table-user-view-management--with-user-view-management

**Comment by JordanWSmith15** [comment]
I assume there is no work-around for a11y users, so this is a sev 1

**Comment by davidicus** [comment]
Hi @bakkireddi. The accessibility spec actually calls for the spacebar to trigger a selection for checkboxes. If you look at these links [here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/checkbox_role#keyboard_interactions) and [here](https://www.w3.org/TR/wai-aria-practices-1.1/#keyboard-interaction-5) you can verify that we are following the spec when it comes to checkbox selection.  I am going to close this issue but feel free to reach out if you would like to discuss further.
