### ISSUE TITLE
[SideNav] Active selection of parent item when child is active, is not working when nav bar is minimised

### ISSUE THREAD

**Issue by vikasjagtap** [carbon-design-system/carbon-addons-iot-react#3433]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug
The active selection is stuck at the first active nav link selected.
The children do not get minimised within the side nav when new selection is made

### To Reproduce
The issue can be seen on the storybook example of [Header with side nav](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-ui-shell-suiteheader--header-with-side-nav)

**Comment by JordanWSmith15** [comment]
I have also noticed this problem in Graphite

**Comment by davidicus** [comment]
The story in question is not a stateful example of the sidenav. The prop, `sideNavProps` is an object that has a property of links which is an array of link objects. This is hard coded in our story. What I do see is that somewhere along the line the prop was changed to align with Carbon refactor but our proptype definition was never updated. `isActive` must be part of the link object to get the active link state. I will update our proptype definitions and update our storybook to be stateful.

**Comment by davidicus** [comment]
I did have to update the SuiteHeader component as I was having troubles getting the story to work. The PR for this is mentioned above and also [here](https://github.com/carbon-design-system/carbon-addons-iot-react/pull/3451)
