### ISSUE TITLE
[Side-nav] Add support for "My recent applications" and pinned items at the top w/line

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-addons-iot-react#3443]
![Screen Shot 2022-05-19 at 9.25.34 AM.png](https://images.zenhubusercontent.com/5c6ea1fad462891b1fd8e59e/331d4bdf-7b34-4ab3-8bcd-f015731ec5fb)
Maximo TPAE has long-standing logic where:
1. Apps recently clicked are stored and easily accessed again within the same session
2. Items such as "Start center" are docked at the top w/the search bar
In order to migrate customers from Maximo 7.6 to 8, we need to retain all existing features to reduce adoption inhibitors. Ensure that TPAE and Graphite are visually identical in terms of navigation is part of this effort.

**Comment by davidicus** [comment]
@JordanWSmith15 are these applications that are chosen in the opposite sliding drawer from the header? If so, should this functionality live over on that side? Or are these "applications" in the sideNav section?
![image](https://user-images.githubusercontent.com/1590966/178283949-fb4bb86a-cf8c-4ca9-a6c2-289d606f60a6.png)
