### ISSUE TITLE
[Time picker] Update old timer picker component 

### ISSUE THREAD

**Issue by dianatran18** [carbon-design-system/carbon-addons-iot-react#3447]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

This is a request from the Maximo Scheduler team, to evolve the date time picker to account for their use cases. 
This issue is specific to building out the time picker portion first. 

[Design specs in Figma](https://www.figma.com/file/PeLztKjMstgRMKz5qfeRHJ/?node-id=101%3A12151) (trying this out)
If more specs are needed, reach out to @dianatran18 

This behaves similarly to the [Carbon date picker](https://react.carbondesignsystem.com/?path=/story/components-datepicker--range-with-calendar)

Variations:
- Single time picker
- Time range picker

**Comment by jessieyan** [comment]
@dianatran18 @JordanWSmith15 @davidicus  
Hello, can anyone grant me access to [Figma](https://www.figma.com/file/PeLztKjMstgRMKz5qfeRHJ/?node-id=101%3A12151) please?
