### ISSUE TITLE
[StatefulTable] The hierarchy tree indicator is missing

### ISSUE THREAD

**Issue by herleraja** [carbon-design-system/carbon-addons-iot-react#3449]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

- [ ] Issue 1: The hierarchy tree indicator is missing on the left side(gray indicator)

- version : 2.148.0-next.13

![image](https://user-images.githubusercontent.com/18572477/170208767-aaa8cdb7-dd08-4113-a61f-fc82c66bbd19.png)

- version : 2.149.0-next.54

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/18572477/170208836-adfda556-5b2f-4036-a1b7-b75c479ea266.png">

- [ ] Issue 2: On the hover of the table row it seems to hover the full row. also, the line separator used to start from the table's left side corner, whereas now it's kind of moved the right side to the level of hierarchy.  

- version : 2.148.0-next.13

![image](https://user-images.githubusercontent.com/18572477/170209011-065340aa-788f-401b-a932-7c7768b81556.png)

- version : 2.149.0-next.54

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/18572477/170209398-40b1b9c8-023f-44c6-9950-29d9933eba44.png">

**Comment by davidicus** [comment]
Hey @herleraja This is a purposeful change to the spec to align Table and List hierarchies as well as the Carbon styling for expanded rows.

**Comment by herleraja** [comment]
@CynZhang FYI

**Comment by herleraja** [comment]
The visualization of hierarchy is hard to read because of the ^-signs in front of a hierarchy resources. It's not clear **at the first glance** to which hierarchy resource a device is assigned to. This makes it unnecessarily difficult to interpret the hierarchy.

Example: Is device KOHL-DT1_3 assigned to KOHLM-ASSET1 or KOHLM-SUBLOCATION1 in the following hierarchy:

![image](https://media.github.ibm.com/user/107619/files/9d5f05ba-c781-4cc2-8cfb-4c0aacc89bbd)


A simple solution could be to add a (hollow) bullet in front of devices to avoid the visual difference in indentation for resources and devices.
