### ISSUE TITLE
[StatefulTable] Sorting 'None' with searching does not work as expected

### ISSUE THREAD

**Issue by ilovepumpkin** [carbon-design-system/carbon-addons-iot-react#3491]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

Input a search keyword to search table data first then sort one column, the result data is not filtered out by search keyword

### To Reproduce

1. Input keyword to search, for example "test"
2. Click column header "Name" to sort column
3. Set sort column type as "None" (with both up arrow and down arrow in table header)
4. The result data includes data rows without "test"
![image](https://user-images.githubusercontent.com/11310645/177031202-0de7a142-075a-4a17-a325-82a7be9809fc.png)

### Expected behavior

The result data should only contain the rows including "test" since the search keyword is not cleaned yet

### Environment/versions:

- OS: all
- Browser: all
- `carbon-addons-iot-react` version: latest 'next' version

**Comment by JordanWSmith15** [comment]
@davidicus FYI. I have not noticed this issue in Graphite. The search behaves differently depending on how you hook it up, I assume.

**Comment by JordanWSmith15** [comment]
@ilovepumpkin Please provide more information Jessie asked for above or we won't be able to progress with this issue.

**Comment by ilovepumpkin** [comment]
@JordanWSmith15 @jessieyan 

This can be easy to reproduce on https://carbon-addons-iot-react.com/?path=/story/1-watson-iot-table--playground, and recorded a video for you. 

https://user-images.githubusercontent.com/11310645/197453564-c4c73401-8653-402d-9291-bb66a40e3465.mp4
