### ISSUE TITLE
[SidePanel] Address gaps in SidePanel to support reconciliation with Graphite SlidingDrawer

### ISSUE THREAD

**Issue by kalyanixraut** [carbon-design-system/carbon-addons-iot-react#3497]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

Following gaps have been identified while incorporating SidePanel in graphite's SlidingDrawer(default theme).

1. Docked footer buttons: Footer buttons always don't dock to bottom of the panel.
<img width="387" alt="image" src="https://user-images.githubusercontent.com/22093326/179455928-8c7e4789-8be4-4e8e-989d-22fe2531534c.png">

2. Footer buttons presently support only callbacks(`onPrimaryButtonClick` and `onSecondaryButtonClick`)  but need addition props to be exposed like icons, disabled, kind, etc.

3. `actionItems` prop should also support passing node like `<ButtonGroup/>` component.

4. Addition of a `busy` state to disable panel header and footer `Cancel` button when it's set `true`.

5. Expose `disabled` prop for close(X) button. So that it can be disabled until an operation is in progress and disallow user to close the side panel.

6. Expose `disabled` prop for footer primary button, so that it can be disabled to support cases where it should remain disabled until all required fields are populated with a value.

**Additional context** 

[SlidingDrawerVsSidePanel.xlsx](https://github.com/carbon-design-system/carbon-addons-iot-react/files/9119350/SlidingDrawerVsSidePanel.xlsx)

### Specific timeline issues / requests

Targeted for MAS-8.9 release.

**Comment by kalyanixraut** [comment]
@JordanWSmith15  @davidicus

**Comment by davidicus** [comment]
@JordanWSmith15 Discussing the items listed out on this issue:
1. This should be an easy css fix of just applying `margin-top: auto;`. @kalyanixraut and I have already discussed. 
2. Jordan, when we discussed I had thought you wanted to lock this down to these primary, secondary buttons. If that is changed we will need to support existing markup but add an additional "danger" button callback that will render that when appropriate. We should also update the design spec.
3. Action items just renders what is passed. I think this will just require a proptype update.
4. This is additive so will not mess with SemVer. Can be added as additional prop and passed to the appropriate components.

**Comment by JordanWSmith15** [comment]
@kalyanixraut @davidicus I am OK with skipping 2, for now, as I don't have a use case for danger state, icons, etc. 1, 3 and 4 are much more important.

**Comment by kalyanixraut** [comment]
> @kalyanixraut @davidicus I am OK with skipping 2, for now, as I don't have a use case for danger state, icons, etc. 1, 3 and 4 are much more important.

Hi @JordanWSmith15 , @davidicus , if we are skipping 2, then user won't be able to disable the buttons or show loading. I think these are must-to-have features for SlidingDrawer's footer buttons. And is linked to point#4 busy state.

Earlier we had button comp passed by app developers and with that they had the full control over its props to disable/loading/kind etc now with SidePanel introduced into SlidingDrawer, can we have a new prop added to SidePanel as `overrides: PropTypes.shape({
    primaryButton: PropTypes.node,
    secondaryButton: PropTypes.node,
  })`
  while still keeping the existing `onPrimaryButtonClick` and `onSecondaryButtonClick` callbacks?
  
Or, add `disabled` prop to SidePanel's secondary button, `loading` prop to primary button and a new prop as `loading` to sidepanel(for point#4), which when set to true will automatically make secondary button disabled and show primary button with loading.

**Comment by JordanWSmith15** [comment]
@kalyanixraut Spoke with Diana, and we should go with this:

> Or, add `disabled` prop to SidePanel's secondary button, `loading` prop to primary button and a new prop as `loading` to sidepanel(for point#4), which when set to true will automatically make secondary button disabled and show primary button with loading.

All we need to do is add 2px white separation between the secondary and primary button. This is actually a bug for all the current buttons in the component. The design has the 2px in it: https://pages.github.ibm.com/ai-applications/design/components/sidepanel/usage
