### ISSUE TITLE
[ListSpinner] Hide scrollbars on mobile browsers

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#3508]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

Hide the scrollbars consistently on all mobile browsers. The current method works on desktop browsers but is not working for mobile. 

**Additional context**
Desktop             |  Mobile
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/1590966/180812729-61777889-31da-4b22-b1a0-3312cbb6a59e.png)  |  ![image](https://user-images.githubusercontent.com/1590966/180812940-5b4562e4-1f73-4048-9c6a-795c645d6373.png)

**Comment by JordanWSmith15** [comment]
The scroll bars don't particularly bother me
