### ISSUE TITLE
[SuiteHeader] Multi-workspace support

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-addons-iot-react#3509]
In the suite header/UI shell
1. Re-design the 9-dot nav menu as shown in the design spec
2. Add support for multi-workspace applications in the Navigator (nine dot) menu. This section only appears if the current user has access to applications in multiple work spaces. 

Design:
https://app.mural.co/invitation/mural/aiapplicationsdesign4698/1654283028012?sender=charlottewittels3890&key=86b4373c-f8b5-4e03-b67e-db819a5bd805

**Comment by blechner** [comment]
I've started working on this issue. [Here is the branch](https://github.com/carbon-design-system/carbon-addons-iot-react/tree/issue-3509).

**Comment by blechner** [comment]
@JordanWSmith15 @sls-ca support for multi-workspaces has been implemented, here is the PR: https://github.com/carbon-design-system/carbon-addons-iot-react/pull/3514
Take a look at the stories, starting in this one: https://deploy-preview-3514--carbon-addons-iot-react.netlify.app/?path=/story/1-watson-iot-ui-shell-suiteheader-multi-workspace--admin-page
