### ISSUE TITLE
[TimePickerDropdown] Single label for range does not span across element

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#3515]
### What package is this for?

- [X] React
- [ ] Angular

### Describe the bug

When the option to hide secondary label is chosen on a range input the primary label is supposed to span across both text input fields. Now there is a max width being applied which is needed when both labels are shown. The fix is to just apply a `:not(legend)` to the end of the selector applying the max width to the labels. 

### To Reproduce

1. Go to this [story](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-timepickerdropdown--default)
2. Click the` hide secondary label` knob and choose range from the `Type` dropdown
3. Make the text in the `i18n` knob's labelText field a long string

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/carbon-design-system/carbon-addons-iot-react/tree/next/packages/react/examples/codesandbox

### Expected behavior

When secondary label is hidden the primary label should span the entire element. 

Current             |  Desired
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/1590966/183432412-7d220c5b-4db6-4b1a-ac60-908f53eb989b.png)  |  ![image](https://user-images.githubusercontent.com/1590966/183432214-3f2b017f-36d5-4772-a4b5-c9080244167a.png)

**Comment by davidicus** [comment]
@jessieyan I think @erzhan-temir-mamyrov is working this as part of the Audit he is doing on TimePickerDropdown. @erzhan-temir-mamyrov please confirm.

**Comment by davidicus** [comment]
Oh maybe it is not part of the Audit. But since @erzhan-temir-mamyrov, you are already in perhaps you can tackle this. This is assuming that @dianatran18 still thinks this should be supported. @dianatran18 Thoughts? We have a prop to hide secondary label which is intended to use the primary as the label for both.

**Comment by erzhan-temir-mamyrov** [comment]
@davidicus Yes, I will fix it with the upcoming audit fixes.
