### ISSUE TITLE
Data table - Row selecion not accessible

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-addons-iot-react#3544]
Go to https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table--with-selection-and-batch-actions
Attempt to select a row with the keyboard
It is not possible to use the enter key to select a row, even when focused on a checkbox item.
We should likely be using the arrow keys (up/down) to navigate the list, and the return button to select a row

**Comment by jessieyan** [comment]
@JordanWSmith15 @davidicus Should we add new prop on <TableBodyRow> to indicate which row is currently focused then update the prop when use ArrowUp/ArrowDown to navigate the rows? Will there be performance issues if there are too many rows?

**Comment by JordanWSmith15** [comment]
Space bar is sufficient! Closing
