### ISSUE TITLE
[DateTimePickerV2] horizontal bar should not show up

### ISSUE THREAD

**Issue by jessieyan** [carbon-design-system/carbon-addons-iot-react#3571]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

A horizontal bar show up when width is set to 100%.

### To Reproduce

https://user-images.githubusercontent.com/24279794/192625880-5fb02567-c8fb-47ea-b924-ea148a722ac6.mov

> Please create a reduced test case in CodeSandbox:
> https://codesandbox.io/s/github/carbon-design-system/carbon-addons-iot-react/tree/next/packages/react/examples/codesandbox

### Environment/versions:

- OS: [e.g. MacOS, Windows]
- Browser: [e.g. chrome, safari]
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by jessieyan** [comment]
I couldn't reproduce the horizontal bar. 

https://user-images.githubusercontent.com/24279794/192629582-84c03b1f-1bb5-420d-8da3-66e99784e06e.mov

**Comment by jessieyan** [comment]
@abhishekpaul mentioned it is reproducible.

"Put .iot--date-time-pickerv2__wrapper width as 100% and in your PAL storybook .storybook-container has 3 rem padding all over the component if you removed that or reduced to 1rem you can reproduce it"

**Comment by jessieyan** [comment]
I removed the padding on `storybook-container` and set width to 100%

![image](https://user-images.githubusercontent.com/24279794/195434092-e7d99166-648b-4233-8e43-9991f2178a93.png)


I can see DateTimePickerV2 is 100% wide within its parent. 

![image](https://user-images.githubusercontent.com/24279794/195434425-8acc7db3-d888-4ad2-b45e-6070ced54c3c.png)


The horizontal bar belongs to html. There is a gab between `html` and the parent `document` object. 

![image](https://user-images.githubusercontent.com/24279794/195434718-347a1fb6-e485-4ddc-9003-344a6f339634.png)

![image](https://user-images.githubusercontent.com/24279794/195434885-ad5104f1-d88a-48dd-90a1-59506114ae66.png)

@davidicus I couldn't figure out what might cause the extra space on the right. Maybe you saw it before?

**Comment by davidicus** [comment]
@jessieyan It looks like this is caused by the button tooltip. We hide this tooltip for this component so we can apply an `overflow: hidden` to the div with the class `iot--flyout-menu iot--flyout-menu__bottom`. That should solve this issue.
