### ISSUE TITLE
[TimePickerDropdown] support for 24-hours format

### ISSUE THREAD

**Issue by erzhan-temir-mamyrov** [carbon-design-system/carbon-addons-iot-react#3575]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

Add support for 24-hours format in `TimePickerDropdown`

**Additional context** Add any other context or screenshots about the feature
request here.

### Specific timeline issues / requests

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### Available extra resources

- Design specification is available in Figma

_Carbon add-ons for Watson IoT is a collaborative system. We encourage teams to
build components and submit them for integration._

**Comment by dianatran18** [comment]
Design specs to the 24-hour time picker: 
https://www.figma.com/file/PeLztKjMstgRMKz5qfeRHJ/Dev-handoff-%E2%80%93%C2%A0PAL?node-id=101%3A12151

The design specs should reflect all comments made on the Time picker audit #3566. Everything should be mostly the same, but there are some differences in the spacing and sizing in the time picker dropdown for the 24-hour variant from the 12-hour variant. Note that there are different minimum and default sizes for the time input too.
