### ISSUE TITLE
[Table] Is there a plan to add an enhancement of retaining table states after redirecting to edit page?

### ISSUE THREAD

**Issue by fengzilaopop** [carbon-design-system/carbon-addons-iot-react#3592]
### What package is this for?

- React

### Summary

As our team gets the requirement that the table component should keep the table state(filters, sorts for example) after redirecting to other pages(editing/adding page for example), leave a message to ask if there is a plan to add this enhancement to carbon-addons-iot-react package?

**Comment by JordanWSmith15** [comment]
We don't handle multi-page states at the PAL React level, and it should likely stay that way, given that most teams such as Maximo have already created mature approaches for doing so.

**Comment by JordanWSmith15** [comment]
We don't handle multi-page states at the PAL React level, and it should likely stay that way, given that most teams such as Maximo have already created mature approaches for doing so.
