### ISSUE TITLE
[DateTimePickerV2] Time picker in the calendar widget is not aligned properly because of fixed width

### ISSUE THREAD

**Issue by bakkireddi** [carbon-design-system/carbon-addons-iot-react#3601]
The Time picker in the calendar widget is not aligned properly because of fixed width.
<img width="277" alt="image" src="https://user-images.githubusercontent.com/37322952/195846244-253996a1-409d-4b7f-a716-3a283600c822.png">

**Comment by jessieyan** [comment]
@bakkireddi  Can you be more specific on the fixed width so that I can reproduce it?  

This is what we have in next branch.

![image](https://user-images.githubusercontent.com/24279794/196236430-347e3078-1612-458a-8760-5c49f773c988.png)
