### ISSUE TITLE
[DateTimePickerV2] The focus for date time input field is working in chrome when doing tabination. But in FF it's not showing the Focus.

### ISSUE THREAD

**Issue by bakkireddi** [carbon-design-system/carbon-addons-iot-react#3619]
The focus for date time input field is working in chrome and Safari when doing tabination. But in FF it's not showing the Focus.
https://next.carbon-addons-iot-react.com/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-datetimepickerv2--single-select
In Chrome, showing the focus when doing tabination (PAL Storybook)
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/37322952/198538439-05696ed0-74bd-4b78-a10e-ec249b461323.png">
(GRAPHITE)
In FireFox, not showing the focus when doing tabination 
<img width="463" alt="image" src="https://user-images.githubusercontent.com/37322952/198538807-2fd1d2aa-01e2-4298-90ff-806dfd5bb9f8.png">
In Chrome, showing the focus
<img width="338" alt="image" src="https://user-images.githubusercontent.com/37322952/198538980-b9de01e7-d95c-4411-8ce4-42c1bed124f7.png">

**Comment by jessieyan** [comment]
@JordanWSmith15 

This is the thing with Firefox on Mac

We need to do 2 things to enable the tabfocus

1. In System Preferences → Keyboard, in the Shortcuts pane, check the “all controls” radio at the bottom.

2. In Firefox, type "about:config" in the URL bar. There is no accessibility.tabfocus preference on the mac, so you'll have to make one. Right click in the window, create a new "integer" pref, and set it to 7.

https://support.mozilla.org/en-US/questions/1278793

**Comment by JordanWSmith15** [comment]
Ok... that's pretty interesting. Why is it different than all the other fields on this page though? https://pages.github.ibm.com/maximo-app-framework/graphite/main/reference-app/?dataFormatting%3AselectedTab=2#/dataFormatting

**Comment by jessieyan** [comment]
Taking another look today. I see the issue is specific to the invalid state not the regular state.
