### ISSUE TITLE
[DateTimePicker] When Date is picked in an empty field, time is auto populated but apply is disabled

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#3631]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

Clicking on a date will auto populate the time in the input but the time is not reflected in the `TimePickerDropdown` and the apply button is disabled. 

### To Reproduce

1. Go to [this](https://next.carbon-addons-iot-react.com/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-datetimepickerv2--single-select) story
2. Click on input to open dropdown and clear hit the clear button
3. Now open calendar and choose date. 
4. See midnight is auto populated but TimePickerDropdown is still empty and the apply button is disabled. 

![image](https://user-images.githubusercontent.com/1590966/200026077-10835503-b70b-4f2b-b417-245c24c07948.png)

### Expected behavior

If we auto populate to midnight that time should be reflected in TimePickerDropdown and apply button should not be disabled.

**Comment by jessieyan** [comment]
@davidicus The old DateTimePickerV2 always auto populate the default value 00:00. I can remove the default value. If time value is not selected, we are not setting time value on `humanValue` object which is the value shown in the input.
