### ISSUE TITLE
[List] Support a horizontal scroll bar for HierarchyList

### ISSUE THREAD

**Issue by ndtx** [carbon-design-system/carbon-addons-iot-react#3639]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug

The List does not support a horizontal scroll bar. In some instances, we cannot see the item names anymore.

### To Reproduce

1. Please see the screenshot

### Expected behavior

The option to have a horizontal scroll bar.

### Environment/versions:

- `carbon-addons-iot-react` version: 2.151.0-next.45

### Additional context

![image](https://user-images.githubusercontent.com/5113965/201144684-9fd095f3-0217-45c6-8e98-950b0da40527.png)

https://github.com/carbon-design-system/carbon-addons-iot-react/issues/3639#tasklist-block-cdc3c347-6858-446d-a600-c2ecb60fc7ef

**Comment by davidicus** [comment]
@dianatran18, @wevinkeaver  I was looking on the site about the design guidelines on numbers  of nested rows but could not find. We do not currently support a horizontal scrollbar but my understanding is that this is by design. Do either of you have anything to weigh in on this?
