### ISSUE TITLE
[DateTimePickerV2] Time picker in the calendar widget is not aligned properly, it's showing extremely left

### ISSUE THREAD

**Issue by bakkireddi** [carbon-design-system/carbon-addons-iot-react#3648]
[DateTimePickerV2] Time picker in the calendar widget is not aligned properly, it's showing extremely left
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/37322952/202184403-e9ef5517-30ec-4c91-8bc7-0cf3d6e6cf23.png">

**Comment by davidicus** [comment]
@JordanWSmith15 This looks to be a defect in Graphite as [our storybook](https://next.carbon-addons-iot-react.com/?path=/story/2-watson-iot-experimental-%E2%98%A2%EF%B8%8F-datetimepickerv2--single-select) does not show the left aligned time input.

**Comment by JordanWSmith15** [comment]
@erzhan-temir-mamyrov This is a great one for you to get your "feet wet" between Graphite and PAL. Let's find the root cause of this and remedy.
