### ISSUE TITLE
[Table] Support a horizontal scroll bar for Table, StatefulTable

### ISSUE THREAD

**Issue by ndtx** [carbon-design-system/carbon-addons-iot-react#3653]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

IBM MAS Monitor team needs Table component to support horizontal scrollbar. Expanding the hierarchy reaches nodes that are not visible on low width screens. Please see attached screenshot.

Similar to the List change done here: https://github.com/carbon-design-system/carbon-addons-iot-react/issues/3639

**Additional context** Add any other context or screenshots about the feature
<img width="812" alt="image" src="https://user-images.githubusercontent.com/5113965/203774958-5fc9030a-c179-406f-842b-3c35de02919a.png">

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by erzhan-temir-mamyrov** [comment]
@ndtx Thank you for bringing this up! We will try to add support for horizontal scrollbar soon. As a temporary workaround you can try to set Table prop:
```js
<Table
  ...
  options={
    ...
    wrapCellText: 'always',
  }
/>
```
