### ISSUE TITLE
[datatable] sort icon should be 16px

### ISSUE THREAD

**Issue by gcate** [carbon-design-system/carbon-addons-iot-react#3676]
### What package is this for?

- [x] React
- [x] Angular

### Describe the bug
In both the angular and react datatable, the sort icons are 20px.  They should be 16px. 

### To Reproduce

1. Go to [react](https://react.carbondesignsystem.com/?path=/story/components-datatable-sorting--default) or [angular](https://angular.carbondesignsystem.com/iframe.html?id=components-table--basic) demo sites. 
2. Use inspect to check icon size. See that it is 20px.

I have also seen the icons change from 20px to 16px as the columns get crowed but I am unable to reproduce it today. Here are screenshots.
![image](https://user-images.githubusercontent.com/4819973/207408319-deed5920-6266-4f5f-8def-c79300a27bb6.png)

### Expected behavior

Sort icons should always be 16x16px. 
Reference comment from Carbon design team: 
![image](https://user-images.githubusercontent.com/4819973/207408855-16e9419a-f743-4384-b4bc-9a4b760df9b7.png)

**Comment by davidicus** [comment]
Hi @gcate. The linked storybook is for the Carbon repo and not this one. We are one of the PAL built on top of Carbon and you can see [our icons](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-table--with-sorting) size are in fact 16 px. 
<img width="576" alt="image" src="https://user-images.githubusercontent.com/1590966/212356486-884366a3-f5a9-4cb6-879a-0334f1116f1a.png">
