### ISSUE TITLE
[UI Shell SideNav] The hamburger menu icon should get replaced with a close icon when its open

### ISSUE THREAD

**Issue by bogy0** [carbon-design-system/carbon-addons-iot-react#3692]
### What package is this for?

- [x] React

### Describe the bug

In the UI Shell SideNav component when I click on the Hamburger menu and the sidenav expanded the "Hamburger" icon should replaced to a "X" or "Close" icon as you can see in the vanilla Carbon storybook (hamburger menu only visible on small screen width):
https://react.carbondesignsystem.com/?path=/story/components-ui-shell--header-base-w-navigation

### To Reproduce

1. Go to [UI Shell SideNav component storybook page](https://next.carbon-addons-iot-react.com/?path=/story/1-watson-iot-ui-shell-sidenav--side-nav-component)
2. Click on "Hamburger" icon
3. When the sidenav expanded the "Hamburger" icon didn't replaced to a "Close" icon

### Expected behavior
The hamburger menu icon should get replaced with a close icon when its in open state.

### Environment/versions:
- all env/version

**Comment by JordanWSmith15** [comment]
I believe @lukefirth and @dianatran18 have determined this item to be invalid/working as designed.
