### ISSUE TITLE
[Table] Add ability to freeze table header and footer. 

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#3696]
### What package is this for?

- [x] React
- [ ] Angular

### Summary

There has been multiple request for the ability to freeze our headers and footers for the Table component. We are currently working on a [column freeze enhancement](https://github.com/carbon-design-system/carbon-addons-iot-react/pull/3677) now. We can use the same mechanism to add this functionality for the header and footer.

**Comment by bharathraomairpady** [comment]
@JordanWSmith15 @davidicus can you please provide an estimate of when this enhancement will be completed? Thanks.

**Comment by JordanWSmith15** [comment]
@erzhan-temir-mamyrov I believe there is a PR for this, correct?

**Comment by erzhan-temir-mamyrov** [comment]
@JordanWSmith15 [There is a PR](https://github.com/carbon-design-system/carbon-addons-iot-react/pull/3677) for freezing column option.
@bharathraomairpady I will start to work on this enhancement because it is assigned to current sprint.

**Comment by bharathraomairpady** [comment]
@erzhan-temir-mamyrov thanks for the confirmation. Much appreciated.
