### ISSUE TITLE
Truncation of first breadcrumb item is inconsistent 

### ISSUE THREAD

**Issue by darshan1290** [carbon-design-system/carbon-addons-iot-react#3700]
There seems to be a break point where the truncation on the front part of the breadcrumb breaks. 

![Screenshot 2023-01-19 185518](https://user-images.githubusercontent.com/36167158/213454459-684ced6d-ebfc-4875-bf6b-e3f32ba3fba8.png)
![Screenshot 2023-01-19 185604](https://user-images.githubusercontent.com/36167158/213454527-df31d447-0fde-4a7b-b572-c89e8fd245a7.png)
[heinsj](https://github.com/heinsj) FYI

**Comment by dianatran18** [comment]
FYI the page title shouldn't get that long. We have some guidance on page title lengths [here](https://pages.github.ibm.com/ai-applications/design/components/page-header/usage#page-title-length).

Also, I haven't really seen breadcrumbs truncate like that. The only truncation I've seen is if there are multiple breadcrumbs and the middle links fall into an [overflow](https://carbondesignsystem.com/components/breadcrumb/usage/#overflow-content), but the first and last breadcrumb are still shown. I think usability wise, the breadcrumb shouldn't be truncated here, so the user can know what page they can go back to, and to be able to read/have a larger touch target to get back to that page. Limiting your page header title will help gain back some of that space. It looks like Lorem ipsum text is used in the page header, so I doubt a page title would ever get that long to come across this issue.

**Comment by darshan1290** [comment]
@dianatran18 , we are using the breadcrumb component to track the folder hierarchy where the folder name can be anything and has n level of parent, so in general, the component can use anywhere and not restricted to the page title. As you can see here the first item is not consistent if the second item text contains a long string. As per your feedback first item should be always visible and the second would be truncated I guess.
