### ISSUE TITLE
Showing white space in table when no Data

### ISSUE THREAD

**Issue by aqibibm** [carbon-design-system/carbon-addons-iot-react#3849]
### What package is this for?

- [x] React
- [ ] Angular

### Describe the bug
[NoData] In Table, placeholders have white space because of wrong colspan calculation in selection Mode "Single"

### To Reproduce
https://carbon-addons-iot-react.com/?path=/story/1-watson-iot-table--with-selection-and-batch-actions

In this, use Selection mode "Single" and search anything random for "NO Data" message.

1. Go to 'https://carbon-addons-iot-react.com/?path=/story/1-watson-iot-table--with-selection-and-batch-actions'
2. from knob change "Enable row selection type (options.hasRowSelection)" to "single"
3. Click on "search"
4. Search anything random ex. "asdf"
5. See error

### Expected behavior
Colspan should be "10" instead of "9" so that blank white space should not be there.

### Environment/versions:

- OS: All
- Browser: All
- `carbon-addons-iot-react` version: [e.g. `v2.60.0`]

### Additional context

<img width="1723" alt="Screenshot 2024-03-12 at 3 56 07 PM" src="https://github.com/carbon-design-system/carbon-addons-iot-react/assets/160481195/aa99e6df-71da-4bc7-906c-cd111633eee6">

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an
upcoming release?

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

**Comment by cgirani** [comment]
Closed issue, PR related to it, is now merged
