### ISSUE TITLE
Expired domain

### ISSUE THREAD

**Issue by splatch** [carbon-design-system/carbon-addons-iot-react#3867]
FYI: Project domain have expired got busted.

**Comment by sls-ca** [comment]
@splatch Can you explain this a little further?  What domain?  What do you mean by busted?

**Comment by splatch** [comment]
https://carbon-addons-iot-react.com/ - website listed as project homepage.

**Comment by sls-ca** [comment]
@splatch Thx, I get it now.

@abpaul1993 Can you update the package.json (https://github.com/carbon-design-system/carbon-addons-iot-react/blob/next/packages/react/package.json#L23) to reflect the correct homepage URL.  Maybe just set it to https://github.com/carbon-design-system/carbon-addons-iot-react/tree/next/packages/react

**Comment by herleraja** [comment]
@sls-ca I have planned to move this to github pages.
