### ISSUE TITLE
RTL: TableDetailWizard : Alignment issues

### ISSUE THREAD

**Issue by KarenGski** [carbon-design-system/carbon-addons-iot-react#450]
- Step text gets cut off in RTL but not in LTR
- Progress bar should be to the right of the steps
- "x" stay right-aligned on body but it should go to the left of the whole thing
![image](https://user-images.githubusercontent.com/51330315/62552443-a4dc6800-b83b-11e9-9a19-39737ec2f836.png)

- Error message highlight does not right align
![image](https://user-images.githubusercontent.com/51330315/62552605-e705a980-b83b-11e9-89db-009e5ed4c0b4.png)

**Comment by davidicus** [comment]
still valid
