### ISSUE TITLE
[TABLE] Multi column sorting

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-iot-react#456]
Multi column sorting is functionality that is needed in both APM and Maximo. This would require both design and development. We should check with the Carbon roadmap to see if this is a priority upstream.  

All designs should be added to this issue and once designs are complete a check list of functionality that would close this issue once built.

**Comment by JordanWSmith15** [comment]
Duplicate. Multi-column sorting has been implemented. Further improvements to be done in https://github.com/carbon-design-system/carbon-addons-iot-react/issues/2398
