### ISSUE TITLE
[Time Series Card] Time Series tooltip dialog scrolls with page

### ISSUE THREAD

**Issue by stuckless** [carbon-design-system/carbon-addons-iot-react#636]
### Describe the bug

In the Dashboard, in the Temperature card, when full screen card, and then open the 'last 7 days' dropdown, and then scroll the screen, the tooltip scrolls instead of being locked in place.

### To Reproduce

1. Open https://deploy-preview-634--carbon-addons-iot-react.netlify.com/?selectedKind=Dashboard%20%28Experimental%29&selectedStory=basic%20dashboard&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs
2. Click fullscreen on temperature card
3. Click 'last 7 days'
4. tooltip opens
5. scroll the page
6. tooltip scrolls

### Expected behavior

Tooltip dialog should be locked in place.

![image](https://user-images.githubusercontent.com/1056553/67598625-fa8a2780-f73b-11e9-8fdf-b5f5e9055d5f.png)

**Comment by enricoberti** [comment]
@davidicus @stuckless this bug is again related to the 'centered' addon that adds a position:fixed container and that interferes with the positioning of the dropdown

**Comment by enricoberti** [comment]
@davidicus @stuckless good to close?

**Comment by stuckless** [comment]
What are we closing it as?  "won't fix" "works as designed", etc?  It just feels wrong to me that an app developer needs to know that some container somewhere might be using position:fixed and if so, then they need to accommodate for that, rather than the component.

**Comment by davidicus** [comment]
This issue has been resolved as seen [here](https://next.carbon-addons-iot-react.com/?path=/story/watson-iot-%F0%9F%9A%AB-dashboard--basic-dashboard)
