### ISSUE TITLE
[Component Proposal] Bullet Graph

### ISSUE THREAD

**Issue by daphoenix** [carbon-design-system/carbon-addons-iot-react#687]
### Summary
Describe in detail the component you would like developed.
Include what offering/product you plan to utilize this new component in.
The Bullet graph for Building Insights from [Watson IoT PAL](https://ibm.invisionapp.com/share/GFNZALEUJ5H#/screens/319100264)

**Additional context**
Add any other context about the component here [e.g. screenshots, code, InVision prototype, Box notes containing details necessary for implementation]
* Invision prototype - https://ibm.invisionapp.com/share/DSNZFODE9JY#/319301005_01-1-Full_Dashboard_complete

### Specific timeline issues / requests
Do you want this work within a specific time period? Is it related to an
upcoming release?
* Required by the end of November for next product release.

_NB: The core contributors will try to work with your timeline, but it's not
guaranteed. The earlier you make a request in advance of a desired delivery
date, the better!_

### You will consider this component complete when...
- [ ] It's available as an export of this library
- [ ] Additional criteria you may have [e.g. Fully responsive, Accessible to WCAG 2.0, etc.]

### Available extra resources

What resources do you have to assist this effort?
Possibly one member of the development team, depending on timelines.
_Carbon Add-ons for Watson IoT is a collaborative system. We encourage teams to build components and submit them for integration._

**Comment by tay1orjones** [comment]
From 
[Internal Watson-IoT/pal-tracking#189](https://github.ibm.com/Watson-IoT/pal-tracking/issues/189)

**What is the rationale for this contribution.**
Bullet graphs are used to provide an idea of a value in comparison towards a goal value, with an added extra 'context' datapoint provided.


**Detail the intended behavior**
A traditional bullet chart with horizontal bars.
- Each bar shows a particular value.
- Each bar will have a vertical line somewhere on its axis to act as a 'target value' indicator
- A larger background area around each bar may be segmented with color to show ranges (good, great poor etc).

Found here: https://ibm.invisionapp.com/share/U2NYW8D7DFV#/screens/319100264
Image:
![image](https://media.github.ibm.com/user/684/files/53738f00-200c-11ea-942c-259e174d79a6)


**Inspiration from other products**
(Optional - remove this is you don't have any)


**Note:** This is not yet in Carbon data viz. So this contribution should aim to provide work to them, as well as our PAL.
