### ISSUE TITLE
[MultiSelect] Dropdown header is not displayed while opened in Android devices when in RTL mode

### ISSUE THREAD

**Issue by camilasb** [carbon-design-system/carbon-addons-iot-react#798]
Pre-condition:
Have an Android device

Steps:
1. Open the Storybook
2. Open MultiSelect component (default sub-item)
3. Click on RTL tab and choose RTL toggle
4. Open the dropdown
Actual Result: Dropdown header is not displayed. User is not able to see how many items are being selected
Expected Result: User should see dropdown header
![image](https://user-images.githubusercontent.com/20360162/71284449-86d25880-2341-11ea-91fb-34f8c46f4107.png)

**Comment by camilasb** [comment]
seems to be closed now
![image](https://user-images.githubusercontent.com/20360162/95460659-9b70f300-094b-11eb-9870-96234e084496.png)

**Comment by davidicus** [comment]
Closing. Feel free to open if you see the issue again.
