### ISSUE TITLE
[Tooltip,Flyout] should not render offscreen with clipped content

### ISSUE THREAD

**Issue by kalyanixraut** [carbon-design-system/carbon-addons-iot-react#802]
### Describe the bug
I am using `<Tooltip> `component, as in below screen when tooltip is on the right of the screen the tooltip notch is misaligned and doesn't stay below the icon.
Expected behavior is the tooltip notch should automatically change the alignment to end/center/start based on its position on the screen .

<img width="147" alt="image" src="https://user-images.githubusercontent.com/22093326/71662811-c9038d00-2d78-11ea-91a1-66444395709a.png">

Do you want this work within a specific time period? Is it related to an
upcoming release?

This fix is required for Jan 2020 release

**Comment by bjornalm** [comment]
@davidicus I have found (but not implemented) a solution this. If we fix it I think it should be fixed in the carbon tooltip.js and we should probably expand this to include fixes for all scenarios with misaligned "notch"/arrow. Should I continue to implement a fix and PR for carbon?

**Comment by davidicus** [comment]
Carbon does not believe in controlling this so I do not think they will accept a PR. If we can create a fix for our tooltips that would be great. Better yet is if we can create a component that just handles this so we can use it for tooltip, overflows or anything that requires awareness of its positioning.

**Comment by bjornalm** [comment]
Ok, I will investigate how to best fix this on our end.

**Comment by bjornalm** [comment]
@davidicus @stuckless 
Sean mentioned that they have their own tooltip that manages the positioning. Is that one based on Carbon? If so perhaps can can we reuse that code?

**Comment by davidicus** [comment]
Pausing this work until we work out priority and come up with a comprehensive solution.

**Comment by bjornalm** [comment]
We can try to build a reusable solution based on the graphite code:

- https://github.ibm.com/maximo-app-framework/graphite/blob/master/packages/react-components/src/ui/TextOverflow/TextOverflow.js
- https://github.ibm.com/maximo-app-framework/graphite/blob/master/packages/react-components/src/ui/Popup/Popup.js
- https://github.ibm.com/maximo-app-framework/graphite/blob/master/packages/react-components/src/ui/common/AbsolutePositioned.js

**Comment by tay1orjones** [comment]
It would be awesome if we could encapsulate this into a custom `usePositioning` hook to be used with the normal Tooltip from Carbon.

**Comment by tay1orjones** [comment]
Going to rename this to be more respective of the work that needs to happen here - the current scope appears to be a broad tooltip "smart positioning" feature that takes into account screen bounds to determine render position left/right and offset properties to prevent the initially described issue but also improve items that rely on the tooltip - things like the Flyout #1266 (which uses tooltip under the hood)

**Comment by tay1orjones** [comment]
Looks like #972 should fix this.

**Comment by kevinsperrine** [comment]
This was addressed in #2052.
