### ISSUE TITLE
[PageForm] need a simple page with Save and Cancel or Update buttons at the bottom in stickyFooter like PageWizard

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-addons-iot-react#880]
### Summary

Currently if we have users with a simple page, we recommend Page Wizard with one step (which seems really artificial)

We should make a component that has a simplified prop model (and children) that basically acts like the old EditPage used to

**Comment by davidicus** [comment]
@scottdickerson do we have designs specs for this that we can include here?

**Comment by davidicus** [comment]
@lukefirth do you have any designs that we can include here?
